### ISSUE TITLE
code: ‘Module Not Found'

### ISSUE THREAD

**Issue by CuriousCrypto** [HashLips/hashlips_art_engine#10]
Thank you very much for all the work and information you provide for the community Hashlips!
I had no issues when using your original generative art node main. However when I downloaded your new ‘hashlips art engine’, changed the layers to mine and run node index.js, it always seems to throw the error below. Can anyone help please? The same error seems to appear on all versions from 1.0.0-1.0.2
Thank you in advance!

Harolds-iMac:hashlips_art_engine-1.0.0 haroldkim$ node index.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'canvas'
Require stack:
- /Users/haroldkim/Downloads/hashlips_art_engine-1.0.0/src/main.js
- /Users/haroldkim/Downloads/hashlips_art_engine-1.0.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/haroldkim/Downloads/hashlips_art_engine-1.0.0/src/main.js:3:37)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/haroldkim/Downloads/hashlips_art_engine-1.0.0/src/main.js',
    '/Users/haroldkim/Downloads/hashlips_art_engine-1.0.0/index.js'
  ]
}

**Comment by HashLips** [comment]
Run Yarn add all before you run node index.js
