### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by DrFalcon13** [HashLips/hashlips_art_engine#1001]
at setSource (C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\node_modules\canvas\index.js:23:10)
    at C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\src\main.js:194:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\src\main.js:193:10)
    at C:\Users\hayal\Desktop\generate-nfts-main\generate-nfts-main\src\main.js:374:31
    at Array.forEach (<anonymous>)

i am getting this error can you help me about this issue.I checked all the layer photos png and their height and width are the same

**Comment by bolshoytoster** [comment]
@DrFalcon13 can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by DrFalcon13** [comment]
@bolshoytoster I didn't try

**Comment by bolshoytoster** [comment]
@DrFalcon13 what?

**Comment by DrFalcon13** [comment]
didn't happen again

**Comment by DrFalcon13** [comment]
i am getting the same error again

**Comment by bolshoytoster** [comment]
@DrFalcon13 can you paste the **full** output from your terminal please.

**Comment by DrFalcon13** [comment]
@bolshoytoster When I use hashlips it started giving this error now 

Error: Cannot find module 'C:\Users\hayal\Desktop\hashlips_art_engine-main/constants/network.js'
Require stack:
- C:\Users\hayal\Desktop\hashlips_art_engine-main\src\main.js
- C:\Users\hayal\Desktop\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\hayal\Desktop\hashlips_art_engine-main\src\main.js:2:21)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\hayal\\Desktop\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\hayal\\Desktop\\hashlips_art_engine-main\\index.js'

**Comment by bolshoytoster** [comment]
@DrFalcon13 can you paste the output of `Get-ChildItem constants`.

**Comment by DrFalcon13** [comment]
Get-ChildItem : Cannot find path 'C:\Users\hayal\Desktop\hashlips_art_engine-main\constants.' because it does not exist.
At line:1 char:1
+ Get-ChildItem constants.
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\hayal\...main\constants.:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by bolshoytoster** [comment]
@DrFalcon13 what about just `Get-ChildItem`?

**Comment by DrFalcon13** [comment]
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        26.01.2022     09:05                .github
d-----        25.03.2022     22:07                build
d-----        25.03.2022     22:25                layers
d-----        07.02.2022     22:48                modules
d-----        20.03.2022     20:32                node_modules
d-----        26.01.2022     09:05                src
d-----        26.01.2022     09:05                utils
-a----        26.01.2022     09:05           1678 .gitignore
-a----        26.01.2022     09:05              9 .nvmrc
-a----        26.01.2022     09:05         441599 banner.png
-a----        06.02.2022     12:27            639 hashlips_art_engine-main.zip.lnk
-a----        26.01.2022     09:05            157 index.js
-a----        26.01.2022     09:05           1065 LICENSE
-a----        26.01.2022     09:05          37711 logo.png
-a----        25.03.2022     22:33          41451 package-lock.json
-a----        26.01.2022     09:05            861 package.json
-a----        26.01.2022     09:05           9930 README.md
-a----        25.03.2022     22:33          16243 yarn.lock

**Comment by DrFalcon13** [comment]
this happened

**Comment by bolshoytoster** [comment]
@DrFalcon13 it doesn't look like you properly unzipped the file.

Extract `hashlips_art_engine-main.zip` to somewhere then open visual studio to there.

**Comment by DrFalcon13** [comment]
@bolshoytoster bug fixed but now i am getting this error

ReferenceError: png is not defined
    at setSource (C:\Users\hayal\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:18)
    at Image.set (C:\Users\hayal\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\hayal\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\hayal\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\hayal\Desktop\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\hayal\Desktop\hashlips_art_engine-main\src\main.js:184:12)
    at C:\Users\hayal\Desktop\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@DrFalcon13 I have no clue how you caused such an error, but I know you're not using my fork.

Please
1. Make a copy of your `src/config.js` and your `layers/` folder.
2. Delete your `hashlips_art_engine-main` folder and any `hashlips_art_engine-main.zip` files
3. Download [this](https://github.com/bolshoytoster/hashlips_art_engine/archive/refs/heads/main.zip) zip
4. Unzip said zip
5. Open visual studio to the extracted folder
6. Copy your saved `src/config.js` and `layers/` folder over to replace the existing.

**Comment by DrFalcon13** [comment]
Error: Unsupported image type: Dress Color/Thumbs.db
Created edition: 1, with DNA: 3c975aca3a1f83ca0799e4b1439ab8db04200e71
Created edition: 2, with DNA: fb6d2df946f966e15ceecadc0bd7c77ed6d34090
Created edition: 3, with DNA: d0f4f3689a2f622c9686ff7501c0f00710619d6c
Created edition: 4, with DNA: 0bf19037e26114451dbba0723a2984ca0c482e4e
Created edition: 5, with DNA: bb13e6f4f13de4fcf8cbdb18cec994604cf6a60d
Saved edition: 1
Saved edition: 2
Saved edition: 3
Saved edition: 4
Saved edition: 5

**Comment by DrFalcon13** [comment]
@bolshoytoster  I did everything you said

**Comment by bolshoytoster** [comment]
@DrFalcon13 it worked.

**Comment by DrFalcon13** [comment]
I don't have a dress color for thumbs

**Comment by bolshoytoster** [comment]
@DrFalcon13 it's a warning because you have a non-image file in one of your layer folders.

**Comment by DrFalcon13** [comment]
If I produce 10 thousand now, it will not fail, right?

**Comment by bolshoytoster** [comment]
@DrFalcon13 it shouldn't.

**Comment by DrFalcon13** [comment]
thank you very much

**Comment by DrFalcon13** [comment]
we can do the numbers by # bringing this tag, right?

**Comment by bolshoytoster** [comment]
@DrFalcon13 I think so?

**Comment by DrFalcon13** [comment]
okey bb

**Comment by DrFalcon13** [comment]
@bolshoytoster (Edition exists!) i started getting this error how can i fix it

**Comment by bolshoytoster** [comment]
@DrFalcon13 it's not an error. My fork lets you continue a previous collection. You'll have to delete the `build/` folder yourself.

**Comment by DrFalcon13** [comment]
@bolshoytoster how can i delete

**Comment by bolshoytoster** [comment]
@DrFalcon13 you can either run `Remove-Item -Recurse build` or just right-click -> delete.

**Comment by DrFalcon13** [comment]
it's ok thank you very much again

**Comment by DrFalcon13** [comment]
@bolshoytoster C:\Users\hayal\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\bulk-upload-to-opensea-main\\upload': [Errno 2] No such file or directory do you have any idea what this error means i couldn't figure it out

**Comment by bolshoytoster** [comment]
@DrFalcon13 what did you run?

**Comment by DrFalcon13** [comment]
@bolshoytoster bulk upload nft

**Comment by bolshoytoster** [comment]
@DrFalcon13 what command did you run?

**Comment by DrFalcon13** [comment]
@bolshoytoster https://github.com/infotrex/bulk-upload-to-opensea

**Comment by DrFalcon13** [comment]
python upload_captcha.py

**Comment by DrFalcon13** [comment]
this command

**Comment by bolshoytoster** [comment]
@DrFalcon13 what did you type into powershell/cmd which resulted in that error?

Besides, you should probably open an issue over there since this is the wrong place to be discussing this.

**Comment by DrFalcon13** [comment]
ok

**Comment by bolshoytoster** [comment]
@DrFalcon13 my guess is that you accidentally added a space in `upload_captcha.py`, try running it again.

If you're using the most recent version of that repo you'll probably have to run `python upload_2captcha_V2.py`

**Comment by Stamoments** [comment]
got this error >>>
/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/lib/image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/lib/image.js:62:9)
    at /Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/index.js:23:10)
    at /Users/mac/Downloads/create-10k-nft-collection-2.0.0/src/main.js:184:25
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/src/main.js:183:10)
    at /Users/mac/Downloads/create-10k-nft-collection-2.0.0/src/main.js:364:31
    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@Stamoments you're in the wrong repo, but you might have luck replacing your `src/main.js` with [mine](https://raw.githubusercontent.com/bolshoytoster/hashlips_art_engine/main/src/main.js)

**Comment by Stamoments** [comment]
Thank you! The code works!

**Comment by DrFalcon13** [comment]
@bolshoytoster Hi.I created 1000 nfts with your code.I will create it again but keep the numbers from 1000.Where should I write the number?

**Comment by bolshoytoster** [comment]
@DrFalcon13 do you mean you want the numbers to start from 1000? If you're using my fork, or at least my `src/main.js` you can set `startEditionFrom` the same way you set `growEditionSizeTo`.

**Comment by DrFalcon13** [comment]
yes

**Comment by DrFalcon13** [comment]
okay ty

**Comment by DrFalcon13** [comment]
ı did

**Comment by DrFalcon13** [comment]
thank you it was
