### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'shift')

### ISSUE THREAD

**Issue by vishwapb** [HashLips/hashlips_art_engine#1020]
Hi,
Can someone please help with this.
Thank you.

TypeError: Cannot read properties of undefined (reading 'shift')
    at cleanDna (E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\src\main.js:61:35)
    at E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\src\main.js:225:22
    at Array.find (<anonymous>)
    at E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\src\main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\src\main.js:223:35)
    at startCreating (E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\src\main.js:363:23)
    at E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\index.js:6:3
    at Object.<anonymous> (E:\Crypto\Hashlips\hashlips_art_engine-1.1.2_patch_v5\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)

**Comment by bolshoytoster** [comment]
@vishwapb can you try using the [latest version](https://github.com/HashLips/hashlips_art_engine/archive/refs/heads/main.zip) please.
