### ISSUE TITLE
When I run node index.js I keep an Error

### ISSUE THREAD

**Issue by Erosa01** [HashLips/hashlips_art_engine#1031]
PS C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6> node index.js
(node:4496) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6/layers/Eye color/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\Carlos\Desktop\Evan\nftproject\NFT Deployment\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Carlos\\Desktop\\Evan\\nftproject\\NFT Deployment\\hashlips_art_engine-1.1.2_patch_v6/layers/Eye color/'
}

**Comment by bolshoytoster** [comment]
@Erosa01 save your `src/config.js`.

**Comment by Erosa01** [comment]
oh thank you

**Comment by John-cel** [comment]
don't work
