### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by metamacias** [HashLips/hashlips_art_engine#1032]
![Capture](https://user-images.githubusercontent.com/101298610/161403327-236af7be-ed12-455c-b4c3-5d9dca4b4da4.PNG)

Everything was running fine than this started happening

Created edition: 151, with DNA: b492bc4469aa09295724a6bc13fa5a08e59c9817
Created edition: 152, with DNA: 9eadbb526e54debfc7a790f2da29098396d66299
Created edition: 153, with DNA: e2072891f4472e9dd15be9166002578e0012c88a
Created edition: 154, with DNA: df5fff3ec9d013154e37ff56ea3ed312e20a86e0
Created edition: 155, with DNA: 83a5f728258a0035f43484a402aacb1956ad0ab1
Created edition: 156, with DNA: dc911d630b7ad48cf250a51596b7b0d0aa4ee186
C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\MustS\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@M3taMacias make sure there are **only** images in your `layers/*/` folders, or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
