### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by milizzz** [HashLips/hashlips_art_engine#1034]
help me plz
C:\Users\TechZone-PC>cd C:\Users\TechZone-PC\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6

C:\Users\TechZone-PC\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>node index.js
C:\Users\TechZone-PC\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\TechZone-PC\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by bolshoytoster** [comment]
@milizzz either update your node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
