### ISSUE TITLE
 Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by milizzz** [HashLips/hashlips_art_engine#1035]
after generated afew its stop
C:\Users\Public\hashlips_art_engine-1.0.7_update>node index.js
Created edition: 1, with DNA: 51ca50bd50581cd231918de330e4c6272aaec077
Created edition: 2, with DNA: 7e3b97c0f6eda16397d0b2fa21bbaea91cc81844
Created edition: 3, with DNA: fcd1357989e615e69af838b951b56b53581f0784
Created edition: 4, with DNA: 9d304d15e94dd386702e3c76509c993d6c7a3287
Created edition: 5, with DNA: 361190ee8aeb6809be3ecfb4aedf98179b7d699d
Created edition: 6, with DNA: 47d68e220bef93a5c5c2f67131ff5bdbd628c0a4
Created edition: 7, with DNA: f83f8160e1856c3d2dce411cbf6f7187b5975eeb
Created edition: 8, with DNA: ac91a69debafa94513aee143442cc1766595fd5e
Created edition: 9, with DNA: dbb6555b7f170a734c4cd3873daad7abae0e7e65
Created edition: 10, with DNA: 98d25ab45424c3941d43c334b8e5040b64140009
Created edition: 11, with DNA: ab1c43d76f106defcf86efb26088e372127e3c08
Created edition: 12, with DNA: bd2d6f839368585cec674f8c8fa8b1ca26535ff9
Created edition: 13, with DNA: 8b2c3c232bdf146b194b1028a3f7c050da2f8fe1
(node:11492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:145:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:144:10)
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:282:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:281:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:145:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:144:10)
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:282:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:281:17)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:145:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:144:10)
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:282:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:281:17)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:11492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:145:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:144:10)
    at C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:282:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Public\hashlips_art_engine-1.0.7_update\src\main.js:281:17)
(node:11492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by bolshoytoster** [comment]
@milizzz try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by ghost** [comment]
Hi milizzz i have exactly the same issue, did u fix it ?

**Comment by bolshoytoster** [comment]
@ADRIhein2 it's likely fixed on [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
