### ISSUE TITLE
npm run generate Issue

### ISSUE THREAD

**Issue by BKdesign016** [HashLips/hashlips_art_engine#1040]
After running npm run generate I'm getting this: 
![npm run generate issue](https://user-images.githubusercontent.com/102361888/161522723-72d655a0-e09e-4618-ae05-bfda54bf1927.png)
Where am I wrong? Please help.

**Comment by MaciekBaron** [comment]
Your paths are using the wrong slashes - on Windows paths use backslashes `\` but the path to your image in your settings is using forward slashes `/`

**Comment by bolshoytoster** [comment]
@BKdesign016 @MaciekBaron
> Your paths are using the wrong slashes - on Windows paths use backslashes `\` but the path to your image in your settings is using forward slashes `/`

no.

It's because you have non-ascii characters in your path - `C:/Graphic Design/Robot b k `.

**Comment by BKdesign016** [comment]
![Robot b²k² non-ascii characters](https://user-images.githubusercontent.com/102361888/161583723-1ca13eb1-97c0-491d-afb1-6d2c4e7393c5.png)
Are these non-ascii characters?

**Comment by BKdesign016** [comment]
![Are these non-ascii characters](https://user-images.githubusercontent.com/102361888/161584156-ece827cb-8743-47ab-babf-a8e84183c7fd.png)
Are these non-ascii characters?

**Comment by bolshoytoster** [comment]
@BKdesign016 yes.

**Comment by BKdesign016** [comment]
Thank you very much.

**Comment by Catzskull** [comment]
<img width="755" alt="Screen Shot 2022-04-04 at 4 38 00 PM" src="https://user-images.githubusercontent.com/102982983/161628054-793e8fc1-fa4d-4b7b-9bc9-8540286d40ef.png">

**Comment by bolshoytoster** [comment]
@Catzskull I assume you just need to run `npm install`, but I can't really help much other than that without the full error.

**Comment by Catzskull** [comment]
Sorry first time here, I don't get it, thk
<img width="1211" alt="Screen Shot 2022-04-04 at 5 25 51 PM" src="https://user-images.githubusercontent.com/102982983/161634968-be2d0859-3201-4383-b0bd-cf6e312240f4.png">
s

**Comment by bolshoytoster** [comment]
@Catzskull I think you'l just need to save your `src/config.js` file.

**Comment by Ademie** [comment]
I am getting the same error I dont think any of this solutions are helpful.. can someone help out I need to set up this project it's an hired contract 😥

**Comment by bolshoytoster** [comment]
@Ademie can you paste the error please.

**Comment by Ademie** [comment]
> @Ademie can you paste the error please.

Please give me a moment, I'll be right back

**Comment by Ademie** [comment]
> @Ademie can you paste the error please.

C:\Users\isijo\Desktop\TortNFT\hashlips>npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

C:\Users\isijo\Desktop\TortNFT\hashlips>

**Comment by Catzskull** [comment]
<img width="1176" alt="Screen Shot 2022-04-04 at 6 18 37 PM" src="https://user-images.githubusercontent.com/102982983/161641262-03629a0b-1802-4469-a034-9e1e1aa5f81b.png">

**Comment by Ademie** [comment]
> @Ademie can you paste the error please.

C:\Users\isijo\Desktop\TortNFT\hashlips>npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: error while reading from input stream
    at setSource (C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\isijo\Desktop\TortNFT\hashlips\node_modules\canvas\index.js:23:10)
    at C:\Users\isijo\Desktop\TortNFT\hashlips\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\isijo\Desktop\TortNFT\hashlips\src\main.js:184:12)
    at C:\Users\isijo\Desktop\TortNFT\hashlips\src\main.js:368:31
    at Array.forEach (<anonymous>)

C:\Users\isijo\Desktop\TortNFT\hashlips>

**Comment by bolshoytoster** [comment]
@Catzskull
Can you send a screenshot of your `src/config.js` file please.

@Ademie
That's usually caused by a non-image file being in one of your layer folders. You can use [my fork](https://github.com/bolshoytoster/hashlips_art_engine) which makes this just a warning (and tells you which file it is).

**Comment by Ademie** [comment]
> @Catzskull Can you send a screenshot of your `src/config.js` file please.
> 
> @Ademie That's usually caused by a non-image file being in one of your layer folders. You can use [my fork](https://github.com/bolshoytoster/hashlips_art_engine) which makes this just a warning (and tells you which file it is).

const basePath = process.cwd();
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "Your Collection";
const description = "Remember to replace this description";
const baseUri = "ipfs://NewUriToReplace";

const solanaMetadata = {
  symbol: "YC",
  seller_fee_basis_points: 1000, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://www.youtube.com/c/hashlipsnft",
  creators: [
    {
      address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC",
      share: 100,
    },
  ],
};

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 10,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Shadow" },
      // { name: "Back Toes" },
      { name: "Back Paws" },
      // { name: "Front Toes" },
      { name: "Neck" },
      { name: "Back Toes" },
      { name: "Front Paws" },
      // { name: "Spots" },
      { name: "Front Toes" },
      { name: "Tail" },
      // { name: "Spots" },
      { name: "Shield" },
      // { name: "Shadow" },
      // { name: "Shine" },
      { name: "SideShield" },
      // { name: "Shadow" },
      // { name: "Eyes" },
      { name: "Right Iris" },
      { name: "Pupils" },
      // { name: "Shine" },
      { name: "Face" },
      // { name: "Shadow" },
      { name: "Spots" },
      { name: "Nose" },
      { name: "Eye Brow" },
      { name: "Mouth" },
      // { name: "Teeth" },
      // { name: "Shadow" },
      { name: "Tongue" },
      { name: "Teeth" },
      { name: "Shadow" },
      { name: "Eyes" },
      { name: "Left Iris" },
      { name: "Pupils" },
      { name: "Shine" },
      { name: "Noise" },

    ],
  },
];

const shuffleLayerConfigurations = false;

const debugLogs = false;

const format = {
  width: 512,
  height: 512,
  smoothing: false,
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: true,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const extraMetadata = {};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,
};

**Comment by Catzskull** [comment]
<img width="1212" alt="Screen Shot 2022-04-04 at 6 35 02 PM" src="https://user-images.githubusercontent.com/102982983/161643022-5c69a49a-
<img width="573" alt="Screen Shot 2022-04-04 at 6 35 25 PM" src="https://user-images.githubusercontent.com/102982983/161643024-74689226-b149-405e-93f9-1e29f543fc79.png">
f74d-40e6-a096-5aa6384a34d4.png">

**Comment by bolshoytoster** [comment]
@Catzskull you need to save the file (`ctrl` + `s`).

**Comment by Catzskull** [comment]
It worked! Thks thks!

**Comment by BKdesign016** [comment]
I have the next issue: After running npm run generate I'm getting this:
![npm run generate error](https://user-images.githubusercontent.com/102361888/161744794-099d59bd-bfc2-4a0e-9d4a-2cb4dcba7543.png)
[A complete log of this run.txt](https://github.com/HashLips/hashlips_art_engine/files/8417683/A.complete.log.of.this.run.txt)
Please help!

**Comment by MaciekBaron** [comment]
Make sure you are running this in the correct folder. You should have a `package.json` file in that folder. You originally run it in a folder called `minter-dapp/backend`.

**Comment by BKdesign016** [comment]
I think I have. Or I am wrong?
![new issue](https://user-images.githubusercontent.com/102361888/161751989-aedf359f-e60d-4fb5-8e55-e74b7b852eab.jpg)

**Comment by MaciekBaron** [comment]
You now have two package.json files, one in the root and one in backend. Just go to backend (`cd backend`).

**Comment by BKdesign016** [comment]
Nightmare!
![Nightmare!](https://user-images.githubusercontent.com/102361888/161753034-ef670b6b-0e08-4ba1-a421-d33131fcb893.jpg)

**Comment by MaciekBaron** [comment]
Please pay attention to the commands, you did a typo (`backhend` instead of `backend`).

**Comment by BKdesign016** [comment]
Oh, what a typo. But I still have a problem.
![4](https://user-images.githubusercontent.com/102361888/161753839-87d24fbf-4001-4fba-9ff9-48e997e896f1.jpg)

**Comment by MaciekBaron** [comment]
Have you installed dependencies using `npm install`?

**Comment by BKdesign016** [comment]
Finally. I can not believe it. I did it. That is, we succeeded together. Thank you very much. Without you, I would never have made this. I'm a graphic designer and I make NFT, I'm not a developer
![5](https://user-images.githubusercontent.com/102361888/161754872-96340e81-74d6-4669-aff4-eeb36f8ed348.jpg)
. Thanks again. You're unbelievable.

**Comment by MaciekBaron** [comment]
Happy you got there in the end!

**Comment by BKdesign016** [comment]
MaciekBaron you are a genius, maybe you can help me with this obstacle I came across. Unable to upload files via NFT port. Do you have any idea why? In addition, the VSC is frozen and I can't type any commands. How do I defrost it?
![NFT port issue](https://user-images.githubusercontent.com/102361888/161791887-91983e26-846f-4aa0-a4a9-1a17d1b264c6.jpg)

**Comment by BKdesign016** [comment]
I need to upload files to IPFS via NFT port. Regarding error 403, I found this explanation: The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it... If authentication credentials were provided in the request, the server considers them insufficient to grant access.

**Comment by BKdesign016** [comment]
I checked the API key I got from NFT Port and it is correct. I don't know how to overcome this issue?

**Comment by Ademie** [comment]
![3 png - TortNFT - Visual Studio Code 06-04-2022 01_09_43 AM](https://user-images.githubusercontent.com/73498011/161871794-89b10408-a055-4c2b-81ee-1fb873881a00.png)
Please does anyone know why my art work is looking distorted? I tried generating it even though I arranges them orderly in the config.js file but this was the output

**Comment by WCACnft** [comment]
@MaciekBaron - if you're willing I'd appreciate your help. I started this for the first time. I have an M1 Mac. Downloaded homebrew, latest version Node JS, VS Code, and the latest Hash Lips art engine version. I confirmed in VS Code that I had a successful version of Node installed. When using "npm install" I get a huge response as seen in the attachment. 
<img width="1187" alt="Screen Shot 2022-04-11 at 11 00 46 PM" src="https://user-images.githubusercontent.com/103372006/162877841-af68bd2a-d682-4722-adcc-de4b07ab0858.png">

**Comment by bolshoytoster** [comment]
@WCACnft in future could you **copy and paste** the (full) error(s), since it's a pain in the arse to cooy text from a screenshot while also not knowing what the rest of the error is.

Also, when pasting long errors it's best to do it within triple-backticks:
\`\`\`
error
\`\`\`

**Comment by Catzskull** [comment]
Hi I'm trying to Create 1of1 edition + the standard ones using the layers. that doesn't work. how can I do?
<img width="1200" alt="Screen Shot 2022-04-13 at 3 39 27 PM" src="https://user-images.githubusercontent.com/102982983/163257961-f0cc405f-654f-44a3-9798-f4fbb49d2986.png">

**Comment by bolshoytoster** [comment]
@Catzskull you've probably misunderstood `shuffleLayerConfigurations`, it's meant to be `true`/`false`.

Could you explain what you want to do please.

**Comment by Catzskull** [comment]
Just trying to do 1 of 1 in the collection

**Comment by bolshoytoster** [comment]
@Catzskull I think you want to add that bit to `layersConfigurations` instead.

**Comment by Catzskull** [comment]
I did it seems to work, metadata read ok. Thks
<img width="1285" alt="Screen Shot 2022-04-13 at 5 19 24 PM" src="https://user-images.githubusercontent.com/102982983/163272505-569a4140-527c-4d8f-bfa9-bb6a36a2c657.png">
