### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by ghost** [HashLips/hashlips_art_engine#1058]
hi, after generating some, i have this issue, can someone help me ? thank you

 npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:4296) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: a944d16cadad76eb6aa6eb5b730fcf7ced454fae
Created edition: 2, with DNA: 12bf08bc4aa3de7fd07e90d3ebafbd04883079bc
Created edition: 3, with DNA: d2be64da7cfac9e7d38f0c6e65604205faf0ec86
C:\Users\PC Adrien\Desktop\NFT\hashlips_art_engine-1.1.1_update\src\main.js:183
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\PC Adrien\Desktop\NFT\hashlips_art_engine-1.1.1_update\src\main.js:183:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\PC Adrien\Desktop\NFT\hashlips_art_engine-1.1.1_update\src\main.js:182:10)
    at C:\Users\PC Adrien\Desktop\NFT\hashlips_art_engine-1.1.1_update\src\main.js:363:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\PC Adrien\Desktop\NFT\hashlips_art_engine-1.1.1_update\src\main.js:362:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\Users\PC Adrien\Desktop\NFT\hashlips_art_engine-1.1.1_update>

**Comment by bolshoytoster** [comment]
@ADRIhein2 try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by ghost** [comment]
Thank u, any idea where the issue could come from ?

**Comment by bolshoytoster** [comment]
@ADRIhein2 there are multiple causes, all of which I have forgotten.

**Comment by ghost** [comment]
i have tried everything but still have this problem, sometimes it appears after 5 generate, other times after 10 generate

**Comment by bolshoytoster** [comment]
@ADRIhein2 are you using my fork?

**Comment by ghost** [comment]
nop whats different compared to hashlips?

**Comment by bolshoytoster** [comment]
@ADRIhein2 it's basically the same, but it fixes this error.

**Comment by ghost** [comment]
ok ill try
keep you in touch

**Comment by ghost** [comment]
I finally managed to do it, i have a question but I don't know if it's the right place and if you're the right person but I'll test anyway

In my layer configuration I would like some layers not to be generated with some file layers, an example: THIS background cannot be generated with the entire eyes category but ONLY this background, i know how to not link files layers between each others but not how to do it with only some layers, i don't know if this is understable

**Comment by bolshoytoster** [comment]
@ADRIhein2 you could try having a seperate `layersConfiguration` with that background, you could make another folder inside your background folder - `special` - and have your `layersConfigurations` something like this:
```js
const layerConfigurations = [
  {
    // Normal
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Background" },
      { name: "Eyes" }
      ...other_layers
    ],
  },
  {
   // Special, without eyes
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Background/special" },
      ...other_layers
    ],
  },
];
```

**Comment by ghost** [comment]
![Capture138](https://user-images.githubusercontent.com/103067553/162307666-88ebb8fc-e24e-4a6e-9b1b-7ef30ec3d0ee.PNG)


thank u 
something like this ? 
i imagine these are not right :

{ name: "Background/Normal" },
{ name: "Background/Special" },

**Comment by bolshoytoster** [comment]
@ADRIhein2 that should work.

**Comment by ghost** [comment]
![34](https://user-images.githubusercontent.com/103067553/162312919-5c7418bf-3a77-4341-96d2-672c68baebf0.PNG)


unfortunately no

**Comment by bolshoytoster** [comment]
@ADRIhein2 it says permission denied, could you try running visual studio as admin?

**Comment by ghost** [comment]
thank u very much 
im a beginner dont even see that :o
indeed it works

speaking on metadata, for example if i sell my nfts on opensea concerning properties/rarity, it will be indicated only "background" or "background normal"/ "background special"

**Comment by bolshoytoster** [comment]
@ADRIhein2 it will say `Background/Normal` in the metadata.

If you want it to just be `Background` you can, ~line 177 in `src/main.js`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L176-L178

Change
```js
   trait_type: _element.layer.name, 
```
to
```js
   trait_type: _element.layer.name.split('/').shift(), 
```
Note that this will break some `utils/` scripts.

**Comment by ghost** [comment]
dude u can't imagine how useful u are, I spent so many hours looking on how to do all of it
how can i like ur profile
