### ISSUE TITLE
Plz_step_dev_I__m_stuck

### ISSUE THREAD

**Issue by GauPerrin** [HashLips/hashlips_art_engine#1059]
hello, I am having hard time figuring out what is the issue with the dna I haven't touch to it.
If someone has any idea where this could come from I'd be grateful :) !

C:\Users\Utilisateur\OneDrive\Bureau\Inpute\hashlips_art_engine\src\main.js:274
  return _dna.replace(query, "");
              ^
    at Array.find (<anonymous>)
    at C:\Users\Utilisateur\OneDrive\Bureau\Inpute\hashlips_art_engine\src\main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\Utilisateur\OneDrive\Bureau\Inpute\hashlips_art_engine\src\main.js:223:35)
    at startCreating (C:\Users\Utilisateur\OneDrive\Bureau\Inpute\hashlips_art_engine\src\main.js:364:23)
    at C:\Users\Utilisateur\OneDrive\Bureau\Inpute\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\Utilisateur\OneDrive\Bureau\Inpute\hashlips_art_engine\index.js:7:3)

**Comment by bolshoytoster** [comment]
@Arcangel505 can you paste the **full** error please, I think [my fork](https://github.com/bolshoytoster/hashlips_art_engine) fixes this.
