### ISSUE TITLE
npm run generate error

### ISSUE THREAD

**Issue by Zoomicious** [HashLips/hashlips_art_engine#1090]
The test generate ran well but after uploading my layers , it gave me this error and I am stuck here, how do I resolve please:?

(node:69932) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/layers/Background/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (/Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/src/main.js:73:6)
    at /Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/src/main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/src/main.js:87:30)
    at startCreating (/Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/src/main.js:348:20)
    at /Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/index.js:6:3
    at Object.<anonymous> (/Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/mamapearl/Dropbox/NFToken/Repos/minter-dapp/backend/layers/Background/'
}

**Comment by bolshoytoster** [comment]
@Zoomicious save your `src/config.js` file.
