### ISSUE TITLE
Dont run "node utils/nftport/uploadFiles.js"

### ISSUE THREAD

**Issue by okarlidag** [HashLips/hashlips_art_engine#1092]
Hello, 
I want to mint my entire collection to Opensea. I have done all instructions but vs dont run "node utils/nftport/uploadFiles.js" command. Please help me to fix this problem.
Best Regards.

<img width="1680" alt="Ekran Resmi 2022-04-18 15 14 50" src="https://user-images.githubusercontent.com/103938144/163806985-7d6a2a30-486e-4fe1-bfdf-cc0aab0e894d.png">

**Comment by bolshoytoster** [comment]
@okarlidag firstly, this issue is in the wrong place, it should be in the place you got the code from (likely [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection)).

Secondly, can you paste the **full** error please.

**Comment by okarlidag** [comment]
Thank you for responding. 
I could not have fixed this problems for days. Please help me to fix this problem. 
My version is: v14.19.1
Full error is that:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
macbook-pro:hashlips_art_engine-1.1.2_patch_v6 okankarlidag$ node utils/nftport/uploadFiles.js
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/okankarlidag/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /Users/okankarlidag/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node-fetch/src/index.js from /Users/okankarlidag/Downloads/hashlips_art_engine-1.1.2_patch_v6/utils/nftport/uploadFiles.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/okankarlidag/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/node-fetch/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/okankarlidag/Downloads/hashlips_art_engine-1.1.2_patch_v6/utils/nftport/uploadFiles.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
macbook-pro:hashlips_art_engine-1.1.2_patch_v6 okankarlidag$ ©

**Comment by bolshoytoster** [comment]
@okarlidag does [this](https://github.com/codeSTACKr/create-10k-nft-collection#es-module-error-err_require_esm) help?

**Comment by okarlidag** [comment]
Yes thanks a lot. 
In this time, i'v got such an error;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
macbook-pro:hashlips_art_engine-1.1.2_patch_v6 okankarlidag$ node utils/nftport/uploadFiles.js
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '${basePath}/build/images'
    at Object.readdirSync (fs.js:1047:3)
    at Object.<anonymous> (/Users/okankarlidag/Downloads/hashlips_art_engine-1.1.2_patch_v6/utils/nftport/uploadFiles.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '${basePath}/build/images'
}
macbook-pro:hashlips_art_engine-1.1.2_patch_v6 okankarlidag$

**Comment by bolshoytoster** [comment]
@okarlidag can you please use the [latest version](https://github.com/codeSTACKr/create-10k-nft-collection/archive/refs/tags/v2.0.0.zip) of that code.

**Comment by okarlidag** [comment]
I just used the latest version that you suggest but I got completely same error above. What can i do apart from this? By the way, thank you for helping. It means a lot.

**Comment by bolshoytoster** [comment]
@okarlidag you shouldn't get the same error, could you paste the error please.
