### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by internetsurfer666** [HashLips/hashlips_art_engine#1098]
please help, I did it on my Mac 2018. I've installed node-v16.14.1.pkg

admin@192 hashlips_art_engine-1.0.8_update % npm install

up to date, audited 69 packages in 727ms

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
admin@192 hashlips_art_engine-1.0.8_update copy %

**Comment by internetsurfer666** [comment]
admin@192 hashlips_art_engine-1.0.8_update copy % npm install

up to date, audited 69 packages in 727ms

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
admin@192 hashlips_art_engine-1.0.8_update copy % npm fund
hashlips_art_engine@1.0.5
├── https://github.com/sponsors/sindresorhus
│   └── make-dir@3.1.0, mimic-response@2.1.0
├── https://github.com/sponsors/isaacs
│   └── rimraf@3.0.2, glob@7.1.7
└── https://github.com/sponsors/feross
    └── simple-concat@1.0.1

admin@192 hashlips_art_engine-1.0.8_update copy %

**Comment by internetsurfer666** [comment]
admin@192 hashlips_art_engine-1.0.8_update copy % npm install

up to date, audited 69 packages in 814ms

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
admin@192 hashlips_art_engine-1.0.8_update copy % node index.js
(node:71049) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/layers/backgound fire/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (/Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/src/main.js:71:6)
    at /Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/src/main.js:87:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/src/main.js:85:30)
    at startCreating (/Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/src/main.js:300:20)
    at /Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/index.js:13:3
    at Object.<anonymous> (/Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/admin/Documents/generate1/hashlips_art_engine-1.0.8_update copy/layers/backgound fire/'
}
admin@192 hashlips_art_engine-1.0.8_update copy %

**Comment by bolshoytoster** [comment]
@internetsurfer666 in your `src/config.js`, you define the layer `backgound fire`. Could you make sure the folder under `layers/` is called the exact same (it's case sensitive).
