### ISSUE TITLE
node index.js not working

### ISSUE THREAD

**Issue by eyjun** [HashLips/hashlips_art_engine#1100]
**I didn't change any default, but I can't build anything.**

C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>node index.js
(node:30376) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)      
C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: EILSEQ, Illegal byte sequence 'C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/Background/Black#1.png'
    at setSource (C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
}
                                                                      C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:19272) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: EILSEQ, Illegal byte sequence 'C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/Background/Black#1.png'
    at setSource (C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\영준\Desktop\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 42,
  code: 'EILSEQ',
  path: 'C:\\Users\\영준\\Desktop\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6/layers/Background/Black#1.png',
  syscall: 'fopen'
}

**Comment by bolshoytoster** [comment]
@eyjun Your username is non-ascii, so you'll have to move the project folder into somewhere like `C:/Users/Public/`.
