### ISSUE TITLE
  code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by xrayexx** [HashLips/hashlips_art_engine#1104]
Hi guys, hope you can help me. I was trying to deploy initially a few NFT using the original code - I have not change anything from the code but receiving below error after installing dependencies and running "node index.js". Below is the terminal logs

PS C:\Users\Cecille\Desktop\HASHLIPS\hashlips_art_engine-1.1.2_patch_v6> npm install

up to date, audited 66 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\Cecille\Desktop\HASHLIPS\hashlips_art_engine-1.1.2_patch_v6> node index.js
node:internal/modules/cjs/loader:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Cecille\Desktop\HASHLIPS\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node is not a valid Win32 application.
\\?\C:\Users\Cecille\Desktop\HASHLIPS\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Cecille\Desktop\HASHLIPS\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by bolshoytoster** [comment]
@xrayexx I think you've installed the wrong achitechture of node (x86/x64) make sure you install the one that matches your system.

**Comment by Nanerito** [comment]
> @xrayexx I think you've installed the wrong achitechture of node (x86/x64) make sure you install the one that matches your system.

how to install that?

**Comment by bolshoytoster** [comment]
@Nanerito given [your comment](https://github.com/HashLips/hashlips_art_engine/issues/245#issuecomment-1116350769) from a few hours ago, I assume you don't get this error. If you do, could you please paste it here.

**Comment by TimeKeyRoll** [comment]
> @Nanerito given [your comment](https://github.com/HashLips/hashlips_art_engine/issues/245#issuecomment-1116350769) from a few hours ago, I assume you don't get this error. If you do, could you please paste it here.

Hey! I have this error. How do i fix this?

```

PS D:\hardhat-erc20-fcc> npx hardhat compile
An unexpected error occurred:

Error: The specified module could not be found.
\\?\D:\hardhat-erc20-fcc\node_modules\@nomicfoundation\solidity-analyzer-win32-x64-msvc\solidity-analyzer.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (D:\hardhat-erc20-fcc\node_modules\@nomicfoundation\solidity-analyzer\index.js:69:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by bolshoytoster** [comment]
@MasterofBlockchain did you get any errors running `npm install`? You should probably open an issue in the repo you got the code from, presumably [this](https://github.com/PatrickAlphaC/hardhat-erc20-fcc).

**Comment by TimeKeyRoll** [comment]
Thanks! I have figured. Newer hardhat version ain't compatible with it. So I have had to go back to th elder version which made it work.
