### ISSUE TITLE
npm run generate does not work

### ISSUE THREAD

**Issue by Sasaofficial** [HashLips/hashlips_art_engine#1110]
hi, I have the problem that when I give the command npm run generate it does nothing.
I have already uninstalled and reinstalled node js and visual studio code several times, but the problem persists.
Now I'm trying with the original file without any changes, but it doesn't work.

PS C:\Users\Sasà\Desktop\hashlips_art_engine-1.1.2_patch_v6> node -v
v14.18.2

audited 65 packages in 0.641s

6 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\Sasà\Desktop\hashlips_art_engine-1.1.2_patch_v6>     
PS C:\Users\Sasà\Desktop\hashlips_art_engine-1.1.2_patch_v6> npm run generate
PS C:\Users\Sasà\Desktop\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@Sasaofficial could you paste your `src/config.js` file please, and make sure you've save it,

**Comment by Sasaofficial** [comment]
const basePath = process.cwd();
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "Your Collection";
const description = "Remember to replace this description";
const baseUri = "ipfs://NewUriToReplace";

const solanaMetadata = {
  symbol: "YC",
  seller_fee_basis_points: 1000, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://www.youtube.com/c/hashlipsnft",
  creators: [
    {
      address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC",
      share: 100,
    },
  ],
};

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color" },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid" },
      { name: "Top lid" },
    ],
  },
];

const shuffleLayerConfigurations = false;

const debugLogs = false;

const format = {
  width: 512,
  height: 512,
  smoothing: false,
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: true,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const extraMetadata = {};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,
};

**Comment by Sasaofficial** [comment]
I have not touched anything

**Comment by bolshoytoster** [comment]
@Sasaofficial I have no clue then, you could try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by Sasaofficial** [comment]
it does the same thing to me

**Comment by bolshoytoster** [comment]
@Sasaofficial does it create the `build/` folder? If so, could you paste the output of `Get-ChildItem -Recurse build`.

**Comment by Sasaofficial** [comment]
PS C:\Users\Sasà\Desktop\hashlips_art_engine-main> Get-ChildItem -Recurse build

    Directory: C:\Users\Sasà\Desktop\hashlips_art_engine-main\build


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        20/04/2022     14:33                images
d-----        20/04/2022     14:33                json


PS C:\Users\Sasà\Desktop\hashlips_art_engine-main> npm run generate
PS C:\Users\Sasà\Desktop\hashlips_art_engine-main>

**Comment by Sasaofficial** [comment]
this is using your fork, but nothing

**Comment by bolshoytoster** [comment]
@Sasaofficial what if you just run `node index.js`?

**Comment by Sasaofficial** [comment]
PS C:\Users\Sasà\Desktop\hashlips_art_engine-main> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\Sasà\Desktop\hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node'
Require stack:
- C:\Users\Sasà\Desktop\hashlips_art_engine-main\src\main.js
- C:\Users\Sasà\Desktop\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\Sasà\Desktop\hashlips_art_engine-main\src\main.js:26:5)    
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Sasà\\Desktop\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\Sasà\\Desktop\\hashlips_art_engine-main\\index.js'
  ]
}

**Comment by bolshoytoster** [comment]
@Sasaofficial could you try deleting the `node_modules/` folder and run `npm install` again.

**Comment by Sasaofficial** [comment]
i have delete node modules and run npm install, but nothing

PS C:\Users\Sasà\Desktop\hashlips_art_engine-main> 

 Session contents restored from 22/4/2022 at 18:57:21 

Copyright (C) Microsoft Corporation. Tutti i diritti riservati.

Prova la nuova PowerShell multipiattaforma https://aka.ms/pscore6

npm WARN hashlips_art_engine@1.1.1 No repository field.

added 66 packages from 35 contributors and audited 66 packages in 0.701s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\Sasà\Desktop\hashlips_art_engine-main> npm run generate
PS C:\Users\Sasà\Desktop\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@Sasaofficial can you just run `node index.js` instead of `npm run generate`.

**Comment by Sasaofficial** [comment]
PS C:\Users\Sasà\Desktop\hashlips_art_engine-main> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\Sasà\Desktop\hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node'
Require stack:
- C:\Users\Sasà\Desktop\hashlips_art_engine-main\src\main.js
- C:\Users\Sasà\Desktop\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\Sasà\Desktop\hashlips_art_engine-main\src\main.js:26:5)     
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Sasà\\Desktop\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\Sasà\\Desktop\\hashlips_art_engine-main\\index.js'
  ]
}

**Comment by 0xFannie** [comment]
I met the same error with Sasao...

Error: Cannot find module 'C:\Users\Sasà\Desktop\hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node'
Require stack:
