### ISSUE TITLE
Removing edition from metadata 

### ISSUE THREAD

**Issue by Carlitos353** [HashLips/hashlips_art_engine#1111]

**Comment by Carlitos353** [comment]
If i remove "edition: _edition " from main.js it gives me an error

**Comment by bolshoytoster** [comment]
@Carlitos353 what is the error?

**Comment by Carlitos353** [comment]
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2148:5)
    at saveMetaDataSingleFile (C:\Users\root\Desktop\hashlips_art_engine-main\src\main.js:313:6)
    at C:\Users\root\Desktop\hashlips_art_engine-main\src\main.js:402:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (C:\Users\root\Desktop\hashlips_art_engine-main\src\main.js:367:9) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by bolshoytoster** [comment]
@edenheijer you'd have to just remove `edition` from the resulting metadata:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L137-L139

https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L154-L156

**Comment by edenheijer** [comment]
was i mentioned by accident?

**Comment by bolshoytoster** [comment]
@edenheijer yes, sorry. It was meant for @Carlitos353
