### ISSUE TITLE
(node:133333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by ebuka-odih** [HashLips/hashlips_art_engine#112]
i got this error when i run (npm run build)

> hashlips_art_engine@1.0.5 build /home/gnosis/Desktop/NFT/hashlips_art_engine
> node index.js

(node:133333) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/home/gnosis/Desktop/NFT/hashlips_art_engine/layers/Background/'
    at Object.readdirSync (fs.js:974:3)
    at getElements (/home/gnosis/Desktop/NFT/hashlips_art_engine/src/main.js:67:6)
    at /home/gnosis/Desktop/NFT/hashlips_art_engine/src/main.js:83:15
    at Array.map (<anonymous>)
    at layersSetup (/home/gnosis/Desktop/NFT/hashlips_art_engine/src/main.js:81:30)
    at startCreating (/home/gnosis/Desktop/NFT/hashlips_art_engine/src/main.js:270:20)
    at /home/gnosis/Desktop/NFT/hashlips_art_engine/index.js:13:3
    at Object.<anonymous> (/home/gnosis/Desktop/NFT/hashlips_art_engine/index.js:14:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:133333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:133333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Judd515** [comment]
do your layers have a dash in the filename?  Was the cause of this issue for me.
