### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 

### ISSUE THREAD

**Issue by diegogerig** [HashLips/hashlips_art_engine#1129]
Could someone help me, I don't understand why it can't find the Eyes folder, when I remove it from the layers folder and run the command npm run generate everything works, but if I put the Eyes folder in layers it doesn't work anymore and gives that error

diegogerigherrera@MBP-de-Diego hashlips_art_engine % npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:20305) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1413
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/layers/Eyes/'
    at Object.readdirSync (node:fs:1413:3)
    at getElements (/Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/src/main.js:73:6)
    at /Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/src/main.js:90:30)
    at startCreating (/Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/src/main.js:356:20)
    at /Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/diegogerigherrera/Desktop/Layers/NFTs/hashlips_art_engine/layers/Eyes/'
}

Node.js v18.0.0
diegogerigherrera@MBP-de-Diego hashlips_art_engine %

**Comment by diegogerig** [comment]
I managed to solve it, it was a typography error
