### ISSUE TITLE
node index.js doesn't work

### ISSUE THREAD

**Issue by mya1266** [HashLips/hashlips_art_engine#1165]
(node:8348) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\layers/body line art/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\src\main.js:71:6)
    at C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\src\main.js:87:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\src\main.js:85:30)
    at startCreating (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\src\main.js:300:20)
    at C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\index.js:6:3
    at Object.<anonymous> (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Asus\\OneDrive\\Masaüstü\\hashlips_art_engine-1.0.8_update\\layers/body line art/'
}
PS C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-1.0.8_update> 

Can anyone help fixing it?

**Comment by bolshoytoster** [comment]
@mya1266 you've probably misspelled `body line art` either in your `layers/` folder or your `layersOrder`.

**Comment by mya1266** [comment]
I fixed it but not it gives me this error

node index.js
(node:16884) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main/layers/rings/ring #1.PNG'
    at setSource (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\src\main.js:184:12)
    at C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\Asus\\OneDrive\\Masaüstü\\hashlips_art_engine-main/layers/rings/ring #1.PNG',
  syscall: 'fopen'
}
PS C:\Users\Asus\OneDrive\Masaüstü\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@mya1266 that's because you have non-ascii characters in your path. Try moving the project to somewhere like just `C:/Users/Asus`.

**Comment by mya1266** [comment]
thank you sooo much I have been tryna fix it for days

**Comment by mya1266** [comment]
its give me this after generating 4 image  how can I fix it?
 Error: Unsupported image type
    at setSource (C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\Asus\Nft collection\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Asus\Nft collection\hashlips_art_engine-main\src\main.js:184:12)
    at C:\Users\Asus\Nft collection\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)
PS C:\Users\Asus\Nft collection\hashlips_art_engine-main>

Thanku for helpp

**Comment by bolshoytoster** [comment]
@mya1266 try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by tylerblack26** [comment]
One of your images is probably saved as a different file type. make sure all of your images are saved as the png file type

> its give me this after generating 4 image how can I fix it? Error: Unsupported image type at setSource (C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13) at Image.set (C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9) at C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\index.js:34:15 at new Promise () at loadImage (C:\Users\Asus\Nft collection\hashlips_art_engine-main\node_modules\canvas\index.js:23:10) at C:\Users\Asus\Nft collection\hashlips_art_engine-main\src\main.js:185:27 at new Promise () at loadLayerImg (C:\Users\Asus\Nft collection\hashlips_art_engine-main\src\main.js:184:12) at C:\Users\Asus\Nft collection\hashlips_art_engine-main\src\main.js:368:31 at Array.forEach () PS C:\Users\Asus\Nft collection\hashlips_art_engine-main>
> 
> Thanku for helpp
