### ISSUE TITLE
Error..Error..

### ISSUE THREAD

**Issue by GGOMND** [HashLips/hashlips_art_engine#1175]
Error: EBUSY: resource busy or locked, open 'C:\hashlips_art_engine-1.1.2_patch_v6/build/images/undefined.png'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at saveImage (C:\hashlips_art_engine-1.1.2_patch_v6\src\main.js:114:6)
    at C:\hashlips_art_engine-1.1.2_patch_v6\src\main.js:404:11
    at async startCreating (C:\hashlips_art_engine-1.1.2_patch_v6\src\main.js:371:9) {
  errno: -4082,
  syscall: 'open',
  code: 'EBUSY',
  path: 'C:\\hashlips_art_engine-1.1.2_patch_v6/build/images/undefined.png'

Hello.
I've never seen such an error.
Can you solve it?
Let me know if you can. I beg you.
I am ashamed of my poor English.

**Comment by Dimkeee777** [comment]
Нажмите на файл package.json и нажмите отладка. после чего установите npm install, вуаля npm run build и должно все получиться, по крайней мере у меня получилось

**Comment by GGOMND** [comment]
> Нажмите на файл package.json и нажмите отладка. после чего установите npm install, вуаля npm run build и должно все получиться, по крайней мере у меня получилось

Click Debug, npm install, voila npmrun build not found.

**Comment by GGOMND** [comment]
> Нажмите на файл package.json и нажмите отладка. после чего установите npm install, вуаля npm run build и должно все получиться, по крайней мере у меня получилось

Thank you for your help. But I failed again.

**Comment by bolshoytoster** [comment]
@GGOMND try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), I've fixed the `undefined.png`.
