### ISSUE TITLE
Error on main.js when trying to build on v1.0.7

### ISSUE THREAD

**Issue by ericklborges** [HashLips/hashlips_art_engine#119]
I am getting an error when I try to build.

The log says `1.0.5` but I am running on `main` which is `1.0.7` already.

```bash
npm run build

> hashlips_art_engine@1.0.5 build
> node index.js

/Users/root/Git/hashlips_art_engine/src/main.js:85
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/root/Git/hashlips_art_engine/index.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I do not have experience with JS, please let me know what informations I should provide to help figure it out.

**Comment by ericklborges** [comment]
Plus, when I checkout to `1.0.6` everything works fine

**Comment by mertozoner** [comment]
Same here; I've found the solution with deleting the ".options?." part, but when I run the code, It's slow like version 1.0.6. So, there has to be another solution.

**Comment by fullakingi** [comment]
Just  confirming that this fix worked for me.

**Comment by mertozoner** [comment]
Also, another and the best solution is to update node.js to the **latest version**. It worked for me.

**Comment by IvanGarzon** [comment]
@dylan96dashintha Thanks, this worked for me.
