### ISSUE TITLE
Error while running on cpanel

### ISSUE THREAD

**Issue by abdullahtilalcodup** [HashLips/hashlips_art_engine#1199]
**I am having this issue when I run app on cpanel terminal.**

return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/stgbm/nfts/hashlipsOld/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/stgbm/nfts/hashlipsOld/src/main.js:28:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bolshoytoster** [comment]
@abdullahtilalcodup [this stackexchange question](https://superuser.com/q/1432321) has some useful answers, could you paste the output of the command `strings /lib64/libstdc++.so.6 | grep '^CXXABI_'` here please.
