### ISSUE TITLE
Error with V1.0.7

### ISSUE THREAD

**Issue by Sathyagithub1** [HashLips/hashlips_art_engine#120]
Did Install Yarn
Deleted the folders in "Layers" Folder and uploaded my Layers
Updated layersorder on config.js
When run below error found
   at startCreating (C:\Users\Sathyamoorthy\Desktop\hashlips_art_engine-1.0.7_update\src\main.js:270:20)
    at C:\Users\Sathyamoorthy\Desktop\hashlips_art_engine-1.0.7_update\index.js:13:3
    at Object.<anonymous> (C:\Users\Sathyamoorthy\Desktop\hashlips_art_engine-1.0.7_update\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Sathyamoorthy\\Desktop\\hashlips_art_engine-1.0.7_update\\layers/Background/'}

![image](https://user-images.githubusercontent.com/67992663/137606392-1ef52190-6629-4424-993e-304aee8bf882.png)

**Comment by Jinxto94** [comment]
then save

**Comment by Jinxto94** [comment]
In your terminal, on the path line.... it's trying to pull from a different path than your folders name, so you could also just rename the folder and the the s off and save.

**Comment by Sathyagithub1** [comment]
My bad, I didnot save before running. Now after saving, it worked fine. Thanks.

**Comment by Sathyagithub1** [comment]
Thanks for this genius code.
