### ISSUE TITLE
node index.js error

### ISSUE THREAD

**Issue by scottskeel** [HashLips/hashlips_art_engine#1208]
Scott@DESKTOP-RICNRBN MINGW64 ~/Desktop/hashlips_art_engine (main)
$ node index.js
(node:7192) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Scott\Desktop\hashlips_art_engine/layers/Eyeball/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Scott\Desktop\hashlips_art_engine\src\main.js:73:6)
    at C:\Users\Scott\Desktop\hashlips_art_engine\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Scott\Desktop\hashlips_art_engine\src\main.js:90:30)
    at startCreating (C:\Users\Scott\Desktop\hashlips_art_engine\src\main.js:356:20)
    at C:\Users\Scott\Desktop\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\Scott\Desktop\hashlips_art_engine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Scott\\Desktop\\hashlips_art_engine/layers/Eyeball/'
}

Scott@DESKTOP-RICNRBN MINGW64 ~/Desktop/hashlips_art_engine (main)
$

**Comment by bolshoytoster** [comment]
@scottskeel make sure you save `src/config.js`.
