### ISSUE TITLE
package.json not found

### ISSUE THREAD

**Issue by NirSanasm** [HashLips/hashlips_art_engine#1213]
I am getting this error when I run "yarn generate"

PS D:\nft\hashlips_art_engine-main> yarn generate
yarn run v1.22.15
error Couldn't find a package.json file in "D:\\nft\\hashlips_art_engine-main"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@Niranjit123 you're in the wrong folder, you can run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by NirSanasm** [comment]
What will be the correct folder to run this command?

**Comment by NirSanasm** [comment]
When I run "yarn" it outputs like this. 


PS D:\nft\hashlips_art_engine-main> yarn
yarn install v1.22.15
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.18s.
PS D:\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@Niranjit123
> What will be the correct folder to run this command?

It'll be something like `hashlips_art_engine-main`, but not the one you're currently in; please refer to the comment I assume you read:
> you can run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by NirSanasm** [comment]
Sorry for bothering you again and  again. I am a newbie. I have a folder like from where I should run this command. I have also included the link for screenshot of my folder

D:\nft\hashlips_art_engine-main\hashlips_art_engine-main
[https://drive.google.com/file/d/1_5MBhpM_Lke1M-xT9gkaGaU1LdMgYy4Z/view?usp=sharing](url)
[https://drive.google.com/file/d/1qhM-E9KyD5MkVxUeVmu-FKsobGNITPHJ/view?usp=sharing](url)

**Comment by NirSanasm** [comment]
ooh this link does not work

**Comment by NirSanasm** [comment]
D:\nft\hashlips_art_engine-main\hashlips_art_engine-main

This is my folder structure.

**Comment by NirSanasm** [comment]
I tried on D:\nft\hashlips_art_engine-main\hashlips_art_engine-main . And  i got this 


PS D:\nft\hashlips_art_engine-main\hashlips_art_engine-main> yarn generate
yarn run v1.22.15
$ node index.js
D:\nft\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
←[90m    at Object.compileFunction (vm.js:344:18)←[39m
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1048:15)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1082:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (D:\nft\hashlips_art_engine-main\hashlips_art_engine-main\index.js:2:39)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
error Command failed with exit code 1.

**Comment by bolshoytoster** [comment]
@Niranjit123 you need to either update node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
