### ISSUE TITLE
npm run build, yarn build and node index.js not working

### ISSUE THREAD

**Issue by Kaytee-dev** [HashLips/hashlips_art_engine#1218]
C:\Users\Public\hashlips_art_engine>node index.js
(node:13892) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Public\hashlips_art_engine/layers/undefined/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Public\hashlips_art_engine\src\main.js:73:6)
    at C:\Users\Public\hashlips_art_engine\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Public\hashlips_art_engine\src\main.js:90:30)
    at startCreating (C:\Users\Public\hashlips_art_engine\src\main.js:356:20)
    at C:\Users\Public\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\Public\hashlips_art_engine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Public\\hashlips_art_engine/layers/undefined/'
}

I just replace the layer folder with mine and added new attributes to the src/config.js file and the build does not work

**Comment by bolshoytoster** [comment]
@Kaytee-dev could you paste your `layersConfigurations` here please.

**Comment by Kaytee-dev** [comment]
@bolshoytoster  I was able to resolve it, the problem arises from adding custom attributes in the layersOrder
which I wish to show the custom rarity like "legendary, rare, common".

This is the code that causes the error
const layerconfiguration : [
//this is for the 100 common Nft
{
growEditionSizeTo: 100,
layersOrder : [
  { name: "Background"},
  { name: "Body"},
  {"attributes" : [
"trait_type" : "Rarity",
"value" : "common"
       ],
     },
   ],
 },

//this is for the additional 20 rare Nft
{
growEditionSizeTo: 120,
layersOrder : [
  { name: "Background"},
  { name: "Body"},
  { name: "Rare layer'},
  {"attributes" : [
"trait_type" : "Rarity",
"value" : "Rare"
       ],
     },
   ],
 },

//this is for the additional 5 legendary Nft
{
growEditionSizeTo: 125,
layersOrder : [
  { name: "Background"},
  { name: "Body"},
  { name: "Legendary Layer'},
  {"attributes" : [
"trait_type" : "Rarity",
"value" : "Legendary"
       ],
     },
   ],
 },
],

@bolshoytoster do you know how I can implement the custom rarity in the metadata for each nft

**Comment by bolshoytoster** [comment]
@Kaytee-dev you still need a `name` property for each `layersOrder` object, and what you're trying to do isn't currently supported.

You could create a `layers/` folder structure like this:
```js
layers/
| Background/
  | ...
| Body/
  | ...
| ...
| Rarity/
  | common
    | common.png // fully transparent
  | Rare
    | Rare.png
  | Legendary
    | Legendary.png
```
Then have your `layersOrder`s like:
```js
layersOrder : [
  { name: "Background"},
  { name: "Body"},
  ...
  {
    name: "Rarity/common", // change this for the others
    options: {
      displayName: "Rarity",
    },
  },
],
```

**Comment by Kaytee-dev** [comment]
@bolshoytoster I will try that out too.

Thanks for your contribution

**Comment by Kaytee-dev** [comment]
@bolshoytoster it works.

Thanks for your help🙏🫂
