### ISSUE TITLE
node index.js not working

### ISSUE THREAD

**Issue by asamox** [HashLips/hashlips_art_engine#1234]
save the config.js and didn't change any default 😢

`kiki@MacBook-Pro hashlips_art_engine-main % node index.js
(node:7822) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: 27953e0009d587ac0d1b434406e5be2c15d092ae
Created edition: 2, with DNA: 0961dc2312a5a4397db734b592c07ac3ed3e0adf
/Users/kiki/Documents/hashlips_art_engine-main/node_modules/canvas/lib/image.js:91
  SetSource.call(img, src);
            ^

Error: node-canvas was built without JPEG support
    at setSource (/Users/kiki/Documents/hashlips_art_engine-main/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/kiki/Documents/hashlips_art_engine-main/node_modules/canvas/lib/image.js:62:9)
    at /Users/kiki/Documents/hashlips_art_engine-main/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/kiki/Documents/hashlips_art_engine-main/node_modules/canvas/index.js:23:10)
    at /Users/kiki/Documents/hashlips_art_engine-main/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/kiki/Documents/hashlips_art_engine-main/src/main.js:184:12)
    at /Users/kiki/Documents/hashlips_art_engine-main/src/main.js:368:31
    at Array.forEach (<anonymous>)

Node.js v18.3.0`

**Comment by bolshoytoster** [comment]
@asamox [this stackoverflow answer](https://stackoverflow.com/a/70064802) suggests running `npm install canvas@2.9.0`.
