### ISSUE TITLE
what is problem ?

### ISSUE THREAD

**Issue by peaceofbulldog** [HashLips/hashlips_art_engine#1242]
Error: EILSEQ, Illegal byte sequence 'C:\Users\Desktop\hashlips_art_engine-main/layers/Background/Black#1.png'
    at setSource (C:\Users\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\Desktop\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Desktop\hashlips_art_engine-main\src\main.js:184:12)
    at C:\Users\Desktop\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 42,
  code: 'EILSEQ',
  path: 'C:\\Users\\Desktop\\hashlips_art_engine-main/layers/Background/Black#1.png',
  syscall: 'fopen'
}

**Comment by peaceofbulldog** [comment]
find out the path way, hashlips file is install to c drive 
that is working
