### ISSUE TITLE
Cant figure out how to update the Uri from Pinata.

### ISSUE THREAD

**Issue by Phall3** [HashLips/hashlips_art_engine#1248]
I updated the Uri in config from my CID. After I save and enter the command "node utils/updateBaseUri.js" I get this error:

  throw err;
  ^

Error: Cannot find module '/Users/patrickhall/Desktop/Master Class/hashlips_art_engine-1.1.2_patch_v6/utils/updateBaseUri.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

Does anyone know how I can fix this?

**Comment by bolshoytoster** [comment]
@Phall3 `utils/updateBaseUri.js` is now `utils/update_info.js`.

**Comment by Phall3** [comment]
> @Phall3 `utils/updateBaseUri.js` is now `utils/update_info.js`.

You are awesome

**Comment by denboydoc** [comment]
After the images and json files created and images loaded to Pinata - Ive got CID
Ok, then I changed config.json line 10 const baseUri = "ipfs://<my pinata CID>";
now I have to update the baseUri and run "npm run update_info"

the output is following:
Updated description for images to ===> Welcome back home
Updated name prefix for images to ===> Panda_life
Updated creators for images to ===> [{"address":"<ADDRESS>","share":100}]

baseUri still not updated....

could you help to find solution (p.s. its solana)

**Comment by bolshoytoster** [comment]
@denboydoc hashlips doesn't set a baseUri for solana, it presumably doesn't need one.

**Comment by denboydoc** [comment]
> @denboydoc hashlips doesn't set a baseUri for solana, it presumably doesn't need one.

So is it enough just to past my Pinata CID to  const baseUri = "ipfs:/xxxxx/" in config.json file?
How to use Pinata or another ipfs storage for Solana?

**Comment by denboydoc** [comment]
@bolshoytoster So is it enough just to past my Pinata CID to const baseUri = "ipfs:/xxxxx/" in config.json file?
 How to use Pinata or another ipfs storage for Solana?

**Comment by bolshoytoster** [comment]
@denboydoc I'm not sure if you can use pinata for solana.

**Comment by denboydoc** [comment]
@bolshoytoster thank you
