### ISSUE TITLE
Node index.js

### ISSUE THREAD

**Issue by valar964** [HashLips/hashlips_art_engine#1257]
PS C:\hashlips_art_engine-1.1.2_patch_v6> node index.js
(node:18952) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'C:\hashlips_art_engine-1.1.2_patch_v6/layers/Ayakkabı/Orange#10.png'
    at setSource (C:\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\hashlips_art_engine-1.1.2_patch_v6/layers/Ayakkabı/Orange#10.png',
  syscall: 'fopen'
}
PS C:\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@valar964 unfortunately, the library we use to load images (canvas) doesn't work if you have non-ascii characters in your path.

Unfortunately, that means you'll have to get rid of the `ı` in the `Ayakkabı` layer name, but you could still re-add it with a find+replace in the `build/json/_metadata.json` file with basically any text editor then running `node utils/update_info.js` to update the individual files.
