### ISSUE TITLE
Cannot generate

### ISSUE THREAD

**Issue by Tusardutta** [HashLips/hashlips_art_engine#1263]
TypeError: Cannot read properties of undefined (reading 'edition')
    at C:\Users\91943\Dropbox\PC\Desktop\t folder\hashlips_art_engine-1.1.1_update\src\main.js:307:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (C:\Users\91943\Dropbox\PC\Desktop\t folder\hashlips_art_engine-1.1.1_update\src\main.js:307:31)
    at C:\Users\91943\Dropbox\PC\Desktop\t folder\hashlips_art_engine-1.1.1_update\src\main.js:402:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (C:\Users\91943\Dropbox\PC\Desktop\t folder\hashlips_art_engine-1.1.1_update\src\main.js:367:9)
trying to generate but this error is comming

**Comment by bolshoytoster** [comment]
@Tusardutta can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by Tusardutta** [comment]
@bolshoytoster how to use my fork

**Comment by bolshoytoster** [comment]
@Tusardutta the fork that I maintain is just a more up to date hashlips. Just use it the same way you use hashlips.

**Comment by wylim6783** [comment]
### npm install error

I'm Windows 10 with nodejs & npm installation. But hit the error after enter npm install. Appreciate if I'd get solution to fix it & continue to move on as it's just the beginning...🙏


Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> node -v
v14.18.2
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm -v
6.14.15
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm install

> canvas@2.8.0 install C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas 
> node-pre-gyp install --fallback-to-build

The system cannot find the path specified.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\@mapbox\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN hashlips_art_engine@1.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pauline&Rueben\AppData\Roaming\npm-cache\_logs\2022-06-19T11_03_27_282Z-debug.log

**Comment by bolshoytoster** [comment]
@wylim6783 that's weird, you could try installing `node-pre-gyp` with `npm install node-pre-gyp`. If it gives the same error you could try installing it globally with `npm install -g node-pre-gyp` (you'll need to run it in an admin powershell/cmd).

**Comment by ghost** [comment]
Sorry, I suposed to drop the new issue from my account but accidentally used other ppl account to ask for help.
Yes, is it ok as shown as below?


PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm install -g node-pre-gyp
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
C:\Users\Pauline&Rueben\AppData\Roaming\npm\node-pre-gyp -> C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp
+ node-pre-gyp@0.17.0
added 67 packages from 25 contributors in 6.289s
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@wylim6783 try running `npm install` again.

**Comment by ghost** [comment]
It's same. But I don't know how run as an admin powershell just now then I type npm install -g node-pre-gyp. I thought it should be fine but after npm install, it come back error again. Could you show me how to run as admin powershell?



Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm install -g node-pre-gyp
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
C:\Users\Pauline&Rueben\AppData\Roaming\npm\node-pre-gyp -> C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp
+ node-pre-gyp@0.17.0
updated 1 package in 4.647s
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6> npm install

> canvas@2.8.0 install C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas 
> node-pre-gyp install --fallback-to-build

The system cannot find the path specified.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\@mapbox\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN hashlips_art_engine@1.1.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pauline&Rueben\AppData\Roaming\npm-cache\_logs\2022-06-19T12_04_34_413Z-debug.log
PS C:\Users\Pauline&Rueben\Desktop\NFT project\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@wylim6783 could you try running `New-Item -Path C:\Users@mapbox -ItemType SymbolicLink -Value C:\Users\Pauline&Rueben\AppData\Roaming\npm\node_modules` to create a symlink to maybe make it work.

You'll probably have to run this in an admin powershell (when running, right click -> run as administrator).

**Comment by ghost** [comment]
I haven't run it yet as I don't understand on which screen to right click. Btw, could you please head over to issue #1264? That's mine....Sorry

**Comment by ermiasabera** [comment]
I am having the same problems. 
PS D:\HASHLIPS\hashlips_art_engine-1.0.8_update> npm run generate

> hashlips_art_engine@1.0.5 generate D:\HASHLIPS\hashlips_art_engine-1.0.8_update
> node index.js

D:\HASHLIPS\hashlips_art_engine-1.0.8_update\src\main.js:89
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\HASHLIPS\hashlips_art_engine-1.0.8_update\index.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.0.5 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.0.5 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\123\AppData\Roaming\npm-cache\_logs\2022-06-23T10_01_39_267Z-debug.log
PS D:\HASHLIPS\hashlips_art_engine-1.0.8_update>

**Comment by bolshoytoster** [comment]
@ermiasabera you need to either upgrade your node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
