### ISSUE TITLE
npm run generate error

### ISSUE THREAD

**Issue by Acexxp** [HashLips/hashlips_art_engine#1265]
I don't understand why it is not working!! help me

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:16356) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6/layers/BACKGROUND/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)       
    at C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)      
    at startCreating (C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)   
    at C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\ahmed\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)    
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\ahmed\\OneDrive\\Desktop\\hashlips_art_engine-1.1.2_patch_v6/layers/BACKGROUND/'
}

**Comment by bolshoytoster** [comment]
@Acexxp it can't find `layers/BACKGROUND`, make sure your folder names match the layer names in your `layersOrder`s exactly (case-sensitive as well).

**Comment by Acexxp** [comment]
> @Acexxp it can't find `layers/BACKGROUND`, make sure your folder names match the layer names in your `layersOrder`s exactly (case-sensitive as well).

it was the dashes "-"  hhhhh xp btw thx mate
