### ISSUE TITLE
node index.js not working

### ISSUE THREAD

**Issue by cool4556** [HashLips/hashlips_art_engine#1271]
PS C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by bolshoytoster** [comment]
@cool4556 run `cd ..` then you can run `node index.js`.

**Comment by cool4556** [comment]
still does not work

**Comment by bolshoytoster** [comment]
@cool4556 can you paste the error please

**Comment by cool4556** [comment]
Error: Cannot find module 'C:\Users\hudson\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by bolshoytoster** [comment]
@cool4556 `cd` is relative to your current path, opening a new terminal resets your path.

Just run `cd C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main` to go to the correct place.

**Comment by cool4556** [comment]
it still isn't working

**Comment by cool4556** [comment]
Error: EACCES, Permission denied 'C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main/layers/body/legendary'
    at setSource (C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)        
    at Image.set (C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:180:10)
    at C:\Users\hudson\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>) {
  errno: 13,
  code: 'EACCES',
  path: 'C:\\Users\\hudson\\Desktop\\hashlips_art_engine-main\\hashlips_art_engine-main/layers/body/legendary',
  syscall: 'fopen'

**Comment by bolshoytoster** [comment]
@cool4556 it doesn't have permission to access `layers/body/legendary`; try running this in an admin powershell.

**Comment by cool4556** [comment]
how do I do that ?

**Comment by bolshoytoster** [comment]
@cool4556 https://www.howtogeek.com/742916/how-to-open-windows-powershell-as-an-admin-in-windows-10/

**Comment by cool4556** [comment]
still does not work

**Comment by bolshoytoster** [comment]
@cool4556 can you paste the error from running it in the admin powershell please.
