### ISSUE TITLE
 layerObj.options?.["displayName"] != undefined    Error. What needs to be done?

### ISSUE THREAD

**Issue by ac6113** [HashLips/hashlips_art_engine#1281]
PS C:\Users\apurv\OneDrive\Desktop\Hashlips\hashlips_art_engine-1.1.2_patch_v6> node index.js
C:\Users\apurv\OneDrive\Desktop\Hashlips\hashlips_art_engine-1.1.2_patch_v6\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\apurv\OneDrive\Desktop\Hashlips\hashlips_art_engine-1.1.2_patch_v6\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by bolshoytoster** [comment]
@ac6113 upgrade node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by ac6113** [comment]
@bolshoytoster I sorted out the issue. Had to gradually upgrade node. Now I am facing -4058 error on both, so, saw the solution that I have to remove png files to layers, how to do that?

**Comment by ac6113** [comment]
@bolshoytoster sorted the -4058 error. Now, I am getting weird output. The images is dots like how TV used to get. Checked the layer folder for hidden files, there are none. 
(node:15528) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead     
(Use `node --trace-deprecation ...` to show where the warning was created)

Getting this error now.

**Comment by ac6113** [comment]
(process:15528): GLib-GIO-WARNING **: 10:20:16.199: Unexpectedly, UWP app `Evernote.Evernote_10.39.6.0_x86__q4d96b2w5wcc2' (AUMId `Evernote.Evernote_q4d96b2w5wcc2!Evernote') supports 1 extensions but has no verbs
