### ISSUE TITLE
error with canvas or input stream

### ISSUE THREAD

**Issue by young-to** [HashLips/hashlips_art_engine#1289]
I tried running with 
node index.js
 npm run generate
  npm run build
  
  all gives this same error
  `hashlips_art_engine % npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:86924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:62:9)
    at /Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/index.js:23:10)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/hamzah/Desktop/hashlips_art_engine/src/main.js:184:12)
    at /Users/hamzah/Desktop/hashlips_art_engine/src/main.js:368:31
    at Array.forEach (<anonymous>)
(node:86924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
(node:86924) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/hamzah/Desktop/hashlips_art_engine/node_modules/canvas/lib/image.js:91:13)`

**Comment by bolshoytoster** [comment]
@young-to use [my fork](https://github.com/bolshoytoster/hashlips_art_engine)

**Comment by zainamroti** [comment]
well, for me it was a nested folder in one of my main folders, that caused this issue, might help someone
