### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by apmg1** [HashLips/hashlips_art_engine#1301]
**** Even if the file name is changed, it shows as follows. ****

Error: layer name can not contain dashes, please fix: pixil-framec #100.png
    at C:\Users\User\Documents\hashlips_art_engine-main\src\main.js:77:15
    at Array.map (<anonymous>)
    at getElements (C:\Users\User\Documents\hashlips_art_engine-main\src\main.js:75:6)
    at C:\Users\User\Documents\hashlips_art_engine-main\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\User\Documents\hashlips_art_engine-main\src\main.js:90:30)
    at startCreating (C:\Users\User\Documents\hashlips_art_engine-main\src\main.js:356:20)
    at C:\Users\User\Documents\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\User\Documents\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
PS C:\Users\User\Documents\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@apmg1 you haven't changed the name, you need to remove the `-` from `pixil-framec #100.png`.

**Comment by apmg1** [comment]
thank you 🤗
