### ISSUE TITLE
problem for node.index

### ISSUE THREAD

**Issue by Digus01** [HashLips/hashlips_art_engine#1309]
at setSource (C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15     
    at new Promise (<anonymous>)
    at loadImage (C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:184:12)      
    at C:\Users\guigu\OneDrive\Área de Trabalho\NFTStuff\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\guigu\\OneDrive\\Área de Trabalho\\NFTStuff\\hashlips_art_engine-main\\hashlips_art_engine-main/layers/Background/Pink#100.png',
  syscall: 'fopen'
}

**Comment by bolshoytoster** [comment]
@Digus01 that's because your path has `Á` in it, try moving the project folder elsewhere.
