### ISSUE TITLE
Im getting the following - SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by LenBob2021** [HashLips/hashlips_art_engine#133]
$ npm run build

> hashlips_art_engine@1.0.5 build C:\Repo\hashlips_art_engine
> node index.js

C:\Repo\BlockChain\HashLips\hashlips_art_engine\src\main.js:85
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Repo\hashlips_art_engine\index.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by LenBob2021** [comment]
Found the solution here:
[https://github.com/HashLips/hashlips_art_engine/issues/119]
