### ISSUE TITLE
Wants to access a layer/Eyeball but i have changed the names in folder ans well as in config

### ISSUE THREAD

**Issue by Versilli0n** [HashLips/hashlips_art_engine#1339]
After i run  nvm run generate   i get this:

rror: ENOENT: no such file or directory, scandir 'C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\Simanchal Dash\Desktop\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Simanchal Dash\\Desktop\\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'

i have changed the layer files and tried several times. I also tried with making a blank folder named Eyeball yet nothing changes. It then starts saying the layer file i have /Eyes does not exist, but it does........

wadu hek i doo?

**Comment by bolshoytoster** [comment]
@Versilli0n make sure you save `src/config.js`.

**Comment by Versilli0n** [comment]
I am eternally grateful to you my king.
