### ISSUE TITLE
please help me! I got the `--location=global` error while running the ''npm run generate'' command.

### ISSUE THREAD

**Issue by ionutdarius11** [HashLips/hashlips_art_engine#1343]
npm run generate
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:14840) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:183
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:183:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:182:10)
    at C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:363:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:362:17)
    at C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\index.js:6:3
    at Object.<anonymous> (C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
PS C:\Users\adria\Desktop\hashlips_art_engine-1.1.1_update>

**Comment by bolshoytoster** [comment]
@ionutdarius11 use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by ionutdarius11** [comment]
@bolshoytoster I downloaded it and after running the command it says 
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
You need more layers or elements to grow your edition to 190 artworks! 

Also, when I check my images, I got only 10 images made only with 2 layers(background and accessories) and they also have the same dimensions

**Comment by bolshoytoster** [comment]
@ionutdarius11 how many source images do you have?

> and they also have the same dimensions

That's intentional.

**Comment by ionutdarius11** [comment]
I got 10 layers and 104 images. I created them in photoshop but after running the command some layers like eyes or nose appear to be bigger and covers other layers like the body

**Comment by bolshoytoster** [comment]
@ionutdarius11 you can use the `options` properties `width`, `height`, `posX` and `posY` to position the images, or just do it in your image editor.

**Comment by ionutdarius11** [comment]
I don't know how to access these options. Do u have any idea why it only creates 5 pictures instead of 2000 with the message "DNA exists!" shown repeatedly?

**Comment by bolshoytoster** [comment]
@ionutdarius11
> I don't know how to access these options.

https://github.com/bolshoytoster/hashlips_art_engine#options

> Do u have any idea why it only creates 5 pictures instead of 2000 with the message "DNA exists!" shown repeatedly?

No clue, you could try saving `src/config.js` though.
