### ISSUE TITLE
Help! Can't get past npm install

### ISSUE THREAD

**Issue by iMetaMoonT** [HashLips/hashlips_art_engine#1362]
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6/package.json
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\package.json'
npm ERR! enoent This is related to npm not being able 
to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:  
npm ERR!     C:\Users\Owner\AppData\Local\npm-cache\_logs\2022-08-15T02_55_23_731Z-debug-0.log
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Owner\Downloads\ha    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {     
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\package.json'
npm ERR! enoent This is related to npm not being able 
to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:  
npm ERR!     C:\Users\Owner\AppData\Local\npm-cache\_logs\2022-08-15T02_58_27_119Z-debug-0.log

**Comment by bolshoytoster** [comment]
@iMetaMoonT you're on the wrong folder, run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by iMetaMoonT** [comment]
when I put that in it gives me 2 locations?

**Comment by bolshoytoster** [comment]
@iMetaMoonT could you paste the output here please then. It should be something like `hashlips_art_engine-main`.

**Comment by iMetaMoonT** [comment]
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6> Get-ChildItem -Directory


    Directory:
    C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6        


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/15/2022   2:39 AM                hashlips_art_engine- 
                                                  1.1.2_patch_v6       
d-----         8/15/2022   2:42 AM                node_modules


PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6>        
not sure on how to read this

**Comment by bolshoytoster** [comment]
@iMetaMoonT run `cd hashlips_art_engine-
1.1.2_patch_v6`.

**Comment by iMetaMoonT** [comment]
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6> cd hashlips_art_engine- 1.1.2_patch_v6
Set-Location : A positional parameter cannot be found that accepts argument '1.1.2_patch_v6'.
At line:1 char:1
+ cd hashlips_art_engine- 1.1.2_patch_v6
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException    
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLoc  
   ationCommand
 
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6>
?
I guess I need to delete and start again?

**Comment by bolshoytoster** [comment]
@iMetaMoonT no, sorry, it should be without the space (`cd hashlips_art_engine-1.1.2_patch_v6`)

**Comment by iMetaMoonT** [comment]
OMG Ty!

**Comment by iMetaMoonT** [comment]
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm run generate
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:22568) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Owner\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'
}
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

is this the same issue
I ran it once to see if it would work and this began to occur

**Comment by bolshoytoster** [comment]
@iMetaMoonT save `src/config.js`.

**Comment by iMetaMoonT** [comment]
same error

**Comment by bolshoytoster** [comment]
@iMetaMoonT can you paste your `layersConfigurations` and the error here again please.

**Comment by iMetaMoonT** [comment]
// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 10000,
    layersOrder: [
      { name: "Background" },
      { name: "Ring" },
      { name: "BodyUnderlay" },
      { name: "Body" },
      { name: "BodyOverlay" },
      { name: "Eyes" },
      { name: "Blush" },
      { name: "Eyebrows "},
      { name: "Accessories "},

    ],
  },
];

**Comment by bolshoytoster** [comment]
@iMetaMoonT could you paste the error again please.

**Comment by iMetaMoonT** [comment]
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm run generate
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:26120) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/BodyUnderlay/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Owner\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6/layers/BodyUnderlay/'
}

**Comment by bolshoytoster** [comment]
@iMetaMoonT you need to make sure `layers/BodyUnderlay/` is spelled correctly, including case.

**Comment by iMetaMoonT** [comment]
maybe cause there was a space?
though this is new PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.


6 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm run generate
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:23584) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/Eyebrows /'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15       
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Owner\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6/layers/Eyebrows /'
}
PS C:\Users\Owner\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by iMetaMoonT** [comment]
thank u for helping its like 4am for me smh stuck on this

**Comment by bolshoytoster** [comment]
@iMetaMoonT also remove the spaces from `layersConfigurations` in `"Eyebrows "` and `"Accessories "`

**Comment by iMetaMoonT** [comment]
same error

**Comment by iMetaMoonT** [comment]
after fix

**Comment by iMetaMoonT** [comment]
Ty! Finally worked
