### ISSUE TITLE
npm run generate gives out syntaxerror

### ISSUE THREAD

**Issue by dyinq** [HashLips/hashlips_art_engine#1372]
Whenever I try to run "npm run generate" it throws up this message:

```
> hashlips_art_engine@1.1.1 generate
> node index.js

/home/ezinvestments/rustprojects/ezinvestments-db-2/hashlips_art_engine-1.1.2_patch_v6/src/main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ezinvestments/rustprojects/ezinvestments-db-2/hashlips_art_engine-1.1.2_patch_v6/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

I haven't touched or done anything to the main.js and I just simply cloned the most recent version. Is there anything I am missing?

**Comment by bolshoytoster** [comment]
@lnterger you need to either update node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by dyinq** [comment]
> @lnterger you need to either update node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

Thank you, Will try this out; If this works I'll close this issue out and mark it as resolved.

**Comment by dyinq** [comment]
I attempted to update Node JS but my CLI says that I am already up to date to Version 12.22.9.
I went ahead and attempted to use your fork but the same error message would still show up. Is there anything else I could check to retry the generation? @bolshoytoster

**Comment by bolshoytoster** [comment]
@lnterger
> I attempted to update Node JS but my CLI says that I am already up to date to Version 12.22.9.

12.22.9 is nowhere near up to date, the current lts version is 16.17.0.

> I went ahead and attempted to use your fork but the same error message would still show up.

You can't get the same error with my fork. Could you paste the error here please.

**Comment by dyinq** [comment]
> 
@bolshoytoster 
Sorry, You are correct. I did a full uninstall of node and npm and reinstalled it. I can confirm I am now on version 16.17

When I do run the fork now I get prompted with this message:

```

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:1210
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/ezinvestments/rustprojects/ezinvestments-db-2/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ezinvestments/rustprojects/ezinvestments-db-2/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'ERR_DLOPEN_FAILED'
}

```

**Comment by bolshoytoster** [comment]
@lnterger delete the `node_modules/` folder and run `npm install`.

**Comment by dyinq** [comment]
@bolshoytoster thank you!! issue is resolved, closing this ticket :D
