### ISSUE TITLE
I'm trying to npm run generate , but it doesn't let me. Error is below Please Help!

### ISSUE THREAD

**Issue by Josip230** [HashLips/hashlips_art_engine#1373]
Error: ENOENT: no such file or directory, scandir 'D:\HashLips NFT\hashlips_art_engine-1.1.1_update/layers/Eyeball/'
    at Object.readdirSync (node:fs:1442:3)
    at getElements (D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:73:6)
    at D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:87:30)
    at startCreating (D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:352:20)
    at D:\HashLips NFT\hashlips_art_engine-1.1.1_update\index.js:6:3
    at Object.<anonymous> (D:\HashLips NFT\hashlips_art_engine-1.1.1_update\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\HashLips NFT\\hashlips_art_engine-1.1.1_update/layers/Eyeball/'
}

**Comment by bolshoytoster** [comment]
@Josip230 you need to save `src/config.js`.

**Comment by Josip230** [comment]
@bolshoytoster I've fixed this problem but now i get this problem please help people!
> hashlips_art_engine@1.1.1 generate
> node index.js

(node:14132) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2200:5)
    at saveMetaDataSingleFile (D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:313:6)
    at D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:402:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (D:\HashLips NFT\hashlips_art_engine-1.1.1_update\src\main.js:367:9) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by bolshoytoster** [comment]
@Josip230 use the current version of hashlips.

**Comment by Josip230** [comment]
So that wil fix it?

**Comment by Josip230** [comment]
@bolshoytoster What tutorial to mint should i watch on youtube?

**Comment by Josip230** [comment]
@bolshoytoster  I did everything as you said but , now i get this problem please help!
(node:18172) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2200:5)
    at saveMetaDataSingleFile (D:\HashLips NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:319:6)
    at D:\HashLips NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:408:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (D:\HashLips NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:373:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by bolshoytoster** [comment]
@Josip230 try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by Josip230** [comment]
How do you mean i'm new to github how to install your fork?

**Comment by bolshoytoster** [comment]
@Josip230 the same way you use hashlips.

**Comment by Josip230** [comment]
@bolshoytoster Yeah but how to install it

**Comment by bolshoytoster** [comment]
@Josip230 you can get a zip [here](https://github.com/bolshoytoster/hashlips_art_engine/archive/refs/heads/main.zip).

**Comment by Josip230** [comment]
So , i just download it set it up like normal , and then it should work yeah? @bolshoytoster

**Comment by bolshoytoster** [comment]
@Josip230 yes.

**Comment by Josip230** [comment]
@bolshoytoster I have a big problem now , npm works now thanks for help! But whenenver i create and NFT , it looks ugly and some properties are bigger then they should be please help
![image](https://user-images.githubusercontent.com/111868694/186641811-698cffa6-8013-4462-8223-ea666a7a31a0.png)

**Comment by bolshoytoster** [comment]
@Josip230 the images aren't placed correctly in the source images. You can either place the images the way whatever tutorial says, or you can place them with 'code':
```js
const layersConfigurations = [
  {
    {
        name: "someLayer",
        options: {
           posX: 96,
           posY: 96,
           width: 384,
           height: 384,
        },
      },
  },
];

**Comment by Josip230** [comment]
![image](https://user-images.githubusercontent.com/111868694/186675774-2d812454-04c5-4ee9-84f1-ea54763b9ad9.png)
I did something wrong here what is it?

**Comment by Josip230** [comment]
@bolshoytoster

**Comment by bolshoytoster** [comment]
@Josip230 that was just an example, you'd have to do the positioning yourself.

e.g.
```js
const layersConfigurations = [
  {
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Base" },
      { name: "Colors Of Suits" },
      { name: "Glasses" },
      { name: "Colors Of Suits" },
      {
        name: "Suits",
        options: {
           posX: 96,
           posY: 96,
           width: 384,
           height: 384,
        },
      },
    ],
  },
];
```

**Comment by Josip230** [comment]
But , how will i know where to position the properties?

**Comment by Josip230** [comment]
Is there a plugin or a program that does it easier @bolshoytoster

**Comment by bolshoytoster** [comment]
@Josip230
> Is there a plugin or a program that does it easier

Yes, your image editor.

You need to scale down the visible part of the images to be in the correct positions. I'd reccomend you watch a tutorial on hashlips.

**Comment by Josip230** [comment]
Can't find the video with my problem can you help me finding it?

**Comment by bolshoytoster** [comment]
@Josip230 I think [this playlist](https://youtu.be/vFY_E3IP6OU?list=PLvfQp12V0hS1PWDxlrfASk0Mq6AbC5n5f) might help.
