### ISSUE TITLE
npm run generate not working anymore

### ISSUE THREAD

**Issue by Wisky101** [HashLips/hashlips_art_engine#1382]
> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\lib\bindings.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\lib\canvas.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\index.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\src\main.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\lib\\canvas.js',    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\index.js',      
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\src\\main.js',
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\index.js'
  ]
}

**Comment by bolshoytoster** [comment]
@Wisky101 can you paste the output of `npm install` here please.

**Comment by Wisky101** [comment]
up to date, audited 66 packages in 996ms

6 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

**Comment by bolshoytoster** [comment]
@Wisky101 what if you run `npm run generate` again?

**Comment by Wisky101** [comment]
@bolshoytoster same again , even after npm audit fix

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\lib\bindings.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\lib\canvas.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\index.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\src\main.js
- C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\lib\\canvas.js',    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\index.js',      
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\src\\main.js',
    'C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\index.js'
  ]
}

**Comment by bolshoytoster** [comment]
@Wisky101 [this stackoverflow post](https://stackoverflow.com/questions/14771781/nodejs-cannot-find-module-build-release-canvas) talks about the same error, the top solution suggests running `npm uninstall canvas` then `npm i canvas`

**Comment by Wisky101** [comment]
@bolshoytoster 
S C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine> npm i canvas        
npm ERR! code 1
npm ERR! path C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute 'C:\Users\pjote\Desktop\node.exe C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.8.0 | win32 | x64
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.3 and node@18.8.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.3/canvas-v2.9.3-node-v108-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.8.0 | win32 | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.8.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Users\pjote\AppData\Local\Programs\Python\Python310\python.exe" 
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS checking VS2019 (16.11.32802.440) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - found VC++ toolset: v142
npm ERR! gyp ERR! find VS - missing any Windows SDK
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
npm ERR! gyp ERR! stack     at C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:385:16
npm ERR! gyp ERR! stack     at C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Users\\pjote\\Desktop\\node.exe" "C:\\Users\\pjote\\Desktop\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas
npm ERR! gyp ERR! node -v v18.8.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\pjote\Desktop\node.exe C:\Users\pjote\Desktop\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19043
npm ERR! node-pre-gyp ERR! command "C:\\Users\\pjote\\Desktop\\node.exe" "C:\\Users\\pjote\\OneDrive\\Desktop\\Solana\\hashlips_art_engine-main\\hashlips_art_engine\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine\node_modules\canvas 
npm ERR! node-pre-gyp ERR! node -v v18.8.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pjote\AppData\Local\npm-cache\_logs\2022-08-31T19_24_43_743Z-debug-0.log
PS C:\Users\pjote\OneDrive\Desktop\Solana\hashlips_art_engine-main\hashlips_art_engine>

**Comment by bolshoytoster** [comment]
@Wisky101 you'll have to either downgrade node or "install the latest version of Visual Studio install the latest version of Visual Studio"

**Comment by Wisky101** [comment]
@bolshoytoster will try with downgrading node.js

**Comment by Wisky101** [comment]
@bolshoytoster fixed
Thanks bud
