### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'

### ISSUE THREAD

**Issue by Vegannx** [HashLips/hashlips_art_engine#1383]
i keep getting this error
can someone please help?
Error: ENOENT: no such file or directory, scandir 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'
    at Object.readdirSync (node:fs:1442:3)
    at getElements (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:73:6)
    at C:\Users\user\Desktop\hashlips_art_engine\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:90:30)
    at startCreating (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:356:20)
    at C:\Users\user\Desktop\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\user\Desktop\hashlips_art_engine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\user\\Desktop\\hashlips_art_engine/layers/Eyeball/'

**Comment by bolshoytoster** [comment]
@Vegannx save `src/config.js`.

**Comment by Vegannx** [comment]
> @Vegannx save `src/config.js`.

Thanks.. worked perfectly :)

**Comment by Vegannx** [comment]
worked thanks
