### ISSUE TITLE
Coding for First Time (nps run generate Not Working)

### ISSUE THREAD

**Issue by DavidPFMedia** [HashLips/hashlips_art_engine#1407]
Hello, everyone. This is my first time coding anything; the most I have learned of this is via codeSTACKr.

I have an issue in trying to generate the NFT art I have created, and I came across this problem.

```
PS C:\Users\Public\hashlips> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:2312) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1442
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\David\hashlips/layers/Background/'
    at Object.readdirSync (node:fs:1442:3)
    at getElements (C:\Users\David\hashlips\src\main.js:73:6)
    at C:\Users\David\hashlips\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\David\hashlips\src\main.js:90:30)
    at startCreating (C:\Users\David\hashlips\src\main.js:356:20)
    at C:\Users\David\hashlips\index.js:6:3
    at Object.<anonymous> (C:\Users\David\hashlips\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\David\\hashlips/layers/Background/'
```
  
I did follow in every direction on that youtube channel, but I still am missing something. I am in need of assistance. Thanks a gain for any tips, help, or suggestions. Thank you.

**Comment by DavidPFMedia** [comment]
Nevermind. Turns out I just have a spelling error. One of the folder names in the Layers folder doesn't match the code.

**Comment by DavidPFMedia** [comment]
Thanks for the help, but I'll have to start over.
