### ISSUE TITLE
Getting Syntax Error Just after Cloning 

### ISSUE THREAD

**Issue by omm-prakash** [HashLips/hashlips_art_engine#1412]
Getting the below error while running `node index.js`

> Versions
> node: 10.18.0
> npm: 6.13.4

```bash
~/Desktop/hashlips_art_engine/src/main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/omm/Desktop/hashlips_art_engine/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

### The code was run just after cloning and showed the above error. I am not able to debug the same. 
Please guide me to resolve the same.

**Comment by bolshoytoster** [comment]
@omm-prakash either upgrade your node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
