### ISSUE TITLE
Index.Js Error

### ISSUE THREAD

**Issue by MatthewTvv** [HashLips/hashlips_art_engine#1416]
C:\Users\matte\Desktop\hashlips_art_engine-main>node idex.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\matte\Desktop\hashlips_art_engine-main\idex.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

What can i do to fix it ?

**Comment by bolshoytoster** [comment]
@MatthewTvv see [my comment on your other issue](https://github.com/HashLips/hashlips_art_engine/issues/1415#issuecomment-1277135203) and you need to spell `index.js` correctly.

**Comment by umer007khan** [comment]
@bolshoytoster your old comments are not helpful. Please, provide step by step guidance of above mentioned issue. Thanks.

**Comment by bolshoytoster** [comment]
@umer007khan
- Run `dir`
- The output should have a line like this:
```
{date}  {time}    <DIR>          hashlips_art_engine-main
```
in the command prompt or
```
d-r---        {date}     {time}                hashlips_art_engine-main
```
in powershell

The name there will depend on how you downloaded hashlips and the version you did.

- Take that name and run `cd {the name}`
- You should be in the right place

You'll have to do that every time you open a new terminal, or:

This issue is usually caused when unzipping, people sometimes make an extra 'outer' folder. 

You can solve this more permanently by opening visual studio or another software you're using to the 'inner' folder, which contains `index.js` etc.

**Comment by umer007khan** [comment]
**@bolshoytoster**  ### Sir, Thanks for guidance. i have solved another issue  (https://github.com/HashLips/hashlips_art_engine/issues/651) by following your old guidance.
