### ISSUE TITLE
Whenever generating starts after a random amount of images created it stops.

### ISSUE THREAD

**Issue by airmagg** [HashLips/hashlips_art_engine#1426]
It started doing this a couple times before I used to be able to generate upto 500 images and their metadata no problem.
However now I come across this error whenever I try to generate anything.

(node:4296) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (/Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/lib/image.js:62:9)
    at /Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas/index.js:23:10)
    at /Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:184:12)
    at /Users/magnusguzman/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This has happened thrice now, each at a different #Image

**Comment by bolshoytoster** [comment]
@airmagg if you use [my fork](https://github.com/bolshoytoster/hashlips_art_engine), it will tell you what file is causing the issue. It's probably just a non-image file in one of your layer folders.

**Comment by airmagg** [comment]
Thank you so much, I looked in layers and some of the files were just misput/mispelt.
