### ISSUE TITLE
I have a error when I type node index.js 

### ISSUE THREAD

**Issue by Shifufu12** [HashLips/hashlips_art_engine#1428]
(node:41044) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6/layers/Backgrounds/park.png'
    at setSource (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:41044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:41044) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6/layers/Body/body 10.png'
    at setSource (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:41044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:41044) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6/layers/Eyes/eye 9.png'
    at setSource (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:41044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:41044) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6/layers/hair/king.png'
    at setSource (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:41044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:41044) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6/layers/Mouth/mouth 5.png'
    at setSource (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
e-1.1.2_patch_v6/layers/shirts/shirt 10.png'
    at setSource (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27    at new Promise (<anonymous>)    at loadLayerImg (C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\momo3\OneDrive\שולחן העבודה\Project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31    at Array.forEach (<anonymous>)
(node:41044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)

**Comment by bolshoytoster** [comment]
@Shifufu12 your path contains non-ascii characters in it (שולחן העבודה), try moving your project to just `C:/Users/momo3/OneDrive/`

**Comment by Shifufu12** [comment]
@bolshoytoster I swear I love you its working

**Comment by hafizvy6** [comment]
I am getting this error, any solutions please
Error: Unsupported image type
    at setSource (C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\index.js:23:10)
    at C:\Users\Hafiz\hashlips_art_engine\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Hafiz\hashlips_art_engine\src\main.js:184:12)
    at C:\Users\Hafiz\hashlips_art_engine\src\main.js:368:31
    at Array.forEach (<anonymous>)
PS C:\Users\Hafiz\hashlips_art_engine>

**Comment by Yoskele** [comment]
Hey when I run node index.js I get this error.

PS C:\Users\jonas\Desktop\Hashlips\hashlips_art_engine-main> node index.js
C:\Users\jonas\Desktop\Hashlips\hashlips_art_engine-main\src\main.js:94
      layerObj.options?.["displayName"] != undefined

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\jonas\Desktop\Hashlips\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
PS C:\Users\jonas\Desktop\Hashlips\hashlips_art_engine-main> 


How do I fix the syntax error?

**Comment by bolshoytoster** [comment]
@Yoskele either update your node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
