### ISSUE TITLE
I have been getting this error every time i try to run engine Very frustrating

### ISSUE THREAD

**Issue by puppetofsmut** [HashLips/hashlips_art_engine#1436]
t

[therooster_any_cock_L_doo@fedora hashlips_art_engine-1.1.2_patch_v6]$ npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/home/therooster_any_cock_L_doo/Downloads/hashlips_art_engine-1.1.2_patch_v6/node_modules/sha1'
Require stack:
- /home/therooster_any_cock_L_doo/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js
- /home/therooster_any_cock_L_doo/Downloads/hashlips_art_engine-1.1.2_patch_v6/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/therooster_any_cock_L_doo/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/therooster_any_cock_L_doo/Downloads/hashlips_art_engine-1.1.2_patch_v6/src/main.js',
    '/home/therooster_any_cock_L_doo/Downloads/hashlips_art_engine-1.1.2_patch_v6/index.js'
  ]
}

Node.js v19.0.1
[therooster_any_cock_L_doo@fedora hashlips_art_engine-1.1.2_patch_v6]$

**Comment by bolshoytoster** [comment]
@puppetofsmut you need to run `npm install` first.

**Comment by puppetofsmut** [comment]
i have npm installed

**Comment by puppetofsmut** [comment]
oh before i do anything?

**Comment by bolshoytoster** [comment]
@puppetofsmut
> oh before i do anything?

yes, before you can generate.

**Comment by puppetofsmut** [comment]
Node.js v19.0.1
[therooster_any_cock_L_doo@fedora hashlips_art_engine]$ npm -v
8.5.0
[therooster_any_cock_L_doo@fedora hashlips_art_engine]$ npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/therooster_any_cock_L_doo/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/therooster_any_cock_L_doo/hashlips_art_engine/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.0.1
[therooster_any_cock_L_doo@fedora hashlips_art_engine]$ npm -v

**Comment by puppetofsmut** [comment]
i didnt have this trouble first time using this art engine i dont really no coding so im lost

**Comment by bolshoytoster** [comment]
@puppetofsmut did you change your node.js version between running `npm install` and now?

**Comment by puppetofsmut** [comment]
yes a bunch of times

**Comment by bolshoytoster** [comment]
@puppetofsmut you need to stay with one version. Delete the `node_modules/` folder and run `npm install` again.

**Comment by puppetofsmut** [comment]
i thoiught i had too cause of the error

**Comment by puppetofsmut** [comment]
oh ok thats it?

**Comment by puppetofsmut** [comment]
Node.js v19.0.1
[therooster_any_cock_L_doo@fedora hashlips_art_engine]$ npm -v
8.5.0
[therooster_any_cock_L_doo@fedora hashlips_art_engine]$ npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/therooster_any_cock_L_doo/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/therooster_any_cock_L_doo/hashlips_art_engine/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.0.1
[therooster_any_cock_L_doo@fedora hashlips_art_engine]$ npm -v

**Comment by puppetofsmut** [comment]
yah i deleted that folder and this came up 
i have three different versions of art engine do ineed to delete folder from all of them ?

**Comment by bolshoytoster** [comment]
@puppetofsmut you could try deleting all of them.

**Comment by puppetofsmut** [comment]
im giving up on this  its boring and frustrating now thanks for trying to help though

**Comment by FuManchuBarber** [comment]
You are using the wrong version of node v14.17.0 works
