### ISSUE TITLE
unsupported image type

### ISSUE THREAD

**Issue by hafizvy6** [HashLips/hashlips_art_engine#1437]
Error: Unsupported image type
    at setSource (C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Hafiz\hashlips_art_engine\node_modules\canvas\index.js:23:10)
    at C:\Users\Hafiz\hashlips_art_engine\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Hafiz\hashlips_art_engine\src\main.js:184:12)
    at C:\Users\Hafiz\hashlips_art_engine\src\main.js:368:31
    at Array.forEach (<anonymous>)
PS C:\Users\Hafiz\hashlips_art_engine>

**Comment by bolshoytoster** [comment]
@hafizvy6 make sure there are no non-image files in your layer folders. [My fork](https://github.com/bolshoytoster/hashlips_art_engine) will tell you which files are causing this error.

**Comment by hafizvy6** [comment]
how do I exactly use your fork

**Comment by bolshoytoster** [comment]
@hafizvy6 same way you use hashlips, you can download a zip [here](https://github.com/bolshoytoster/hashlips_art_engine/archive/refs/heads/main.zip).

**Comment by hafizvy6** [comment]
@bolshoytoster 
Why there is no error in hashlips layers only error with my layers?

**Comment by hafizvy6** [comment]
Thank you bro, error got solved But couldn't create 10k only 2.5k , my project is having 4 traits and each layer how much images needed?

**Comment by bolshoytoster** [comment]
@hafizvy6 you can multiply together the number of images in each layer to get the max collection size, i.e:
1 image per layer - 1 * 1 * 1 * 1 = 1 image
2 images ... - 2 * 2 * 2 * 2 = 16 images
4 images ... - 4 * 4 ... = 256 images
8 images ... - 8 * 8 ... = 4k images
16 images ... - 16 * 16 ... = 65k images

(If you want to use the same number of images per layer, you could use [this](https://latex.codecogs.com/svg.image?\sqrt[l]{c}) (where `l` is the number of layers and `c` is the number if images you want) to figure out the minimum per layer (round up))

Keep in mind you don't need to have the same number of images in each layer, they just have to multiply to your target or higher (I'd recomend higher, otherwise rarity won't matter as much).
