### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by Jardiceeek** [HashLips/hashlips_art_engine#1445]
Hello, iI created new terminal, installed npm and tried to generate 5 picture examples and it wrote me this error:
PS C:\Users\jara2\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\jara2\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/node_modules/sha1'
Require stack:
- C:\Users\jara2\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js
- C:\Users\jara2\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\Users\jara2\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jara2\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\src\\main.js',
    'C:\\Users\\jara2\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\index.js'
  ]
}
Please help,  I have been strugling with this and trying to fix this all day and nothing seemed to work.

**Comment by bolshoytoster** [comment]
@Jardiceeek you need to run `npm install` first.
