### ISSUE TITLE
Rename Error

### ISSUE THREAD

**Issue by steigenn** [HashLips/hashlips_art_engine#1457]
It gives the following error in `yarn rename-contract NFTNAME` command. What do I need to do to solve it?

`Internal Error: @hashlips-lab/nft-erc721-collection-smart-contract@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at pQ.getCandidates (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:435:5146)
    at Wf.getCandidates (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:391:1264)
    at C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:7695
    at Rf (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8965)
    at ge (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:7675)
    at async Promise.allSettled (index 0)
    at async eo (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:8293)
    at async C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:8205
    at async ni.startProgressPromise (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:390:45507)      
    at async He.resolveEverything (C:\Users\User\AppData\Local\node\corepack\yarn\3.3.0\yarn.js:439:6238)
PS C:\Users\User\Downloads\nftproject\nft-erc721-collection-2.4.4\smart-contract> `

**Comment by bolshoytoster** [comment]
@steigenn you probably meant to open this issue on [hashlips-lab/nft-erc721-collection](https://github.com/hashlips-lab/nft-erc721-collection).
