### ISSUE TITLE
npm install error (Downgraded node js)

### ISSUE THREAD

**Issue by monkugames** [HashLips/hashlips_art_engine#1458]
64-bit

PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> python --version
Python 3.11.0
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.6
node-pre-gyp info using node@18.12.1 | win32 | x64
node-pre-gyp info check checked for "D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node" (not found)      
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with 
node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz

D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.12.1 | win32 | x64
gyp info ok

D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node" --module_name=canvas "--module_path=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release" --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108 )  else (node "" configure --fallback-to-build "--module=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node" --module_name=canvas "--module_path=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release" --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108 )
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@18.12.1 | win32 | x64
gyp info find Python using Python version 3.11.0 found at "D:\python\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.10.31321.278) found at:
gyp ERR! find VS "e:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)       
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:385:16
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\final nft\\hashlips_art_engine-1.1.2_patch_v6\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\final nft\\hashlips_art_engine-1.1.2_patch_v6\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas
gyp ERR! node -v v18.12.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Windows_NT 10.0.19043
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\final nft\\hashlips_art_engine-1.1.2_patch_v6\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas
node-pre-gyp ERR! node -v v18.12.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.6
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\final nft\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> 
 *  History restored 

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
removed 5 packages, changed 8 packages, and audited 66 packages in 7s

6 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues, run:
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> npm install
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> npm install
up to date, audited 66 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> npm install
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6> npm install

up to date, audited 66 packages in 2s

6 packages are looking for funding   
  run `npm fund` for details

4 high severity vulnerabilities      

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
PS D:\final nft\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@monkugames try downgrading your node.js.

**Comment by hamzailyas434** [comment]
Try to download this Node.js
https://nodejs.org/download/release/v14.17.6/
