### ISSUE TITLE
Out of memory , after 1 generated image

### ISSUE THREAD

**Issue by yernurdev** [HashLips/hashlips_art_engine#1462]
C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>node index.js
(node:3572) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: 49394e7ad00f6493805166a4ae12807ddf85b333
C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: out of memory
    at setSource (C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\1\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
-----------------------------------------------------------
so my transparent layers are done in illustrator. They are 3000 x 3000 :)). like I wrote to size 3000x3000.

**Comment by bolshoytoster** [comment]
@yernurdev you could try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), which will use less memory if needed. If that doesn't work it's probably an issue with node.

**Comment by yernurdev** [comment]
> @yernurdev you could try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), which will use less memory if needed. If that doesn't work it's probably an issue with node.

i have already tried it . It's amazing thank you. Issue was size of an image)))

**Comment by saad3074** [comment]
@bolshoytoster when we generate 500+ images ,usage or Server RAM is near to 99% and our server is slow down , is it work for this which you forked.. we are generating 500+ and on that time server stuck on that request, and all other requests are not working when images are not completely generated.

**Comment by bolshoytoster** [comment]
@saad3074 if you're using my fork, you can set it to use less memory (but also slower) by changing lines ~462-463 in `src/main.js`:
https://github.com/bolshoytoster/hashlips_art_engine/blob/16a9d9c2581ff78f13db064d1e830a0e5d8d2637/src/main.js#L462-L463

to:
```js
  lowMemory = true
//    freemem() < format.width * format.height * (background.generate ? 3 : 4) * abstractedIndexes.filter(val => val != undefined).length;
```
