### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by GlebZann** [HashLips/hashlips_art_engine#1468]
When I write node index.js

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\zanam\OneDrive\Рабочий стол\my nft\hashlips_art_engine\node_modules\canvas\lib\bindings.js
- C:\Users\zanam\OneDrive\Рабочий стол\my nft\hashlips_art_engine\node_modules\canvas\lib\canvas.js
- C:\Users\zanam\OneDrive\Рабочий стол\my nft\hashlips_art_engine\node_modules\canvas\index.js
- C:\Users\zanam\OneDrive\Рабочий стол\my nft\hashlips_art_engine\src\main.js
- C:\Users\zanam\OneDrive\Рабочий стол\my nft\hashlips_art_engine\index.js
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:841:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1061:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:103:18)←[39m
    at Object.<anonymous> ←[90m(C:\Users\zanam\OneDrive\Рабочий стол\my nft\hashlips_art_engine\←[39mnode_modules\←[4mcanvas←[24m\lib\bindings.js:3:18←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1159:14)←[39m
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1037:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:878:12)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1061:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\zanam\\OneDrive\\Рабочий стол\\my nft\\hashlips_art_engine\\node_modules\\canvas\\lib\\bindings.js'←[39m,
    ←[32m'C:\\Users\\zanam\\OneDrive\\Рабочий стол\\my nft\\hashlips_art_engine\\node_modules\\canvas\\lib\\canvas.js'←[39m,
    ←[32m'C:\\Users\\zanam\\OneDrive\\Рабочий стол\\my nft\\hashlips_art_engine\\node_modules\\canvas\\index.js'←[39m,
    ←[32m'C:\\Users\\zanam\\OneDrive\\Рабочий стол\\my nft\\hashlips_art_engine\\src\\main.js'←[39m,
    ←[32m'C:\\Users\\zanam\\OneDrive\\Рабочий стол\\my nft\\hashlips_art_engine\\index.js'←[39m
  ]
}

Node.js v18.12.1

**Comment by faustoandreabellucci** [comment]
downgrade node js

**Comment by faustoandreabellucci** [comment]
i use version 14.17.3

**Comment by faustoandreabellucci** [comment]
And remember to go to the Main Directory -> cd hashlips_art_engine-main

**Comment by GlebZann** [comment]
Error: ENOENT, No such file or directory 'C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine/layers/Background/2#18.png'
    at setSource (C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\node_modules\←[4mcanvas←[24m\lib\image.js:91:13)
    at Image.set (C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\node_modules\←[4mcanvas←[24m\lib\image.js:62:9)
    at C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\node_modules\←[4mcanvas←[24m\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\node_modules\←[4mcanvas←[24m\index.js:23:10)
    at C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\src\main.js:184:12)
    at C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: ←[33m2←[39m,
  code: ←[32m'ENOENT'←[39m,
  path: ←[32m'C:\\Users\\zanam\\OneDrive\\Рабочий стол\\nft p\\hashlips_art_engine/layers/Background/2#18.png'←[39m,
  syscall: ←[32m'fopen'←[39m
}

C:\Users\zanam\OneDrive\Рабочий стол\nft p\hashlips_art_engine>

What this?

**Comment by bolshoytoster** [comment]
@GlebZann this is an issue with canvas. On windows, it can't use paths containing non-ascii characters (i.e. russian letters). Try moving your project to somewhere like just `C:/Users/zanam/`.
