### ISSUE TITLE
npm run build issue

### ISSUE THREAD

**Issue by validusvell** [HashLips/hashlips_art_engine#1472]
Can you guys help me troubleshoot this? I rolled the node version back using NVM 

PS C:\Users\VellKanj\OneDrive\Desktop\hashlips> npm run build      

> hashlips_art_engine@1.1.1 build C:\Users\VellKanj\OneDrive\Desktop\hashlips
> node index.js

C:\Users\VellKanj\OneDrive\Desktop\hashlips\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\VellKanj\OneDrive\Desktop\hashlips\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 build: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VellKanj\AppData\Roaming\npm-cache\_logs\2022-12-20T23_50_34_962Z-debug.log
PS C:\Users\VellKanj\OneDrive\Desktop\hashlips> 

**** ADDITIONAL LOGGING ****
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.13.4
3 info using node@v10.18.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle hashlips_art_engine@1.1.1~prebuild: hashlips_art_engine@1.1.1
6 info lifecycle hashlips_art_engine@1.1.1~build: hashlips_art_engine@1.1.1
7 verbose lifecycle hashlips_art_engine@1.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle hashlips_art_engine@1.1.1~build: PATH: C:\Users\VellKanj\nvm\v10.18.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\VellKanj\OneDrive\Desktop\hashlips\node_modules\.bin;C:\Program Files (x86)\PowerShell\7;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Python310\Scripts\;C:\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\PowerShell\7\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Go\bin;C:\ProgramData\chocolatey\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\VellKanj\AppData\Local\Microsoft\WindowsApps;C:\Users\VellKanj\AppData\Local\GitHubDesktop\bin;C:\Users\VellKanj\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\VellKanj\.dotnet\tools;C:\Users\VellKanj\go\bin;C:\Users\VellKanj\AppData\Roaming\npm;C:\Users\VellKanj\nvm;C:\Program Files\nodejs
9 verbose lifecycle hashlips_art_engine@1.1.1~build: CWD: C:\Users\VellKanj\OneDrive\Desktop\hashlips
10 silly lifecycle hashlips_art_engine@1.1.1~build: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle hashlips_art_engine@1.1.1~build: Returned: code: 1  signal: null
12 info lifecycle hashlips_art_engine@1.1.1~build: Failed to exec build script
13 verbose stack Error: hashlips_art_engine@1.1.1 build: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\VellKanj\nvm\v10.18.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\VellKanj\nvm\v10.18.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid hashlips_art_engine@1.1.1
15 verbose cwd C:\Users\VellKanj\OneDrive\Desktop\hashlips
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.18.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error hashlips_art_engine@1.1.1 build: `node index.js`
22 error Exit status 1
23 error Failed at the hashlips_art_engine@1.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bolshoytoster** [comment]
@validusvell you need to either update your node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
