### ISSUE TITLE
Issue when attempting npm run build

### ISSUE THREAD

**Issue by Manerino** [HashLips/hashlips_art_engine#1475]
This is the error I'm getting:

> hashlips_art_engine@1.1.1 build C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5
> node index.js

(node:8180) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5/layers/Eyeball/'
    at Object.readdirSync (fs.js:1047:3)
    at getElements (C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:73:6)
    at C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:90:30)
    at startCreating (C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:356:20)
    at C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js:6:3
    at Object.<anonymous> (C:\Users\Mabud\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How do I fix this?

**Comment by bolshoytoster** [comment]
@Manerino make sure you save `src/config.js` and make sure the `Eyeball` layer is spelled the same in your `layersOrder`(s) and the folder in `layers/` (case sensitive).
