### ISSUE TITLE
someone help please npm install problem

### ISSUE THREAD

**Issue by oyanenda** [HashLips/hashlips_art_engine#1478]
PS C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main> npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.       
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@18.12.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python39-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python39-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python38-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python38-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python37-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python37-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\oyan\AppData\Local\Programs\Python\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Users\oyan\AppData\Local\Programs\Python\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python36-32\python.exe
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python36-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:228:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:432:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)       
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\oyan\\Pictures\\New folder\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\oyan\\Pictures\\New folder\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\oyan\\Pictures\\New folder\\hashlips_art_engine-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"npm ERR! node-pre-gyp ERR! cwd C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main\node_modules\canvas    
npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oyan\AppData\Local\npm-cache\_logs\2023-01-06T17_43_27_784Z-debug-0.log
PS C:\Users\oyan\Pictures\New folder\hashlips_art_engine-main>

**Comment by sammaji** [comment]
@oyanenda It's said in the `README.md` to use node version v10.18.0 Try that! I think it will fix the issue.

**Comment by oyanenda** [comment]
> 

PS C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6> npm install

> canvas@2.8.0 install C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas
> node-pre-gyp install --fallback-to-build

\Release\canvas.node" is installed via remote
npm WARN hashlips_art_engine@1.1.1 No repository field.

added 65 packages from 34 contributors and audited 65 packages in 96.165s

4 packages are looking for funding
  run `npm fund` for details

found 6 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6> node index.js
C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6\index.js:2:39)   
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
PS C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6> node index.js
C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6\index.js:2:39)   
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
PS C:\Users\oyan\Pictures\New folder\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@oyanenda you should either update your node (`README.md` is wrong) or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by NetworkEntity** [comment]
@bolshoytoster update to what version?

**Comment by bolshoytoster** [comment]
@NetworkEntity at least version 14.

**Comment by NetworkEntity** [comment]
Thanks for the reply, when running nvm install 14 i'm getting a continuous errors like below, do you know why?

Downloading and installing node v14.21.2...
Downloading https://nodejs.org/dist/v14.21.2/node-v14.21.2-darwin-arm64.tar.xz...
curl: (22) The requested URL returned error: 404                                                                                                                       

Binary download from https://nodejs.org/dist/v14.21.2/node-v14.21.2-darwin-arm64.tar.xz failed, trying source.
grep: /Users/admin/.nvm/.cache/bin/node-v14.21.2-darwin-arm64/node-v14.21.2-darwin-arm64.tar.xz: No such file or directory
Provided file to checksum does not exist.
Binary download failed, trying source.
Detected that you have 10 CPU core(s)
Running with 9 threads to speed up the build
Clang v3.5+ detected! CC or CXX not specified, will use Clang as C/C++ compiler!
Local cache found: ${NVM_DIR}/.cache/src/node-v14.21.2/node-v14.21.2.tar.xz
Checksums match! Using existing downloaded archive ${NVM_DIR}/.cache/src/node-v14.21.2/node-v14.21.2.tar.xz
$>./configure --prefix=/Users/admin/.nvm/versions/node/v14.21.2 <
Node.js configure: Found Python 3.9.7...
INFO: configure completed successfully
...........
DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-exceptions -fno-strict-aliasing -MMD -MF /Users/admin/.nvm/.cache/src/node-v14.21.2/files/out/Release/.deps//Users/admin/.nvm/.cache/src/node-v14.21.2/files/out/Release/obj.host/icutools/deps/icu-small/source/common/uprops.o.d.raw   -c
  g++ -o /Users/admin/.nvm/.cache/src/node-v14.21.2/files/out/Release/obj.host/icutools/deps/icu-small/source/common/usetiter.o ../deps/icu-small/source/common/usetiter.cpp '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-D_DARWIN_USE_64_BIT_INODE=1' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DU_COMMON_IMPLEMENTATION=1' '-DU_I18N_IMPLEMENTATION=1' '-DU_IO_IMPLEMENTATION=1' '-DU_TOOLUTIL_IMPLEMENTATION=1' '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=1' '-

**Comment by bolshoytoster** [comment]
@NetworkEntity there's no arm build of node v14, just install `stable`.

**Comment by NetworkEntity** [comment]
@bolshoytoster Thank you very much that' resolved! Do you perhaps know how i update my canvas version to work with arm64e (apple silicon)?

**Comment by bolshoytoster** [comment]
@NetworkEntity you could try running `npm install canvas@2.11.0` then `npm install`.

**Comment by NetworkEntity** [comment]
@bolshoytoster Didn't seem to work, still looking like its installing an incompatible version

node:internal/modules/cjs/loader:1332
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/Main Branch/node_modules/canvas/build/Release/canvas.node, 0x0001): tried: '/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/Main Branch/node_modules/canvas/build/Release/canvas.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/canvas.node' (no such file), '/usr/lib/canvas.node' (no such file)
    at Module._extensions..node (node:internal/modules/cjs/loader:1332:18)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/Main Branch/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.5.0

**Comment by bolshoytoster** [comment]
@NetworkEntity try deleting `node_modules/` first and trying again.

**Comment by NetworkEntity** [comment]
@bolshoytoster Couldn't get it working, tried from scratch again but ended up with this:
npm -v 9.3.1
node -v v19.5.0

hashlips_art_engine-main % npm install canvas@2.11.0
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/Users/admin/.nvm/versions/node/v19.5.0/bin/node /Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@19.5.0 | darwin | arm64
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v111-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v111-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.0 and node@19.5.0 (node-v111 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v111-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.5.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@19.5.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.11.1 found at "/usr/local/bin/python3"
npm ERR! gyp info spawn /usr/local/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/admin/Library/Caches/node-gyp/19.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/admin/Library/Caches/node-gyp/19.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/admin/Library/Caches/node-gyp/19.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/admin/.nvm/versions/node/v19.5.0/bin/node" "/Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
npm ERR! gyp ERR! cwd /Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas
npm ERR! gyp ERR! node -v v19.5.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/admin/.nvm/versions/node/v19.5.0/bin/node /Users/admin/.nvm/versions/node/v19.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.1.0
npm ERR! node-pre-gyp ERR! command "/Users/admin/.nvm/versions/node/v19.5.0/bin/node" "/Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v19.5.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2023-01-31T23_07_33_895Z-debug-0.log


Completely stuck, been at this for hours

**Comment by NetworkEntity** [comment]
+ node_modules/  has disappeared from my directory

**Comment by bolshoytoster** [comment]
@NetworkEntity you could try changing line ~27 in `package.json`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/package.json#L26-L28

To:
```json
   "canvas": "^2.11.0", 

```
(make sure you save), then run `npm install`.

**Comment by NetworkEntity** [comment]
@bolshoytoster no joy it seems.. hmmm

npm list canvas

npm ERR! code ELSPROBLEMS
npm ERR! invalid: canvas@2.8.0 /Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main/node_modules/canvas
hashlips_art_engine@1.1.1 /Users/admin/Desktop/ShodoCrypts/Shodocrypts v.3 GIF/hashlips_art_engine-main
└── canvas@2.8.0 invalid: "^2.11.0" from the root project


npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2023-01-31T23_21_45_344Z-debug-0.log

**Comment by bolshoytoster** [comment]
@NetworkEntity what if you delete `node_modules/` and run `npm install` again?

**Comment by NetworkEntity** [comment]
@bolshoytoster running into the same errors, seem to be completely stuck. Thank you for your help, its appreciated. i wonder if theres another way around this, a fork or previous version of this application i can use.

**Comment by NetworkEntity** [comment]
have no package-lock.json or node_modules/ and trying to install everything again runs into errors.

**Comment by bolshoytoster** [comment]
@NetworkEntity
> i wonder if theres another way around this, a fork or previous version of this application i can use.

As I suggested first, you can use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
