### ISSUE TITLE
generating issue

### ISSUE THREAD

**Issue by Maticyo** [HashLips/hashlips_art_engine#1495]
I'm ready for everything and I'm trying to create an image, but I keep getting these statements and the creation doesn't proceed. Help me.

> hashlips_art_engine@1.1.1 generate C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6
> node index.js

(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/background/background9#10.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:18776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.    
(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/skin/Sprite10#28.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/eyes/eyes10#5.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/hat/hat12#5.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/body/body14#5.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/mouse/mouse8#10.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:18776) UnhandledPromiseRejectionWarning: Error: EILSEQ, Illegal byte sequence 'C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6/layers/ears/none2#40.png'
    at setSource (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\andyj\OneDrive\바탕 화면\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:18776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)

**Comment by bolshoytoster** [comment]
@Maticyo you have non-ascii characters in your path, which canvas doesn't support on windows.

Try moving hashlips to somewhere like `C:/Users/andyj/`

**Comment by Maticyo** [comment]
It's resolved. Thank you!
