### ISSUE TITLE
Module_not_found

### ISSUE THREAD

**Issue by bconeyoukay** [HashLips/hashlips_art_engine#1501]
Hi. Been trying for ages to try and get this to work. 

I've installed node correctly using every cmd possible, I've gone through all similar posts in the forum but I can't get `node index.js` to work at all.
Error code: `internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/Users/theostephenson/Desktop/hashlips_art_engine/node_modules/sha1'
Require stack:
- /Users/theostephenson/Desktop/hashlips_art_engine/src/main.js
- /Users/theostephenson/Desktop/hashlips_art_engine/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/theostephenson/Desktop/hashlips_art_engine/src/main.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/theostephenson/Desktop/hashlips_art_engine/src/main.js',
    '/Users/theostephenson/Desktop/hashlips_art_engine/index.js'
  ]
}`

Can anyone help? I was watching a tutorial on running the code and it says to use `node index.js` but it literally won't do anything despite me following all the recommendations and checks, which I've seen on GitHub

Thanks

**Comment by bolshoytoster** [comment]
@bconeyoukay did you get any errors running `npm install` (you need to run it to install dependencies)?

**Comment by bconeyoukay** [comment]
@bolshoytoster 


This is what I get from npm install


npm WARN theostephenson No description
npm WARN theostephenson No repository field.
npm WARN theostephenson No license field.

audited 64 packages in 1.319s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

theostephenson@Theos-MacBook-Pro ~ %

**Comment by bolshoytoster** [comment]
@bconeyoukay good. You should be able to run `node index.js` now.

**Comment by bconeyoukay** [comment]
@bolshoytoster just tried. Still getting this:

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/Users/theostephenson/Desktop/hashlips_art_engine/node_modules/sha1'
Require stack:
- /Users/theostephenson/Desktop/hashlips_art_engine/src/main.js
- /Users/theostephenson/Desktop/hashlips_art_engine/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/theostephenson/Desktop/hashlips_art_engine/src/main.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/theostephenson/Desktop/hashlips_art_engine/src/main.js',
    '/Users/theostephenson/Desktop/hashlips_art_engine/index.js'
  ]

**Comment by bolshoytoster** [comment]
@bconeyoukay what if you run `npm install sha1` first?

**Comment by bconeyoukay** [comment]
@bolshoytoster such a lifesaver man. its worked. will let you know if any other issues but couldn't be more grateful for your help

**Comment by bconeyoukay** [comment]
<img width="826" alt="Screenshot 2023-03-06 at 16 36 20" src="https://user-images.githubusercontent.com/127065465/223173325-8a2a28b6-e448-4230-90b5-0b6c4ec21210.png">

just gone to generate my files and they're all like this but in different colours. pretty sure I added all the folder & file names correctly & the rarities correctly, so any ideas what's up?

**Comment by bconeyoukay** [comment]
@bolshoytoster the file sizing and layer order seems to be okay too, and the meta data is fine, so not sure whats up

**Comment by bolshoytoster** [comment]
@bconeyoukay you may have put the layers in your `layersOrder`s the wrong way round.

**Comment by bconeyoukay** [comment]
@bolshoytoster seems fine to me. unless i've arranged them wrong? the background etc all seem fine to me tho

**Comment by bconeyoukay** [comment]
<img width="257" alt="Screenshot 2023-03-06 at 16 43 06" src="https://user-images.githubusercontent.com/127065465/223174942-51532e90-4251-4ed5-aafb-624d0c51dd9d.png">

**Comment by bolshoytoster** [comment]
@bconeyoukay you could try removing all layers but the background, then add them back one layer at a time to see when it stops working.

**Comment by bconeyoukay** [comment]
@bolshoytoster all of my layers scale up to fill the page. it's fine with just the background but anything added just upscales and goes to 1024x1024 (which is what my image is set to be, and is what I designed the background and all other assets around)

**Comment by bconeyoukay** [comment]
will try re-exporting my layers differently
