### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by SplattaSlacks3** [HashLips/hashlips_art_engine#1506]
Hey everyone! I'm having some trouble running the npm install command. I am constantly receiving an error regarding my "permissions" when i try to run the npm install command.
I currently have node v19.7.0 AND npm v9.5.0 installed. I would truly appreciate it if anyone could lend some knowledge or a solution to this issue. Thank you very much. 

Below I have attached the error that I am receiving:

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../@mapbox/node-pre-gyp/bin/node-pre-gyp
npm ERR! dest /mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin/node-pre-gyp
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../@mapbox/node-pre-gyp/bin/node-pre-gyp' -> '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin/node-pre-gyp'
npm ERR!  [Error: EACCES: permission denied, symlink '../@mapbox/node-pre-gyp/bin/node-pre-gyp' -> '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin/node-pre-gyp'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../@mapbox/node-pre-gyp/bin/node-pre-gyp',
npm ERR!   dest: '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin/node-pre-gyp'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/_splattaslacks/.npm/_logs/2023-03-15T02_17_38_817Z-debug-0.log

**Comment by bolshoytoster** [comment]
@SplattaSlacks3 you could try deleting `node_modules/` and trying again or try running installing dependencies as root (`sudo npm install -g --unsafe-perm=true --allow-root`)

I've never seen this error before so it's likely a chromeos issue.

**Comment by SplattaSlacks3** [comment]
Hey thank you! I actually did try something like that with [sudo npm install -g {package name}] and this command worked. However, I ran into yet another obstacle when trying to run the command [node index.js] I am met with this error below. Would you happen to be familiar with this one?

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/node_modules/sha1'
Require stack:
- /mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/src/main.js
- /mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/src/main.js',
    '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/index.js'
  ]
}

Node.js v18.15.0

**Comment by bolshoytoster** [comment]
@SplattaSlacks3 it looks like it hasn't actually installed any dependencies. You could try running `sudo npm install -g --unsafe-perm=true --allow-root` again.

**Comment by SplattaSlacks3** [comment]
Hey thanks for responding. I ran the command   sudo npm install -g --unsafe-perm=true --allow-root   as you recommend, and this is the error that I am getting now: 

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /mnt/chromeos/MyFiles/Downloads/VS Code/hashlips_art_engine-1.1.2_patch_v6/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/mnt/chromeos/MyFiles/Downloads/VS Code/hashlips_art_engine-1.1.2_patch_v6/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-20T14_35_50_644Z-debug-0.log


any idea on how i could get around this? thank you again.

**Comment by bolshoytoster** [comment]
@SplattaSlacks3 you could try running `cd hashlips_art_engine-1.1.2_patch_v6` first, if that doesn't work then you're missing the [`package.json` file](https://github.com/HashLips/hashlips_art_engine/blob/main/package.json) - you could either download that or run `sudo npm install -g --unsafe-perm=true --allow-root canvas gif-encoder-2 sha1` instead.

**Comment by SplattaSlacks3** [comment]
Okay, It looks like I did, indeed, have the package.json file when i ran the command cd hashlips_art_engine-1.1.2_patch_v6 it did not give me an error. When I ran the second command sudo npm install -g --unsafe-perm=true --allow-root canvas gif-encoder-2 sha1 It appears as tho the dependencies get installed because I do get a new node_modules folder in my explorer. 

However, when I try to run the node index.js command after, I am still getting an error that states it cannot find the module: 

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/node_modules/canvas'
Require stack:
- /mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/src/main.js
- /mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/src/main.js:5:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/src/main.js',
    '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/hashlips_art_engine-1.1.2_patch_v6/index.js'

**Comment by bolshoytoster** [comment]
@SplattaSlacks3 it looks like it didn't install canvas. Do you get any errors running `sudo npm install -g --unsafe-perm=true --allow-root`?

**Comment by SplattaSlacks3** [comment]
It appears to be successful when I run "sudo npm install -g --unsafe-perm=true --allow-root"
This is what I get:

changed 1 package in 58ms

However, when I go into the node_modules folder I still don't see a file for canvas so I'm still not sure if doing that actually installed the canvas package.

I was wondering if there was a way I could manually install that package and add it to the node_modules folder?

**Comment by SplattaSlacks3** [comment]
Hey I hope all is well. I'm still trying to figure out that npm install issue. Now, when I run "npm install" I get this output:

npm WARN saveError ENOENT: no such file or directory, open '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/mnt/chromeos/MyFiles/Downloads/hashlips_art_engine-1.1.2_patch_v6/package.json'
npm WARN hashlips_art_engine-1.1.2_patch_v6 No description
npm WARN hashlips_art_engine-1.1.2_patch_v6 No repository field.
npm WARN hashlips_art_engine-1.1.2_patch_v6 No README data
npm WARN hashlips_art_engine-1.1.2_patch_v6 No license field.

up to date in 0.354s
found 0 vulnerabilities

Any idea as to what this could mean? The node_modules folder did not get installed neither when I ran this.

**Comment by bolshoytoster** [comment]
@SplattaSlacks3 your terminal is in the wrong directory, try running `cd hashlips_art_engine-1.1.2_patch_` first`

**Comment by SplattaSlacks3** [comment]
i finally got the node_modules folder to install thank you! 

Now when I go to run the command "node index.js" i am getting another MODULE_NOT_FOUND error:

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/_splattaslacks/hashlips_art_engine/modules/HashlipsGiffer.js'
Require stack:
- /home/_splattaslacks/hashlips_art_engine/src/main.js
- /home/_splattaslacks/hashlips_art_engine/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/_splattaslacks/hashlips_art_engine/src/main.js:32:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/_splattaslacks/hashlips_art_engine/src/main.js',
    '/home/_splattaslacks/hashlips_art_engine/index.js'
  ]
}

**Comment by bolshoytoster** [comment]
@SplattaSlacks3 looks like you're missing `modules/HashlipsGiffer.js`. As long as you don't want to export gifs, you can just remove line 32 in `sec/main.js`:

https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L31-L33

**Comment by WeissKai** [comment]
> 看起来你失踪了.只要您不想导出 gif，您只需删除 ：`modules/HashlipsGiffer.js``sec/main.js`
> 
> https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L31-L33

事实上，31行的不需要删除
