### ISSUE TITLE
layerObj.options?.["displayName"] != undefined

### ISSUE THREAD

**Issue by DuckiesFarm** [HashLips/hashlips_art_engine#1509]
Is there a solution to this problem? I have tried various ways, one of which is deleting the node_module file and reinstalling npm install, but it still doesn't work.

Note : hashlips_art_engine-1.1.2_patch_v6.zip and node-v19.8.1

when I run the index.js node a problem occurs like this :

C:\Duckies\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\Duckies\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js:2:39)     
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)

**Comment by bolshoytoster** [comment]
@DuckiesFarm you need to either update youre node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by DuckiesFarm** [comment]
> @DuckiesFarm you need to either update youre node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

Solved, Thanks for your great jobs!
