### ISSUE TITLE
layerObj.options?.["displayName"] != undefined ?

### ISSUE THREAD

**Issue by VII-XXIX** [HashLips/hashlips_art_engine#1521]
(base) lee@lee-Lenovo-E41-15:~/Desktop/hashlips_art_engine-1.1.2_patch_v6$ node index.js
/home/lee/Desktop/hashlips_art_engine-1.1.2_patch_v6/src/main.js:94
      layerObj.options?.["displayName"] != undefined ?
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lee/Desktop/hashlips_art_engine-1.1.2_patch_v6/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

How to solve this

**Comment by bolshoytoster** [comment]
@VII-XXIX either update your node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
