### ISSUE TITLE
I need help!🙏

### ISSUE THREAD

**Issue by GUNZE314532** [HashLips/hashlips_art_engine#1557]
Hello, 

I need help.

What is causing the error below?

satoshishigeta@Satoshis-MBP hashlips_art_engine-main % node index.js
(node:7271) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1457
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/layers/BODY/'
    at Object.readdirSync (node:fs:1457:3)
    at getElements (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:73:6)
    at /Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:90:30)
    at startCreating (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:356:20)
    at /Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/index.js:6:3
    at Object.<anonymous> (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/layers/BODY/'
}

Node.js v20.0.0

**Comment by GUNZE314532** [comment]
Hi, @bolshoytoster 

Hi, 
Thank you so much for the other day! But I need your help again...🙏

First, when I ran "node index.js" in Terminal, the NFT was successfully generated because of you. After that, I wanted to try a completely different design, so I deleted the image and json files in the first generated "build folder" and replaced them with different data in the "layer folder".
After that, when I ran "node index.js" again, I got the above error.

**Comment by bolshoytoster** [comment]
@GUNZE314532 the error is:
```js
Error: ENOENT: no such file or directory, scandir '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/layers/BODY/'
```

Make sure the names in your `layersOrder`s match the folders under `layers/` (they're case sensitive).

**Comment by amritabithi** [comment]
> @GUNZE314532 the error is:
> 
> ```js
> Error: ENOENT: no such file or directory, scandir '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/layers/BODY/'
> ```
> 
> Make sure the names in your `layersOrder`s match the folders under `layers/` (they're case sensitive).

- First make sure to remove any dashes from the filenames that you have saved in your layers.  I would remove any spaces also.

- Also make sure that you are running from the hashlips folder when you try to run it, so in our case make sure you change directories to '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/' while running the script.

Finally, from the hashlips folder, do these steps and it should hopefully build for you:
1) Delete the "node-modules" folder in your hashlips directory if you have one.
2) Run commands:
```
npm cache clean --force
npm install
```

If you are using Yarn,  replace the last line above with:
`yarn install`

Good luck .

**Comment by amritabithi** [comment]
> Hi, @bolshoytoster
> 
> Hi, Thank you so much for the other day! But I need your help again...pray
> 
> First, when I ran "node index.js" in Terminal, the NFT was successfully generated because of you. After that, I wanted to try a completely different design, so I deleted the image and json files in the first generated "build folder" and replaced them with different data in the "layer folder". After that, when I ran "node index.js" again, I got the above error.

<br>
<br>

First make sure to remove any dashes from the filenames that you have saved in your layers. I would remove any spaces also.

<br>
Also make sure that you change to the hashlips directory on the command line when you run the program so in our case make sure you change directories to 'C:/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/' while running the script.  Use the full entire pathname to the file, instead of the relative pathname to make things easier.  ( Fix the dashes and spaces first. )

<br>
<br>
<br>
Finally, from the hashlips folder, do these steps and it should hopefully build for you:

1)  Delete the "node-modules" folder in your hashlips directory if you have one.

2)  Run commands:
```
npm cache clean --force
npm install
```

If you are using Yarn, replace the last line above with:
`yarn install`

Good luck .

**Comment by bolshoytoster** [comment]
@amritabithi did you read the error? None of that would fix it.

**Comment by GUNZE314532** [comment]
@bolshoytoster Thanks your advise.


<img width="1349" alt="Screenshot 2023-06-11 at 12 06 06 PM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/2f934969-9759-46db-b23d-c4dac6f09afd">
↑The "BODY" / LAYERS of folder name is a folder name of the previous artwork I tried fist one.



<img width="1280" alt="Screenshot 2023-06-11 at 11 55 58 AM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/3b7681d3-fc98-4143-aa6e-c6f986a0ba3f">
↑Current my folder name is below, and it is matching.

**Comment by bolshoytoster** [comment]
@GUNZE314532 make sure you save `src/config.js`, and could you paste the error here in case it has changed.

**Comment by amritabithi** [comment]
First of all "/Users/..." is not a valid windows path, which is covered by the steps I listed to check, whether other people here like it or not.

Your errors are due to incorrect paths being passed, try my advice to rule that out, regardless of what some random idiot thinks about what I said.

**Comment by GUNZE314532** [comment]
> @GUNZE314532 make sure you save `src/config.js`, and could you paste the error here in case it has changed.

I checked `src/config.js` again, and my error is below.

satoshishigeta@Satoshis-MBP hashlips_art_engine-main % node index.js
(node:27395) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1457
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/layers/BODY/'
    at Object.readdirSync (node:fs:1457:3)
    at getElements (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:73:6)
    at /Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:90:30)
    at startCreating (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/src/main.js:356:20)
    at /Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/index.js:6:3
    at Object.<anonymous> (/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/hashlips_art_engine-main/layers/BODY/'
}

Node.js v20.0.0

**Comment by GUNZE314532** [comment]
Hi @amritabithi 

Should I delete below? Please let me know.
<img width="1310" alt="Screenshot 2023-06-11 at 7 16 57 PM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/5efdec32-d76d-4ba8-911a-f1b40e106191">

**Comment by bolshoytoster** [comment]
@GUNZE314532 that's weird, it's still complaining about `layers/BODY/`. You could try running `cat src/config.js` and making sure the output matches it in the editor. You may be editing a `src/config.js` from a different copy of hashlips, make sure you're editing `/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/src/config.js`. Also check again that you've definetely saved (`ctrl` + `S`).

> Should I delete below? Please let me know.

No, it would break hashlips. @amritabithi suggested deleting `node_modules/`, which wouldn't help with this issue.

---

@amritabithi
> First of all "/Users/..." is not a valid windows path

Windows is not the only operating system. @GUNZE314532 is using a unix-like OS.

> Your errors are due to incorrect paths being passed

While I agree with this statement on it's own, the error is complaining about `layers/BODY/` specifically, which is a layer supposedly not in their `src/config.js`. The information you've given wouldn't help.

> regardless of what some random idiot thinks about what I said.

I've been working with hashlips as a developer for over a year. Where's your fork?

**Comment by amritabithi** [comment]
> Hi @amritabithi
> 
> Should I delete below? Please let me know. <img alt="Screenshot 2023-06-11 at 7 16 57 PM" width="1310" src="https://user-images.githubusercontent.com/131314141/244991739-5efdec32-d76d-4ba8-911a-f1b40e106191.png">

The one you want to delete is called "node_modules" that shows on the second row of file icons in your screenshot, and then run theese commands:
```
npm cache clean --force
npm install
```
I recommend renaming your folder called "hashlips_art_engine-main" to "hashlips_art_engine_main" ( replace the dash with an underscore, we don't want any dashes in our filenames when using Hashlips.  Again, make sure that you are changed to the hashlips directory on the command line when running the commands.  ( On Windows, you can type the command "cd" to show your current working directory, make sure this shows your Hashlips directory. )

**Comment by amritabithi** [comment]
> @GUNZE314532 that's weird, it's still complaining about `layers/BODY/`. You could try running `cat src/config.js` and making sure the output matches it in the editor. You may be editing a `src/config.js` from a different copy of hashlips, make sure you're editing `/Users/satoshishigeta/Desktop/NEW DATA/THE CAVEMANS GENERATE/src/config.js`. Also check again that you've definetely saved (`ctrl` + `S`).
> 
> > Should I delete below? Please let me know.
> 
> No, it would break hashlips. @amritabithi suggested deleting `node_modules/`, which wouldn't help with this issue.
> 
> @amritabithi
> 
> > First of all "/Users/..." is not a valid windows path
> 
> Windows is not the only operating system. @GUNZE314532 is using a unix-like OS.
> 
> > Your errors are due to incorrect paths being passed
> 
> While I agree with this statement on it's own, the error is complaining about `layers/BODY/` specifically, which is a layer supposedly not in their `src/config.js`. The information you've given wouldn't help.
> 
> > regardless of what some random idiot thinks about what I said.
> 
> I've been working with hashlips as a developer for over a year. Where's your fork?

That's funny because I'm not aware of any linux variant that uses a "/Users/" folder, but Windows does.  Linux doesn't allow unenclosed spaces in folder or filenames, but Windows does.

I'm not a hashlips developer but I've been working with it for a couple of years but that doesn't matter here and nobody cares if I have or haven't. 

My fork is not on github, I updated how the DNA works a year or so ago to add some features for a project that was delayed, and had a lot of problems building also, and so my suggestions are meant to rule out the obvious common things people run in to or overlook, I have helped several people get your project set up and having them go through the basic steps again tends to fix it, steps they can go back to later and just paste in if things break again and they forget what they did to fix it.

**Comment by bolshoytoster** [comment]
@amritabithi
> That's funny because I'm not aware of any linux variant that uses a "/Users/" folder, but Windows does.

I said unix-like, which includes macOS, which does use `/Users/`.

>  Linux doesn't allow unenclosed spaces in folder or filenames

Linux allows spaces in file names, I don't know what you mean by 'unenclosed', if you mean surrounded by quotes, then it depends from application to application.

> On Windows, you can type the command "cd" to show your current working directory

Or `ls`, since they're probably on macOS, `cd` on it's own sends you to `~`.

> I'm not a hashlips developer but I've been working with it for a couple of years but that doesn't matter here and nobody cares if I have or haven't.

I apologise for saying that, it was a little unprofessional.

> my suggestions are meant to rule out the obvious common things people run in to or overlook

I understand this when there isn't enough information, but there is a full error, deleting `node_modules/` wouldn't help in this case.

**Comment by amritabithi** [comment]
One thing I had to do with some other projects like the Solana Candy Machine or Metaplex I forget which, but I had to run the builds as a root user so that it could create the folders it needed during the install.  I believe that I then needed to run the script as root when I used it because it would then be installed under the context of the root user and it's folders.  

If running as the root user does work without issues, then it would be a permissions problem.  You may be able to fix that by changing permissions on the parent folders of the folders that are showing errors, but what I personally preferred to do is just run as superuser / root while working with the project.  If it were a web application that users were using then running as root would be a bad idea, but in this case just running a local script like this as root is fine since you are the only one accessing it.

That is at least something to rule out to narrow down the problem hopefully.

( Running things as root is generally not a recommended solution to anything, but in my case it was a choice between spending a lot more time figuring out why my setup was having issues which got in to a complicated rabbit hole witih Node... so I elected to just run as root for the sake of time instead of solving the da vinci code of what I had to fix to run as the normal user. )

**Comment by bolshoytoster** [comment]
@amritabithi again, the error is `Error: ENOENT: no such file or directory ... layers/BODY/`, the issue is that hashlips is trying to read a layer that doesn't exist and isn't in the `layersConfig`s (at least in the editor).

**Comment by GUNZE314532** [comment]
Hi @bolshoytoster @amritabithi , Thank you for many advise.

The problem may have been solved. Sorry, it could be a very easy mistake. The cause is probably just the folder structure, where I placed each folder on my computer desktop, and the folder name I made. Please see the screen shot below.
<img width="1112" alt="Screenshot 2023-06-13 at 10 34 55 AM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/6496e31f-79ad-4db0-9fae-8cc034841ae3">


Also, I have additional questions. Is it possible to generate gif data using this art engine?
I don't know how to do that, but I've tried for now. Then my terminal mentioned something like this:

satoshishigeta@Satoshis-MBP hashlips_art_engine-main % node index.js
(node:42361) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: fc9a3b662eb34a355512cc9c7c648929484e723f
Created edition: 2, with DNA: d817832a16e3d817fb1e55fa376cb0003cd33226
Created edition: 3, with DNA: 12989631a589e68f4124f3792881f94aa3534bfd
Created edition: 4, with DNA: 77c1f5fe2e7c2fb783ac3c65103c84a251159567
Created edition: 5, with DNA: 47c4246fc3bb8cd0a1449c407dd30d023a526d34
Created edition: 6, with DNA: 2694ea9ad42994fd56419549a994a3f42ad50892
Created edition: 7, with DNA: 4caffd00d53b551a8fe7a4e06fd4127bf2534378
Created edition: 8, with DNA: 1af955e6118efa9f60c38b21fc9bf522df393f5a
Created edition: 9, with DNA: a43aeab338116df55b3952ad37e111b3a4bb86ec
Created edition: 10, with DNA: 2822daa3a7dc1f225ea722188077221de1abea50
DNA exists!
DNA exists!
DNA exists!
Created edition: 11, with DNA: 30ddbd98501bcf1a54808bad1a8813a0c3d7e5bb
Created edition: 12, with DNA: 26abc0eae933020efd22aece6c2fafb6d2265aef
Created edition: 13, with DNA: dcc580e1e1c2697ad71f711128d2092df664086f
DNA exists!
DNA exists!
Created edition: 14, with DNA: b8e5a3d85d56c147ae267c3891a4338a5c8c7f6a
Created edition: 15, with DNA: 7690afcbba24d40007dded368495ecede5102f9c
Created edition: 16, with DNA: 5c766df8a41895521fe70bfe8d2c1ef6fbe69e8e
DNA exists!
DNA exists!
DNA exists!
Created edition: 17, with DNA: 8a66d2dd50ace7881a380ec2220640d5b61dfb7e
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
Created edition: 18, with DNA: 4e949c494b941100d82b441a31a9b63a3e3afde4
DNA exists!
DNA exists!
Created edition: 19, with DNA: 83cf282172867d8126d058c3c9ffae13eb163990
Created edition: 20, with DNA: b2fb800b97d7d49c8fb07030f9c27f3701343b51
DNA exists!
DNA exists!
Created edition: 21, with DNA: 26c0e0d2bb09a9341fc4445cdfa7c383a5a7cae3
DNA exists!
DNA exists!
DNA exists!
DNA exists!
Created edition: 22, with DNA: 422e07288e237e5147d319562c3d8a5d06663293
Created edition: 23, with DNA: 0af387dccc2acc78473ded14afb0fb1483d8135f
DNA exists!
Created edition: 24, with DNA: a3aefbab833fc441d76b66c91e263ab28c29a123
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
Created edition: 25, with DNA: edfc1582a146c7797af6efc025ed2403368a921b
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
Created edition: 26, with DNA: 6ea7198cc29445dd5c09e140b74f0ba4a64097dc
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
DNA exists!
Created edition: 27, with DNA: be104662736e9c0998212a7fad07c77934d0fdaf
satoshishigeta@Satoshis-MBP hashlips_art_engine-main % 


In addition, my layer variations are below. Only background data is png. Everything else is gif, and lastly, I want it to be gif data.

Please check and I would appreciate it if you could help me with it.

<img width="399" alt="Screenshot 2023-06-12 at 11 09 11 PM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/cf81ac0c-8bcd-44c2-84b0-83a3d032eeef">
<img width="477" alt="Screenshot 2023-06-12 at 11 09 15 PM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/3c5d42cf-d279-4258-819a-7c3c6c6b74f7">
<img width="475" alt="Screenshot 2023-06-12 at 11 09 20 PM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/39920e00-a80a-48a6-9b6f-8455dde5fa5f">
<img width="494" alt="Screenshot 2023-06-12 at 11 09 24 PM" src="https://github.com/HashLips/hashlips_art_engine/assets/131314141/b5a38bdd-426e-494f-a423-9f50e2d96d04">

**Comment by bolshoytoster** [comment]
@GUNZE314532
> Is it possible to generate gif data using this art engine?

Not with the main project, you could try looking at [this](https://github.com/HashLips/hashlips_art_engine/issues/1008#issuecomment-1086636163) though.

**Comment by GUNZE314532** [comment]
@bolshoytoster Okay, I will check it. Thank you! :)
