### ISSUE TITLE
error in   var dna = Number(_str.split(":").shift()); what can i do ?

### ISSUE THREAD

**Issue by SomeoneSon** [HashLips/hashlips_art_engine#1560]
$ npm run build

> hashlips_art_engine@1.0.5 build
> node index.js

E:\FIVVER\NSTYA\IN\GENERATOR\src\config.js
(node:17688) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use node --trace-deprecation ... to show where the warning was created)
E:\FIVVER\NSTYA\IN\GENERATOR\src\main.js:55
  var dna = Number(_str.split(":").shift());
                        ^

TypeError: Cannot read properties of undefined (reading 'split')
    at cleanDna (E:\FIVVER\NSTYA\IN\GENERATOR\src\main.js:55:25)
    at E:\FIVVER\NSTYA\IN\GENERATOR\src\main.js:152:22
    at Array.find (<anonymous>)
    at E:\FIVVER\NSTYA\IN\GENERATOR\src\main.js:151:42
    at Array.map (<anonymous>)
    at constructLayerToDna (E:\FIVVER\NSTYA\IN\GENERATOR\src\main.js:150:35)
    at startCreating (E:\FIVVER\NSTYA\IN\GENERATOR\src\main.js:249:23)      
    at E:\FIVVER\NSTYA\IN\GENERATOR\index.js:13:3
    at Object.<anonymous> (E:\FIVVER\NSTYA\IN\GENERATOR\index.js:14:3)      
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.16.0

**Comment by bolshoytoster** [comment]
@SomeoneSon I think I fixed that on [my fork](https://github.com/bolshoytoster/hashlips_art_engine), you could try using that.

**Comment by Storleo** [comment]
@bolshoytoster  можете пожалуйста ответить в твиттере?Я попробовал вашу ветку и все тоже самое, у меня почему-то ошибка на ошибке все:(

**Comment by bolshoytoster** [comment]
@Storleo could you paste any errors you get here please?

**Comment by Storleo** [comment]
Да, могу, я на всякий случай все удалю и еще раз попробую поставить все и скину ошибки.Отправлю это завтра утром, как буду у пк. В любом случае спасибо вам что оказываете поддержку!

**Comment by Storleo** [comment]
PS E:\PlsLetsWork\hashlips_art_engine-main> yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 13.78s.
PS E:\PlsLetsWork\hashlips_art_engine-main> npm install
npm ERR! code 1
npm ERR! path E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! node-pre-gyp info using node@18.16.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node" (not found)     
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz   
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.0 and node@18.16.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "C:\Users\Leo Collection\AppData\Local\Programs\Python\Python310\python.exe"      
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details      
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\PlsLetsWork\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=E:\\PlsLetsWork\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\PlsLetsWork\hashlips_art_engine-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\PlsLetsWork\\hashlips_art_engine-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd E:\PlsLetsWork\hashlips_art_engine-main\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v18.16.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Leo Collection\AppData\Local\npm-cache\_logs\2023-06-21T13_32_23_798Z-debug-0.log
PS E:\PlsLetsWork\hashlips_art_engine-main>

**Comment by Storleo** [comment]
![image](https://github.com/HashLips/hashlips_art_engine/assets/137202967/212435b2-8b12-437a-aeee-249e9b8b1cc5)

**Comment by bolshoytoster** [comment]
@Storleo this is because canvas 2.9.0 doesn't support the node version you're using. You can either run `npm install canvas@2.11.2` first or downgrade your node.js.

**Comment by Storleo** [comment]
![image](https://github.com/HashLips/hashlips_art_engine/assets/137202967/21b9ebb3-0aac-469f-88d2-d96e248f3f93)
Работает все, выдало результат и вроде как все хорошо, но почему-то некоторые файлы оно пишет что не находит.

**Comment by bolshoytoster** [comment]
@Storleo [the errors are given by canvas](https://github.com/bolshoytoster/hashlips_art_engine/blob/f5955bcb3f847a7ee17ed1648e86b7d75bf4a6df/src/main.js#L156), this may happen if you have non-ascii characters in those files' names/paths.
