### ISSUE TITLE
cannot deploy contract

### ISSUE THREAD

**Issue by chrisharvie** [HashLips/hashlips_art_engine#1562]
Hi, I get this error message

PS C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract> yarn deploy --network truffle
yarn run v1.22.19
warning ..\..\..\..\package.json: No license field
$ hardhat run scripts/1_deploy.ts --network truffle
No need to generate any newer typings.
Deploying contract...
HardhatError: HH108: Cannot connect to the network truffle.
Please make sure your node is running, and check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:209:15)  
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpProvider.request (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:84:29)
    at async EthersProviderWrapper.send (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
    at async getSigners (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:45:20)
    at async getContractFactoryByAbiAndBytecode (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:288:21)
    at async main (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\scripts\1_deploy.ts:17:20)

    Caused by: Error: connect ECONNREFUSED ::1:24012
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

Is there any solutions that can help?

**Comment by chrisharvie** [comment]
PS C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract> yarn deploy --network truffle
yarn run v1.22.19
warning ..\..\..\..\package.json: No license field
$ hardhat run scripts/1_deploy.ts --network truffle
Generating typings for: 2 artifacts in dir: typechain for target: ethers-v5
Successfully generated 7 typings!
Compiled 2 Solidity files successfully
Deploying contract...
HardhatError: HH108: Cannot connect to the network truffle.
Please make sure your node is running, and check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:209:15)  
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpProvider.request (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:84:29)
    at async EthersProviderWrapper.send (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
    at async getSigners (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:45:20)
    at async getContractFactoryByAbiAndBytecode (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:288:21)
    at async main (C:\Users\chris\OneDrive\Desktop\nft-erc721-collection-2.4.5\smart-contract\scripts\1_deploy.ts:17:20)

    Caused by: Error: connect ECONNREFUSED ::1:24012
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chrisharvie** [comment]
Is it just a network error, seemed to make more progress second time i ran the command

**Comment by bolshoytoster** [comment]
@chrisharvie [it's just a network error](https://hardhat.org/hardhat-runner/docs/errors#HH108), the error says:
> Please make sure your node is running, and check your internet connection and networks config

Also, you almost certainly wanted to open this issue on [the `nft-erc721-collection` repo](https://github.com/hashlips-lab/nft-erc721-collection), not here.
