### ISSUE TITLE
npm run buid bug

### ISSUE THREAD

**Issue by GemMy02** [HashLips/hashlips_art_engine#1580]
> hashlips_art_engine@1.1.1 build
> node index.js

(node:9824) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:77
        throw new Error(`layer name can not contain dashes, please fix: ${i}`);
              ^

Error: layer name can not contain dashes, please fix: Yo-Gi.png
    at C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:77:15
    at Array.map (<anonymous>)
    at getElements (C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:75:6)
    at C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:90:30)
    at startCreating (C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:356:20)
    at C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\A\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.9.0

**Comment by bolshoytoster** [comment]
@GemMy02 the error is:
```js
Error: layer name can not contain dashes, please fix: Yo-Gi.png
```
