### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Zakalwe-x** [HashLips/hashlips_art_engine#1583]
Hi there,

I'm running node.js 10.24.1 + canvas@2.11.2, after having issues with the latest node.js install. Everything seems to have loaded with no vulnerabilities. Ran the node index.js and have the following message. Any thoughts?

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Volumes/Home Store/Crypto/Zakalwe_x/Collaborations/ZKX-Draconis/Avatar project/Test Mint/hashlips_art_engine-main/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by bolshoytoster** [comment]
@Zakalwe-x this is likely the same as #1521. You'll have to either update your node.js or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by Pirulax** [comment]
Node versions 14 or above should work.

**Comment by sandeepsingh11** [comment]
node 14.19.0 worked for me
