### ISSUE TITLE
Please help npm not install error old please help them any one 

### ISSUE THREAD

**Issue by Kingriyas** [HashLips/hashlips_art_engine#1584]

**Comment by bolshoytoster** [comment]
@Kingriyas could you paste the error here please.

**Comment by Kingriyas** [comment]
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.       
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\OS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1) 
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@20.11.0 | win32 | ia32
npm ERR! node-pre-gyp info check checked for "C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@20.11.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | ia32
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | ia32
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python311\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python311\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python310\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python310\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is  - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python310\python.exe" could not be run

**Comment by sandeepsingh11** [comment]
@Kingriyas installing the Node 10.18.0 version resolved this issue for me. 

1. Try installing nvm in the command line, then run `nvm install 10.18.0`. 
2. Type `nvm list` to make sure node 10.18.0 is selected. 
3. Then try `npm install` again.

UPDATE: if you install this version you'll run into [this issue](https://github.com/HashLips/hashlips_art_engine/issues/1583). Replace 10.18.0 with version 14.19.0 and it should work fine.

**Comment by Kingriyas** [comment]
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code 1
npm ERR! path C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\OS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@20.11.0 | win32 | ia32
npm ERR! node-pre-gyp info check checked for "C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@20.11.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | ia32
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is ""
npm ERR! gyp ERR! find Python - "" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python311\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python311\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python311-32\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python311-32\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python310\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python310\python.exe
npm ERR! gyp ERR! find Python - version is ""
npm ERR! gyp ERR! find Python - version is - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python - "C:\Program Files\Python310\python.exe" could not be run

Not responding

**Comment by Kingriyas** [comment]
Open
https://github.com/HashLips/hashlips_art_engine/issues/1383#top
https://github.com/HashLips/hashlips_art_engine/issues/1383
[Vegannx](https://github.com/Vegannx) opened this issue on 2 2, 204 · 3 comments
Comments
[Vegannx](https://github.com/Vegannx) commented https://github.com/HashLips/hashlips_art_engine/issues/1383#issue-1357917317
i keep getting this error
can someone please help?
Error: ENOENT: no such file or directory, scandir 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'
at Object.readdirSync (node:fs:1442:3)
at getElements (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:73:6)
at C:\Users\user\Desktop\hashlips_art_engine\src\main.js:92:15
at Array.map ()
at layersSetup (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:90:30)
at startCreating (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:356:20)
at C:\Users\user\Desktop\hashlips_art_engine\index.js:6:3
at Object. (C:\Users\user\Desktop\hashlips_art_engine\index.js:7:3)
at Module._compile (node:internal/modules/cjs/loader:1126:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
errno: -4058,
syscall: 'scandir',
code: 'ENOENT',
path: 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'

**Comment by Kingriyas** [comment]
Any one please help me

**Comment by sandeepsingh11** [comment]
> npm WARN old lockfile npm WARN old lockfile The package-lock.json file was created with an old version of npm, npm WARN old lockfile so supplemental metadata must be fetched from the registry. npm WARN old lockfile npm WARN old lockfile This is a one-time fix-up, please be patient... npm WARN old lockfile npm ERR! code 1 npm ERR! path C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas npm ERR! command failed npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build npm ERR! Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\OS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1) npm ERR! node-pre-gyp info it worked if it ends with ok npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6 npm ERR! node-pre-gyp info using node@20.11.0 | win32 | ia32 npm ERR! node-pre-gyp info check checked for "C:\Users\OS\Downloads\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\build\Release\canvas.node" (not found) npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@20.11.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp) npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-ia32.tar.gz npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@10.0.1 npm ERR! gyp info using node@20.11.0 | win32 | ia32 npm ERR! gyp info ok npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@10.0.1 npm ERR! gyp info using node@20.11.0 | win32 | ia32 npm ERR! gyp ERR! find Python npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python 3 npm ERR! gyp ERR! find Python - executable path is "" npm ERR! gyp ERR! find Python - "" could not be run npm ERR! gyp ERR! find Python checking if "python3" can be used npm ERR! gyp ERR! find Python - executable path is "" npm ERR! gyp ERR! find Python - "" could not be run npm ERR! gyp ERR! find Python checking if "python" can be used npm ERR! gyp ERR! find Python - executable path is "" npm ERR! gyp ERR! find Python - "" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python311\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python311\python.exe" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Program Files\Python311\python.exe" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python311-32\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python311-32\python.exe" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python311-32\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Program Files\Python311-32\python.exe" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Program Files (x86)\Python311-32\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Program Files (x86)\Python311-32\python.exe" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Users\OS\AppData\Local\Programs\Python\Python310\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Users\OS\AppData\Local\Programs\Python\Python310\python.exe" could not be run npm ERR! gyp ERR! find Python checking if Python is C:\Program Files\Python310\python.exe npm ERR! gyp ERR! find Python - version is "" npm ERR! gyp ERR! find Python - version is - should be >=3.6.0 npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED npm ERR! gyp ERR! find Python - "C:\Program Files\Python310\python.exe" could not be run
> 
> Not responding

Try to delete your **node_modules/canvas** folder, then delete your **package-lock.json** file, then try `npm install` again using node version 14.19.0
