### ISSUE TITLE
What is ENOENT error please help me 

### ISSUE THREAD

**Issue by Kingriyas** [HashLips/hashlips_art_engine#1585]
Open
[Error: ENOENT: no such file or directory, scandir 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'](https://github.com/HashLips/hashlips_art_engine/issues/1383#top)
#1383
[Vegannx](https://github.com/Vegannx) opened this issue on 2 2, 204 · 3 comments
Comments
[Vegannx](https://github.com/Vegannx) commented [on Sep 1, 2022](https://github.com/HashLips/hashlips_art_engine/issues/1383#issue-1357917317)
i keep getting this error
can someone please help?
Error: ENOENT: no such file or directory, scandir 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'
at Object.readdirSync (node:fs:1442:3)
at getElements (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:73:6)
at C:\Users\user\Desktop\hashlips_art_engine\src\main.js:92:15
at Array.map ()
at layersSetup (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:90:30)
at startCreating (C:\Users\user\Desktop\hashlips_art_engine\src\main.js:356:20)
at C:\Users\user\Desktop\hashlips_art_engine\index.js:6:3
at Object. (C:\Users\user\Desktop\hashlips_art_engine\index.js:7:3)
at Module._compile (node:internal/modules/cjs/loader:1126:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
errno: -4058,
syscall: 'scandir',
code: 'ENOENT',
path: 'C:\Users\user\Desktop\hashlips_art_engine/layers/Eyeball/'

**Comment by Kingriyas** [comment]
Any one please help

**Comment by bolshoytoster** [comment]
@Kingriyas have you edited **and saved** src/config.js?
