### ISSUE TITLE
npm run generate not working (i already tried npm install)

### ISSUE THREAD

**Issue by Maartin2800** [HashLips/hashlips_art_engine#1586]
**_Error when installing:_**
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code 1
npm ERR! path D:\Aplikace\hashlips_art_engine-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Warning: Missing input files:
npm ERR! C:\GTK\bin\libpango-1.0-0.dll
npm ERR! C:\GTK\bin\libglib-2.0-0.dll
npm ERR! C:\GTK\bin\libintl-8.dll
npm ERR! C:\GTK\bin\libpng14-14.dll
npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
npm ERR! C:\GTK\bin\libfreetype-6.dll
npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
npm ERR! C:\GTK\bin\zlib1.dll
npm ERR! C:\GTK\bin\libcairo-2.dll
npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
npm ERR! C:\GTK\bin\libexpat-1.dll
npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
npm ERR! C:\GTK\bin\libfontconfig-1.dll
npm ERR! Prob�h� postupn� sestavov�n� projekt� v tomto �e�en�. Pokud chcete povolit paraleln� sestavov�n�, p�idejte pros�m p�ep�na� -m.
npm ERR!   Backend.cc
npm ERR! D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Nejde otev��t 
soubor zahrnout: cairo.h: No such file or directory [D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\build\canvas.vcxproj]
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@20.11.0 | win32 | x64     
npm ERR! node-pre-gyp info check checked for "D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@20.11.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v115-win32-unknown-x64.tar.gz       
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.5 found 
at "C:\Users\bflmp\AppData\Local\Programs\Python\Python311\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.33927.289) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\bflmp\AppData\Local\Programs\Python\Python311\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'msvs',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'D:\\Aplikace\\hashlips_art_engine-main\\node_modules\\canvas\\build\\config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 'C:\\Users\\bflmp\\AppData\\Local\\node-gyp\\Cache\\20.11.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',        
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=C:\\Users\\bflmp\\AppData\\Local\\node-gyp\\Cache\\20.11.0',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\bflmp\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.11.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=D:\\Aplikace\\hashlips_art_engine-main\\node_modules\\canvas',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'D:\\Aplikace\\hashlips_art_engine-main\\node_modules\\canvas\\build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.11.0 | win32 | x64
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args 'build\\binding.sln',
npm ERR! gyp info spawn args '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args '/nologo',
npm ERR! gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (C:\Program 
Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" 
"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Aplikace\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=D:\\Aplikace\\hashlips_art_engine-main\\node_modules\\canvas\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm ERR! gyp ERR! cwd D:\Aplikace\hashlips_art_engine-main\node_modules\canvas
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=D:\Aplikace\hashlips_art_engine-main\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Aplikace\hashlips_art_engine-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Aplikace\\hashlips_art_engine-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd D:\Aplikace\hashlips_art_engine-main\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v20.11.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\bflmp\AppData\Local\npm-cache\_logs\2024-02-05T15_46_22_151Z-debug-0.log
PS D:\Aplikace\hashlips_art_engine-main>

**_Generate error:_**
> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'D:\Aplikace\hashlips_art_engine-main/node_modules/sha1'
Require stack:
- D:\Aplikace\hashlips_art_engine-main\src\main.js
- D:\Aplikace\hashlips_art_engine-main\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)   
    at Module.require (node:internal/modules/cjs/loader:1235:19)    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\Aplikace\hashlips_art_engine-main\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)   
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Aplikace\\hashlips_art_engine-main\\src\\main.js',     
    'D:\\Aplikace\\hashlips_art_engine-main\\index.js'
  ]
}

Node.js v20.11.0
PS D:\Aplikace\hashlips_art_engine-main>
PS D:\Aplikace\hashlips_art_engine-main>

Thanks for help

**Comment by bolshoytoster** [comment]
@Maartin2800 node-canvas v2.8.0 is not available for node v115 (the one you're using). You need to either use a more up to date version of canvas (change `"canvas": "^2.8.0",` to `"canvas": "^2.11.2",`) or downgrade your node.js.

**Comment by Maartin2800** [comment]
**@bolshoytoster** I tryed to downgrade node but it didnt work and I cant figure out how to chnge to canvas 2.11.2.

**Comment by bolshoytoster** [comment]
@Maartin2800
> I cant figure out how to chnge to canvas 2.11.2.

Just change the line:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/package.json#L27

in `package.json` to:
```json
    "canvas": "^2.11.2",
```

Make sure you save, then delete the `node_modules/` folder, then run `npm install` again.

**Comment by Maartin2800** [comment]
![image](https://github.com/HashLips/hashlips_art_engine/assets/159046570/5e22c022-8588-4094-9214-30ded5cf7d73)
i had it this whole time but it doesnt work.

**Comment by bolshoytoster** [comment]
@Maartin2800 make sure you have saved `package.json` and deleted `node_modules/` before you run `npm install`.

> it doesnt work

How does it not work? Does `npm install` give you the same error as before?

**Comment by wodsuz** [comment]
"canvas": "^2.11.2",
Solved my issue

**Comment by NFTlancer** [comment]
FIXED! Just delete your node.js from Program files, and download and install older version (i installed 16.20.2)
