### ISSUE TITLE
Generating Images for Solana blockchain TypeError reading 'path'

### ISSUE THREAD

**Issue by marcelluseasley** [HashLips/hashlips_art_engine#168]
When I generate images for ethereum blockchain, everything works smoothly. When I change for Solana blockchain, some files get generated, but sure enough I end up getting the following error. NOTE, there are no dashes in my filenames, only spaces (which work for Ethereum images):

```
npm run generate

> hashlips_art_engine@1.0.9 generate
> node index.js

(node:3546) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 61, with DNA: 1d07301eae53ddea6d79409f0507cfa1cb96fb38
Created edition: 60, with DNA: 2cd60f887c76b8345c9dd57d3d24f92adc5a9729
Created edition: 30, with DNA: 1d722093c86868210d7dc5f7be06083f4bd25b31
Created edition: 1, with DNA: 3decec6c524a30b24be3a0ebda9244fc755dfc7b
Created edition: 98, with DNA: f5fe9c1b6782e67d3ae2c4f3e0366100812b9681
Created edition: 35, with DNA: 62e965e748371e850c7b24f11f0a2f4421bb8827
/home/marcellus/code/nodecode/github.com/HashLips/hashlips_art_engine/src/main.js:185
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at /home/marcellus/code/nodecode/github.com/HashLips/hashlips_art_engine/src/main.js:185:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/marcellus/code/nodecode/github.com/HashLips/hashlips_art_engine/src/main.js:184:10)
    at /home/marcellus/code/nodecode/github.com/HashLips/hashlips_art_engine/src/main.js:322:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/marcellus/code/nodecode/github.com/HashLips/hashlips_art_engine/src/main.js:321:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by L3ming** [comment]
i get the same thing how to fix?

**Comment by RandomRaine** [comment]
I am having the same issue. Works with -- Network ETH, but not with SOL.  :/
