### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by L3ming** [HashLips/hashlips_art_engine#176]
When i type: node index.js    i get this

TypeError: Cannot read properties of undefined (reading 'path')
at C:\Users\Redux Gamer\OneDrive\Bureaublad\hashlips_art_engine\src\main.js:190:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Redux Gamer\OneDrive\Bureaublad\hashlips_art_engine\src\main.js:189:10)
    at C:\Users\Redux Gamer\OneDrive\Bureaublad\hashlips_art_engine\src\main.js:368:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Redux Gamer\OneDrive\Bureaublad\hashlips_art_engine\src\main.js:367:17)
    at C:\Users\Redux Gamer\OneDrive\Bureaublad\hashlips_art_engine\index.js:13:3
    at Object.<anonymous> (C:\Users\Redux Gamer\OneDrive\Bureaublad\hashlips_art_engine\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by AldrenDG** [comment]
rename all your images inside the layers remove all "-"

**Comment by Radomski13** [comment]
I get the same problem

**Comment by wibletcodes** [comment]
does anyone know how I can add a start edition from a certain number to this code?

**Comment by RiadTCG** [comment]
> rename all your images inside the layers remove all "-"

I did remove all the "-" and i still have the error any other solution ?

TypeError: Cannot read properties of undefined (reading 'path')
    at MY PATH\hashlips_art_engine-1.0.1_update\src\main.js:113:61
    at new Promise (<anonymous>)
    at loadLayerImg (MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\src\main.js:112:10)
    at MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\src\main.js:181:29
    at Array.forEach (<anonymous>)
    at startCreating (MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\src\main.js:180:15)
    at MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\index.js:5:3
    at Object.<anonymous> (MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\index.js:6:3)

**Comment by fiqart** [comment]
i get the same problem

**Comment by philip-denys** [comment]
I managed to solve it with the following link:
https://www.imore.com/how-rename-multiple-files-once-mac

**Comment by bmnvnt** [comment]
> rename all your images inside the layers remove all "-"

it works, thanks
