### ISSUE TITLE
MODULE NOT FOUND

### ISSUE THREAD

**Issue by Coudaa** [HashLips/hashlips_art_engine#179]
Error: Cannot find module 'C:\Users\Alfonsus Jericho\Desktop\hashlips_art_engine-main\...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by dynastohami** [comment]
I have the same problem.

**Comment by jvel07** [comment]
Did you run npm run build?

**Comment by Coudaa** [comment]
that's what I when running npm run build

**Comment by jvel07** [comment]
sorry, I meant `npm install`

**Comment by dhyeythumar** [comment]
Hi,
Did you run `npm install` or `yarn add all`?

**Comment by fonzi69** [comment]
> Error: Cannot find module 'C:\Users\Alfonsus Jericho\Desktop\hashlips_art_engine-main...' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15) at Function.Module._load (internal/modules/cjs/loader.js:745:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }

Have you found a solution?

**Comment by CrapFX** [comment]
have you solved it? i got the same issue

**Comment by Wolodude** [comment]
same issue has this been solved?

**Comment by Dylanv1324** [comment]
type cd and the get the root from  repos/project file open the file and copy the adress then paste it in after like this : cd C:\Users\Dylan\source\Repos\hashlips_art_engine
