### ISSUE TITLE
(node:7344) UnhandledPromiseRejectionWarning: Error: Unsupported image type

### ISSUE THREAD

**Issue by Coudaa** [HashLips/hashlips_art_engine#180]
When I type npm run build. It shows me this

(node:7344) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\src\main.js:190:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\src\main.js:189:10)
    at C:\Users\Alfonsus Jericho\Desktop\NFT\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.

**Comment by dhyeythumar** [comment]
Hi @Coudaa,
What image formats you are using?
