### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by TgCoff** [HashLips/hashlips_art_engine#188]
Hey i saw that this issues was already posted and the fix is to remove the "-" from the layers i did remove them all and still have the error any help please ?

TypeError: Cannot read properties of undefined (reading 'path')
at MY PATH\hashlips_art_engine-1.0.1_update\src\main.js:113:61
at new Promise ()
at loadLayerImg (MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\src\main.js:112:10)
at MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\src\main.js:181:29
at Array.forEach ()
at startCreating (MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\src\main.js:180:15)
at MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\index.js:5:3
at Object. (MY PATH\hashlips_art_engine-1.0.1_update\hashlips_art_engine-1.0.1_update\index.js:6:3)

**Comment by TgCoff** [comment]
I just moved the folder to my desktop and it worked

**Comment by dhyeythumar** [comment]
Hi,
If the error is resolved then can you please close this issue.

**Comment by Spaksu** [comment]
Delete all blanks, "-" and "_" in the layers name.
