### ISSUE TITLE
code: module not found

### ISSUE THREAD

**Issue by manueldaz** [HashLips/hashlips_art_engine#190]
code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Manueldaz\\Desktop\\art-engine\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\Users\\Manueldaz\\Desktop\\art-engine\\node_modules\\canvas\\lib\\canvas.js',
    'C:\\Users\\Manueldaz\\Desktop\\art-engine\\node_modules\\canvas\\index.js',
    'C:\\Users\\Manueldaz\\Desktop\\art-engine\\src\\main.js',
    'C:\\Users\\Manueldaz\\Desktop\\art-engine\\index.js'
  ]
}

**Comment by TgCoff** [comment]
yarn add all

**Comment by manueldaz** [comment]
when i did that this is what i got


error C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@17.0.1 | win32 | x64
node-pre-gyp info check checked for "C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release\canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-win32-unknown-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@17.0.1 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-win32-unknown-x64.tar.gz 

C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@17.0.1 | win32 | x64
gyp info ok

C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102 )  else (node "" configure --fallback-to-build --module=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102 )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@17.0.1 | win32 | x64
gyp info find Python using Python version 3.10.0 found at "C:\Users\Manueldaz\AppData\Local\Programs\Python\Python310\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)    
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Manueldaz\\Desktop\\art-engine\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Manueldaz\\Desktop\\art-engine\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
gyp ERR! cwd C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas
gyp ERR! node -v v17.0.1
gyp ERR! node-gyp -v v8.2.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Manueldaz\Desktop\art-engine\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Manueldaz\\Desktop\\art-engine\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas
node-pre-gyp ERR! node -v v17.0.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Manueldaz\Desktop\art-engine\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
