### ISSUE TITLE
node index.js Error

### ISSUE THREAD

**Issue by werebly** [HashLips/hashlips_art_engine#193]
When i type node index.js to my terminal an error occurs like that

hashlips_art_engine % node index.js
,/Users/code/hashlips_art_engine/src/main.js:100
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/code/hashlips_art_engine/index.js:6:39)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

Is there any solution ?

**Comment by tombenj** [comment]
You are using an old node version. This one works for me:
```
hashlips_art_engine go$ nvm ls
         v4.6.0
         v6.9.0
        v10.0.0
       v10.13.0
        v11.8.0
        v12.0.0
       v12.18.4
->     v14.16.0
         system
```

**Comment by werebly** [comment]
Tnx

**Comment by dhyeythumar** [comment]
Hi @werebly,
If this error is resolved then can you please close this issue.
