### ISSUE TITLE
Doesn't work with more than 8 layers

### ISSUE THREAD

**Issue by Madaragog** [HashLips/hashlips_art_engine#210]
Hi,

I have 12 layers and everything works perfectly fine with 8 or less layers but when I try with 9, 10, 11 or 12 layers I get this error.

PS C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main> node index.js
C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:190
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:190:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:189:10)
    at C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:367:17)
    at C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\index.js:13:3
    at Object.<anonymous> (C:\Users\cedric\Desktop\hashlips_art_engine-main\hashlips_art_engine-main\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

Thanks for your help

**Comment by Spaksu** [comment]
Just try to delete all blanks, "-" and "_" in the layers fie name.

**Comment by Madaragog** [comment]
Thanks, it works

**Comment by dhyeythumar** [comment]
Hi,
If the error is resolved then can you please close the Issue.
