### ISSUE TITLE
Error: Unsupported Image Type Issue

### ISSUE THREAD

**Issue by kristiangabriel** [HashLips/hashlips_art_engine#231]
First off, the HashLips Art Engine is awesome! I am having this issue with the latest Hashlips Art Engine which happens when I start outputting my NTFs. Sometimes I get to 1000, sometimes 200, sometimes only 30 NTFs generated before I get the error below. I've replaced the images, changed drives--but I know the error will pop up and interrupt the output even though the **TogrowEditionSize** is set to 10000. Any help would be greatly appreciated! Thx :)

`C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^
Error: Unsupported image type
    at setSource (C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:180:10)
    at C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
PS C:\Users\user profile\Downloads\hashlips_art_engine-main\hashlips_art_engine-main>`

**Comment by LKYSE7EN** [comment]
Hi kristiangabriel,

Can you check your file names for all your layers and ensure that none of them include any "-", for some reason the hyphen causes an error.

From memory the error looked similar to what you're showing me and due to the rarity weights it can throw the error at different intervals.

I hope this helps!

Cheers.

**Comment by kristiangabriel** [comment]
> Hi kristiangabriel,
> 
> Can you check your file names for all your layers and ensure that none of them include any "-", for some reason the hyphen causes an error.
> 
> From memory the error looked similar to what you're showing me and due to the rarity weights it can throw the error at different intervals.
> 
> I hope this helps!
> 
> Cheers.

Thanks so much! There was a few stray marks in there. I also think I had a few corrupted graphics from the new Adobe Illustrator. Some of the vector to PNG outputs have been problematic but I'm sure there is an update soon. Thx! :)

**Comment by LKYSE7EN** [comment]
You're very welcome!

Good luck with your NFT Collection!

**Comment by salonikoo** [comment]
I got the same exact problem, but all my png are just fine. No spaces or any unlliget symbols. There's possibly any other solution? Ive tried EVERYTHING! 3 days of that issues. Im lost!

**Comment by kristiangabriel** [comment]
> I got the same exact problem, but all my png are just fine. No spaces or any unlliget symbols. There's possibly any other solution? Ive tried EVERYTHING! 3 days of that issues. Im lost!

That sounds like what I went through! I even tried different computers MAC/PC and all kinds of things. Aside from the naming issue with dashes, etc--the other thing I found was a corruption in a few of the graphics files that were not visually or functionally apparent at all. Depend on how you are creating and outputting your graphic content makes a difference. I use primarily Adobe Illustrator and sometimes Photoshop to create most of my content. I found out that creating the graphics in the 2021 versions and then outputting them from the 2022 versions of Adobe caused slight corruptions in some of the files and this also caused the nft outputs to stop and cause errors. Here is what I did to fix my issues:

- Check that all my names have hash symbols unless the delimiter is changed 
- Check that there are no dashes or any special characters in the naming of graphics or the layer file names (this fixed my first issue)
- Then I eliminated my layer folders (background, body, etc) one at a time and re-output my NFTs to see if I received the same problem.** 

Other than the naming fixes, I was able to bypass issues and located problems across a few layer folders.

Solution: I re-output a small batch of graphics in the new Adobe 2022 apps and they seem to be fine so I re-generated my new layers. And this seemed to do the trick.**

As a side note, in Illustrator, **I flattened, expanded and outlined EVERYTHING** before output. So if you are working in Illustrator you'll probably want to duplicate your project first. There are known corruptions with some PNG outputs from Illustrator and Photoshop. In Photoshop I duplicate my files and merge layers with transparencies to fix this. While this doesn't always happen, I've learned to do this for my NFT artwork to avoid as much corruptions as possible. I know there are other things that can contribute to error issues as well but this is my experience so far.
