### ISSUE TITLE
error when trying to run

### ISSUE THREAD

**Issue by tonispoisz** [HashLips/hashlips_art_engine#245]
PS C:\Users\Tõnis\Desktop\hashlips_art_engine-main> node index.js
C:\Users\Tõnis\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'C:\Users\Tõnis\Desktop\hashlips_art_engine-main/layers/Background/Pink#100.jpg'
    at setSource (C:\Users\Tõnis\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Tõnis\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Tõnis\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Tõnis\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\Tõnis\Desktop\hashlips_art_engine-main\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Tõnis\Desktop\hashlips_art_engine-main\src\main.js:180:10)
    at C:\Users\Tõnis\Desktop\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\Tõnis\\Desktop\\hashlips_art_engine-main/layers/Background/Pink#100.jpg',
  syscall: 'fopen'
}

Anyone know how to fix? I really dont know how to code.

**Comment by AlapanMondal** [comment]
Make sure that you have saved the file after changes.

**Comment by damith48** [comment]
my error
PS D:\hashlips_art_engine-1.0.2_update> npm i canvas

up to date, audited 66 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\hashlips_art_engine-1.0.2_update> node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\bindings.js
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\canvas.js
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\index.js
- D:\hashlips_art_engine-1.0.2_update\src\main.js
- D:\hashlips_art_engine-1.0.2_update\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\lib\\bindings.js',
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\lib\\canvas.js',
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\index.js',
    'D:\\hashlips_art_engine-1.0.2_update\\src\\main.js',
    'D:\\hashlips_art_engine-1.0.2_update\\index.js'
  ]
}
PS D:\hashlips_art_engine-1.0.2_update>


How to fix this

**Comment by MrWhite1102** [comment]
Hello, I have the exact same. Did you find a solution ? Thks

**Comment by Nanerito** [comment]
to be more visual here are the image os the issue, please help us!
![WhatsApp Image 2022-05-03 at 13 09 08](https://user-images.githubusercontent.com/91572819/166505427-9c4d0fef-46d9-4d3e-9efb-d26ed3895c00.jpeg)

**Comment by bolshoytoster** [comment]
@Nanerito try moving the project folder to somewhere like `C:/Users/Public`.

**Comment by Nanerito** [comment]
> @Nanerito try moving the project folder to somewhere like `C:/Users/Public`.

ill try
