### ISSUE TITLE
Can't continue image creation, const image = await loadImage(`${_layer.selectedElement.path}`);

### ISSUE THREAD

**Issue by bmnvnt** [HashLips/hashlips_art_engine#247]
TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\user\Pictures\project\NFT\tarsiers\MadTarsiers\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\user\Pictures\project\NFT\tarsiers\MadTarsiers\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:180:10)
    at C:\Users\user\Pictures\project\NFT\tarsiers\MadTarsiers\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\user\Pictures\project\NFT\tarsiers\MadTarsiers\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:360:17)

what do I have to do? Thanks

**Comment by Spidle** [comment]
Remove dashes from file names

**Comment by gauravraj0510** [comment]
> Remove dashes from file names

Can you please elaborate?

**Comment by bmnvnt** [comment]
remove the "-" in the filename

Pada tanggal Min, 21 Nov 2021 16.40, Gaurav Raj ***@***.***>
menulis:
