### ISSUE TITLE
Cannot run node index.js

### ISSUE THREAD

**Issue by unixbird** [HashLips/hashlips_art_engine#250]
After editing the layers and other info in the config.js i attempt to generate everything but am met with this errror

`hashlips_art_engine>node index.js
(node:1074921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1074921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1074921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1074921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1074921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1074921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1074921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1074921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1074921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1074921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1074921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:1074921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1074921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
zach 13:43 Sat Nov 13
hashlips_art_engine>npm run build

> hashlips_art_engine@1.1.1 build /home/zach/hashlips_art_engine
> node index.js

(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1075020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:1075020) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /home/zach/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/home/zach/hashlips_art_engine/src/main.js:180:10)
    at /home/zach/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/home/zach/hashlips_art_engine/src/main.js:360:17)
    at /home/zach/hashlips_art_engine/index.js:6:3
    at Object.<anonymous> (/home/zach/hashlips_art_engine/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(node:1075020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
`

I am running Fedora 34 with nodejs installed and i have run npm install before running the node index.js command is there something I'm missing?

**Comment by unixbird** [comment]
Well I fixed my own issue. Don't include dashes or _s as that will throw that error and will confuse you.
