### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Lendaryuri** [HashLips/hashlips_art_engine#266]
TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\src\main.js:267:15)
    at cleanDna (C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\src\main.js:60:26)
    at C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\src\main.js:218:22
    at Array.find (<anonymous>)
    at C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\src\main.js:217:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\src\main.js:216:35)
    at startCreating (C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\src\main.js:357:23)
    at C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\index.js:6:3
    at Object.<anonymous> (C:\Users\iurio\OneDrive\Bureau\hashlips_art_engine-1.1.1_update\index.js:7:3)

**Comment by SorinIScintei** [comment]
@Lendaryuri  did you resolve it?

**Comment by wesdeth** [comment]
I'm also having this issue

**Comment by bolshoytoster** [comment]
@CryptoniteMining if you have the same error can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.
