### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Engin92** [HashLips/hashlips_art_engine#267]
Hi I wanted to create some images, but neither "npm run build" nor "npm run preview" won't work.

if i try to generate images with "npm run build" or "node index.js" the following Error is thrown:
```
(node:18272) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:267
  return _dna.replace(query, "");
              ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:267:15)
    at cleanDna (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:60:26)
    at C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:218:22
    at Array.find (<anonymous>)
    at C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:217:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:216:35)
    at startCreating (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:357:23)
    at C:\Users\Engin\Desktop\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\Engin\Desktop\hashlips_art_engine-main\index.js:7:3)
PS C:\Users\Engin\Desktop\hashlips_art_engine-main> 
```

if i try to run "npm run preview" i get the following ERROR:
```
> node index.js

(node:18272) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:267
  return _dna.replace(query, "");
              ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:267:15)
    at cleanDna (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:60:26)
    at C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:218:22
    at Array.find (<anonymous>)
    at C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:217:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:216:35)
    at startCreating (C:\Users\Engin\Desktop\hashlips_art_engine-main\src\main.js:357:23)
    at C:\Users\Engin\Desktop\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\Engin\Desktop\hashlips_art_engine-main\index.js:7:3)
PS C:\Users\Engin\Desktop\hashlips_art_engine-main> npm run preview

> hashlips_art_engine@1.1.1 preview
> node utils/preview.js

node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\Engin\Desktop\hashlips_art_engine-main/build/json/_metadata.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (C:\Users\Engin\Desktop\hashlips_art_engine-main\utils\preview.js:9:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Engin\\Desktop\\hashlips_art_engine-main/build/json/_metadata.json'
}
PS C:\Users\Engin\Desktop\hashlips_art_engine-main> 
```

what did i do before that:
run: npm install
run: npm install truffle
run: npm install canvas

renamed my layers in config.js >"layerOrder" to the files I have created. Every file has at least 1 png file.
and tried to generate the images

(and yes, i have saved the vscode file before generating, it doesn't work :( )

**Comment by aminebidda** [comment]
Duplicate of #
did you manage to solve the issue?

**Comment by viirse** [comment]
having the exact same problem how can i fix this?????
