### ISSUE TITLE
Error: error while reading from input stream

### ISSUE THREAD

**Issue by prshnandaniya** [HashLips/hashlips_art_engine#271]
Created edition: 1, with DNA: 23,55,38,82,56,15,18,46,8,0,0
Created edition: 2, with DNA: 51,64,98,82,55,17,21,2,12,0,0
Created edition: 3, with DNA: 4,34,33,78,69,8,24,79,8,0,0
Created edition: 4, with DNA: 10,74,92,52,4,12,16,33,3,0,0
/Users/pareshnandaniya/projects/nft-generator/generator/node_modules/canvas/lib/image.js:91
  SetSource.call(img, src);
            ^

Error: error while reading from input stream
    at setSource (/Users/pareshnandaniya/projects/nft-generator/generator/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/pareshnandaniya/projects/nft-generator/generator/node_modules/canvas/lib/image.js:62:9)
    at /Users/pareshnandaniya/projects/nft-generator/generator/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/pareshnandaniya/projects/nft-generator/generator/node_modules/canvas/index.js:23:10)
    at /Users/pareshnandaniya/projects/nft-generator/generator/src/main.js:101:25
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/pareshnandaniya/projects/nft-generator/generator/src/main.js:100:10)
    at /Users/pareshnandaniya/projects/nft-generator/generator/src/main.js:158:29
    at Array.forEach (<anonymous>)

**Comment by cdric** [comment]
The png that the generator is trying to access might not be available. Make sure all your files are valid and the program can have access to them.

**Comment by gewure** [comment]
> The png that the generator is trying to access might not be available. Make sure all your files are valid and the program can have access to them.

i have the exact same error (sometimes after 10 generate, somtimes after 27, ..) and whonder what do you mean with 'might not be available' or not valid.

**Comment by gewure** [comment]
I fixed my issue!

It really was a problem with one of the background PNGs. It had a transparent part. when i excluded it all was generated fine.

=> Make sure all your images are really fit for the purpose.. same size, format, backgrounds not transparent like in my case :roll_eyes:

**Comment by reubennn** [comment]
Can confirm this is to do with bad files in your layers folder. For some reason some of my images had gotten corrupted (not sure how) and this was causing this error. Replaced the corrupted files and the generator works perfectly again!
