### ISSUE TITLE
Unexpected token error on run

### ISSUE THREAD

**Issue by zarveyy** [HashLips/hashlips_art_engine#282]
```
src\main.js:91
      layerObj.options?.["displayName"] != undefined
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\axelb\Bureau\workspace\NFT\art_engine\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
``` 
I cloned the repo, runned npm install and tried to run it to see if it worked and I'm getting this error

**Comment by FernandoGMorales** [comment]
Same issue here, any update on this???

**Comment by FernandoGMorales** [comment]
> ```
> src\main.js:91
>       layerObj.options?.["displayName"] != undefined
>                                  ^
> 
> SyntaxError: Unexpected token '.'
>     at wrapSafe (internal/modules/cjs/loader.js:1053:16)
>     at Module._compile (internal/modules/cjs/loader.js:1101:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (C:\Users\axelb\Bureau\workspace\NFT\art_engine\index.js:2:39)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> ```
> 
> I cloned the repo, runned npm install and tried to run it to see if it worked and I'm getting this error

Solved! Just update the lates version of:

**Comment by crabnebulla** [comment]
I'm still getting the same issue running 
1. hashlips_art_engine (v1.1.1 or v1.1.2)
2. node (mine is: v16.13.0)

Any idea what the issue would be or a workaround?

**Comment by luangjokaj** [comment]
> I'm still getting the same issue running
> 
> 1. hashlips_art_engine (v1.1.1 or v1.1.2)
> 2. node (mine is: v16.13.0)
> 
> Any idea what the issue would be or a workaround?

https://github.com/HashLips/hashlips_art_engine/issues/375#issuecomment-1025135259

**Comment by calebrcannon** [comment]
I tried everything, using every nvm version, etc, and eventually what worked is just:
`nvm use`
It must have been that my node version was correct but not my npm version? This was after reinstalling all of my packages.
