### ISSUE TITLE
get a npm issue when trying too install and can not figure out what im doing wrong or cant find any videos on youtube

### ISSUE THREAD

**Issue by Masonry317** [HashLips/hashlips_art_engine#292]
![Screenshot (3)](https://user-images.githubusercontent.com/89306057/142780354-52cfcdda-d56d-4f47-b995-1c461bbba0be.png)

**Comment by Masonry317** [comment]
when i also try too install canvas through VSC its also giving me the same thing

**Comment by hector4213** [comment]
Which version of node are you currently using?

**Comment by damith48** [comment]
PS D:\hashlips_art_engine-1.0.2_update> npm i canvas

up to date, audited 66 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\hashlips_art_engine-1.0.2_update> node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\bindings.js
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\canvas.js
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\index.js
- D:\hashlips_art_engine-1.0.2_update\src\main.js
- D:\hashlips_art_engine-1.0.2_update\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\lib\\bindings.js',
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\lib\\canvas.js',
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\index.js',
    'D:\\hashlips_art_engine-1.0.2_update\\src\\main.js',
    'D:\\hashlips_art_engine-1.0.2_update\\index.js'
  ]
}
PS D:\hashlips_art_engine-1.0.2_update>

How to fix this

**Comment by Masonry317** [comment]
> Which version of node are you currently using?

i am using the lastest vesion of node . just downloaded it yesturday

**Comment by curreythomas** [comment]
Try running `$ npm update` then `$ npm install`. This seemed to work for me.

**Comment by curreythomas** [comment]
if you have yarn installed you can try this.

Download a the project zip file and unzip it. Navigate into the project directory (for me  that is 'hashlips_art_engine-1.1.2_patch_v1'). Once inside the project, run `$ yarn install` - I received the same errors you previously reported in you image. After this I ran `npm install` and get 
'''up to date, audited 66 packages in 406ms

6 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
'''

**Comment by FunkySea** [comment]
Literally going through all of these open issues trying stuff and nothing is working. still getting errors. can anyone help. yarn install doesn't nothing for me by the way
