### ISSUE TITLE
when I type node index.js I get this message

### ISSUE THREAD

**Issue by jaemazor** [HashLips/hashlips_art_engine#293]
when I type node index.js i get this message
![Screenshot 2021-11-21 143112](https://user-images.githubusercontent.com/94377729/142781459-c9f23034-9c4b-4fce-8f30-c70d44bfe816.jpg)
get this message

**Comment by damith48** [comment]
PS D:\hashlips_art_engine-1.0.2_update> npm i canvas

up to date, audited 66 packages in 2s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\hashlips_art_engine-1.0.2_update> node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\bindings.js
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\canvas.js
- D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\index.js
- D:\hashlips_art_engine-1.0.2_update\src\main.js
- D:\hashlips_art_engine-1.0.2_update\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\hashlips_art_engine-1.0.2_update\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\lib\\bindings.js',
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\lib\\canvas.js',
    'D:\\hashlips_art_engine-1.0.2_update\\node_modules\\canvas\\index.js',
    'D:\\hashlips_art_engine-1.0.2_update\\src\\main.js',
    'D:\\hashlips_art_engine-1.0.2_update\\index.js'
  ]
}
PS D:\hashlips_art_engine-1.0.2_update>


my error
need for help...

**Comment by damith48** [comment]
how to fix this

**Comment by CapSens-SM** [comment]
> when I type node index.js i get this message ![Screenshot 2021-11-21 143339](https://user-images.githubusercontent.com/94377729/142781528-381f9fbc-b491-4911-94b1-de96ead82e8f.jpg)

Install NVM and ensure to use Node 16.x.x, you're using a too recent version of nodejs

**Comment by FloBorg** [comment]
i have a similar issue on Mac, using node 16.3

**Comment by EDAN555** [comment]
same here
