### ISSUE TITLE
no such file or directory pls help 

### ISSUE THREAD

**Issue by nelisj** [HashLips/hashlips_art_engine#305]
I am trying to create a NFT collection from a set of 9 features each with 5-10 versions of the features formatted as xxx#10.png the visual studio code editor recognises all of the folders and files but somehow the files cannot be accessed during the run. What may be the issue here ? Thanks a lot! 

node:44898) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/layers/GesichtAccessoires/'
    at Object.readdirSync (fs.js:1043:3)
    at getElements (/Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/src/main.js:73:6)
    at /Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/src/main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/src/main.js:87:30)
    at startCreating (/Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/src/main.js:349:20)
    at /Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/index.js:6:3
    at Object.<anonymous> (/Users/jnelis/Desktop/CV_21124_v001/hashlips_art_engine-main/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(base) jans-macbook-pro:hashlips_art_engine-main jnelis$

**Comment by FloBorg** [comment]
I have a similar issue on Monterey - Mac

**Comment by BlackBagels** [comment]
Try hitting save before running node index.js in the terminal.

**Comment by luisgarcia4511** [comment]
Fixed it !!!
on the image layer files take off any —
and include a #10 at the end
ex. Yellowbg#10.png
