### ISSUE TITLE
error "split" and others

### ISSUE THREAD

**Issue by masad08** [HashLips/hashlips_art_engine#31]
Hi. Thanks for the program

for V1.00 and 1.002, all ok, but not for 3 or 4.
getting this if you can help. Thanks
(.... is part of the directory, replaced it here with dots)

PS ....\hashlips_art_engine-1.0.4> node index.js
(node:27828) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at cleanDna (....\hashlips_art_engine-1.0.4\src\main.js:46:25)
    at ....\hashlips_art_engine-1.0.4\src\main.js:142:22
    at Array.find (<anonymous>)
    at ....\hashlips_art_engine-1.0.4\src\main.js:141:42
    at Array.map (<anonymous>)
    at constructLayerToDna (....\hashlips_art_engine-1.0.4\src\main.js:140:35)
    at startCreating (....\hashlips_art_engine-1.0.4\src\main.js:209:23)
    at D:\nft3\hashlips_art_engine-1.0.4\index.js:5:3
    at Object.<anonymous> (....\hashlips_art_engine-1.0.4\index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by masad08** [comment]
found the issue.
layer files have to have the # or whatever is used.

This could be changed to be optional

**Comment by soliditywiz** [comment]
Getting this as well

**Comment by jovenxo** [comment]
how exactly do i fix this , don't understand "layer files have to have the # or whatever is used."

**Comment by Th3HotDog** [comment]
> how exactly do i fix this , don't understand "layer files have to have the # or whatever is used."

This is from the Read Me. Hope this helps:

"Create your different layers as folders in the 'layers' directory, and add all the layer assets in these directories. You can name the assets anything as long as it has a rarity weight attached in the file name like so: example element#70.png. You can optionally change the delimiter # to anything you would like to use in the variable rarityDelimiter in the src/config.js file."

**Comment by SakuruNakamoto** [comment]
I also had this problem and can confirm that adding # with the rarity weight works.

**Comment by walterpinson** [comment]
Thanks, gents.  Was experiencing the exact same problem.  Adding rarity to the element file names resolved the issue.
