### ISSUE TITLE
help

### ISSUE THREAD

**Issue by phantomcodee** [HashLips/hashlips_art_engine#314]
hey i need help i keep getting this error every time i get this error when i go to run it i have all the things done correctly like my folders are named the same thing as the layers configuratiion please help
 C:\Users\jeanm\Downloads\hashlips_art_engine-main(2)> node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\jeanm\Downloads\hashlips_art_engine-main(2)\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)  
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by FrankLio13213** [comment]
Delete all the three downloaded folders, download again, decompress and re-run "npm install". It may take a few minutes to complete the download. After the download is complete, run other commands, such as "node index.js". You can give it a try, hope it helps you.
