### ISSUE TITLE
Cant create rarity info "forEach" Error

### ISSUE THREAD

**Issue by lm166796** [HashLips/hashlips_art_engine#318]
Get the following upon running

> hashlips_art_engine@1.1.1 rarity
> node utils/rarity.js

C:\Users\Lm166\Documents\hashlips_art_engine\utils\rarity.js:53
    rarityDataTraits.forEach((rarityDataTrait) => {
                     ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at C:\Users\Lm166\Documents\hashlips_art_engine\utils\rarity.js:53:22
    at Array.forEach (<anonymous>)
    at C:\Users\Lm166\Documents\hashlips_art_engine\utils\rarity.js:48:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Lm166\Documents\hashlips_art_engine\utils\rarity.js:46:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)

**Comment by edenheijer** [comment]
have you successfully generated all editions, i.e. has `node run build` generated the _metadata.json file?

**Comment by lm166796** [comment]
yes, i even rebuilt

**Comment by Andr3json** [comment]
What fixed it for me was from
![RARITY](https://user-images.githubusercontent.com/94962908/144652866-9ef54886-a3eb-4c9a-8a09-be87f9296ee9.PNG)

to 

![rarity2](https://user-images.githubusercontent.com/94962908/144653136-08c463b9-3549-47c1-bfd7-8667c3fad8de.PNG)

at least i think i fixed it lol :)

**Comment by Andr3json** [comment]
Since this is in my main.js, hope it helps 

![Uploading main.PNG…]()

**Comment by Andr3json** [comment]
@HashLips sorry for bothering you, is this fixed? Might help people out idk :)
