### ISSUE TITLE
v 1.1.2 issue node index.js

### ISSUE THREAD

**Issue by joyboykda** [HashLips/hashlips_art_engine#321]
when i run node index.js i always get this error. i do not know how to fix it 

(node:32108) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\menat\Desktop\code\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\menat\Desktop\code\src\main.js:180:10)
    at C:\Users\menat\Desktop\code\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\menat\Desktop\code\src\main.js:360:17)
(Use node --trace-warnings ... to show where the warning was created)
(node:32108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:32108) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\menat\Desktop\code\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\menat\Desktop\code\src\main.js:180:10)
    at C:\Users\menat\Desktop\code\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\menat\Desktop\code\src\main.js:360:17)
(node:32108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
PS C:\Users\menat\Desktop\code> ^C
PS C:\Users\menat\Desktop\code>

**Comment by joyboykda** [comment]
no i havent

**Comment by luisgarcia4511** [comment]
Fixed it !!!
on the image layer files take off any — 
and include a #10 at the end 
ex. Yellowbg#10.png
