### ISSUE TITLE
Node index.js displayname error

### ISSUE THREAD

**Issue by Gmurray86** [HashLips/hashlips_art_engine#327]
Every time I run node index.js I end up with the following error.  I have done some searching on my own before posting.  I have tried installing Canvas, uninstalling node.js, and reinstalling node.js.  I am using HashLips 1.1.2.
Here is the error

/home/gmurray86/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js:91  
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/gmurray86/Desktop/hashlips_art_engine-1.1.2_patch_v1/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    
The error references this line.

layerObj.options?.["displayName"] != undefined

to which Visual Code Studio suggests refactoring?  I am also having this problem when I use all of the original files without any of my own images files.

**Comment by MonkIsReal** [comment]
had the same error
update your node js
npm install -g npm@8.1.4

delete your node_modules file

rebuild your project
npm install

**Comment by GuillaumeFitzrichard** [comment]
> had the same error update your node js npm install -g npm@8.1.4
> 
> delete your node_modules file
> 
> rebuild your project npm install


Was just about to reply similarly, I had an old version of node, wasn't recognizing the optional chaining. 
Node update and then reinstalling the modules did the trick

**Comment by Gmurray86** [comment]
Thank you guys, I had just figured this all out.  I should have started by making sure I had everything installed.  I'm still new to all this.
