### ISSUE TITLE
dlopen error PLEASE HELP (fast if you can;-)

### ISSUE THREAD

**Issue by nikhebborn** [HashLips/hashlips_art_engine#329]
Hello,
I had the script running all the time with no problems.

All of a sudden I can't run "node index.js" anymore and keep getting this error below. We want to drop our NFT very soon and were just about to generate the pictures. So... ANY HELP VERY VERY MUCH APPRECIATED!

(base) timhebborn@Air-von-Tim hashlips_art_engine-main % node index.js
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/timhebborn/Desktop/LB_CREATE BUCKS/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node, 1): no suitable image found.  Did find:
        /Users/timhebborn/Desktop/LB_CREATE BUCKS/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
        /Users/timhebborn/Desktop/LB_CREATE BUCKS/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/timhebborn/Desktop/LB_CREATE BUCKS/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'

**Comment by edenheijer** [comment]
Are you by any chance coding on a M1 Mac? It would seem there is no canvas module for ARM available/installed

**Comment by nikhebborn** [comment]
yes I am, but I solved it by re-installing canvas with npm

**Comment by bolshoytoster** [comment]
@mmaklary 
> How to u reinstal canvas? same issue with mbp m1

Delete the `node_modules` folder and run `npm install` again.

**Comment by cryptofannatic** [comment]
@nikhebborn which version of node are you using?
