### ISSUE TITLE
Generate not complete

### ISSUE THREAD

**Issue by alkan2798** [HashLips/hashlips_art_engine#343]
C:\Users\alkan\Desktop\hashlips_art_engine-main2\src\main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\alkan\Desktop\hashlips_art_engine-main2\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\alkan\Desktop\hashlips_art_engine-main2\src\main.js:180:10)
    at C:\Users\alkan\Desktop\hashlips_art_engine-main2\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\alkan\Desktop\hashlips_art_engine-main2\src\main.js:360:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by DOGEDRAGONS** [comment]
I am getting the same! Any luck?

**Comment by Lenarp** [comment]
I have the same error! Theres another thread where someone was having this error. Someone suggested using 1.03 version of Visual Studio (from what I understand). I tried that, but still had the same path error.

**Comment by Lenarp** [comment]
figured it out from another thread!

remove any symbol from names of layers
for example bg-black becomes bgblack

**Comment by HAMZAJAVEDKHAN** [comment]
@Lenarp Thank you. I was trying to do the same by removing (-) instead I added ( _ ) which also causes the issue, so I removed all the symbols and worked for me.

**Comment by jvargasnmhu** [comment]
> figured it out from another thread!
> 
> remove any symbol from names of layers for example bg-black becomes bgblack

How does this work when adding rarities to a layer? I am running into issues using a star (*) with a number behind it (i.e: faceOne*10.png ). 5% of my generated images are not populating all the layers.
