### ISSUE TITLE
Tring to get npm install to work - seems as though canvas is the issue. Any help is appreciated!

### ISSUE THREAD

**Issue by ZacharyTanner1** [HashLips/hashlips_art_engine#345]
node-pre-gyp@0.17.0  /usr/local/lib/node_modules/node-pre-gyp
node@16.13.0
@MacBook-Air hashlips_art_engine-1.1.2_patch_v1 % -c node-pre-gyp install --fallback-to-build 
zsh: command not found: -c
@MacBook-Air hashlips_art_engine-1.1.2_patch_v1 %  node-pre-gyp install --fallback-to-build  
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@16.13.0 | darwin | arm64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: hashlips_art_engine package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties: 
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at install (/usr/local/lib/node_modules/node-pre-gyp/lib/install.js:241:31)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (/usr/local/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1101:14)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
node-pre-gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:981:32)
node-pre-gyp ERR! stack     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
node-pre-gyp ERR! System Darwin 20.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1
node-pre-gyp ERR! node -v v16.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok 
hashlips_art_engine package.json is not node-pre-gyp ready:
package.json must declare these properties: 
binary.module_name
binary.module_path
binary.host

**Comment by k-v-r-l** [comment]
having the same problem

**Comment by k-v-r-l** [comment]
I had the same problem. Installing an older version of node (14.18.1) fixed the problem for me. Hope this helps.

**Comment by ZacharyTanner1** [comment]
> I had the same problem. Installing an older version of node (14.18.1) fixed the problem for me. Hope this helps.

It worked, but now it is giving me this error when I type node index.js: 

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas'
Require stack:
- /Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1/src/main.js
- /Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1/src/main.js:5:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1/src/main.js',
    '/Users/zachary/Downloads/hashlips_art_engine-1.1.2_patch_v1/index.js'
  ]
}

**Comment by BrandonFassberg** [comment]
> I had the same problem. Installing an older version of node (14.18.1) fixed the problem for me. Hope this helps.

Where can we download this older version? trying to find it on the site. tx!

**Comment by BrandonFassberg** [comment]
> 

Found it and it worked! https://nodejs.org/en/blog/release/v14.18.1/
