### ISSUE TITLE
Can't get generate started?

### ISSUE THREAD

**Issue by vicvic18** [HashLips/hashlips_art_engine#347]
After entering "npm run generate"

It shown:
Error: The specified module could not be found.
\\?\C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-12-06T14_48_43_437Z-debug.log
PS C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1> npm run generate

> hashlips_art_engine@1.1.1 generate C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1
> node index.js

internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-12-06T14_56_18_600Z-debug.log
PS C:\SOLANA\hashlips_art_engine-1.1.2_patch_v1>

ANYONE HELP?? THANK YOU !!

**Comment by anuuo** [comment]
Hello, I solved that issue. You have to change your node version to 14.18.1 or 14.18.2.
You can simply check your current version with this command : node -v

My past version was 16 (lastest). You can delete node.js with this command: brew uninstall node
Just change it to version 14

**Comment by vicvic18** [comment]
It's working now after I reinstall everything...
