### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by basharww** [HashLips/hashlips_art_engine#355]
after replacing the folders in 'Layers' I started getting this error... it appears to be found in line 267 in Main ( return _dna.replace(query, ""); )
can anyone help me get passed this issue?

**Comment by basharww** [comment]
FIX : just change the Images' names to  'Gray#30' or any percentage you want it to have.

**Comment by jonny-vanessen** [comment]
I had a similar issue, you cannot have any hyphens in your layer names

**Comment by theHighLibrarian** [comment]
is it the hash tag (#) thats key?

**Comment by byustephen** [comment]
@jonny-vanessen You are a saint! I had the same issue and when I removed my hypens from the layer names it worked. This was my error though:

```
ip-10-13-13-3:hashlips_art_engine sgodfrey$ node index.js
(node:49354) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: 42d817413952f272658206b63b3407fb05ab9b9d
/Users/sgodfrey/projects/nfts/wonderous_worlds/hashlips_art_engine/src/main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read property 'path' of undefined
    at /Users/sgodfrey/projects/nfts/wonderous_worlds/hashlips_art_engine/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/sgodfrey/projects/nfts/wonderous_worlds/hashlips_art_engine/src/main.js:180:10)
    at /Users/sgodfrey/projects/nfts/wonderous_worlds/hashlips_art_engine/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/Users/sgodfrey/projects/nfts/wonderous_worlds/hashlips_art_engine/src/main.js:360:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by GabrielCHP** [comment]
I'm having the same issue, I followed what you told and nothing changed.
`(node:6248) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:267
  return _dna.replace(query, "");
              ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:267:15)
    at cleanDna (C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:60:26)
    at C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:218:22
    at Array.find (<anonymous>)
    at C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:217:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:216:35)
    at startCreating (C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:357:23)
    at C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\index.js:6:3
    at Object.<anonymous> (C:\Users\user\Desktop\hashlips_art_engine-1.1.2_patch_v1\index.js:7:3)

Node.js v17.4.0`

**Comment by SorinIScintei** [comment]
@GabrielCHP , did you resolve the issue?

**Comment by bolshoytoster** [comment]
@SorinIScintei make sure there are no `-` characters and you have a `#` for rarity in all of your element names.

**Comment by chudney** [comment]
I can confirm that @[GabrielCHP] error was solved for me by adding rarities with #1-1000 etc in ALL image titles in ALL layers, I only needed them for some folders and left some without, this caused the 'TypeError: Cannot read properties of undefined (reading 'replace') error'

**Comment by SorinIScintei** [comment]
@bolshoytoster @chudney thank you, guys. The generate function worked after I've set the rarity of each layer.

**Comment by AdityaNikhil** [comment]
Though I set the rarity, it doesn't work... Any other solutions?

**Comment by bolshoytoster** [comment]
@AdityaNikhil try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), it probably won't fix it but it'll give a more informative error.

**Comment by AdityaNikhil** [comment]
@bolshoytoster Setting the rarity works but am afraid there are 100s of images and it's tedious to rename every file right now. Will your code work without providing rarity?

**Comment by bolshoytoster** [comment]
@AdityaNikhil yes, in my repo, if all images in a layer don't have a rarity it will just pick a random one.

**Comment by AdityaNikhil** [comment]
@bolshoytoster Great, will try that and do you have any solution for this [issue](https://github.com/HashLips/hashlips_art_engine/issues/801) I opened today?

**Comment by bolshoytoster** [comment]
@AdityaNikhil no, sorry.

**Comment by Eluwsive** [comment]
@bolshoytoster Im using your fork but i get this error Error: EACCES, Permission denied 'D:\downies\hashlips_art_engine-main/layers/Background/PNG'

**Comment by bolshoytoster** [comment]
@Eluwsive can you paste the full error please.

**Comment by theHighLibrarian** [comment]
FYI. My issue was fixed by using the exact same file names as you used.

**Comment by thursday15** [comment]
Hi, how to solve this error

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (D:\Montana NFT\src\main.js:274:15)
    at cleanDna (D:\Montana NFT\src\main.js:60:26)
    at D:\Montana NFT\src\main.js:225:22
    at Array.find (<anonymous>)
    at D:\Montana NFT\src\main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (D:\Montana NFT\src\main.js:223:35)
    at startCreating (D:\Montana NFT\src\main.js:364:23)
    at D:\Montana NFT\index.js:6:3
    at Object.<anonymous> (D:\Montana NFT\index.js:7:3)

**Comment by bolshoytoster** [comment]
@thursday15 try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
