### ISSUE TITLE
It always stops when generating images...

### ISSUE THREAD

**Issue by vicvic18** [HashLips/hashlips_art_engine#363]
The number of generations is also not fixed when stopping
Please help！
Thanks a lot, guys！！

IT SAYS

(node:13904) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at E:\SOLANA\hashlips_art_engine-main\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (E:\SOLANA\hashlips_art_engine-main\src\main.js:180:10)
    at E:\SOLANA\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (E:\SOLANA\hashlips_art_engine-main\src\main.js:360:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13904) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at E:\SOLANA\hashlips_art_engine-main\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (E:\SOLANA\hashlips_art_engine-main\src\main.js:180:10)
    at E:\SOLANA\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (E:\SOLANA\hashlips_art_engine-main\src\main.js:360:17)
(node:13904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by patch2828** [comment]
I'm getting the same error message

**Comment by Sicktear** [comment]
Getting the same error message as well. Also @vicvic18: you might want to change the name of this issue to "UnhandledPromiseRejectionWarning: Unhandled promise rejection." or something so that people who experience the same thing can recognize the error and jump in to comment or help solve. Just a suggestion :D
