### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'C:\hashlips_art_engine-main/layers/Eyeball/'

### ISSUE THREAD

**Issue by arlene91** [HashLips/hashlips_art_engine#370]
Hi
I have been having this issue without being able to see how to resolve it.
I'm not technical at all so this has been very helpful.
But what I did,is changing the folders of my layers in my file explorer to match the ones I created in the LayersConfiguration in Visual Studio Code. So I don't have any folder called EyeBall and can't find why I got this error message.

Can anyone help, please ?

**Error message:**

Error: ENOENT: no such file or directory, scandir 'C:\hashlips_art_engine-main/layers/Eyeball/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\hashlips_art_engine-main\src\main.js:73:6)
    at C:\hashlips_art_engine-main\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\hashlips_art_engine-main\src\main.js:87:30)
    at startCreating (C:\hashlips_art_engine-main\src\main.js:349:20)
    at C:\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\hashlips_art_engine-main/layers/Eyeball/'

**Comment by Fergoshi** [comment]
It cannot find your eyeball layer , you must have it misspelled or in the wrong order.

**Comment by Zzzeps** [comment]
Getting the same Error

I don't have an eyeball layer either. I've updated all the layer names to match the image folders and it's still trying to find an eyeball layer which doesn't exist

**Comment by Zzzeps** [comment]
Super easy fix...Click on the config.js file and click save. Worked for me 👍

**Comment by arlene91** [comment]
Thank you all.
I finally got it work with no such error anymore. I don't know exactly how the error disappeared.
I think it's because the content of each layer's folder didn't have the appropriate format, such as .png.
Now I have other issues, like it doesn't take all layers into account and doesn't name the files as I asked it to name it.
Well need to test by changing the parameters to see what works !!!!

**Comment by arlene91** [comment]
I got it alright now :-)

**Comment by charliesnft** [comment]
Im having the same issue. I've created NFTs collection before but  I been stuck on this for a couple of days. 

errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/charle/Downloads/hashlips_art_engine-1.1.0_update/layers/Background/'
}

What do I need to do? I somewhat understand that its missing  the file but all I did was following the tutorial and deleted the default files and added my own. I have a backgrounds file  but It can't find the  original  background. im using 1.10 art engine and im using node js 17 version.

**Comment by strokEA** [comment]
hi me when I do npm run build (I have the generative-art-node-main folder from HashLips) it generated the nft's for me but after I got an error message here it is
![Uploading 3.png…]()

**Comment by strokEA** [comment]
<img width="770" alt="3" src="https://user-images.githubusercontent.com/96946219/147853268-dd011cab-326e-48ec-88a7-5575413d77bd.png">

**Comment by strokEA** [comment]
hi me when I do npm run build (I have the generative-art-node-main folder from HashLips) it generated the nft's for me but after I got an error message here it is



<img width="770" alt="3" src="https://user-images.githubusercontent.com/96946219/147853273-a47b24fa-2ea0-456b-8a25-237fcfa42a5d.png">

**Comment by arlene91** [comment]
> Im having the same issue. I've created NFTs collection before but I been stuck on this for a couple of days.
> 
> errno: -2, syscall: 'scandir', code: 'ENOENT', path: '/Users/charle/Downloads/hashlips_art_engine-1.1.0_update/layers/Background/' }
> 
> What do I need to do? I somewhat understand that its missing the file but all I did was following the tutorial and deleted the default files and added my own. I have a backgrounds file but It can't find the original background. im using 1.10 art engine and im using node js 17 version.

**Comment by mj-afk** [comment]
Hello i have this problem,
 errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\alfon\\OneDrive - Università degli Studi del Molise\\Desktop\\hashlips_art_engine-main/layers/Background/Black#1.png',  
  syscall: 'fopen'
}
what is mean? All the directory have the exact name in the code and all the images are in png.

**Comment by arlene91** [comment]
I don't know Im new to this too.
Please create a new thread to ask around

**Comment by Fergoshi** [comment]
saving before you run will work

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Sem-mem** [comment]
> 

hi! have you solved this problem ? I get the same thing (( If you understand how to fix it, please write

**Comment by bolshoytoster** [comment]
@Sem-mem the names of your folders have to match the layer names in `src/config.js` (case sensitive as well).

**Comment by Sem-mem** [comment]
> @Sem-mem the names of your folders have to match the layer names in `src/config.js` (case sensitive as well).

Of course, everything matches and the pictures are exactly png, but still. Now I'll check again, but it seems that's not the point

**Comment by mrpkay01** [comment]
save your file and all will work good..i wasted my 3 days for this error

**Comment by nftgreat** [comment]
> hashlips_art_engine@1.1.1 generate

> node index.js

 

(node:7336) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: t

rue }) instead

(Use `node --trace-deprecation ...` to show where the warning was created)

node:fs:1392

  handleErrorFromBinding(ctx);

  ^

 

Error: ENOENT: no such file or directory, scandir 'C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/Background/'

    at Object.readdirSync (node:fs:1392:3)

    at getElements (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:73:6)

at C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:89:15

    at Array.map (<anonymous>)

    at layersSetup (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:87:30)

    at startCreating (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:351:20)

    at C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\index.js:6:3

    at Object.<anonymous> (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\index.js:7:3)

    at Module._compile (node:internal/modules/cjs/loader:1103:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {

  errno: -4058,

  syscall: 'scandir',

code: 'ENOENT',

  path: 'C:\\Users\\ckali\\Downloads\\hashlips_art_engine-1.1.1_update/layers/Background/'

}

PS C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update>

**Comment by nftgreat** [comment]
> @nftgreat can you paste the full error please.

Posted

**Comment by bolshoytoster** [comment]
@nftgreat can you also paste the `layerConfigurations` bit of your `src/config.js`, and make sure it's saved as well.

**Comment by nftgreat** [comment]
> @nftgreat can you also paste the `layerConfigurations` bit of your `src/config.js`, and make sure it's saved as well.

// If you have selected Solana then the collection starts from 0 automatically

const layerConfigurations = [

  {

    growEditionSizeTo: 5,

    layersOrder: [

      { name: "Background" },

      { name: "sign" },

      { name: "numbers" },

    ],

  },

];

 

const shuffleLayerConfigurations = false;

 

const debugLogs = false;

 

const format = {

width: 1500,

  height: 1500,

  smoothing: false,

};

**Comment by nftgreat** [comment]
All layers folders are spelled exactly how you see there

**Comment by bolshoytoster** [comment]
@nftgreat can you run the command `ls C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/` and paste the output please.

**Comment by nftgreat** [comment]
PS C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update> C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/

C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/ : The term 'C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/' is not

recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 

path is correct and try again.

At line:1 char:1

+ C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (C:\Users\ckali\..._update/layers/:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by nftgreat** [comment]
> @nftgreat can you run the command `ls C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/` and paste the output please.

Posted

**Comment by bolshoytoster** [comment]
@nftgreat with the `ls` at the start of the command.

**Comment by nftgreat** [comment]
> @nftgreat can you run the command `ls C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/` and paste the output please.

PS C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update> ls C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update/layers/

 

 

    Directory: C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\layers

 

 

Mode                 LastWriteTime         Length Name

----                 -------------         ------ ----

d-----         2/28/2022   8:35 AM                Backround

d-----         2/28/2022   8:35 AM                numbers

d-----         2/28/2022   8:35 AM                sign

-a----         2/28/2022   8:28 AM           6148 .DS_Store

**Comment by bolshoytoster** [comment]
@nftgreat you've spelled `Backround` wrong in the folder name.

**Comment by nftgreat** [comment]
> 

Ok I changed it spelled correctly now but still won’t work to generate

**Comment by bolshoytoster** [comment]
@nftgreat does it give an error?

**Comment by nftgreat** [comment]
Yes 

> @nftgreat does it give an error?

Yes

**Comment by nftgreat** [comment]
It says out of memory

**Comment by nftgreat** [comment]
> @nftgreat does it give an error?

PS C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update> npm run generate

 

> hashlips_art_engine@1.1.1 generate

> node index.js

 

(node:3168) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead

(Use `node --trace-deprecation ...` to show where the warning was created)

C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\node_modules\canvas\lib\image.js:91

  SetSource.call(img, src);

            ^

 

Error: out of memory

    at setSource (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_
update\node_modules\canvas\lib\image.js:91:13)

    at Image.set (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\node_modules\canvas\lib\image.js:62:9)

    at C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\node_modules\canvas\index.js:34:15

    at new Promise (<anonymous>)

    at loadImage (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\node_modules\canvas\index.js:23:10)   

    at C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:183:25

    at new Promise (<anonymous>)

    at loadLayerImg (C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:182:10)

    at C:\Users\ckali\Downloads\hashlips_art_engine-1.1.1_update\src\main.js:363:31

    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@nftgreat you could try rebooting, and running it with just powershell (Visual Studio can use a lot of memory sometimes).

**Comment by nftgreat** [comment]
They make it look so easy on the videos it’s complicated lmao

**Comment by tryshka** [comment]
![image](https://user-images.githubusercontent.com/101057184/156931056-827130b9-e630-478c-a851-67d1fc8ae0dd.png)
 help solve this problem
 
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\Пользователь\\Documents\\hashlips_art_engine-main/layers/1_Background/error#5.png',
  syscall: 'fopen'

**Comment by mya1266** [comment]
> 

could you solve the problem because i have exacly same error and been tryna fix but nothing works out((

**Comment by bolshoytoster** [comment]
@mya1266 can you paste your error here please.

**Comment by Tdawg007** [comment]
i am getting the same thing-

errno -4058
syscall scandir
code enoent
path c:\\bsks2\\minter-dapp\\backend/layers/girl base/

**Comment by Tdawg007** [comment]
please help me

**Comment by bolshoytoster** [comment]
@Tdawg007 it can't find `backend/layers/girl base/`, make sure your folder names in `backend/layers` match the names in your `layersOrder`s.

If that doesn't work, could you try opening an issue in the place you actually got the code from.

**Comment by ermiasabera** [comment]
> Super easy fix...Click on the config.js file and click save. Worked for me 👍

Very Nice!

**Comment by ahmmaadd17** [comment]
mac@MACs-MacBook-Air hashlips_art_engine-1.1.2_patch_v6 2 % npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:70620) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1451
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/layers/backgorund/'
    at Object.readdirSync (node:fs:1451:3)
    at getElements (/Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/src/main.js:73:6)
    at /Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/src/main.js:90:30)
    at startCreating (/Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/src/main.js:356:20)
    at /Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/index.js:6:3
    at Object.<anonymous> (/Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/mac/Downloads/hashlips_art_engine-1.1.2_patch_v6 2/layers/backgorund/'
}

Node.js v18.12.1
need help..........

**Comment by bolshoytoster** [comment]
@ahmmaadd17 make sure you spell your layer names in your `layersOrder`s correctly. You probably misspelled `background` as `backgorund`.

**Comment by ahmmaadd17** [comment]
thanks

**Comment by ahmmaadd17** [comment]
can you help me how i can upload nfts on opensea without wasting time

**Comment by bolshoytoster** [comment]
@ahmmaadd17 I have no idea, but you check out [this video I found](https://www.youtube.com/watch?v=M5eCg_udGIA) and skip to the uploading part, or [find](https://duckduckgo.com/?q=upload+to+opensea) some other resource on the internet.

**Comment by Mkirill123** [comment]
PS C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6> npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:1688) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:77
        throw new Error(`layer name can not contain dashes, please fix: ${i}`);
              ^

Error: layer name can not contain dashes, please fix: Holo-kitty#3.png
    at C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:77:15
    at Array.map (<anonymous>)
    at getElements (C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:75:6)
    at C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\Кирюша\\Desktop\\hashlips_art_engine-1.1.2_patch_v6/layers/Background/light_purple#8.png',
  syscall: 'fopen'
}

Node.js v18.16.0

**Comment by Mkirill123** [comment]
hello everyone, please help with the code, all the pictures in png and layers are written correctly, I'm not a programmer, so you can use simple words

**Comment by bolshoytoster** [comment]
@Mkirill123 the large amount of text in the error may be daunting, here's the important part:
> Error: layer name can not contain dashes, please fix: Holo-kitty#3.png

**Comment by Mkirill123** [comment]
PS C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6> node index.js
(node:18772) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94
  SetSource.call(img, src)
            ^

Error: ENOENT, No such file or directory 'C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6/layers/Background/blue#8.png'
    at setSource (C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:94:13)
    at Image.set (C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:65:9)
    at C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12) 
    at C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\Кирюша\\Desktop\\hashlips_art_engine-1.1.2_patch_v6/layers/Background/blue#8.png',
  syscall: 'fopen'

**Comment by Mkirill123** [comment]
@bolshoytoster i`ve tried

**Comment by bolshoytoster** [comment]
@Mkirill123 the error is different now:
> Error: ENOENT, No such file or directory 'C:\Users\Кирюша\Desktop\hashlips_art_engine-1.1.2_patch_v6/layers/Background/blue#8.png'

This is because one of out dependencies doesn't support non-ascii characters in paths. Try moving hashlips to somewhere like `C:/Users/Public/`.

**Comment by Mkirill123** [comment]
Yes!!! It's working, thank you very much
