### ISSUE TITLE
layerObj.options?.["displayName"] != undefined

### ISSUE THREAD

**Issue by phoenixcreatives** [HashLips/hashlips_art_engine#375]
```
\> hashlips_art_engine@1.1.1 generate E:\Software\hashlips_art_engine-main
\> node index.js

E:\Software\hashlips_art_engine-main\src\main.js:91
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\Software\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-12-14T15_55_23_204Z-debug.log
```

**Comment by GuigzLab** [comment]
Same problem here

**Comment by mario-oliver** [comment]
Having the same issue. Is there a new patch released in the past few days? Looks like a new issue

**Comment by mario-oliver** [comment]
https://github.com/HashLips/hashlips_art_engine/issues/2220 
Here's the solution

**Comment by mario-oliver** [comment]
From my rudimentary knowledge of javascript and node, we are using the wrong version of node (it was automatically installed by nodejs package download. You'll need to switch your node version and the package installer could mess this up again. Here's the solution also mentioned. You'll need to download nvm (a node js package version manager). Do it as follows:
1. wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
2. nvm install v16.13.0

Because you ran `npm install` and downloaded all of the dependencies, you will need to recompile/rebuild your npm dependencies with the newest version of node you download. The way to do this is as follows:

1.  **Make sure you are in the hashlips_art_engine/ root directory**
2. run `rm -rf node_modules` 
3. run `npm install`

You should now be able to successfully run node index.js or the build script successfully.
Good luck!

**Comment by meliodev** [comment]
I fixed it.

1. Got to src/main.js
2. Find layerssetup
3. Replace by this:

```
const layersSetup = (layersOrder) => {
  const layers = layersOrder.map((layerObj, index) => ({
    id: index,
    elements: getElements(`${layersDir}/${layerObj.name}/`),
    name:
      layerObj.options && layerObj.options["displayName"] != undefined
        ? layerObj.options["displayName"]
        : layerObj.name,
    blend:
      layerObj.options && layerObj.option["blend"] != undefined
        ? layerObj.options["blend"]
        : "source-over",
    opacity:
      layerObj.options && layerObj.option["opacity"] != undefined
        ? layerObj.options["opacity"]
        : 1,
    bypassDNA:
      layerObj.options && layerObj.option["bypassDNA"] !== undefined
        ? layerObj.options["bypassDNA"]
        : false,
  }));
  return layers;
};
```

**Comment by luangjokaj** [comment]
Had the same issue but managed to fix it in macOS ✅ 

I just installed these packages: `brew install pkg-config cairo pango libpng jpeg giflib librsvg` and everything worked as expected. I think node canvas requires them in order to work properly. 

I'm running on Apple Silicon.

**Comment by haticecs** [comment]
@luangjokaj Hi, Which node version are you using?

**Comment by luangjokaj** [comment]
> @luangjokaj Hi, Which node version are you using?

v16.13.1 running on MacOS, Apple M1 Max.

**Comment by haticecs** [comment]
> 

Thanks, I tried with node 17 on macbook air but it gave error. I dowgraded node to the 10, it still gives error. I am gonna try that command.
