### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by patch2828** [HashLips/hashlips_art_engine#387]
Attempting to generate any amount of images, "node index.js" is sent into terming. A few images get made with a DNA and then this error pops up:

C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\src\main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);  
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')       
    at C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\src\main.js:180:10)
    at C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\src\main.js:360:17)
    at C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\index.js:6:3
    at Object.<anonymous> (C:\Users\Patch\OneDrive\Desktop\doggo\NFT GENERATOR\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)     
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by Happyprince65** [comment]
you can't use "-" in any image name

**Comment by tagachistudio** [comment]
make sure your image assets are properly named.

E.g. Blue Eyes#10.png instead of Blue-Eyes#10.png

**Comment by AlanGCruz** [comment]
Maybe the `DNA_DELIMITER` should be changed to a pattern not commonly used when naming a file,  for example: `>>>` or `***`

But if its planned to leave as is, it would be good to add to the `README.md` file that no hyphens should be used in the file name

**Comment by Dulcinea88** [comment]
I have the same issue. In my case, it works and it is creating images that contain "-" and even "&" and "+" because I can see them in the .json file. But at one point it clashes and I get the same error. 
Any other idea?

**Comment by AlanGCruz** [comment]
@Dulcinea88 it should depend in the actual file names that you created. I was naming my files something like this: `some_file_name-10#10.png`  and in my case the error appeared in the `cleanDna` function. 
Because of the `-` in my file's name, when splitting the dna by `DNA_DELIMITER`(main.js:220) the resulting array will split my file name in two like this: `["some_file_name", "10#10.png"]` and when the second elements get passed to the `cleanDna` function, it fails when trying to parse that string into a Number.

Hope that this gives you an idea of what could be happening in your case.

**Comment by pouryanft** [comment]
cannot read properties of undefined (reading 'path') i fix it everything but still i have problem 
[](url)

**Comment by aadi3124** [comment]
hi,
I am quite new in nodejs and express, getting this error and not finding any solution. Please help me.
thanks!

C:\D\PlayBox\back_end\middlewares\auth.js:41
    return res.sendStatus(401).send("Invalid Token");
               ^

TypeError: Cannot read properties of undefined (reading 'sendStatus')
    at Object.verifyToken (C:\D\PlayBox\back_end\middlewares\auth.js:41:16)
    at C:\D\PlayBox\back_end\app.js:70:21
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5)
    at C:\D\PlayBox\back_end\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\D\PlayBox\back_end\node_modules\express\lib\router\index.js:341:12)
    at next (C:\D\PlayBox\back_end\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\D\PlayBox\back_end\node_modules\body-parser\lib\types\json.js:119:7)
[nodemon] app crashed - waiting for file changes before starting...



#This is my code#

`function verifyToken(req, res, next) {
  let token = req.body.token || req.query.token || req.headers["authorization"];
  token = token.split(" ")[1];

  console.log(">>>>>token   " + token);
  if (!token) {
    return res.send(403, "A token is required for authentication");
  }
  try {
    const decoded = jwt.verify(token, "process.env.ACCESS_TOKEN_SECRET");
    req.user = decoded;
  } catch (err) {
    return res.sendStatus(401).send("Invalid Token");
  }
  return next();
}`


getting error in this line >>>  return res.sendStatus(401).send("Invalid Token");

**Comment by bolshoytoster** [comment]
@aadi3124 the function (`verifyToken`) is being passed `undefined` for `res`. If you don't mind, could you share the code where you call `verifyToken` (~line 70).

Also, in future, if you're making a multi-line code block use triple backticks:
\`\`\`js
code
\`\`\`

**Comment by aadi3124** [comment]
Hi @bolshoytoster 
First of all thanks a lot for the reply. 
here is my code from where I am calling verifyToken() function.

```
app.post("/verify", async (req, res) => {
  const resp = auth.verifyToken(req);
  console.log(">>>>> " + resp);
});

```

I am providing token in header as Authorization>> Bearer token
which  I am getting correctly here in the verifyToken() function
```
  let token = req.body.token || req.query.token || req.headers["authorization"];
  token = token.split(" ")[1];
  console.log(">>>>>token   " + token);
```

**Comment by bolshoytoster** [comment]
@aadi3124
> ```js
>   const resp = auth.verifyToken(req);
> ```

Looks like you only pass `req` to it. Try changing it to `auth.verifyToken(req, res, () => {});`.

Obviously change `() => {}` to whatever function `next` should be.

**Comment by aadi3124** [comment]
Hi @bolshoytoster,
Yes, got it. Thanks for helping me out. Its working now.
Just wanted to ask, right now I am getting resp = undefined
I want to send some message to client. How can I do that? May be this silly doubt but Its very new to me so. Hope you understand.
thanks!
```
const resp = auth.verifyToken(req, res, () => {});
console result>>> resp = undefined
```

**Comment by bolshoytoster** [comment]
@aadi3124 looking at your `verifyToken` function, it looks like if there's no error it returns the function you pass to it. (`() => {}` in this case).

As I mentioned, you should change the `() => {}` to the function you want to be called. I'm not completely sure what you want to do, but you could change it to `() => res.sendStatus(200).send("Message")` and it will send the message with the [status code 200](https://httpstatuses.com/200).

**Comment by aadi3124** [comment]
@bolshoytoster I am making system in which if user is already registered and try to login again in the system and if user's token is valid, user can directly login and can access resources.
I tried () => res.sendStatus(200).send("Message"), getting a message "OK" in postman with a code 200 but also getting below error in terminal. Can you please help me with this

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (C:\D\PlayBox\back_end\node_modules\express\lib\response.js:776:10)
    at ServerResponse.send (C:\D\PlayBox\back_end\node_modules\express\lib\response.js:170:12)
    at C:\D\PlayBox\back_end\app.js:71:25
    at Object.verifyToken (C:\D\PlayBox\back_end\middlewares\auth.js:47:10)
    at C:\D\PlayBox\back_end\app.js:70:21
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:112:3) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by bolshoytoster** [comment]
@aadi3124 sorry, I just copied the code you pasted before. I think `() => res.send("message")` will work for this one, then for the ones in the `verifyToken` function just change the `sendStatus`s to just `status`s.

**Comment by aadi3124** [comment]
@bolshoytoster Thanks! Its working and able to send the "message" to the client till my token is valid, once token get expired, getting same above error.

this is my verifyToken() function

```
function verifyToken(req, res, next) {
  let token = req.body.token || req.query.token || req.headers["authorization"];
  token = token.split(" ")[1];

  console.log(">>>>>token   " + token);
  if (!token) {
    return res.send(403, "A token is required for authentication");
  }
  try {
    const decoded = jwt.verify(token, "process.env.ACCESS_TOKEN_SECRET");
    req.user = decoded;
    console.log("valid");
  } catch (err) {
    return res.sendStatus(401).send("Invalid Token");
  }
  console.log("valid>>>");
  return next();
}
``` 
Error is (when token expired)
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)    at ServerResponse.header (C:\D\PlayBox\back_end\node_modules\express\lib\response.js:776:10)
    at ServerResponse.send (C:\D\PlayBox\back_end\node_modules\express\lib\response.js:170:12)
    at Object.verifyToken (C:\D\PlayBox\back_end\middlewares\auth.js:43:32)
    at C:\D\PlayBox\back_end\app.js:70:21
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\D\PlayBox\back_end\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\D\PlayBox\back_end\node_modules\express\lib\router\layer.js:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by bolshoytoster** [comment]
@aadi3124 you also have to change the second `sendStatus` to `send`.

**Comment by jamestailor91** [comment]
> you can't use "-" in any image name

Thank you very much!

**Comment by ugurberkecan** [comment]
@bolshoytoster  what if he want to use it as a middleware, still he can get res undefined error ?
