### ISSUE TITLE
NPM Generating issue can someone help me figure out what is wrong?

### ISSUE THREAD

**Issue by kenscore** [HashLips/hashlips_art_engine#389]
I can run the program no problem when generating at least 5 images but anything after this creates a problem. I attached the error I get below. All of my files are names correctly with no"-" in the name and they all have #. I am new to this so it could be a super little easy fix or something big I'm not sure.  

`TypeError: Cannot read properties of undefined (reading 'path')
    at /Users/kenspohr/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/kenspohr/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:180:10)
    at /Users/kenspohr/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/Users/kenspohr/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:360:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by emilioSordo** [comment]
I also have that problem, in line 184

**Comment by AlfieDarko** [comment]
I get this issue too, Hope we can resolve it

**Comment by tagachistudio** [comment]
make sure you use the correct version of node.

nvm use 16.3.0

**Comment by uahmedio** [comment]
Does not work...
