### ISSUE TITLE
Problem with generating 

### ISSUE THREAD

**Issue by Z3R0-420** [HashLips/hashlips_art_engine#398]
Witam mam problem z generowaniem obrazów i nie mogę go rozwiązać.
Below is what the terminal displays.

`(node:6516) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\nultv\Documents\Crypto.Death.Project/layers/Eye color/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\nultv\Documents\Crypto.Death.Project\src\main.js:73:6)
    at C:\Users\nultv\Documents\Crypto.Death.Project\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\nultv\Documents\Crypto.Death.Project\src\main.js:87:30)
    at startCreating (C:\Users\nultv\Documents\Crypto.Death.Project\src\main.js:349:20)
    at C:\Users\nultv\Documents\Crypto.Death.Project\index.js:6:3
    at Object.<anonymous> (C:\Users\nultv\Documents\Crypto.Death.Project\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\nultv\\Documents\\Crypto.Death.Project/layers/Eye color/'
}`

**Comment by TheRealBo21** [comment]
I have the same issue.

**Comment by haitam2010** [comment]
me too i get the same error

**Comment by haitam2010** [comment]
everyone can help me

**Comment by haitam2010** [comment]
oh i get how to fix error

**Comment by haitam2010** [comment]
in fact you must have installed the generative art node file but there were layers on it so you deleted the layer file then you just have to delete what it has in it and put your layers because the code is made for the layer file so when you do it delete it remains in the code but when you put yours it is not recognized so take a new generative art node file and go to layers and delete what is in it and put your layers but do not delete the layer file just what is in it so if its not working yet check if the name of the file in which your layers are located are written correctly in the code here is how to install generative art node https://github.com/HashLips/generative-art-node

**Comment by orian3737** [comment]
yes you want to keep your layer folder but if you delete it you can create another in your file manager it is much easier to manage the folders in file manger. As opposed to moving then on vs code. where it is easy to move files on vs code. Instead of cloning repositories I download the zip and save all extracted files in a separate folder. that way I can just delete the project re-extract the zip and start over.

**Comment by Novemburr** [comment]
This happened to me because my layer directory names were not the same as my config. I had used bash to replace all hyphen with underscores but forgot to update my config.
