### ISSUE TITLE
Problem with generating NFTs

### ISSUE THREAD

**Issue by hamzailyas434** [HashLips/hashlips_art_engine#399]
![image](https://user-images.githubusercontent.com/63106388/147086007-79ddc7f5-17e2-4078-8158-def353511c87.png)
![image](https://user-images.githubusercontent.com/63106388/147086063-f97b968a-470c-40f4-993c-9f73aba0dfcd.png)
Please help me. Thanks

**Comment by hamzailyas434** [comment]
Created edition: 1, with DNA: c8f0ea9f5a88c45a33b46be003dc03e7c8671c64
Created edition: 2, with DNA: b709505cbdcfff021b476df544b2d10560367f60
Created edition: 3, with DNA: ce72b2fcb91ebc51b5883d0c5ab001af81186d70
Created edition: 4, with DNA: d83e7f5a35f237ea12f88ca6e3a6a766ca99502d
Created edition: 5, with DNA: 2074debe076507265440d5024f73e47da80e56b6
(node:4500) UnhandledPromiseRejectionWarning: Error: out of memory
    at setSource (C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\index.js:23:10)
    at C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:180:10)
    at C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:361:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\Hamza Ilyas\Downloads\Compressed\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1>

**Comment by tagachistudio** [comment]
This is due to lack of memory allocation for Node.

`node --max-old-space-size=8192 index.js #increase to 8gb`

**Comment by ncp103** [comment]
Hi, I've experienced exactly the same issue, although in my case, I can't get past the 1st edition. I've increased node memory allocation to 16gb which is the max of my machine with no improvement... does it really require this much memory? 

I'm experimenting with 8 different categories, each with no more than 3 or 4 items each with a max file size of @3Mb. Perhaps I need to compress the images drastically?

PS thanks for the awesome work

**Comment by defdiff1** [comment]
I found what caused my node.js out of memory error is I had decided to change the size of my final pictures to 1024x1024 in the index.js file, but hadn't changed the original layers, which were still much larger dimensions  After going back and downsizing the layers files to match the new output size, it worked perfectly.

**Comment by ymc182** [comment]
I also found that if you use terminal inside code editor eg. vs code, this problem occur, but no problem in window terminal
