### ISSUE TITLE
Files Not Found After Swap

### ISSUE THREAD

**Issue by TheRealBo21** [HashLips/hashlips_art_engine#405]
PS C:\Users\Brand\Desktop\code\hashlips_art_engine-1.1.2_patch_v1> node index.js
(node:21472) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
    at C:\Users\Brand\Desktop\code\hashlips_art_engine-1.1.2_patch_v1\index.js:6:3
    at Object.<anonymous> (C:\Users\Brand\Desktop\code\hashlips_art_engine-1.1.2_patch_v1\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Brand\\Desktop\\code\\hashlips_art_engine-1.1.2_patch_v1/layers/Eye color/'
}

Node.js v17.3.0
PS C:\Users\Brand\Desktop\code\hashlips_art_engine-1.1.2_patch_v1>

**Comment by TheRealBo21** [comment]
or whatever that means, I've spent most of my day trying over and over and I can generate HashLips NFT's but not mine with my personal files

**Comment by orian3737** [comment]
re install requsites then double check your spelling in your layers and config.js "addLayer" script you cant have dashes or underscores unless they are at the end followed by "r" or 
"sr".
