### ISSUE TITLE
error during running node utils/nftport/updateFiles.js

### ISSUE THREAD

**Issue by sonuaa** [HashLips/hashlips_art_engine#411]
Node.js v17.2.0
PS C:\hashlips_art_engine-1.1.2_patch_v1> node utils/nftport/uploadFiles.js
C:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js:2
const fetch = require("node-fetch");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\hashlips_art_engine-1.1.2_patch_v1\node_modules\node-fetch\src\index.js from C:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js not supported.
Instead change the require of index.js in C:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js:2:15) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by victorcjb** [comment]
hey how did you fix this

**Comment by MaxSmeets** [comment]
I had this same issue today, looking into the node packeage documentation I found you should uninstall node-fetch and install node-fetch@2
Importing the module remains the same:
`const fetch = require("node-fetch");`

**Comment by KaiWenF** [comment]
Are you able to run the uploadFiles.js now?  I am having a running the code.

This is the issue I am having:
 hashlips_art_engine@1.1.1 uploadfiles
> node utils/nftport/uploadFiles.js

C:\Users\kaiwen\source\repos\HashLips Art Engine\utils\nftport\uploadFiles.js:21
    if(!metaData.file_url.includes('https://')) {
                          ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at main (C:\Users\kaiwen\source\repos\HashLips Art Engine\utils\nftport\uploadFiles.js:21:27)
    at Object.<anonymous> (C:\Users\kaiwen\source\repos\HashLips Art Engine\utils\nftport\uploadFiles.js:42:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Would welcome any help.

**Comment by Markkevin052** [comment]
Pls find solution pals

**Comment by locateandrew** [comment]
> I had this same issue today, looking into the node packeage documentation I found you should uninstall node-fetch and install node-fetch@2 Importing the module remains the same: `const fetch = require("node-fetch");`

How did you manage to do this - I am at a complete loss :-(

**Comment by KaiWenF** [comment]
Hello,

I just gave up on the code I got from codeSTACKr and went with another
similar solution.
https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection

This is working like a charm and is built on the same code as Hashlips and
codeSTACKr.

Regards,
Kai

**Comment by Markkevin052** [comment]
hello
that problems solved but new one arised
while minting
it shows that
minting limit is exceeded on polygon     pls help

**Comment by Markkevin052** [comment]
pls help

**Comment by Markkevin052** [comment]
![mint lim excee](https://user-images.githubusercontent.com/98245385/150823429-5edccefe-fee2-4c88-85aa-f3930955db78.png)

**Comment by KaiWenF** [comment]
Hi Markkevin052,

I was not able to get the code you are using to work.  I could never get
past the problem with the uploadFiles.js issues so I have not tried to mint
anything.  I am just going to go with another solution.  With some many
things to learn about NFTs and selling them I really don't want to worry
about the javascript code not working as it is shown in the YouTube
videos.  I know the guys who did the videos showing the code working are
super busy and can't help as much as I would like them to when we have
problem so I am going with a different solution just so that I don't have
to bang my head trying to figure out Javascript problems.

Please let me know how the uploadFiles.js file was fixed for you.

Best of Luck,
Kai

**Comment by MaxSmeets** [comment]
> > I had this same issue today, looking into the node packeage documentation I found you should uninstall node-fetch and install node-fetch@2 Importing the module remains the same: `const fetch = require("node-fetch");`
> 
> How did you manage to do this - I am at a complete loss :-(
> 

Check out https://www.npmjs.com/package/node-fetch under the "loading and configuring the module section". You'll net to use the npm command described in the commonJS section. Next you can use the import as stated in the CodeStackr video

**Comment by KaiWenF** [comment]
Hey Max,

I had the same problem and tried the same solution but it didn't work.  Let
me know if you find a solution.  I went with another project that is
similar to the hashlips art engine that works fine for me.

Regards,
Kai

**Comment by MaxSmeets** [comment]
@KaiWenF did you npm uninstall node-fetch before running the new install command?

**Comment by KaiWenF** [comment]
Hi Max,

Yes I tried all of the suggested things to fix the problem but could not
figure it out.  My problem was with the uploadFiles.js file.  I could
generate the NFTs with no problem but could not run the uploadFiles util.
I went with another version of the code that I got from The Peanut Gallery
And Co!  THis code was also built on the Hashlips code base, but everything
works like a champ.  I have spoken to the developer a few dozen times and
he is AWESOME and very very nice.  I am a developer too but I am a .net
VB.net and c# coder.  Javascript is similar to C so I could follow the
logic of the source code with no problems.  I think the problems I was
having had to do with node.js  version or some other support file that was
the wrong version.  With the code I am using now I have been able to go
through the entire process of getting my test NFT images on to Opensea
testnet with no one problem.

Kai

**Comment by adisyngrace** [comment]
> ![mint lim excee](https://user-images.githubusercontent.com/98245385/150823429-5edccefe-fee2-4c88-85aa-f3930955db78.png)

how did you get this issue to resolve?

**Comment by Glitchbes** [comment]
I have wasted so much time with this certain part!!!! I am on a depression now thanks to it! t months of work down the drain! because I can get past this!

uninstall node-fetch and install node-fetch@2

does nothing!

- C:\hashlips_art_engine-1.1.1_update\utils\nftport\uploadFiles.js
?[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)?[39m
?[90m    at Module.require (node:internal/modules/cjs/loader:999:19)?[39m
?[90m    at require (node:internal/modules/cjs/helpers:102:18)?[39m
    at Object.<anonymous> (C:\hashlips_art_engine-1.1.1_update\utils\nftport\uploadFiles.js:1:18)
?[90m    at Module._compile (node:internal/modules/cjs/loader:1097:14)?[39m
?[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)?[39m
?[90m    at Module.load (node:internal/modules/cjs/loader:975:32)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [
    ?[32m'C:\\hashlips_art_engine-1.1.1_update\\utils\\nftport\\uploadFiles.js'?[39m
  ]
}

**Comment by MadManwithaBlueBox** [comment]
FYI, since this nftport script file is created by someone else it would be best to inform the creator if you are having issues getting it to work.

It is not a part of the HashLips Art Engine so nothing with the art engine needs to be fixed if you are having issues with nftport.

I would suggest sending comments and bug fixes to the creators webiste/github.
