### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by mahmoudarb** [HashLips/hashlips_art_engine#424]
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by medcv** [comment]
Initially I had this error in older version of node, so I updated my node, removed `node_module` folder, ran `npm install` and ` npm run build` then the error gone!
node -v
v17.3.0

**Comment by bigcat411** [comment]
im getting the same...

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/scottkirby/Desktop/hashlips_art_engine/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

when i try and update node as you say above - i get a whole range of other errors saying "made with older version of node"

**Comment by medcv** [comment]
Yes that's because you ran `npm install` with older version of node. just delete `node_module` folder and rerun `npm install` and everything should works

**Comment by evanjealous** [comment]
hello medcv
i received this syntax error after successful "npm install" when i ran "node index.js" - question is do i delete the node module folder anyway? see error below. thank  you So much

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/redcap/Documents/hashlipsnftguide/hashlips_art_engine-1.1.2_patch_v1/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by evanjealous** [comment]
also medcv i have already installed updated node-v10.18.0 before getting this syntaxerror

**Comment by medcv** [comment]
so latest node version is v17.3.0 (https://nodejs.org/en/) and that's what I used and worked for me. so update your node to this version. remove `node_module` and run the steps again for `npm install` and `npm run build`

**Comment by dvogureckiy99** [comment]
> npm install

how I need use `npm install` and `npm run build` ?

**Comment by bolshoytoster** [comment]
@dvogureckiy99 you run them in a terminal, although they won't fix this error. You need to either upgrade your node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by Joshua-Ogbonna** [comment]
I updated my node version and it solved the issue for me

**Comment by Mat-Longinow** [comment]
> Initially I had this error in older version of node, so I updated my node, removed `node_module` folder, ran `npm install` and ` npm run build` then the error gone! node -v v17.3.0

Life saver! Hard stuck on an error similar when trying to `npm start` a fresh `create-react-app` application. My node version ended up being way behind (had to go from v6 to v14) and that was my issue.

Thank you! 🍻

**Comment by karan753** [comment]
Follow below steps

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
nvm install node
node -v

after that restart the command prompt

**Comment by pavankumarNM** [comment]
if anyone linux try with 
1) npm cache clean -force
2) rm -rf node_modules
3) npm install node
4) npm run start

**Comment by LucaBarbaLata** [comment]
> if anyone linux try with
> 
> 1. npm cache clean -force
> 2. rm -rf node_modules
> 3. npm install node
> 4. npm run start

this worked. thank you very much for your help. but can you tell me what those commands are doing? if u wish

**Comment by pavankumarNM** [comment]
first cleaning the cache 
second remove the node modules 
third installing the node with the help of node package manager (npm)
fourth - u obviously know 
:) happy coding .

**Comment by LucaBarbaLata** [comment]
> first cleaning the cache second remove the node modules third installing the node with the help of node package manager (npm) fourth - u obviously know :) happy coding .

thank you. i now understand. happy coding to you too :)

**Comment by Wesley00s** [comment]
> Follow below steps
> 
> curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash nvm install node node -v
> 
> after that restart the command prompt

u save my life bro

**Comment by PieterjanDeClippel** [comment]
For me the issue was caused by building on Node 18 and running on node 12

**Comment by pavankumarNM** [comment]
> For me the issue was caused by building on Node 18 and running on node 12
I think it won't support some files.... 
U work in belgium right, give me referral for your company I can fix that. 🙂

**Comment by sachinmahesh2000** [comment]
> if anyone linux try with
> 
> 1. npm cache clean -force
> 2. rm -rf node_modules
> 3. npm install node
> 4. npm run start

I was on ubuntu and vscode and this worked for me. thankyou alot!

**Comment by Marcjabbourr** [comment]
Hello, I've been stuck on the same error for a while and can't find a solution. I tried the stuff mentionned in the previous comments but still not working. Anyone got a different solution? I am using ubuntu

**Comment by coneycalifornia** [comment]
SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1350:18)                
    at Module._compile (node:internal/modules/cjs/loader:1379:20)         
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)  
    at Module.load (node:internal/modules/cjs/loader:1249:32)             
    at Module._load (node:internal/modules/cjs/loader:1065:12)            
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:12)                     
    at node:internal/main/run_main_module:30:49

**Comment by IdrisVeli1987** [comment]
Hello. please help me. i have this error in TS. and i dont now how can i delete this error
SyntaxError: Unexpected token ':'
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.14.0

**Comment by bolshoytoster** [comment]
@IdrisVeli1987 can you give more context? What code is causing this error?

**Comment by rhostec** [comment]
> si quelqu'un Linux essaie avec
> 
> 1. npm cache nettoyer -force
> 2. rm -rf noeud_modules
> 3. nœud d'installation npm
> 4. npm exécuter démarrer

Merci beaucoup ça marche

**Comment by Grom8306** [comment]
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

bot discord

**Comment by mrtechnic** [comment]
SyntaxError: Unexpected token ')'
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at requireOrImport (C:\Users\Apple\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:20:11)
    at execute (C:\Users\Apple\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^5.0.0\index.js:35:3)
    at onExecute (C:\Users\Apple\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js:230:24)

i got this errors on my terminal after trying to run "gulp" please i need help on what next to do.

**Comment by rhostec** [comment]
https://www.cotizup.com/world

**Comment by yashksaini-coder** [comment]
yashksaini@LUCIFER007:/mnt/e/Only-Dust-OSS/html-to-markdown$ pnpm
/usr/local/lib/node_modules/pnpm/bin/pnpm.cjs:18
  if(!require('module')?.enableCompileCache?.())
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47


---

I got this error when I installed pnpm in windows 11 wsl.
