### ISSUE TITLE
Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by mahmoudarb** [HashLips/hashlips_art_engine#441]
TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\lenovo\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\lenovo\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:180:10)
    at C:\Users\lenovo\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\lenovo\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:360:17)
    at C:\Users\lenovo\Desktop\hashlips_art_engine-1.1.2_patch_v1\index.js:6:3
    at Object.<anonymous> (C:\Users\lenovo\Desktop\hashlips_art_engine-1.1.2_patch_v1\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by maazullah96** [comment]
Same issue I am facing

**Comment by Jakeblackfield** [comment]
Same issue here. Please help!

**Comment by KamiSenpia** [comment]
Most likely the same issue as in [this thread](https://github.com/HashLips/hashlips_art_engine/issues/387) => layer file names can't contain hyphen (-).
