### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: error while reading from input stream

### ISSUE THREAD

**Issue by w4sb0y** [HashLips/hashlips_art_engine#443]
> hashlips_art_engine@1.1.1 generate C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main

(node:6792) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:180:10)
    at C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:6792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6792) UnhandledPromiseRejectionWarning: Error: error while reading from input stream
    at setSource (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:180:10)
    at C:\Users\w4sb0y\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
(node:6792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by loloz95** [comment]
help! having the same issue :(

**Comment by salake** [comment]
Having the same issue

**Comment by derrils** [comment]
Same. I've tried it without each layer individually and it still encounters an error - so that should eliminate an issue with any  single corrupt image going in.

/Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/lib/image.js:91
  SetSource.call(img, src);
            ^

Error: error while reading from input stream
    at setSource (/Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/lib/image.js:62:9)
    at /Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/index.js:23:10)
    at /Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/src/main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/src/main.js:180:10)
    at /Users/xxx/Documents/Hashlips/hashlips_art_engine-1.1.2_patch_v1/src/main.js:361:31
    at Array.forEach (<anonymous>)

**Comment by itsDev018** [comment]
I had the same problem. I fixed it by deleting the .DS_Store from the layers folder.
It, was a hidden file(in my case). I hope it helps you.

**Comment by derrils** [comment]
I fixed my issue by moving to a PC (was on mac), re-rendering all of my layers, and making sure I deleted any hidden files like you mentioned. There were indeed a dew hidden .DS_Store and icon files that I assume were generated by either Photoshop or Mac OS.

**Comment by littlehansel** [comment]
This error occurs when you have something other than the images in your layer folders. For instance if you have a folder or an mp4 file in one of your layer folders , the code will go through every layer folder and try to pick each item , one at a time .. so if it picks up at random a folder or an mp4 (or anything else other than the image) the code will try to parse it but fail throwing an "Error while reading from input stream". Just make sure that your layer folders only have images and nothing else  .. ✌️

**Comment by TharushaT** [comment]
This error occurs when you have corrupted image in layers just double check

**Comment by reubennn** [comment]
Can confirm this is to do with bad files in your layers folder. For some reason some of my images had gotten corrupted (not sure how) and this was causing this error. Replaced the corrupted files and the generator works perfectly again!

**Comment by wondermarq** [comment]
Yup. Deleting those hidden files did the trick. The file was named "icon" for me. Been banging my head on my keyboard last 3 days trying to figure this out. Thanks for your help!

**Comment by TinoJHB** [comment]
Go Into Your Layers And Tripple Check File By Opening Them One By One If you Have To. They Should Be corrupted files, especially in the Background Folder. In My Case, I use the size to see Files With No data Eg (Filename#2.png = 0kb)...It took me two days just to find These posts up lol Thanks, Guys.
