### ISSUE TITLE
errno: 2,   code: 'ENOENT', DIRECTORY ERROR

### ISSUE THREAD

**Issue by mj-afk** [HashLips/hashlips_art_engine#472]
I LAUNCH THE CODE ANDI I DO:
npm install
NEXT
npm run generate
 
> hashlips_art_engine@1.1.1 generate
> node index.js

C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\image.js:91  
  SetSource.call(img, src);
            ^
AND THE  TERMINAL SHOW THIS ERROR, I LAUNCH THE CODE WITH NOTHING MODIFICATION I LAUNCH ONLY FOR TEST IF IT RUN BUT NO...
SOMEONE CAN HELP ME PLEASE?

Error: ENOENT, No such file or directory 'C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1/layers/Background/Black#1.png'
    at setSource (C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\node_modules\canvas\index.js:23:10)
    at C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:180:10)
    at C:\Users\alfon\OneDrive - Università degli Studi del Molise\Desktop\hashlips_art_engine-1.1.2_patch_v1\src\main.js:361:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\alfon\\OneDrive - Università degli Studi del Molise\\Desktop\\hashlips_art_engine-1.1.2_patch_v1/layers/Background/Black#1.png',
  syscall: 'fopen'

**Comment by JasonJvV** [comment]
I ran version 14 from 2019 without having to delete the node. Follow the following commands to run an older version. (https://www.surrealcms.com/blog/how-to-upgrade-or-downgrade-nodejs-using-npm.html)
