### ISSUE TITLE
Missing script generate

### ISSUE THREAD

**Issue by Cxwebb11** [HashLips/hashlips_art_engine#480]
I have got to the point where my traits are ready and named.  when I run: npm run generate or npm generate I get the error:
npm ERR! Missing script: "generate"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

I was getting the same issue before I uploaded my files aswell.  Any way to fix this?

**Comment by rodrigovaladao** [comment]
I got the same error, I don't know how to fix it. Any uptade?

**Comment by miahf** [comment]
I have the same error, searched the enter internet but no solution found yet. Please someone help.

**Comment by nftnutz** [comment]
I tried to install on a new CPU with the newest version of VS Code doesn't work.  I downgraded VS Code to an older version and is working fine.

**Comment by benhalverson** [comment]
This error means in the scripts section of package.json generate doesn't exist

If it looks like this it wont work
```json
  "scripts": {
    "build": "node index.js",
    "rarity": "node utils/rarity.js",
    "preview": "node utils/preview.js",
    "pixelate": "node utils/pixelate.js",
    "update_info": "node utils/update_info.js",
    "preview_gif": "node utils/preview_gif.js",
    "generate_metadata": "node utils/generate_metadata.js"
  },
```

if it looks like this it will work
```json
  "scripts": {
    "build": "node index.js",
    "generate": "node index.js",
    "rarity": "node utils/rarity.js",
    "preview": "node utils/preview.js",
    "pixelate": "node utils/pixelate.js",
    "update_info": "node utils/update_info.js",
    "preview_gif": "node utils/preview_gif.js",
    "generate_metadata": "node utils/generate_metadata.js"
  },
```

**Comment by ricothronic** [comment]
I got the same error and based on the above comment, my package.json has the "generate" module just like this:

"scripts": {
    "build": "node index.js",
    "generate": "node index.js",
    "rarity": "node utils/rarity.js",
    "preview": "node utils/preview.js",
    "pixelate": "node utils/pixelate.js",
    "update_info": "node utils/update_info.js",
    "preview_gif": "node utils/preview_gif.js",
    "generate_metadata": "node utils/generate_metadata.js"
  },

Go on the package.json module and under line 13 (at least for me)  you'll see the "Debug" option with a "play" button ▶️
Run the dubugger and you'll probably discover a few errors.
Run: 'nmp audit' and after confirming, run: 'npm audit fix: 
After the fix is complete, the critical error won't show any longer.

Go back to your terminal and run: 'npm run generate' and you should be all set!

**Comment by mednologic** [comment]
i get the same :( i cant solve it

**Comment by bolshoytoster** [comment]
@mednologic can you paste your error here please? You're probably just in the wrong folder.

**Comment by P0p0lv1ll3cr0ze** [comment]
I tried to do what @ricothronic said, but I still does not work.

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze can you paste your error(s) here please.

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze can you paste your error(s) here please.

How?

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze you copy the errors then paste them here.

**Comment by P0p0lv1ll3cr0ze** [comment]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "generate"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicol\AppData\Local\npm-cache\_logs\2022-07-01T19_20_39_671Z-debug-0.log

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze you're likely in the wrong folder. run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze you're likely in the wrong folder. run `Get-ChildItem -Directory` to get the name, then run `cd ` + the name to change into it.

What name?

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze the name of the folder.

**Comment by P0p0lv1ll3cr0ze** [comment]
wich folder?😅

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze the one you get from running `Get-ChildItem -Directory`

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze the one you get from running `Get-ChildItem -Directory`

I wavent got any folder with Get-ChildItem -Directory

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze can you paste the output of `Get-ChildItem -Directory` here please

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze can you paste the output of `Get-ChildItem -Directory` here please

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        01.07.2022     21:15                create-10k-nft-collection-2.0.0
d-----        01.07.2022     18:47                node_modules

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze run `cd create-10k-nft-collection-2.0.0` then.

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze run `cd create-10k-nft-collection-2.0.0` then.

I di it, then I put "npm run generate" and I still have an Error
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> 10k-collection-video@2.0.0 generate
> node index.js

(node:3408) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0/layers/Background/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0\src\main.js:73:6)
    at C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0\src\main.js:87:30)
    at startCreating (C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0\src\main.js:352:20)
    at C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0\index.js:6:3
    at Object.<anonymous> (C:\Users\Nicol\Downloads\create-10k-nft-collection-2.0.0\create-10k-nft-collection-2.0.0\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Nicol\\Downloads\\create-10k-nft-collection-2.0.0\\create-10k-nft-collection-2.0.0/layers/Background/'
}

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze make sure you save `src/config.js`

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze make sure you save `src/config.js`

I do

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze can you paste your `layersOrder`s and the output of running `Get-ChildItem layers` here please.

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze can you paste your `layersOrder`s and the output of running `Get-ChildItem layers` here please.

const layerConfigurations = [
  {
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Background" },
      { name: "Body" },
      { name: "Durags" },
      { name: "Eyes" },
      { name: "Mouths" },
      { name: "Necklaces" },
    ],
  },
];

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        01.07.2022     20:07                layers

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze can you make sure you spell `layers/Background` correctly.

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze can you make sure you spell `layers/Background` correctly.

it is

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze can you make sure it's spelled with an uppercase `B`, could you try pasting the output of `Get-ChildItem layers/*` here please.

**Comment by P0p0lv1ll3cr0ze** [comment]
> @P0p0lv1ll3cr0ze can you make sure it's spelled with an uppercase `B`, could you try pasting the output of `Get-ChildItem layers/*` here please.

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        01.07.2022     20:07                layers

**Comment by bolshoytoster** [comment]
@P0p0lv1ll3cr0ze I think I know the issue; I think you have another `layers` folder inside the existing one, could you try running `Move-Item -Path layers/layers/* -Destination layers` to move them into the expected place.

**Comment by P0p0lv1ll3cr0ze** [comment]
> Move-Item -Path layers/layers/* -Destination layers

thak you very much!
It works!
