### ISSUE TITLE
Need Help Please

### ISSUE THREAD

**Issue by pbnft** [HashLips/hashlips_art_engine#484]
Trying to generate my first nft and keep getting the follow error.  Any help would be appreciated!

susanburris@Susans-Mac-mini hashlips_art_engine-1.1.2_patch_v1 % node index.js
(node:37717) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/layers/Eyeball/'
    at Object.readdirSync (fs.js:1047:3)
    at getElements (/Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js:73:6)
    at /Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js:87:30)
    at startCreating (/Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js:349:20)
    at /Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/index.js:6:3
    at Object.<anonymous> (/Users/susanburris/Desktop/hashlips_art_engine-1.1.2_patch_v1/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
susanburris@Susans-Mac-mini hashlips_art_engine-1.1.2_patch_v1 %

**Comment by pbnft** [comment]
Just as an FYI, I created layers via PSD, 64 x 64 pixels and then resized to 5x5 at 300 pixels and export layers to png., replaced the layers folder with my layers and then changed config.js to match the layers.  then ran node index.js

**Comment by ganidu94** [comment]
Probably an issue with how you have renamed your files. Did you add the rarity to your individual files?

**Comment by econcepcion** [comment]
Just FYI, I know that the file names can not have hyphens in them, use underscore instead.
