### ISSUE TITLE
Issue after adding my new layers and adding them in to the configure js

### ISSUE THREAD

**Issue by natalion13** [HashLips/hashlips_art_engine#487]
TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:184:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:183:10)
    at C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:364:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update\src\main.js:363:17)
    at C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update\index.js:6:3
    at Object.<anonymous> (C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
PS C:\Users\18179\Desktop\hashlips_art_engine-1.1.1_update> 
I have tried multiple times and keep getting stopped right before it will generate i have no issues generating the sample images. Send help pls

**Comment by nickbuono** [comment]
Same for me!
