### ISSUE TITLE
Code isnt running

### ISSUE THREAD

**Issue by horizongfx** [HashLips/hashlips_art_engine#496]
TypeError: Cannot read properties of undefined (reading 'path')
    at E:\hashlips_art_engine-main\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (E:\hashlips_art_engine-main\src\main.js:180:10)
    at E:\hashlips_art_engine-main\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (E:\hashlips_art_engine-main\src\main.js:360:17)
    at E:hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (E:\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

Whenever I run node inex.js this happens

**Comment by listennman** [comment]
I am having the same issue when I run npm run generate and also node index.js

**Comment by wess1111** [comment]
i am having the same issue

**Comment by desmax-designer** [comment]
i am alos having the samw issue

**Comment by benhalverson** [comment]
See https://github.com/HashLips/hashlips_art_engine/pull/559
