### ISSUE TITLE
Element Limit?

### ISSUE THREAD

**Issue by horizongfx** [HashLips/hashlips_art_engine#497]
Ok, So I have been working on this engine for a while and I think there is some sort of limit for elements as I have got many layers with varying elements (One can have 5 here one can have over 20). I tried to generate NFTs with all of them but there was an error:

TypeError: Cannot read properties of undefined (reading 'path')
    at E:\NFT Generatr 2\hashlips_art_engine-main\src\main.js:180:61
    at new Promise (<anonymous>)
    at loadLayerImg (E:\NFT Generatr 2\hashlips_art_engine-main\src\main.js:179:10)
    at E:\NFT Generatr 2\hashlips_art_engine-main\src\main.js:360:31
    at Array.forEach (<anonymous>)
    at startCreating (E:\NFT Generatr 2\hashlips_art_engine-main\src\main.js:359:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

BUT....

When I try to generate art with the same Layer Folders but with a lesser amount, it generates them with no errors.

need help

**Comment by ezrana94** [comment]
Make sure your image name does not hat dash / "-". It may disturb your generation
