### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Path')

### ISSUE THREAD

**Issue by listennman** [HashLips/hashlips_art_engine#498]
I am getting the following error message

PS C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\src\main.js:184
    const image = await loadImage(`${_layer.selectedElement.Path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'Path')
    at C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\src\main.js:184:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\src\main.js:183:10)
    at C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\src\main.js:364:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\src\main.js:363:17)
    at C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\liste\Downloads\Try this guy\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
![error](https://user-images.githubusercontent.com/34762609/148697004-9745cacf-c8d7-4831-b165-95260dbd3be5.PNG)

**Comment by GitCulture** [comment]
same here

**Comment by nichochar** [comment]
+1 same issue. Any resolution? Trying to debug now...

**Comment by nichochar** [comment]
I figured it out. It was because one of the filenames was wrong.

In particular for me, I was using a hyphen.

**Comment by listennman** [comment]
It turns out I had hyphens - in the file name of my images. Once, I removed them all, it worked. Thank Jesus.

**Comment by ZaryImortal** [comment]
remove "-" from names

**Comment by khldyboy** [comment]
any one have a solution for low resolution ?

**Comment by MrrGnu** [comment]
@listennman could you explain what the solution was pls? 
i got the same problem but i dont get what you did

**Comment by bebrutas** [comment]
I had the same issue and the problem was the hyphens. Thank you guys, your comments helped! @nichochar @listennman

**Comment by Lowkeydro** [comment]
Where do I find the file name to delete hyphens

**Comment by Lowkeydro** [comment]
> 

Where do I go to find the files so I can delete the hyphens?

**Comment by roy3892** [comment]
My God. I was stuck in this issue for over 2 weeks now and it was just a hyphen in the name of one of my images. Hallelujah.

**Comment by RajatShinde3** [comment]
i have same problem please help me..........

**Comment by bolshoytoster** [comment]
@RajatShinde3 can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by immrstock** [comment]
I just set the same name of the file at the png images and solve the problem. Good luck.

**Comment by Goldleader7** [comment]
The solution for me was that one of my files/folders was empty.
