### ISSUE TITLE
Please Help! My Code isn't running : ( 

### ISSUE THREAD

**Issue by Lovebunni** [HashLips/hashlips_art_engine#514]
maccity-mac@Sarahs-Air hashlips_art_engine-1.1.2_patch_v1 % npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/maccity-mac/Desktop/hashlips_art_engine-1.1.2_patch_v1/node_modules/sha1'
Require stack:
- /Users/maccity-mac/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js
- /Users/maccity-mac/Desktop/hashlips_art_engine-1.1.2_patch_v1/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/maccity-mac/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/maccity-mac/Desktop/hashlips_art_engine-1.1.2_patch_v1/src/main.js',
    '/Users/maccity-mac/Desktop/hashlips_art_engine-1.1.2_patch_v1/index.js'
  ]

**Comment by g010329** [comment]
Same error here:(
Btw I'm using Apple m1

❯ node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/grace/Desktop/hashlips_art_engine/node_modules/sha1'
Require stack:
- /Users/grace/Desktop/hashlips_art_engine/src/main.js
- /Users/grace/Desktop/hashlips_art_engine/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/grace/Desktop/hashlips_art_engine/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/grace/Desktop/hashlips_art_engine/src/main.js',
    '/Users/grace/Desktop/hashlips_art_engine/index.js'
  ]
}

**Comment by tuncbb** [comment]
Same here

**Comment by Alexisgarci** [comment]
i have the same error, anyone knows how to solve it?

**Comment by Alexisgarci** [comment]
Guys i found what was missing, in the terminal type ''npm i yarn'' it will install yarn and it will work

**Comment by Lovebunni** [comment]
Where should we type it?Should we just type it at the end?

**Comment by Cfhhunt** [comment]
As it says in the error, you're missing node_modules/sha1

Try 
`npm install sha1`

Hope this helps :)
