### ISSUE TITLE
Facing Issue while installing Hashlips on visual studio code

### ISSUE THREAD

**Issue by toseef-yousaf** [HashLips/hashlips_art_engine#518]
Hi, I'm facing this issue:
![image_2022-01-12_082338](https://user-images.githubusercontent.com/97287889/149169129-72e22c2b-80cf-487d-8f30-9ab160972feb.png)

Could you please help me solve this issue? I don't know to code

**Comment by psavva** [comment]
Make a directory directly on the c:

Like C:\Repos\HashLips

**Comment by billrod76** [comment]
same here running into the same problem

**Comment by psavva** [comment]
show screenshot of directory contents

**Comment by tribalstomp** [comment]
Im on a M1 Mac and I am having the same issue. I don't have a C: directory on Mac so I can't make the directory like psavva is suggesting

**Comment by tribalstomp** [comment]
here is the error code when running "npm i"
hashlips_art_engine-1.1.2_patch_v1 % npm i
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@17.3.1 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@17.3.1 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.1 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.3.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v17.3.1/node-v17.3.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.3.1/node-v17.3.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v17.3.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.3.1/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/rpm/Library/Caches/node-gyp/17.3.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/rpm/Library/Caches/node-gyp/17.3.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/rpm/Library/Caches/node-gyp/17.3.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
npm ERR! gyp ERR! cwd /Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas
npm ERR! gyp ERR! node -v v17.3.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.1.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/rpm/Downloads/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v17.3.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rpm/.npm/_logs/2022-01-13T10_19_36_239Z-debug-0.log
rpm@Ryans-MacBook-Pro hashlips_art_engine-1.1.2_patch_v1 %
