### ISSUE TITLE
code not working help please

### ISSUE THREAD

**Issue by nomoreghosts** [HashLips/hashlips_art_engine#521]
i followed all the steps from your youtube video side by side but this pops up. i hope you can help. Thank you.

Justins-MacBook-Pro-2:hashlips_art_engine-1.0.6_update justindeleon$ node index.js
/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/src/config.js
(node:8555) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/layers/Eyeball/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/src/main.js:66:6)
    at /Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/src/main.js:83:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/src/main.js:80:30)
    at startCreating (/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/src/main.js:240:20)
    at /Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/index.js:13:3
    at Object.<anonymous> (/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/justindeleon/Downloads/hashlips_art_engine-1.0.6_update/layers/Eyeball/'
}
Justins-MacBook-Pro-2:hashlips_art_engine-1.0.6_update justindeleon$

**Comment by b0bs1one** [comment]
I have the same issue. Let me know if you manage to fix it.
