### ISSUE TITLE
Cannot read property "path" of undefined

### ISSUE THREAD

**Issue by cosmin-negoita** [HashLips/hashlips_art_engine#535]
Hey there, first of all thanks for this awesome tool!

I've downloaded the package and ran it successfully, once. After adding more assets and running "npm run build" again, it didn't work anymore and gave me this error:

`/Users/cosminnegoita/Downloads/hashlips2/src/main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read property 'path' of undefined
    at /Users/cosminnegoita/Downloads/hashlips2/src/main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/cosminnegoita/Downloads/hashlips2/src/main.js:180:10)
    at /Users/cosminnegoita/Downloads/hashlips2/src/main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (/Users/cosminnegoita/Downloads/hashlips2/src/main.js:360:17)
    at /Users/cosminnegoita/Downloads/hashlips2/index.js:6:3
    at Object.<anonymous> (/Users/cosminnegoita/Downloads/hashlips2/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)`
    
    Any idea why or how to fix it? Thank you!

**Comment by cosmin-negoita** [comment]
UPDATE: Found out the problem. My asset file names were including a "-" character.
