### ISSUE TITLE
Npm run generate issue 

### ISSUE THREAD

**Issue by Tousif502** [HashLips/hashlips_art_engine#546]
i hav come with this issue 
i cant install hashlips 
{{{ 
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS F:\hashlips_art_engine-1.1.1_update> npm i
npm WARN hashlips_art_engine@1.1.1 No repository field.

audited 65 packages in 3.17s

6 packages are looking for funding
  run `npm fund` for details

found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
PS F:\hashlips_art_engine-1.1.1_update> npm run generate

> hashlips_art_engine@1.1.1 generate F:\hashlips_art_engine-1.1.1_update
> node index.js

F:\hashlips_art_engine-1.1.1_update\src\main.js:91
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
←[90m    at Object.compileFunction (vm.js:344:18)←[39m
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1048:15)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1082:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (F:\hashlips_art_engine-1.1.1_update\index.js:2:39)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tausif\AppData\Roaming\npm-cache\_logs\2022-01-17T18_23_15_630Z-debug.log
PS F:\hashlips_art_engine-1.1.1_update> }

.
.
.
.
 pls solve the issue i know less about coding

**Comment by LordSpecterOne** [comment]
Your config.js file looks to have typos in your syntax.  Double check it.  But the line that says "SyntaxError: Unexpected token '.'"

That says that somewhere you didn't close out a string or you have a stray . somewhere.   Check around any custom displayNameyou might have set since that's where the syntax error was thrown.

**Comment by zenkog** [comment]
Hi, I got the same problem. I didn't change anything in the code. I downloaded it straight from the Github repository. 
1. I ran `npm i` in the terminal.
2. I ran `npm run generate` 

I also got the same error.

**Comment by zenkog** [comment]
I solved my problem by updating my nodejs. Maybe it was because the newer version of node has newer syntax.

**Comment by rutvij2811** [comment]
After updating the node version. Delete the "node module" folder.
Run `npm install` again. This resolved the issue on my end.
