### ISSUE TITLE
bypassDNA Not working

### ISSUE THREAD

**Issue by legsofjesus** [HashLips/hashlips_art_engine#554]
Hi team,

The bypassDNA is not working correctly. It will not exclude traits in the meta data JSON files. 
     
       { name: "Body 2", 
                options: {
                    bypassDNA: true,
                }
            },

**Comment by sal-420** [comment]
To clarify are you trying to include the art work and exclude the meta data from the json which is what I'm trying to do
If so have the solution and can you share it

**Comment by thepeanutgalleryandco** [comment]
@sal-420 i jave added support for bypassing metadata in my repo - https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection

The section is in the src/main.js file.

**Comment by sal-420** [comment]
@thepeanutgalleryandco  thanks for the the update. I'll head over tot your repo. compare the main.js and apply changes. I may switch over to your solution depending on use case

**Comment by murkai** [comment]
> @sal-420 i have added support for bypassing metadata in my repo - https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection
> 
> The section is in the src/main.js file.

How would I get this to work on a pre-existing build? Do I have to completely start over using your repo? 

Also I'm not sure what you mean when you say the section is in the src/main.js file and I didn't see any reference to bypassDNA in the link. I did see reference to omitting "blanks" - by renaming layers with 'blank' that you don't want to show up in metadata <- is this how it needs to be done (in response to OPs original inquiry) ?

Thanks in advance

**Comment by sal-420** [comment]
@thepeanutgalleryandco  After heading to your repo and re-reading the the option bypassDNA: true I realized what I really need is your  removeTrait.js script. I tested this on your solution with your sample data and it worked as expected. 
I copied it to the HashLips solution, did a NPM Install and ran your script. Also, I get an error with: npm install commander
Would you be able to let me know why I'm unable to run your script on the Hashlips solution

Users\sal\hashlips_art_engine-1.1.2_patch_v1> node utils/removeTrait.js "Background"
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- C:\Users\sal\hashlips_art_engine-1.1.2_patch_v1\utils\removeTrait.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\sal\hashlips_art_engine-1.1.2_patch_v1\utils\removeTrait.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\smagl\\Documents\\Crypto\\Ruggie\\hashlips_art_engine-1.1.2_patch_v1\\utils\\removeTrait.js'   
  ]
}

PS C:\Users\sal\hashlips_art_engine-1.1.2_patch_v1> node utils/removeTrait.js "Background" 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- C:\Users\sal\hashlips_art_engine-1.1.2_patch_v1\utils\removeTrait.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\sal\hashlips_art_engine-1.1.2_patch_v1\utils\removeTrait.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\sal\\hashlips_art_engine-1.1.2_patch_v1\\utils\\removeTrait.js'   
  ]
}
PS C:\Users\sal\hashlips_art_engine-1.1.2_patch_v1>

**Comment by thepeanutgalleryandco** [comment]
@sal-420 unfortunately my repo does not have any "removeTrait.js" script and that functionality is not described in my repo.

**Comment by MelanieCroce** [comment]
@thepeanutgalleryandco 
I don't know if you still need a solution to make byPassDNA: true work, I found a simple solution :

In main.js
```
const constructLayerToDna = (_dna = "", _layers = []) => {
  let mappedDnaToLayers = _layers.map((layer, index) => {
    let selectedElement = layer.elements.find(
      (e) => e.id == cleanDna(_dna.split(DNA_DELIMITER)[index])
    );
    return {
      name: layer.name,
      blend: layer.blend,
      opacity: layer.opacity,
      bypassDNA: layer.bypassDNA, // Add this ligne
      selectedElement: selectedElement,
    };
  });
  return mappedDnaToLayers;
};
```

```
const addAttributes = (_element) => {
  let selectedElement = _element.layer.selectedElement;
  if (!_element.layer.bypassDNA) { //Push only if byPassDNA is false
    attributesList.push({
      trait_type: _element.layer.name,
      value: selectedElement.name,
    });
  }
};
```
