### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by ddc29** [HashLips/hashlips_art_engine#569]
> hashlips_art_engine@1.1.1 generate D:\hashlips_art_engine-1.1.2_patch_v1
> node index.js

(node:4136) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at D:\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181:61       
    at new Promise (<anonymous>)
    at loadLayerImg (D:\hashlips_art_engine-1.1.2_patch_v1\src\main.js:180:10)
    at D:\hashlips_art_engine-1.1.2_patch_v1\src\main.js:361:31       
    at Array.forEach (<anonymous>)
    at startCreating (D:\hashlips_art_engine-1.1.2_patch_v1\src\main.js:360:17)
    at D:\hashlips_art_engine-1.1.2_patch_v1\index.js:6:3
    at Object.<anonymous> (D:\hashlips_art_engine-1.1.2_patch_v1\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)       
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.       
PS D:\hashlips_art_engine-1.1.2_patch_v1> 

if i change layers always error, if i use the original file its works.
anyone can help ?

**Comment by joaobrasil65** [comment]
Same error here

**Comment by joaobrasil65** [comment]
When I change layers and art, I get the problems. As far as I know, the layers and config.js are correct.

(node:39984) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:180:10)
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:360:17)
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:39984) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:180:10)
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:360:17)
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
(node:39984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:39984) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:180:10)
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\src\main.js:360:17)
    at C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\paulb\Documents\GitHub\Hashlips_art2\hashlips_art_engine\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
(node:39984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by thepeanutgalleryandco** [comment]
Can you share your layer folder names and layer item names please along with your configuration for your layers in the config.js file. It is difficult to see what is going wrong based on the error shared.

**Comment by joaobrasil65** [comment]
It is likely your assets have special characters in their name. This blows up the program

**Comment by dalogikpapa** [comment]
Agree with @joaobrasil65 , i had the same issue today. I had special characters in my layer element names. Change that up and try, it should work.

**Comment by DarkRafas** [comment]
> It is likely your assets have special characters in their name. This blows up the program

Thank you, this help me out with the issue :)
