### ISSUE TITLE
What i can do with this Error to fix?

### ISSUE THREAD

**Issue by redscarf0** [HashLips/hashlips_art_engine#578]
at Array.map (<anonymous>)
    at layersSetup (C:\Users\workgroup\Desktop\video-source-code-create-nft-collection-main\src\main.js:87:30)
    at startCreating (C:\Users\workgroup\Desktop\video-source-code-create-nft-collection-main\src\main.js:351:20)
    at C:\Users\workgroup\Desktop\video-source-code-create-nft-collection-main\index.js:6:3
    at Object.<anonymous> (C:\Users\workgroup\Desktop\video-source-code-create-nft-collection-main\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Waiting for the debugger to disconnect...

**Comment by joaobrasil65** [comment]
It is likely your assets have special characters in their name. This blows up the program

**Comment by redscarf0** [comment]
Thank you for your answer, I do not have any special characters. This program is super great but just not working in Visual Code on Win 10 I tray everything to find wats wrong. When I start generating the images after installing dependencies default layer folders it is working, after I replace the layers folder name the project desc. and set up my project I have this error or module is not found in 4 different version releases. I can upload the screenshot of my setup to see what is a problem or which version is for win 10  if that is the problem.

**Comment by joaobrasil65** [comment]
special characters or spaces or _ or - all crashed the program for me

**Comment by thepeanutgalleryandco** [comment]
Please share screenshots of all your configs or alternatively, can you please zip / compress your folder and share here so that we can test it.

**Comment by redscarf0** [comment]
Yes . Sory or late response I will share. About 20 min I need. Thank you

**Comment by redscarf0** [comment]
Zip files .SCR.SHOTS
[Eroor Isusues sc.shot githubHlip .zip](https://github.com/HashLips/hashlips_art_engine/files/7923620/Eroor.Isusues.sc.shot.githubHlip.zip)

**Comment by redscarf0** [comment]
This Screenshot is from the latest version update 1.1.2

**Comment by thepeanutgalleryandco** [comment]
Thank you. I suspect the issue is due to your computer reading your paths with "\" while the paths for the code are specified as "/". This creates a combination of "\" and "/" when searching for your directory, which causes issues.

When looking at my terminal, it has "bash" as my terminal type while yours has "powershell". Can you check to see if you can get a "bash" terminal or something similar when clicking on that dropdown or attempt to install an extension for bash so that you have a different terminal?

<img width="1409" alt="Screenshot 2022-01-24 at 13 08 25" src="https://user-images.githubusercontent.com/52892685/150772087-efb8e9cf-0c9d-4cf6-ba65-817525402e1a.png">
.

**Comment by thepeanutgalleryandco** [comment]
@redscarf0 you might need to check your terminal settings inside your preferences / settings to see if you can use VS Code's terminal itself instead of the external powershell terminal.

**Comment by redscarf0** [comment]
Ok, thank you I will try. Yes, I suspected to but I do not have too many experiences with Coding I am a Designer.
I will reply back. Sorry for the late reply I was busy.

**Comment by redscarf0** [comment]
Thank you very much. Success.YES!!! The first run is the same but i change the base URI it must be the same as the location folder main folder, with no spaces in the folder and config.js. Git bash its need for Windows to install in default no bash terminal.
[Suces gitbash 1.zip](https://github.com/HashLips/hashlips_art_engine/files/7927927/Suces.gitbash.1.zip)

**Comment by redscarf0** [comment]
Now I have hard part smart contract bulk upload ower ips am not sure I can do that. I read instructions and I watch processes .
For me very confusing. Ther an easier way to ips smart contract bulk upload with metadata to Open sea?
