### ISSUE TITLE
Unexpected token error 

### ISSUE THREAD

**Issue by th3b3st1** [HashLips/hashlips_art_engine#584]
I apologize if this issue may have been fixed already but i cant seem to find a work around. im using visual studio on ubuntu 20.04 and I get this error when i run npm run build.
 i deleted everything and once again cloned the repo and tried npm run build without changing a single thing in the directory and i am still getting the issue.
does anyone have a solution?
below is the output from the terminal after running npm run build.

Thank you in advance!!!!!

michael@michael-HP-EliteDesk-705-G2-SFF:~/hashlips/hashlips_art_engine$ npm run build

> hashlips_art_engine@1.1.1 build /home/michael/hashlips/hashlips_art_engine
> node index.js

/home/michael/hashlips/hashlips_art_engine/src/main.js:91
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/michael/hashlips/hashlips_art_engine/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 build: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashlips_art_engine@1.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/michael/.npm/_logs/2022-01-22T17_40_14_683Z-debug.log
michael@michael-HP-EliteDesk-705-G2-SFF:~/hashlips/hashlips_art_engine$

**Comment by Aman7080** [comment]
I am also getting this issue, I am using visual studio on linuxmint

**Comment by armintrepic** [comment]
I'm getting the same issue as well. First I verified that I am running the correct version (I wasn't), so I downloaded and installed node.js v10.18.0 and I am still getting the same error.

**Comment by armintrepic** [comment]
> I'm getting the same issue as well. First I verified that I am running the correct version (I wasn't), so I downloaded and installed node.js v10.18.0 and I am still getting the same error.

I've found the solution in the discord channel

open visual studio
npm install, then
npm update

run 'npm run generate', again.

**Comment by th3b3st1** [comment]
that did not solve it for me. i uninstalled npm and all the necessary packages and then reinstalled it. i still got the same unexpected token error

**Comment by th3b3st1** [comment]
I was finally able to get it working however not Ubuntu 20.04. I moved over to my windows pc and installed everything there and problem solved. I'm still hunting for a fix on Ubuntu though because that's my preferred pc.

**Comment by macorifice** [comment]
Same issue here (`npm -v 8.3.2` - `node -v 16.9.1`)
Solved following these steps: 

> rm -rf node_modules && rm package-lock.json

> npm update

> npm install

> node index.js or npm run generate

**Comment by WaterlessPiano2** [comment]
> Same issue here (`npm -v 8.3.2` - `node -v 16.9.1`) Solved following these steps:
> 
> > rm -rf node_modules && rm package-lock.json
> 
> > npm update
> 
> > npm install
> 
> > node index.js or npm run generate

This has worked after setting my node modules to be the same as yours on my Ubuntu machine! Thanks!

**Comment by saviour07** [comment]
I had this exact same issue, the winning combination for me on Windows 10 (20H2 19042.1415) was `npm 8.4.1` and `node 16.9.1`
