### ISSUE TITLE
Error when running npm

### ISSUE THREAD

**Issue by DvDup** [HashLips/hashlips_art_engine#599]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\15182\Downloads\hashlips_art_engine-1.1.2_patch_v1/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\15182\Downloads\hashlips_art_engine-1.1.2_patch_v1\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\15182\AppData\Local\npm-cache\_logs\2022-01-26T01_00_25_797Z-debug-0.log

Backstory: Node is setup properly and I've tried multiple versions to bypass the problem, it cannot locate a file which is clearly there.

**Comment by Deep-nub49** [comment]
Yes i saw hash lips's youtube video and got inspired to create nft's but i also triggered same issues and try to fix it by so many means but the result is same for me, pls provide any solutions if possible

**Comment by BPWCNRZ** [comment]
also having same issue

**Comment by ebonylady** [comment]
Also having the same issue.

**Comment by SamTheNoob69** [comment]
```
(node:13304) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
D:\Desktop\artengine\src\main.js:77
        throw new Error(`layer name can not contain dashes, please fix: ${i}`);
              ^

Error: layer name can not contain dashes, please fix: 1-1.png
    at D:\Desktop\artengine\src\main.js:77:15
    at Array.map (<anonymous>)
    at getElements (D:\Desktop\artengine\src\main.js:75:6)
    at D:\Desktop\artengine\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (D:\Desktop\artengine\src\main.js:90:30)
    at startCreating (D:\Desktop\artengine\src\main.js:358:20)
    at D:\Desktop\artengine\index.js:6:3
    at Object.<anonymous> (D:\Desktop\artengine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
PS D:\Desktop\artengine> 
```
