### ISSUE TITLE
Issue I need help

### ISSUE THREAD

**Issue by h2022m** [HashLips/hashlips_art_engine#614]
Error: Unsupported image type
    at setSource (/Users/Usr/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/Usr/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/lib/image.js:62:9)
    at /Users/Usr/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/Usr/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/node_modules/canvas/index.js:23:10)
    at /Users/Usr/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/src/main.js:184:25
    at new Promise (<anonymous>)
    at Usr (/Users/houssamalloum/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/src/main.js:183:10)
    at /Users/Usr/Documents/nft codiing/hashlips_art_engine-1.1.2_patch_v1/src/main.js:364:31
    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@h2022m canvas (the library HashLips uses to load images) only supports PNG, GIF, JPEG, SVG and BMP formats. If you weren't using any of them you should convert your images.
