### ISSUE TITLE
Npm run generate issue : need help

### ISSUE THREAD

**Issue by deebajkazmi** [HashLips/hashlips_art_engine#617]
Hi guys when ever I tried to run the npm run generate command following error is displayed 

(node:7932) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. 
Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:77
        throw new Error(`layer name can not contain dashes, please fix: ${i}`);
              ^

Error: layer name can not contain dashes, please fix: Dyed-brown#19.png
    at C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:77:15
    at Array.map (<anonymous>)
    at getElements (C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:75:6)
    at C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:90:30)
    at startCreating (C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:356:20)
    at C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js:6:3
    at Object.<anonymous> (C:\Users\sm_de\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

Node.js v17.4.0

**Comment by deebajkazmi** [comment]
found out there were some  '-' in the layers, those need to remove
