### ISSUE TITLE
No such file or directory, scandeir'${basePath}/build/images '

### ISSUE THREAD

**Issue by SomeGuy253** [HashLips/hashlips_art_engine#626]
Error: ENOENT: no such file or directory, scandir '${basePath}/build/images
I have this issue i don't know what to do i looked for an answer for a day and haven't found anything, can someone help me?

**Comment by RequiemDreams** [comment]
I had this issue when the name of my layers didn't fully match what I had typed out in config.js I'd suggest looking over and making sure all files/folders are in the right location and names are matching. 

for instance if your layer order looks something like this:

layersOrder: [
      { name: "Background" },
      { name: "Flag Pole" },
      { name: "behind the mask 5" },
      { name: "Hands" },
      { name: "Torso" },
      { name: "OuterHelmet" },
      { name: "Glass" },
      { name: "Feet" },
      { name: "NameTags" },
      { name: "Flag" },
    ],
make sure the files are labeled exactly alike capitals spaces and all.

**Comment by sudip-blip** [comment]
> Error: ENOENT: no such file or directory, scandir '${basePath}/build/images I have this issue i don't know what to do i looked for an answer for a day and haven't found anything, can someone help me?

is your problem solved?

**Comment by Mistermatthews** [comment]
> > Error: ENOENT: no such file or directory, scandir '${basePath}/build/images I have this issue i don't know what to do i looked for an answer for a day and haven't found anything, can someone help me?
> 
> is your problem solved?

I am having the same issue, did you find a fix?

**Comment by bolshoytoster** [comment]
@Mistermatthews can you paste the full error please?

**Comment by Mistermatthews** [comment]
> @Mistermatthews can you paste the full error please?

PS C:\Users\Player One\Desktop\hashlips_art_engine-1.1.2_patch_v5> node utils/nftport/uploadfiles.js
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '${basePath}/build/images'
    at Object.readdirSync (fs.js:1047:3)
    at Object.<anonymous> (C:\Users\Player One\Desktop\hashlips_art_engine-1.1.2_patch_v5\utils\nftport\uploadfiles.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '${basePath}/build/images'
}
PS C:\Users\Player One\Desktop\hashlips_art_engine-1.1.2_patch_v5> 

I have tried everything I can think of

**Comment by bolshoytoster** [comment]
@Mistermatthews I don't think that error is related to this repo, `utils/nftport/uploadfiles.js` doesn't even exist. Do you know where the file came from? It could be one of [these](https://github.com/search?p=2&q=path%3Autils%2Fnftport%2F&type=Code) repos.

**Comment by Mistermatthews** [comment]
@bolshoytoster yea its CodeStakrs repo from his generate and minting video, im not sure if that repo is out of date or not. Its only about a month old

**Comment by bolshoytoster** [comment]
@Mistermatthews you should probably open an issue over there then.

**Comment by Mistermatthews** [comment]
@bolshoytoster unfortunately I have tried and nobody likes to answer

**Comment by nftholding** [comment]
hi i have the same error, i have tried anything and couldnt fix it. i hope sombady help us.

**Comment by KS1388** [comment]
> Error: ENOENT: no such file or directory, scandir '${basePath}/build/images I have this issue i don't know what to do i looked for an answer for a day and haven't found anything, can someone help me?

I am having the same issue. Is there any solution found? Thanks

**Comment by parsadevuk** [comment]
typo error. Do not use " ' " instead use " ` "

**Comment by CarlBainbridge** [comment]
Hmm I always questioned that, however I cannot find that symbol on any of my apple keyboards



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bolshoytoster** [comment]
@CarlBainbridge it should be in the top left, if not you can copy/paste them.

**Comment by Tab007** [comment]
I'm having the same issue

**Comment by Tab007** [comment]
> 

didnt work

**Comment by bolshoytoster** [comment]
@Tab007 can you paste the error please.

**Comment by Tab007** [comment]
> 

Error: ENOENT: no such file or directory, scandir '${basePath}/build/images'
    at Object.readdirSync (node:fs:1392:3)
    at Object.<anonymous> (C:\Users\Dell\Desktop\nft\utils\nftport\uploadFiles.js:7:4)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '${basePath}/build/images'

**Comment by bolshoytoster** [comment]
@Tab007 can you paste the first ~10 lines of `utils\nftport\uploadFiles.js` please, there are sevral versions I've found.

**Comment by Tab007** [comment]
> @Tab007 can you paste the first ~10 lines of `utils\nftport\uploadFiles.js` please, there are sevral versions I've found.

https://github.com/codeSTACKr/create-10k-nft-collection/blob/main/utils/nftport/uploadFiles.js    I think this is the solution it already started working I think.
