### ISSUE TITLE
Writing metadata for 1: undefined node:internal/errors:464     ErrorCaptureStackTrace(err);     ^

### ISSUE THREAD

**Issue by RoyalCactusFruit** [HashLips/hashlips_art_engine#629]
Writing metadata for 1: undefined
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
I am trying to generate and it only generates one image before this error message is shown with more information on it.

**Comment by RoyalCactusFruit** [comment]
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2146:5)
    at saveMetaDataSingleFile (C:Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:320:6)
    at C:\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:409:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (C:\\hashlips_art_engine-1.1.2_patch_v5\src\main.js:374:9) {
  code: 'ERR_INVALID_ARG_TYPE'

I deleted my folder locations cause their names are specific.

**Comment by RoyalCactusFruit** [comment]
I have noticed for the one image created, it does not have its own Json.
