### ISSUE TITLE
NPM install not working

### ISSUE THREAD

**Issue by mmaklary** [HashLips/hashlips_art_engine#639]
I am getting this message, what could be the issue?:

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@16.13.2 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.2 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.2 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.2 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/maklarym./Library/Caches/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/maklarym./Library/Caches/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/maklarym./Library/Caches/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/maklarym./Desktop/DSC/hashlips_art_engine_1.1_2.2_patch_v5/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v16.13.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maklarym./.npm/_logs/2022-01-31T09_38_16_584Z-debug.log
maklarym.@Maklarys-MacBook-Pro hashlips_art_engine_1.1_2.2_patch_v5 %

**Comment by bolshoytoster** [comment]
@mmaklary as [this](https://github.com/Automattic/node-canvas/issues/1274#issuecomment-428390433) comment says, canvas doesn’t support arm node.js. You can try running `npm install --target_arch=x64` instead, if that doesn’t work, you might have to install x64 node.js.

It also looks like you need `pkg-config`, which can be installed with `brew install pkg-config`.

**Comment by mmaklary** [comment]
**Thx now it works but i get this:** 


6 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (3 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
maklarym.@Maklarys-MacBook-Pro hashlips_art_engine-1.1.1_update % 


**After running it I get stuck:**

maklarym.@Maklarys-MacBook-Pro hashlips_art_engine-1.1.1_update % node index.js
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1.1_update/node_modules/canvas/build/Release/canvas.node, 1): no suitable image found.  Did find:
        /Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1.1_update/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
        /Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1.1_update/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1.1_update/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'

**Comment by bolshoytoster** [comment]
@mmaklary [this](https://github.com/HashLips/hashlips_art_engine/issues/329#issuecomment-983758731) comment suggests reinstalling canvas, if it still doesn’t work you could do what [this](https://github.com/HashLips/hashlips_art_engine/issues/455#issuecomment-1006056844) comment suggests and run `npm install --build-from-source`.

**Comment by mmaklary** [comment]
6 vulnerabilities (3 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
maklarym.@Maklarys-MacBook-Pro hashlips_art_engine-1.1-3.2_patch_v5 % node index.js
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1-3.2_patch_v5/node_modules/canvas/build/Release/canvas.node, 1): no suitable image found.  Did find:
        /Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1-3.2_patch_v5/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
        /Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1-3.2_patch_v5/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/maklarym./Desktop/DSC/hashlips_art_engine-1.1-3.2_patch_v5/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}



**Its difficult because I am new to this, don t really getting why its not working :( thankx the help BTW**

**Comment by bolshoytoster** [comment]
@mmaklary
> Maybe its the M1 chip

Yeah, this seems to have been an issue with canvas since 2017.

I think you could maybe get around it with rosetta but I've never used it personally (only ever used macOS in a VM).

**Comment by itsforren** [comment]
Was there a fix to this? because I am running into the same issue and I also have a m1 Mac. Would love the help, as I am a noob when it comes to coding

**Comment by bolshoytoster** [comment]
@mmaklary @itsforren I'm going to see if I can get this working in a mac vm, I'll update here if I get it working.

**Comment by itsforren** [comment]
@bolshoytoster thanks, I look forward to your results

**Comment by bolshoytoster** [comment]
Since my emulator can't emulate M1 (without modifications) I'm not able to test this, but it looks like if you just have it installed it might work.

You can install it with `/usr/sbin/softwareupdate --install-rosetta` if you haven't already.

[Somebody else](https://github.com/HashLips/hashlips_art_engine/issues/645#issuecomment-1026165028) is trying this as well so you could wait for their results if just installing rosetta doesn't work.

**Comment by mmaklary** [comment]
> 

Thanks, node 14 works :)
