### ISSUE TITLE
canva.node         node_modules/canva/lib/bindings.js:3:18   how to fix it

### ISSUE THREAD

**Issue by ivanluhur** [HashLips/hashlips_art_engine#641]

**Comment by bolshoytoster** [comment]
@ivanluhur can you share the whole error?

**Comment by ivanluhur** [comment]
Error: The specified module could not be found
\\?\c:\Users\....\Downloads\hashlips_art_engine_1.1.2_patch_v1\node_modules\canvas\build\Release\canva.node
at Object.Module._extensions. .node (internal/modules/cjs/loader.js:1144:8)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Fuction.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/loader.js:93:18)
at Object.<anonymous> (C:\Users\....\Download\hashlips_art_engine_1.1.2_patch_v1\node_modules\canva\lib\bindings.js:3:18)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions. .js (intenal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (intenal/modules/cjs/loader.js:790:12) {
code: 'ERR_DLOPEN_FAILED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: 'node index.js'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script
npm ERR! This probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!    C:\Users\...\AppData\Roaming\npm-cache\_log\2022-01-31T17_28_14_642Z-debug.log

**Comment by ivanluhur** [comment]
i tried to open debug still confused about what are they meaning and i cannot find any wrong on it pls give me the answer

**Comment by ivanluhur** [comment]
this is the error when i npm run generate of corse if i npm install, it still 1 high from 66 pakage from the script terminal

**Comment by bolshoytoster** [comment]
@ivanluhur could you delete the `node_modules` folder and run `npm install` again

**Comment by ivanluhur** [comment]
i must use the file source.ziptar
