### ISSUE TITLE
run generate

### ISSUE THREAD

**Issue by Longshoreking** [HashLips/hashlips_art_engine#648]
after installing npm and imputing all of the layers into thee config.js I run generate and this prompts in the terminal...

stevenanthony@Stevens-Air hashlips_art_engine-1.1.2_patch_v5 % npm run generate

> hashlips_art_engine@1.1.1 generate /Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5
> node index.js

(node:14057) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/layers/Background/'
    at Object.readdirSync (fs.js:1043:3)
    at getElements (/Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:73:6)
    at /Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:90:30)
    at startCreating (/Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:356:20)
    at /Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/index.js:6:3
    at Object.<anonymous> (/Users/stevenanthony/Downloads/hashlips_art_engine-1.1.2_patch_v5/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
stevenanthony@Stevens-Air hashlips_art_engine-1.1.2_patch_v5 % 

need help understanding please! thank you

**Comment by bolshoytoster** [comment]
@Longshoreking it can't find the `layers/Background` folder, make sure the folder names match your jayer names in `src/config.js` (match case as well).

**Comment by Longshoreking** [comment]
Just read in an issue above that the layer names cant have a "-" in them! going to remove the dash and see if that fixes the problem thank you!
