### ISSUE TITLE
 layer name can not contain dashes, please fix: 

### ISSUE THREAD

**Issue by MrrGnu** [HashLips/hashlips_art_engine#655]
hello, pls help me! i just cant get the generator to run, everytime i try running it tells me: 

Error: layer name can not contain dashes, please fix: Untitled_Artwork-10.png
    at /Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:77:15
    at Array.map (<anonymous>)
    at getElements (/Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:75:6)
    at /Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:90:30)
    at startCreating (/Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:356:20)
    at /Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/index.js:6:3
    at Object.<anonymous> (/Users/timroes/Downloads/hashlips_art_engine-1.1.2_patch_v5/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

**Comment by bolshoytoster** [comment]
@MrrGnu you can't have '-' in your file names, remove/replace them.

**Comment by Noodz-NFT** [comment]
This was partially fixed in later versions of hashlips. main.js has:
const DNA_DELIMITER = "-";

which you change to "#" or some other delimiter. However, in 1.1.2 there is still a bug. Line 76 of main.js
still has:
 if (i.includes("-"))

instead of:
 if (i.includes(DNA_DELIMITER))

**Comment by TimBritcliffe** [comment]
> This was partially fixed in later versions of hashlips. main.js has: const DNA_DELIMITER = "-";
> 
> which you change to "#" or some other delimiter. However, in 1.1.2 there is still a bug. Line 76 of main.js still has: if (i.includes("-"))
> 
> instead of: if (i.includes(DNA_DELIMITER))

Do you happen to know which version has it fixed?

**Comment by John-cel** [comment]
thanks
