### ISSUE TITLE
error please help

### ISSUE THREAD

**Issue by rahulsai821** [HashLips/hashlips_art_engine#660]
hlo.. iam new to visual studio
while running npm run generate i got an issue please help me

error: ENOENT: no such file or directory, scandir 'C:\Users\acer\Desktop\nft\hashlips_art_engine-main/layers/Background/'       
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\acer\Desktop\nft\hashlips_art_engine-main\src\main.js:73:6)
    at C:\Users\acer\Desktop\nft\hashlips_art_engine-main\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\acer\Desktop\nft\hashlips_art_engine-main\src\main.js:90:30)
    at startCreating (C:\Users\acer\Desktop\nft\hashlips_art_engine-main\src\main.js:356:20)
    at C:\Users\acer\Desktop\nft\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\acer\Desktop\nft\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\acer\\Desktop\\nft\\hashlips_art_engine-main/layers/Background/'
}
PS C:\Users\acer\Desktop\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@rahulsai821 it can't find the `layers/Background` folder, make sure your folder names match the names in your `src/config.js` (it's case sensitive).
