### ISSUE TITLE
Error shows after yarn install

### ISSUE THREAD

**Issue by HUANGWentan** [HashLips/hashlips_art_engine#666]
Hi everybody, I clone the project and used the yarn install  and this happened..

wentanhuang@Wentans-Air hashlips_art_engine-main % yarn install
yarn install v1.22.15
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.6
node-pre-gyp info using node@16.13.2 | darwin | arm64
node-pre-gyp info check checked for "/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz failed, reason: read ETIMEDOUT 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@16.13.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz failed, reason: read ETIMEDOUT 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@16.13.2 | darwin | arm64
gyp info find Python using Python version 3.10.2 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wentanhuang/Library/Caches/node-gyp/16.13.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/wentanhuang/Library/Caches/node-gyp/16.13.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/wentanhuang/Library/Caches/node-gyp/16.13.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas
gyp ERR! node -v v16.13.2
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas
node-pre-gyp ERR! node -v v16.13.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.6
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Then I try npm install**

wentanhuang@Wentans-Air hashlips_art_engine-main % npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 

removed 5 packages, and audited 66 packages in 5s

6 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

**and then type in node index.js**

wentanhuang@Wentans-Air hashlips_art_engine-main % node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js
- /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/lib/canvas.js
- /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/index.js
- /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/src/main.js
- /Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/lib/bindings.js',
    '/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/lib/canvas.js',
    '/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/node_modules/canvas/index.js',
    '/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/src/main.js',
    '/Users/wentanhuang/Documents/nft_project/hashlips_art_engine-main/index.js'
  ]
}

**Comment by HUANGWentan** [comment]
I am currently using a m1 chip macbook then I uninstall my latest Nodejs verion 16 and install the v14, problem fixed!
here is the link of the v14 nodejs 
https://nodejs.org/download/release/v14.19.0/
