### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by aymanawwad** [HashLips/hashlips_art_engine#671]
hi
I was watching your tutorial about nft but when i upload the last version of art code its not the same, src and utlis folders not in it .
I'm lost now wat to do ,
thank you 
sorry for my English

**Comment by bolshoytoster** [comment]
@aymanawwad if I understand correctly, you are missing `src/` and `utils/`. I think this might be because you're in the wrong folder.

Try running `cd */` in the powershell, then run `npm run build` to test.

**Comment by aymanawwad** [comment]
PS C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main> cd */
cd : Cannot set the location because path '*/' resolved to multiple containers. You can only the set 
location to a single container at a time.
At line:1 char:1
+ cd */
+ ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by bolshoytoster** [comment]
@aymanawwad sorry, I thought powershell could do that. It looks like you're already in the right place. Could you send the output of `ls` please?

**Comment by aymanawwad** [comment]
i removed the file and installed , the missing folder showed up , i have them now , 
i also tried npm install many errors 
is this wat u mean 1s output
1s : The term '1s' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct     
and try again.
At line:1 char:1
+ 1s
+ ~~
    + CategoryInfo          : ObjectNotFound: (1s:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
ty

**Comment by bolshoytoster** [comment]
@aymanawwad it's an L instead on a 1. Could you send the errors from `npm install` instead please.

**Comment by aymanawwad** [comment]
npm install
PS C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main> npm install truffle -p   
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated       
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated ipld-raw@6.0.0: This module has been superseded by the multiformats module
npm WARN deprecated apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated cids@1.1.9: This module has been superseded by the multiformats module
npm WARN deprecated ipld-dag-cbor@0.17.1: This module has been superseded by @ipld/dag-cbor and multiformats
npm WARN deprecated apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module        
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated ipld-dag-pb@0.20.0: This module has been superseded by @ipld/dag-pb and multiformats
npm WARN deprecated multicodec@3.2.1: This module has been superseded by the multiformats module
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future       
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module        
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module        
npm WARN deprecated multicodec@2.1.3: This module has been superseded by the multiformats module        
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ursa-optional',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\ursa-optional'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ursa-optional'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\sqlite3',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\sqlite3'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\sqlite3'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ganache\\node_modules\\leveldown',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\ganache\node_modules\leveldown'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ganache\\node_modules\\leveldown'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ganache\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\ganache\node_modules\bufferutil'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ganache\\node_modules\\bufferutil'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ganache',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\ganache\node_modules\utf-8-validate'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\ayman\\Downloads\\hashlips_art_engine-main\\hashlips_art_engine-main\\node_modules\\ganache\\node_modules\\utf-8-validate'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\ganache\node_modules\keccak
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v17.4.0/node-v17.4.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.4.0/node-v17.4.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v17.4.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v17.4.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v17.4.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v17.4.0/win-arm64/node.lib
npm ERR! gyp http 404 https://nodejs.org/download/release/v17.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.4.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.4.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.4.0/win-x86/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS checking VS2019 (16.11.32106.194) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - found VC++ toolset: v142
npm ERR! gyp ERR! find VS - missing any Windows SDK
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\node_modules\ganache\node_modules\keccak
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ayman\AppData\Local\npm-cache\_logs\2022-02-05T18_19_25_885Z-debug-0.log
PS C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main> 1s

**Comment by aymanawwad** [comment]
ls
PS C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main> ls


    Directory: C:\Users\ayman\Downloads\hashlips_art_engine-main\hashlips_art_engine-main


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          2/5/2022  10:15 PM                .github
d-----          2/5/2022  10:15 PM                constants
d-----          2/5/2022  10:15 PM                layers
d-----          2/5/2022  10:15 PM                modules
d-----          2/5/2022  10:22 PM                node_modules
d-----          2/5/2022  10:15 PM                src
d-----          2/5/2022  10:15 PM                utils
-a----          2/5/2022  10:15 PM           1678 .gitignore
-a----          2/5/2022  10:15 PM              9 .nvmrc
-a----          2/5/2022  10:15 PM         441599 banner.png
-a----          2/5/2022  10:15 PM            157 index.js
-a----          2/5/2022  10:15 PM           1065 LICENSE
-a----          2/5/2022  10:15 PM          37711 logo.png
-a----          2/5/2022  10:18 PM          41285 package-lock.json
-a----          2/5/2022  10:15 PM            861 package.json
-a----          2/5/2022  10:15 PM           9930 README.md
-a----          2/5/2022  10:18 PM          16243 yarn.lock

**Comment by bolshoytoster** [comment]
@aymanawwad you need to install [visual studio](https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&channel=Release&version=VS2022) with the c++ development workload. Not visual studio code.

**Comment by aymanawwad** [comment]
hi
plz share me the link to the software visual studio with the c++ development workload. i downloaded it ,but there is no new terminal option , the one i see in your video is visual studio code. 
thank you

**Comment by bolshoytoster** [comment]
@aymanawwad [does this help you?](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation)

**Comment by aymanawwad** [comment]
hi
idk wat happened ,but now everything is matching your tutorial .now I'm in pinata ,and code is generating my collection .thanks man your amazing

**Comment by bolshoytoster** [comment]
@aymanawwad no problem

**Comment by aymanawwad** [comment]
hi 
im sorry but this error happened update baseuri
PS C:\Users\ayman\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5> node utils/updatebaseuri.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\ayman\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\utils\updatebaseuri.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.4.0
PS C:\Users\ayman\Downloads\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5>

**Comment by bolshoytoster** [comment]
@aymanawwad that file doesn't exist, what are you trying to do?

**Comment by aymanawwad** [comment]
updae ipfs

**Comment by bolshoytoster** [comment]
@aymanawwad I think you can do it by runnung `npm run update_info`.

**Comment by aymanawwad** [comment]
ya its worked , thanks man your support services is better than google .thanks

**Comment by aymanawwad** [comment]
hi 
i know i asked too much , but if i dont have hidden image how to fill the spaces in remix becuz i cant copy the code and paste it in vs code
