### ISSUE TITLE
errno: -4058

### ISSUE THREAD

**Issue by G0804019u** [HashLips/hashlips_art_engine#672]
Error: ENOENT: no such file or directory, scandir 'C:\Users\justy\nft_collection\hashlips_art_engine/layers/Eyeball/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\justy\nft_collection\hashlips_art_engine\src\main.js:73:6)
    at C:\Users\justy\nft_collection\hashlips_art_engine\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\justy\nft_collection\hashlips_art_engine\src\main.js:90:30)
    at startCreating (C:\Users\justy\nft_collection\hashlips_art_engine\src\main.js:356:20)
    at C:\Users\justy\nft_collection\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\justy\nft_collection\hashlips_art_engine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\justy\\nft_collection\\hashlips_art_engine/layers/Eyeball/'

I am sure i do not have Eyeball in my layers folder but it keep showing me this error

**Comment by bolshoytoster** [comment]
@G0804019u the error is because it looks for an `Eyeball/` folder but it doesn't exist. Make sure the folders in `layers/` match the names in `src/config.js`. (It's case sensitive as well).

**Comment by Niahig** [comment]
having the same issue, its looking for a background folder, the folder exists. so not sure what is going on with it 
did you figure it out?

**Comment by bolshoytoster** [comment]
@Niahig make sure the folder names match the names in `src/config.js` exactly (case sensitive as well).

**Comment by Niahig** [comment]
Hi, they match exactly, it worked fine . i was able to test run, when i changed the grow edition size, it no longer works

**Comment by bolshoytoster** [comment]
@Niahig are you using this repo or my fork?

**Comment by Niahig** [comment]
Hi using your Fork, today the issue is showing eyeball, there is no eyeball in my layers

**Comment by bolshoytoster** [comment]
@Niahig have you saved it?

**Comment by Niahig** [comment]
Hi, yes multiple times and have uninstalled node, visual studio code, just cant seem to fix the error.

**Comment by Niahig** [comment]
debugging has fixed it

**Comment by Gavethereum** [comment]
![config js - hashlips_art_engine-main png](https://user-images.githubusercontent.com/99564114/153730873-cc80f3ca-db7c-43dd-896e-5a222fdf520c.png)
I am attempting to render these files, but I am unable to do so, can anyone help me?

**Comment by bolshoytoster** [comment]
@Gavethereum it can't find `layers/Background`. Make sure the folder names match the layer names exactly (case sensitive as well).
