### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Apoloniyr** [HashLips/hashlips_art_engine#674]
Guys, how can I solve this error? 

**TypeError: Cannot read properties of undefined (reading 'split')
    at cleanDna (C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\src\main.js:44:25)
    at C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\src\main.js:135:22
    at Array.find (<anonymous>)
    at C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\src\main.js:134:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\src\main.js:133:35)
    at startCreating (C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\src\main.js:196:23)
    at C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\index.js:5:3
    at Object.<anonymous> (C:\Users\hp\Desktop\hashlips_art_engine-1.0.2_update\hashlips_art_engine-1.0.2_update\index.js:6:3)**

**Comment by bolshoytoster** [comment]
@Apoloniyr it looks like you're using an old release, could you try again on a newer version please?
