### ISSUE TITLE
Canot change Layers

### ISSUE THREAD

**Issue by xbergrunner** [HashLips/hashlips_art_engine#675]
When i add my layers i got a lot of errors, have to change thé taxonomies back to the default from hashlips to run

tim@Tims-MBP hashlips_art_engine-1.1.2_patch_v5 % npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:1302) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/tim/hashlips_art_engine-1.1.2_patch_v5/layers/Eyeball/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (/Users/tim/hashlips_art_engine-1.1.2_patch_v5/src/main.js:73:6)
    at /Users/tim/hashlips_art_engine-1.1.2_patch_v5/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/tim/hashlips_art_engine-1.1.2_patch_v5/src/main.js:90:30)
    at startCreating (/Users/tim/hashlips_art_engine-1.1.2_patch_v5/src/main.js:356:20)
    at /Users/tim/hashlips_art_engine-1.1.2_patch_v5/index.js:6:3
    at Object.<anonymous> (/Users/tim/hashlips_art_engine-1.1.2_patch_v5/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/tim/hashlips_art_engine-1.1.2_patch_v5/layers/Eyeball/'
}
tim@Tims-MBP hashlips_art_engine-1.1.2_patch_v5 % npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:1345) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: ee0bdf0a1effb0c3b14cd02811e21e81a08bca99
Created edition: 2, with DNA: f23577c2b02a9f4a3a95ddafe2531f7d68443ab5
DNA exists!
Created edition: 3, with DNA: 247f55973146e83b223fb86463850a6bb792801c
tim@Tims-MBP hashlips_art_engine-1.1.2_patch_v5 %

**Comment by bolshoytoster** [comment]
@xbergrunner the layer folder names have to match exactly (case-sensitive) with the layer names in `src/config.js`.

**Comment by TheRudist** [comment]
I'm having the same issue. I elimnated spaces. All folder names match with the config. idk whats wrong

**Comment by TheRudist** [comment]
you have to save before running ::facepalm::

**Comment by xbergrunner** [comment]
Trank you Guys, sometimes ist is Test easy
