### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by Bakhshi007** [HashLips/hashlips_art_engine#676]
D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
PS D:\CV\generate-nfts-main\hashlips_art_engine-main> node index.js
D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
SetSource.call(img, src);
^

Error: Unsupported image type
at setSource (D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
at Image.set (D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
at D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
at new Promise ()
at loadImage (D:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
at D:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:185:27
at new Promise ()
at loadLayerImg (D:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:184:12)
at D:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:368:31
at Array.forEach ()

**Comment by bolshoytoster** [comment]
@Bakhshi007 this only supports PNG, GIF, JPEG, SVG and BMP images. make sure all of your images are one of those.

**Comment by Bakhshi007** [comment]
@bolshoytoster 
Thanks for the comment , I have checked all of my layers are PNG but I get the same error

**Comment by Bakhshi007** [comment]
node:13100) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: fbe4f4053b9add70509951e9428a19a09de3209e
Created edition: 2, with DNA: 4a2f6ad98145cae3ebca43829473cc25dd24b693
Created edition: 3, with DNA: 7173a071c81df13229e5fe73c5f084f820c96c14
Created edition: 4, with DNA: 053de1f77a868edf6e27478827e7bd2e2b7b5856
d:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (d:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (d:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at d:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (d:\CV\generate-nfts-main\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at d:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (d:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:184:12)
    at d:\CV\generate-nfts-main\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)

**Comment by Xanph** [comment]
Would be good if this could be merged into #615

**Comment by Alexandriaaaaa** [comment]
I have a similar problem.
I set it to generate 1000 undamaged 3000x3000 png images. Error: Unsupported image type appears on the way.
The timing when this error appears may appear after randomly generating 18 pieces.
I changed the version of the node and tried it, but it doesn't work at all.

Created edition: 45, with DNA: 43a4b262ad61e35dd529731a18cf9dab1baf676f
(node: 8448) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C: \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 91: 13)
    at Image.set (C: \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 62: 9)
    at C: \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 34: 15
    at new Promise (<anonymous>)
    at loadImage (C: \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 23: 10)
    at C: \ hashlips_art_engine-main \ src \ main.js: 185: 27
    at new Promise (<anonymous>)
    at loadLayerImg (C: \ hashlips_art_engine-main \ src \ main.js: 184: 12)
    at C: \ hashlips_art_engine-main \ src \ main.js: 368: 31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node: 8448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node: 8448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bolshoytoster** [comment]
@Alexandriaaaaa could you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine). It doesn't fix the issue but it should tell you what image(s) cause it to fail.

**Comment by Alexandriaaaaa** [comment]
> @Alexandriaaaaa[私のフォーク](https://github.com/bolshoytoster/hashlips_art_engine)を使ってみてください。問題は修正されませんが、どの画像が原因で失敗するかがわかります。

thank you.
I tried it with npm run generate and node index.js.

PS C: \ new folder \ hashlips_art_engine-main> npm run generate

> hashlips_art_engine@1.1.1 generate C: \ new folder \ hashlips_art_engine-main
> node index.js

(node: 16360) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory'C: \ new folder \ hashlips_art_engine-main / layers / Background / Pink # 4.PNG'
    at setSource (C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 91: 13)
    at Image.set (C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 62: 9)
    at C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 34: 15
    at new Promise (<anonymous>)
    at loadImage (C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 23: 10)
    at C: \ new folder \ hashlips_art_engine-main \ src \ main.js: 207: 25
    at new Promise (<anonymous>)
    at loadLayerImg (C: \ new folder \ hashlips_art_engine-main \ src \ main.js: 206: 10)
    at C: \ new folder \ hashlips_art_engine-main \ src \ main.js: 423: 29
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node: 16360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node: 16360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node: 16360) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory'C: \ new folder \ hashlips_art_engine-main / layers / Item / Gun & Bat # 13.PNG'
    at setSource (C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 91: 13)
    at Image.set (C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 62: 9)
    at C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 34: 15
    at new Promise (<anonymous>)
    at loadImage (C: \ new folder \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 23: 10)
    at C: \ new folder \ hashlips_art_engine-main \ src \ main.js: 207: 25
    at new Promise (<anonymous>)
    at loadLayerImg (C: \ new folder \ hashlips_art_engine-main \ src \ main.js: 206: 10)
    at C: \ new folder \ hashlips_art_engine-main \ src \ main.js: 423: 29

However, these images have been successfully generated so far.
Since it is not damaged, there may be other causes.
I forgot to say that I'm using node v14.18.1 and vs studio on windows.

**Comment by bolshoytoster** [comment]
@Alexandriaaaaa [this](https://github.com/HashLips/hashlips_art_engine/issues/276#issuecomment-974693486) comment suggests moving the `hashlips_art_engine-main` folder to your user folder (`C:\Users\whatever`).

**Comment by Alexandriaaaaa** [comment]
> @Alexandriaaaaa [この](https://github.com/HashLips/hashlips_art_engine/issues/276#issuecomment-974693486)コメントは、`hashlips_art_engine-main`フォルダをユーザーフォルダに移動することを提案しています（`C:\Users\whatever`）。

You are a surprisingly gentleman.
thank you.
When I expanded it to the user folder and tried it, I encountered a new problem. I'm about to cry (´ ； ω ； `) Wow
PS C: \ Users \ hashlips_art_engine-main> npm install
npm WARN hashlips_art_engine@1.1.1 No repository field.

audited 66 packages in 1.201s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C: \ Users \ hashlips_art_engine-main> npm run generate

> hashlips_art_engine@1.1.1 generate C: \ Users \ hashlips_art_engine-main
> node index.js

Edition exists!
Edition exists!
Edition exists!
Edition exists!
Edition exists!
Created edition: 6, with DNA: 80cbc531b2060a98b759551b752569c361b5625e
(node: 11324) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 91: 13)
    at Image.set (C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 62: 9)
    at C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 34: 15
    at new Promise (<anonymous>)
    at loadImage (C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 23: 10)
    at C: \ Users \ hashlips_art_engine-main \ src \ main.js: 207: 25
    at new Promise (<anonymous>)
    at loadLayerImg (C: \ Users \ hashlips_art_engine-main \ src \ main.js: 206: 10)
    at C: \ Users \ hashlips_art_engine-main \ src \ main.js: 423: 29
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node: 11324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node: 11324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Alexandriaaaaa** [comment]
I'm sorry many times.
Thank you for your precious time.
I was able to generate up to 6 normally, but I don't know where there is a problem.

PS C: \ Users \ hashlips_art_engine-main> npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion @ 1, but package-lock.json was generated for lockfileVersion @ 2. I'll try to do my best
with it!

> canvas@2.9.0 install C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas
> node-pre-gyp install --fallback-to-build

[canvas] Success: "C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ build \ Release \ canvas.node" is installed via remote
npm WARN hashlips_art_engine@1.1.1 No repository field.

added 66 packages from 35 contributors and audited 66 packages in 5.61s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C: \ Users \ hashlips_art_engine-main> npm run generate

> hashlips_art_engine@1.1.1 generate C: \ Users \ hashlips_art_engine-main
> node index.js

Created edition: 1, with DNA: cc8291ddb94250000692bcaa15ce35a0f1493f68
Created edition: 2, with DNA: 0a9e32c119f71078f831d0f8694c05306d92cfb0
Created edition: 3, with DNA: 99e37834efa7a477b20a046dc19a882a8c72b176
Created edition: 4, with DNA: 988cdee89aa63b57f5fee82eaa38f8c5c4186130
Created edition: 5, with DNA: 77d7b0aa514951bdba50f00c58608fccaca45a26
Created edition: 6, with DNA: c6429fb30c8f52e6586cdb422d68234d28bce75c
(node: 16480) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 91: 13)
    at Image.set (C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ lib \ image.js: 62: 9)
    at C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 34: 15
    at new Promise (<anonymous>)
    at loadImage (C: \ Users \ hashlips_art_engine-main \ node_modules \ canvas \ index.js: 23: 10)
    at C: \ Users \ hashlips_art_engine-main \ src \ main.js: 207: 25
    at new Promise (<anonymous>)
    at loadLayerImg (C: \ Users \ hashlips_art_engine-main \ src \ main.js: 206: 10)
    at C: \ Users \ hashlips_art_engine-main \ src \ main.js: 423: 29
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node: 16480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node: 16480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C: \ Users \ hashlips_art_engine-main>

**Comment by TravelingTechGuy** [comment]
Suffering from "unsupported image type" as well. 

```
C:\Users\myuser\hashlips\node_modules\canvas\lib\image.js:92
  SetSource.call(img, src)
            ^

Error: Unsupported image type
    at setSource (C:\Users\myuser\hashlips\node_modules\canvas\lib\image.js:92:13)
    at Image.set (C:\Users\myuser\hashlips\node_modules\canvas\lib\image.js:62:9) 
    at C:\Users\myuser\hashlips\node_modules\canvas\index.js:34:15
```

I've upgraded my canvas module to latest (version `2.9.1`)
I've added a `console.log(src);` to `node_modules/canvas/lib/image.js` to find the errant file names.

All images are 3000x3000 32 bit PNGs. Whenever I remove an image that appears, another one blows up (I have removed 5 so far - still exploding). Nothing special that I can see about the image. They're all transparent PNG, all the same size, no punctuation letters in their name, all end with #0n (where n between 1 and 9). So no naming issues.

Any idea what else should I look for?

**Comment by bolshoytoster** [comment]
@TravelingTechGuy can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.

**Comment by TravelingTechGuy** [comment]
@bolshoytoster Thanks for replying! From what I've seen, your fork prints out the name of the "unsupported" file (which i already handled). Does it actually solve the issue? Could you tell me what have you changed?

**Comment by bolshoytoster** [comment]
@TravelingTechGuy it usually solves the issue (the issue is usually just a hidden file), it now ignores files it can't load and gives a warning.

**Comment by TravelingTechGuy** [comment]
> @TravelingTechGuy it usually solves the issue (the issue is usually just a hidden file), it now ignores files it can't load and gives a warning.

One of the first things I did was look for hidden files in the layers folders (since my artist works on a Mac) - there were none (she shared on Dropbox, which removes all hidden files).

If your fork just ignores files it can't use, then I'll end up with the wrong rarities, no?

Do you have any idea why certain files are "unsupported"?

**Comment by bolshoytoster** [comment]
@TravelingTechGuy just use it and read the warning to see which files it can't load, I need to sleep.

**Comment by TravelingTechGuy** [comment]
👍

**Comment by guyleung801** [comment]
For Someone who still facing this issues, I have my solutions here.

Actually this might happens just for Windows users, this error in my case, is because of the "Thumb.db" files exists in your layers folder, I have my view Hidden items option checked, but I cannot see this file, but after I follow the steps below, I finally see it and after I deleted the "Thumb.db" files that in my layers folder, I can successfully generate all images without seeing any errors again, hurray!

**I found this procedure to work for me ("Always show icons, never thumbnails" was already unchecked):**
1. Open Window File Explorer
2. Click View tab
3. Options / Change folder and search options
4. Click View tab
5. Uncheck "Hide protected operating system files (Recommended)"
6. Click on Apply and OK

Hope this help.

**Comment by Stamoments** [comment]
i'm having issues with the code,
/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/lib/image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/lib/image.js:62:9)
    at /Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/index.js:23:10)
    at /Users/mac/Downloads/create-10k-nft-collection-2.0.0/src/main.js:184:25
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/mac/Downloads/create-10k-nft-collection-2.0.0/src/main.js:183:10)
    at /Users/mac/Downloads/create-10k-nft-collection-2.0.0/src/main.js:364:31
    at Array.forEach (<anonymous>)

**Comment by blahkheart** [comment]
> For Someone who still facing this issues, I have my solutions here.
> 
> Actually this might happens just for Windows users, this error in my case, is because of the "Thumb.db" files exists in your layers folder, I have my view Hidden items option checked, but I cannot see this file, but after I follow the steps below, I finally see it and after I deleted the "Thumb.db" files that in my layers folder, I can successfully generate all images without seeing any errors again, hurray!
> 
> **I found this procedure to work for me ("Always show icons, never thumbnails" was already unchecked):**
> 
> 1. Open Window File Explorer
> 2. Click View tab
> 3. Options / Change folder and search options
> 4. Click View tab
> 5. Uncheck "Hide protected operating system files (Recommended)"
> 6. Click on Apply and OK
> 
> Hope this help.

Thanks!!! This worked for me

**Comment by Alpaga2** [comment]
Hello everyone

I can't fix this error, I'm at the end of my life x)

The generation of nft stops suddenly ...




PS E:\StickMania\Layers-sans-PSD\hashlips_art_engine> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:7464) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: 0cecf8bac94fe2dfe6e2b902ff52142630f94eed
Created edition: 2, with DNA: abf61eb6e7c3c4e2dd7be28e2a1229a30d324c14
Created edition: 3, with DNA: 1ccdba03544a289f47dae6c9f03fba04e3f7e1ad
Created edition: 4, with DNA: e052ce9a6830afea455ea93ba3d911fdf0411592
E:\StickMania\Layers-sans-PSD\hashlips_art_engine\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'E:\StickMania\Layers-sans-PSD\hashlips_art_engine/layers/Rod/Bois épicéa.png'
    at setSource (E:\StickMania\Layers-sans-PSD\hashlips_art_engine\node_modules\canvas\lib\image.js:91:13)
    at Image.set (E:\StickMania\Layers-sans-PSD\hashlips_art_engine\node_modules\canvas\lib\image.js:62:9)
    at E:\StickMania\Layers-sans-PSD\hashlips_art_engine\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (E:\StickMania\Layers-sans-PSD\hashlips_art_engine\node_modules\canvas\index.js:23:10)
    at E:\StickMania\Layers-sans-PSD\hashlips_art_engine\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (E:\StickMania\Layers-sans-PSD\hashlips_art_engine\src\main.js:184:12)
    at E:\StickMania\Layers-sans-PSD\hashlips_art_engine\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'E:\\StickMania\\Layers-sans-PSD\\hashlips_art_engine/layers/Rod/Bois épicéa.png',
  syscall: 'fopen'

**Comment by bolshoytoster** [comment]
@Alpaga2 the dependency we use for images (canvas.js) doesn't support loading files with non-ascii characters in the path - you should remove the `é`s from `layers/Rod/Bois épicéa.png`.

**Comment by blahkheart** [comment]
> For Someone who still facing this issues, I have my solutions here.
> 
> Actually this might happens just for Windows users, this error in my case, is because of the "Thumb.db" files exists in your layers folder, I have my view Hidden items option checked, but I cannot see this file, but after I follow the steps below, I finally see it and after I deleted the "Thumb.db" files that in my layers folder, I can successfully generate all images without seeing any errors again, hurray!
> 
> **I found this procedure to work for me ("Always show icons, never thumbnails" was already unchecked):**
> 
> 1. Open Window File Explorer
> 2. Click View tab
> 3. Options / Change folder and search options
> 4. Click View tab
> 5. Uncheck "Hide protected operating system files (Recommended)"
> 6. Click on Apply and OK
> 
> Hope this help.

@Alpaga2 Did u try this yet??

**Comment by ashdelta1023** [comment]
> For Someone who still facing this issues, I have my solutions here.
> 
> Actually this might happens just for Windows users, this error in my case, is because of the "Thumb.db" files exists in your layers folder, I have my view Hidden items option checked, but I cannot see this file, but after I follow the steps below, I finally see it and after I deleted the "Thumb.db" files that in my layers folder, I can successfully generate all images without seeing any errors again, hurray!
> 
> **I found this procedure to work for me ("Always show icons, never thumbnails" was already unchecked):**
> 
> 1. Open Window File Explorer
> 2. Click View tab
> 3. Options / Change folder and search options
> 4. Click View tab
> 5. Uncheck "Hide protected operating system files (Recommended)"
> 6. Click on Apply and OK
> 
> Hope this help.

This worked for me, thank you!
