### ISSUE TITLE
HasgLips_Art_Engine issue 

### ISSUE THREAD

**Issue by Sait691** [HashLips/hashlips_art_engine#678]
I did the file commands as you did but npm finds 5 vulnerabilities when installing. When I do the npm audit fix, it pretends to work, but node index.js doesn't upload pictures in the commune. It gives the error;
 SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'C:\Users\ismai\OneDrive\Masaüstü\Bored/layers/Background/Black#1.png'
    at setSource (C:\Users\ismai\OneDrive\Masaüstü\Bored\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\ismai\OneDrive\Masaüstü\Bored\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\ismai\OneDrive\Masaüstü\Bored\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\ismai\OneDrive\Masaüstü\Bored\node_modules\canvas\index.js:23:10)
    at C:\Users\ismai\OneDrive\Masaüstü\Bored\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\ismai\OneDrive\Masaüstü\Bored\src\main.js:184:12)
    at C:\Users\ismai\OneDrive\Masaüstü\Bored\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\ismai\\OneDrive\\Masaüstü\\Bored/layers/Background/Black#1.png',
  syscall: 'fopen'
}
how do I resolve this error please help me

**Comment by Sait691** [comment]
node index.js
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082/layers/Eyeball/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082\src\main.js:73:6)
    at C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082\src\main.js:87:30)
    at startCreating (C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082\src\main.js:349:20)
    at C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082\index.js:6:3
    at Object.<anonymous> (C:\Users\ismai\OneDrive\Masaüstü\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\ismai\\OneDrive\\Masaüstü\\hashlips_art_engine-5363ccc8f9e0991d3bc269d6b8b81a39d5bee082/layers/Eyeball/'
}

**Comment by bolshoytoster** [comment]
@Sait691 that second error is because the names of your folder names need to match exactly with the layer names in `src/config.js`.

**Comment by Sait691** [comment]
Thank you but other issue what is the problem ı didn't understand

**Comment by Sait691** [comment]
I went back to windows 10 to see if it was because of it I was using Windows 11 but it hasn't changed. He's always finding 5 vulnerabilities.

**Comment by bolshoytoster** [comment]
@Sait691 you can ignore the vulnerabilities

**Comment by Sait691** [comment]
But even if I ignore it, he doesn't upload all kinds of photos and json files.

**Comment by bolshoytoster** [comment]
@Sait691 this probably isn't the issue, but it might be that your path contains `ü` characters or because it's in the OneDrive folder. You could try moving the project folder somewhere else.

**Comment by Sait691** [comment]
yes one drive can be in the toilet bowl auto throwing thank you very much
