### ISSUE TITLE
 Error: Unsupported image type 2

### ISSUE THREAD

**Issue by Bakhshi007** [HashLips/hashlips_art_engine#679]
D:\CV\generate-nfts-main\generate-nfts-main>node index.js
Created edition: 1, with DNA: 0dff911acb06e547cae26cb7fa30c0170f2f2555
Created edition: 2, with DNA: 03eab343ab2f0653a7c62790a98232ce158fe7e4
Created edition: 3, with DNA: 6d2781a7e2a6731ac3a1a8a6a04967c896c10076
Created edition: 4, with DNA: 1ad160fea0ec4922ab295dd2dedd5fba4831b5b4
Created edition: 5, with DNA: 224a6ed7a6f69ac2fda9770acae23d140ca976a6
Created edition: 6, with DNA: 3983209886d56c14f76c2035bb59679f0d0d1bcb
D:\CV\generate-nfts-main\generate-nfts-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (D:\CV\generate-nfts-main\generate-nfts-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (D:\CV\generate-nfts-main\generate-nfts-main\node_modules\canvas\lib\image.js:62:9)
    at D:\CV\generate-nfts-main\generate-nfts-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (D:\CV\generate-nfts-main\generate-nfts-main\node_modules\canvas\index.js:23:10)
    at D:\CV\generate-nfts-main\generate-nfts-main\src\main.js:194:25
    at new Promise (<anonymous>)
    at loadLayerImg (D:\CV\generate-nfts-main\generate-nfts-main\src\main.js:193:10)
    at D:\CV\generate-nfts-main\generate-nfts-main\src\main.js:374:31
    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@Bakhshi007 if you made some images with different software (i.e. gimp/photoshop) one of the editors might have corrupted some images.

**Comment by Bakhshi007** [comment]
@bolshoytoster 
Thanks you so much. 
issue is now solved.

**Comment by bolshoytoster** [comment]
@Bakhshi007 could you make a comment on #615 saying how you fixed this please.
