### ISSUE TITLE
Error Function Modul

### ISSUE THREAD

**Issue by Dr-SIRM** [HashLips/hashlips_art_engine#68]
I get this error. What do I need to solve this?

Error: Cannot find module '/Users/thomassouthon/Downloads/hashlips_art_engine-1.0.6_update/indext.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by Dr-SIRM** [comment]
<img width="701" alt="Screen Shot 2021-09-28 at 2 58 32 pm" src="https://user-images.githubusercontent.com/91543656/135091537-43c3ac71-c105-40bc-a62d-1205db543806.png">
