### ISSUE TITLE
NPM run generate

### ISSUE THREAD

**Issue by MohamedAmmarrrr** [HashLips/hashlips_art_engine#686]
Hello I was runnng the npm run generate command when it creates 5 or 6 images then says an error

**Comment by bolshoytoster** [comment]
@MohamedAmmarrrr could you copy/paste the full error here please

**Comment by VikasGoyal0806** [comment]
@bolshoytoster 

I am facing almost similar issue. I deleted the readymade layers and added my own layers and tried to generate the images. This is the below result:

PS D:\NFT_Project\Hashlips\hashlips_art_engine-1.1.2_patch_v5(1)> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

node:internal/fs/utils:344
    throw err;
    ^

Error: EEXIST: file already exists, mkdir 'D:\NFT_Project\Hashlips\hashlips_art_engine-1.1.2_patch_v5(1)/build'
    at Object.mkdirSync (node:fs:1336:3)
    at buildSetup (D:\NFT_Project\Hashlips\hashlips_art_engine-1.1.2_patch_v5(1)\src\main.js:40:6)
    at D:\NFT_Project\Hashlips\hashlips_art_engine-1.1.2_patch_v5(1)\index.js:5:3
    at Object.<anonymous> (D:\NFT_Project\Hashlips\hashlips_art_engine-1.1.2_patch_v5(1)\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)      
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4075,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: 'D:\\NFT_Project\\Hashlips\\hashlips_art_engine-1.1.2_patch_v5(1)/build'
}

It seems that I already have a images folder. When I try to access the ..\build\images folder, it says it is inaccessible. The file or directory is corrupted and unreadable.

Please help

**Comment by bolshoytoster** [comment]
@VikasGoyal0806 you could try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by VikasGoyal0806** [comment]
@bolshoytoster 

Thanks! It worked. Above error did not come up. But when I proceeded, it gave below error:

PS D:\NFT_Project\Bolshoytoster\hashlips_art_engine-main> npm run generate

> hashlips_art_engine@1.1.1 generate
> node index.js

Edition exists!
Edition exists!
Edition exists!
Edition exists!
Edition exists!
D:\NFT_Project\Bolshoytoster\hashlips_art_engine-main\src\main.js:343
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
                                                                ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at D:\NFT_Project\Bolshoytoster\hashlips_art_engine-main\src\main.js:343:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (D:\NFT_Project\Bolshoytoster\hashlips_art_engine-main\src\main.js:343:31)
    at D:\NFT_Project\Bolshoytoster\hashlips_art_engine-main\src\main.js:460:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)   
    at async startCreating (D:\NFT_Project\Bolshoytoster\hashlips_art_engine-main\src\main.js:428:7)

**Comment by bolshoytoster** [comment]
@VikasGoyal0806 strange, that code doesn't exist in my repo. Could you try downloading it again?
