### ISSUE TITLE
SyntaxError: missing ) after argument list 

### ISSUE THREAD

**Issue by larryj52** [HashLips/hashlips_art_engine#698]
What does this mean?

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/index.js:2:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

**Comment by bolshoytoster** [comment]
@larryj52 there is a syntax error in `src/main.js`, what have you changed?

**Comment by larryj52** [comment]
I just followed the instructions given on https://www.youtube.com/watch?v=AaCgydeMu64&t=1760s

**Comment by bolshoytoster** [comment]
@larryj52 could you paste the bit(s) you changed. (if you have git installed you can run `git diff`).

**Comment by larryj52** [comment]
const addMetadata = (_dna, _edition) => {
  let dateTime = Date.now();
  let tempMetadata = {
    name: `${namePrefix} #${_edition}`,
    description: description,
    file_url: `${baseUri}/${_edition}.png`,
    custom_fields:{
      dna: sha1(_dna),
      edition: _edition,
      date: dateTime,
      compiler: "HashLips Art Engine",
    },

**Comment by larryj52** [comment]
const saveMetaDataSingleFile = (_editionCount) => {
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
  debugLogs

**Comment by bolshoytoster** [comment]
@larryj52 the error should say what line the syntax error is on, it's just before the bit you pasted. Could you send the full error please.

**Comment by larryj52** [comment]
Terminal Message:
> hashlips_art_engine@1.1.1 generate
> node index.js

/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:184
    const image = await loadImage(`${_layer.selectedElement.fs.rm(path,{ recursive: true }},`);
                                                                                         ^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/index.js:2:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

**Comment by bolshoytoster** [comment]
@larryj52 can you send the lines around line 184 please.

**Comment by larryj52** [comment]
Problems tab Message:
',' expected. ts(1005) [184, 91]

**Comment by larryj52** [comment]
182 - 187

const loadLayerImg = async (_layer) => {
  return new Promise(async (resolve) => {
    const image = await loadImage(`${_layer.selectedElement.fs.rm(path,{ recursive: true }}`);
    resolve({ layer: _layer, loadedImage: image });
  });
};

**Comment by bolshoytoster** [comment]
@larryj52 you're missing a `)` near the end of the line. Change ```...true }}`);``` to ```...true })}`);```.

**Comment by larryj52** [comment]
Problem code went away.  Going to try to run again.  Stand by.

**Comment by larryj52** [comment]
New TypeError:
TypeError: Cannot read properties of undefined (reading 'rm')
    at /Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:184:64
    at new Promise (<anonymous>)
    at loadLayerImg (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:183:10)
    at /Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:364:31
    at Array.forEach (<anonymous>)
    at startCreating (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/src/main.js:363:17)
    at /Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/index.js:6:3
    at Object.<anonymous> (/Users/raad_1/Downloads/hashlips_art_engine-1.1.1_update/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)

**Comment by bolshoytoster** [comment]
@larryj52 `_layer.selectedElement.fs` is undefined. Where did you add something like `fs: `?

**Comment by larryj52** [comment]
I don't recall adding anything like that.

**Comment by bolshoytoster** [comment]
@larryj52 you were probably meant to then.

**Comment by larryj52** [comment]
Where should that go?  What line?

**Comment by bolshoytoster** [comment]
@larryj52 it should say in the video.

**Comment by larryj52** [comment]
I see "selectedElement. fs.rm(path,{...." on line 184

**Comment by bolshoytoster** [comment]
@larryj52 it'll be somewhere near line 100.

**Comment by bolshoytoster** [comment]
@larryj52 
> I see "selectedElement. fs.rm(path,{...." on line 184

That's where the error is coming from.

**Comment by larryj52** [comment]
This is in the main.js  The video changes the main in the places I pasted earlier and then if changes the config.js

**Comment by larryj52** [comment]
Does fs. mean folder structure?

**Comment by bolshoytoster** [comment]
@larryj52 I have no idea. I'd recommend just using the base repo without making modifications, because it actually gets maintained.

**Comment by larryj52** [comment]
I am not experienced enough to modify beyond the instructions.

**Comment by bolshoytoster** [comment]
@larryj52 just delete what you've done and start over without changing what the video said to change.

**Comment by larryj52** [comment]
I agree. That makes sense
