### ISSUE TITLE
Syntax error: unexpected token 

### ISSUE THREAD

**Issue by Inquisitive-Learner** [HashLips/hashlips_art_engine#707]
...path/src/main.js:94
      layerObj.options?.["displayName"] != undefined
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (B:\Personal CL PI\NFT\program\hashlips_art_engine-main\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

**Comment by d49976110** [comment]
you could see here:
