### ISSUE TITLE
(node:11004) UnhandledPromiseRejectionWarning: Error: out of memory

### ISSUE THREAD

**Issue by sujeewakabeysinghe** [HashLips/hashlips_art_engine#708]
When I tried to generate more than 10K images + Gifs together, I get the heap out or out of memory issue,
But I tried compile this with this command by increasing the allocated memory like this,
`export NODE_OPTIONS=--max_old_space_size=204800`
Still it crash in the middle of the generation.
Any solution?
![error](https://user-images.githubusercontent.com/36567954/153258380-eaaf5b6a-ff6f-4333-ba99-839a98e1b291.PNG)

Thank you!

**Comment by bolshoytoster** [comment]
@sujeewakabeysinghe could you post a screenshot of task manager (`ctrl` + `shift` + `esc`)  when you run into these errors please.

**Comment by sujeewakabeysinghe** [comment]
Thank you for responding.
Sure, I will.
Do you know the minimum PC requirement for running this app?
Because It holds the Gif preview until the generation process finishes or crashes.
While it generates I couldn't check them, I mean cannot preview it.

**Comment by bolshoytoster** [comment]
@sujeewakabeysinghe I believe that's meant to happen. Although there is room for optimisation.

**Comment by bolshoytoster** [comment]
@sujeewakabeysinghe after some investigation it looks like there might be a memory leak somewhere. I'll keep looking.

**Comment by bolshoytoster** [comment]
It looks like the issue is caused by the `loadedElements` variable not being GCd after each loop. We could empty it ourselves instead.

**Comment by sujeewakabeysinghe** [comment]
Thank you,
BTW I could generate 20K images with no issues,
Yes, there's something with GIFs generation.

**Comment by khyyle** [comment]
@bolshoytoster i have the same issue.
i am quite new to coding and have no idea what you mean by "GCing loadedElements"
i have installed the latest version of visual studio code, i have v1.1.2 hashlips art engine, v16.14.15 node package manager, and node v14.18.1
i have been able to successfully generate 4 nfts before i get the UnhandledPromiseRejectionWarning error. 
how can i solve this specifically?

**Comment by bolshoytoster** [comment]
@khyyle
The GC is the 'Garbage Collector', it's meant to free memory when it's not needed. `loadedElements` is the variable that isn't being freed after each generation (it's meant to be).

The best solution would probably be to cache every image so they aren't loaded separately each time they're used.

But if it occurs after 4 nfts, it's probably a different error (or you have very little memory). Can you paste the full error here please.

**Comment by khyyle** [comment]
@bolshoytoster appreciate the response! (sorry about my late response)
heres what happened when i did `npm run generate`

`> hashlips_art_engine@1.1.1 generate Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main
> node index.js

Created edition: 1, with DNA: 20549220df7f53bc8c1bdf10e1c0aa29a6ded3e2
Created edition: 2, with DNA: f988efcfd1fca1727f5f4f9aa52864cfb8da24c9
Created edition: 3, with DNA: 0df34eb825978535d30a0a80ea26a35056aed82c
Created edition: 4, with DNA: fd9e19571609c874ecaeba6b92a9e72c48a41398
(node:5344) UnhandledPromiseRejectionWarning: Error: Unsupported image type
    at setSource (Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\src\main.js:185:27
    at loadLayerImg (Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\src\main.js:184:12)
    at Z:\Users\kyleberkson\Downloads\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by khyyle** [comment]
@bolshoytoster huh all of my images are .png files

**Comment by bolshoytoster** [comment]
@khyyle yeah, there's something weird about the library we use to load images. The issue I linked might help you to fix it.

**Comment by khyyle** [comment]
@bolshoytoster k thx appreciate it

**Comment by bolshoytoster** [comment]
@khyyle Id you're on Mac there might be `.DS_STORE` files messing it up. In which case you could run `find . -name ".DS_Store" -delete` to delete them.

**Comment by khyyle** [comment]
@bolshoytoster im on a mac and using windows parallels. i did notice a .DS_STORE a few days ago but i deleted it immediately.  I ran the command and it appears there are no .DS_Store files

**Comment by ymc182** [comment]
I also found that if you use terminal inside code editor eg. vs code, this problem occur, but no problem in window terminal

**Comment by sleiman88** [comment]
> 

Can you add a code how to do that Please ?

**Comment by ymc182** [comment]
if you using terminal inside VS Code and having this issue, try running the build command from external terminal like powershell or windows terminal

**Comment by sleiman88** [comment]
> if you using terminal inside VS Code and having this issue, try running the build command from external terminal like powershell or windows terminal

You are a savior. Thanks a lot .Problem solved using window terminal

**Comment by DevMarc16** [comment]
Ive generated many other collections before and now im getting this error and cant finish a collection, ive also tried to run from the windows terminal.  please help lol
Error: out of memory
    at Image.<anonymous> (<anonymous>)
    at setSource (C:\Users\lagom\hash art engine\hashlips_art_engine\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\lagom\hash art engine\hashlips_art_engine\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\lagom\hash art engine\hashlips_art_engine\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\lagom\hash art engine\hashlips_art_engine\node_modules\canvas\index.js:23:10)
    at C:\Users\lagom\hash art engine\hashlips_art_engine\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\lagom\hash art engine\hashlips_art_engine\src\main.js:184:12)
    at C:\Users\lagom\hash art engine\hashlips_art_engine\src\main.js:368:31

**Comment by bolshoytoster** [comment]
@DDev16 you could try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine), it splits the work between a few processes so it might avoid this error.
