### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'program')

### ISSUE THREAD

**Issue by frasil1** [HashLips/hashlips_art_engine#713]
**Hello, there is an error while verifying the collection. I can't figure out what the problem is. Please help me solve this problem or has anyone else had this problem?**
C:\Users\bugae\Stone\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:386
      new PublicKey(cacheContent.program.candyMachine),
                                 ^
TypeError: Cannot read properties of undefined (reading 'program')
    at Command.<anonymous> (C:\Users\bugae\Stone\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:386:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
![image](https://user-images.githubusercontent.com/96686007/153296324-abfeab11-7969-4439-bac8-bac51946cba4.png)

**Comment by bolshoytoster** [comment]
@frasil1 I think you've posted the issue in the wrong place, it should be [here](https://github.com/metaplex-foundation/metaplex/issues).

**Comment by frasil1** [comment]
ok

**Comment by gforcexx** [comment]
> **Hello, there is an error while verifying the collection. I can't figure out what the problem is. Please help me solve this problem or has anyone else had this problem?** C:\Users\bugae\Stone\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:386 new PublicKey(cacheContent.program.candyMachine), ^ TypeError: Cannot read properties of undefined (reading 'program') at Command. (C:\Users\bugae\Stone\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:386:34) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> ![image](https://user-images.githubusercontent.com/96686007/153296324-abfeab11-7969-4439-bac8-bac51946cba4.png)

did you fix this?

**Comment by bolshoytoster** [comment]
@gforcexx assuming you're actually using hashlips, you can try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) instead.
