### ISSUE TITLE
issue on node index.js

### ISSUE THREAD

**Issue by phelamm** [HashLips/hashlips_art_engine#718]
C:\Users\xxx\code\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\andyt\Pictures\NFT\code\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by phelamm** [comment]
thank you so much! its working after reading a couple of issues here

**Comment by N-Z-R** [comment]
Hi @bolshoytoster ! Yesterday I faced the same error (_SyntaxError: Unexpected token ._) after I downgraded Node to v10.18.0. Please advice.
@phelamm could you please share your solution?

**Comment by bolshoytoster** [comment]
@N-Z-R It's because node 10 doesn't support this.

**Comment by phelamm** [comment]
He's right, I was using node 10.18 too as the description said, then I upgraded to the most recent version, and I got the problem as I mentioned in the 3rd comment. So I tried a number of methods.

1. I tried to uninstall and install node 16 again 
2. I installed "visual studio setup" as it was mentioned in another issue, chose the "C++" option
3. I saved the file with the amendment I made in src -->config.js

I am not an expert but these are the things I tried, and it started generating. Not sure they're the correct steps to do so though
