### ISSUE TITLE
npm run generate not working. 

### ISSUE THREAD

**Issue by vishwapb** [HashLips/hashlips_art_engine#722]
Hi,
I am trying to create a collection. And getting the following text when trying to run _npm run generate_ I have no coding knowledge so i dont understand what am i supposed to do.
Thank you in advance.

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:1908) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update/layers/Background/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:73:6)
    at E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:87:30)
    at startCreating (E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\src\main.js:349:20)
    at E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\index.js:6:3 
    at Object.<anonymous> (E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\hashlips_art_engine-1.1.1_update\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'E:\\Crypto\\Hashlips\\hashlips_art_engine-1.1.1_update\\hashlips_art_engine-1.1.1_update/layers/Background/'

**Comment by bolshoytoster** [comment]
@vishwapb it can't find the `layers/Background/` folder. Make sure your layer folder names match with the layer names in `src/config.js` (case sensitive as well).

**Comment by vishwapb** [comment]
> @vishwapb it can't find the `layers/Background/` folder. Make sure your layer folder names match with the layer names in `src/config.js` (case sensitive as well).

Thanks mate. The name was different. An extra S. Phew.

**Comment by Chroniccoding** [comment]
Hi I am also trying to create a NFT collection in the Visual Studio Code Terminal and keep getting this error

Error: Cannot find module 'C:\Users\Owner\Documents\create-10k-nft-collection-2.0.0/node_modules/sha1'
Require stack:
- C:\Users\Owner\Documents\create-10k-nft-collection-2.0.0\src\main.js
- C:\Users\Owner\Documents\create-10k-nft-collection-2.0.0\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Owner\Documents\create-10k-nft-collection-2.0.0\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Owner\\Documents\\create-10k-nft-collection-2.0.0\\src\\main.js',
    'C:\\Users\\Owner\\Documents\\create-10k-nft-collection-2.0.0\\index.js'
  ]

Can any one help me out?

**Comment by bolshoytoster** [comment]
@Chroniccoding run `npm install`.

**Comment by Chroniccoding** [comment]
Thanks. I tried that with the package name and this is the error i got 

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/10k-collection-video - Not found
npm ERR! 404
npm ERR! 404  '10k-collection-video@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by bolshoytoster** [comment]
@Chroniccoding I believe this is an issue with [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection/issues), if you're using it can you please open an issue there.
