### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by ErenACR** [HashLips/hashlips_art_engine#735]
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
rect and try again.
At line:1 char:1
+ node index.js
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
![2022-02-13 (2)](https://user-images.githubusercontent.com/88158555/153728859-6a41a041-2cfd-4665-918b-87c25f8a0346.png)

**Comment by chypchrome** [comment]
I'm pretty sure this just means you don't have node installed. Can you try running `node --version` in your terminal and see what comes up?

**Comment by ErenACR** [comment]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update/node_modules/sha1'
Require stack:
- C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update\src\main.js
- C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update\src\main.js:4:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\90546\\OneDrive\\Masaüstü\\hashlips_art_engine-1.1.1_update\\src\\main.js',
    'C:\\Users\\90546\\OneDrive\\Masaüstü\\hashlips_art_engine-1.1.1_update\\index.js'
now what should ı do

**Comment by ErenACR** [comment]
> I'm pretty sure this just means you don't have node installed. Can you try running `node --version` in your terminal and see what comes up?

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update/node_modules/sha1'
Require stack:
- C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update\src\main.js
- C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\Users\90546\OneDrive\Masaüstü\hashlips_art_engine-1.1.1_update\src\main.js:4:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\90546\\OneDrive\\Masaüstü\\hashlips_art_engine-1.1.1_update\\src\\main.js',
    'C:\\Users\\90546\\OneDrive\\Masaüstü\\hashlips_art_engine-1.1.1_update\\index.js'
 now what should ı do
