### ISSUE TITLE
no such file or directory...

### ISSUE THREAD

**Issue by trisznft** [HashLips/hashlips_art_engine#740]
Hi my files exist and put everything well in config so i don't know what happened... 
Heres The whole error:

Error: ENOENT, No such file or directory 'C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main/layers/background/dawn#100.png'
    at setSource (C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\node_modules\canvas\index.js:23:10)
    at drawLayer (C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\src\main.js:117:25)
    at C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\src\main.js:136:12
    at Array.forEach (<anonymous>)
    at createFiles (C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\src\main.js:135:17)
    at C:\Users\trisztan\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\Asztal\generative-art-node-main\index.js:8:3 {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\trisztan\\OneDrive - Kormányzati Informatikai Fejlesztési Ügynökség\\Asztal\\generative-art-node-main/layers/background/dawn#100.png',
  syscall: 'fopen'

**Comment by bolshoytoster** [comment]
@trisznft this can be because you're doing it in the `OneDrive` folder.

**Comment by trisznft** [comment]
@bolshoytoster thanks, may i ask you for help again if it still does not work?

**Comment by trisznft** [comment]
@bolshoytoster it worked thank you very much bro

**Comment by Tanjilh** [comment]
hello, i have the same issue. how do i get out of the onedrive folder?

**Comment by Tanjilh** [comment]
thank you so much ! i will try that

**Comment by bolshoytoster** [comment]
@trisznft @Tanjilh you don't hve to uninstall onedrive, you can just move the hashlips folder out of the onedrive folder.
