### ISSUE TITLE
 layerObj.options?.["displayName"] != undefined

### ISSUE THREAD

**Issue by NINJAind** [HashLips/hashlips_art_engine#745]
C:\Users\Public\Downloads\hashlips_art_engine-main\hashlips_art_engine-main>node index.js
C:\Users\Public\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Public\Downloads\hashlips_art_engine-main\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by bolshoytoster** [comment]
@NINJAind update node

**Comment by Lust7373** [comment]
Hello! I am encountering the same issue. Updating the node did not work for me :( 
Any ideas?

**Comment by bolshoytoster** [comment]
@Lust7373 the most recent nore version is 17. You can't have updated it much.

**Comment by Lust7373** [comment]
> @Lust7373 the most recent nore version is 17. You can't have updated it much.

Thanks man. I have managed to solve the issue in the end and generated images with the script by taking a few looks in other issues posted by people. All good now :) 

PS: managed to make it work with the setup I mentioned above ( node 10.18.0 )

**Comment by sigmagirl** [comment]
i am having the same issue. Can you please share what you did to make it work?

**Comment by bolshoytoster** [comment]
@sigmagirl you can either upgrade node or use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
