### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by vishwapb** [HashLips/hashlips_art_engine#751]
Hi all,
I am facing this error while running 'npm run generate'. I have no knowledge of coding so please excuse me if it is something stupid i am doing. ;-)

SyntaxError: Unexpected token '}'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\Crypto\Hashlips\hashlips_art_engine-1.1.1_update\src\main.js:24:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

**Comment by nelso0** [comment]
same

**Comment by vishwapb** [comment]
Fixed it. Just downloaded the latest version hashlips art engine. Try that.

**Comment by bolshoytoster** [comment]
@nelso0 @vishwapb
The actual reason was because you just need to run `yarn`/`npm` `install`.

**Comment by Jis-4** [comment]
> Fixed it. Just downloaded the latest version hashlips art engine. Try that.

hi how you have fixed the error

**Comment by vishwapb** [comment]
> > Fixed it. Just downloaded the latest version hashlips art engine. Try that.
> 
> hi how you have fixed the error

I had V1.1.1. I just removed everything from this version, downloaded 1.1.2 and voilà, everything works fine.

**Comment by vishwapb** [comment]
> @nelso0 @vishwapb The actual reason was because you just need to run `yarn`/`npm` `install`.

👍🏼👍🏼

**Comment by pratham-abc** [comment]
@vishwapb how do I do this

> > > Fixed it. Just downloaded the latest version hashlips art engine. Try that.
> > 
> > 
> > hi how you have fixed the error
> 
> I had V1.1.1. I just removed everything from this version, downloaded 1.1.2 and voilà, everything works fine.

**Comment by bolshoytoster** [comment]
@pratham-abc If you have the same error, you should be able to fix it by just running `yarn`/`npm` `install`.

**Comment by pratham-abc** [comment]
> @pratham-abc If you have the same error, you should be able to fix it by just running `yarn`/`npm` `install`.

I tried but it still doesn't work

**Comment by bolshoytoster** [comment]
@pratham-abc What error do you get?

**Comment by pratham-abc** [comment]
> @pratham-abc What error do you get?

no such file or directory: yarn

**Comment by bolshoytoster** [comment]
@pratham-abc you don't have yarn installed, you can just run `npm install` and you don't need to install it.

**Comment by pratham-abc** [comment]
> > @pratham-abc What error do you get?
> > n
> 
> > @pratham-abc you don't have yarn installed, you can just run `npm install` and you don't need to install it.
> 
> yeah I did that but I can't run node index.js

ode:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/prathamvats/Dope-MetaTorts/hashlips_art_engine/node_modules/sha1'
Require stack:
- /Users/prathamvats/Dope-MetaTorts/hashlips_art_engine/src/main.js
- /Users/prathamvats/Dope-MetaTorts/hashlips_art_engine/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/prathamvats/Dope-MetaTorts/hashlips_art_engine/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/prathamvats/Dope-MetaTorts/hashlips_art_engine/src/main.js',
    '/Users/prathamvats/Dope-MetaTorts/hashlips_art_engine/index.js'
  ]
}


This is the error I'm getting for node index.js

**Comment by bolshoytoster** [comment]
@pratham-abc not with `-g`.

**Comment by pratham-abc** [comment]
> > @pratham-abc not with `-g`.
> 
> its showing EACCESS error

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code 1
npm ERR! path /Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/Users/prathamvats/.nvm/versions/node/v17.4.0/bin/node /Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@17.4.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@17.4.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/prathamvats/Library/Caches/node-gyp/17.4.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/prathamvats/Library/Caches/node-gyp/17.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/prathamvats/Library/Caches/node-gyp/17.4.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/Users/prathamvats/.nvm/versions/node/v17.4.0/bin/node" "/Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
npm ERR! gyp ERR! cwd /Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/prathamvats/.nvm/versions/node/v17.4.0/bin/node /Users/prathamvats/.nvm/versions/node/v17.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.6.0
npm ERR! node-pre-gyp ERR! command "/Users/prathamvats/.nvm/versions/node/v17.4.0/bin/node" "/Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/prathamvats/DopeMetaTorts/hashlips_art_engine/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v17.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prathamvats/.npm/_logs/2022-02-16T16_49_19_775Z-debug-0.log


This is the error I'm getting after npm install

**Comment by bolshoytoster** [comment]
@pratham-abc this is a known issue with M1 macs, as [this comment](https://github.com/HashLips/hashlips_art_engine/issues/654#issuecomment-1034406728) suggests you should downgrade node to 14.19.0.
