### ISSUE TITLE
 node index.js is not working 

### ISSUE THREAD

**Issue by Jis-4** [HashLips/hashlips_art_engine#753]

**Comment by bolshoytoster** [comment]
@Jis-4 how is it not working?
If it gives an error can you paste it here please.

**Comment by GiraffeValley** [comment]
(node:14916) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main/layers/body/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:73:6)    at C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:90:30)
    at startCreating (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:356:20)
    at C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\minai\\OneDrive\\Pictures\\nft\\hashlips_art_engine-main/layers/body/'
}

> @Jis-4 how is it not working? If it gives an error can you paste it here please.

**Comment by bolshoytoster** [comment]
@GiraffeValley your layer names need to match the folder names exactly (case sensitive).

**Comment by GiraffeValley** [comment]
> I did everything more than once, and with other code not from Hashlips it always gives the same error

> @GiraffeValley your layer names need to match the folder names exactly (case sensitive).
