### ISSUE TITLE
Node index.js is not working, gives an error message

### ISSUE THREAD

**Issue by GiraffeValley** [HashLips/hashlips_art_engine#755]
(node:14916) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use node --trace-deprecation ... to show where the warning was created)
node:fs:1392
handleErrorFromBinding(ctx);
^

Error: ENOENT: no such file or directory, scandir 'C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main/layers/body/'
at Object.readdirSync (node:fs:1392:3)
at getElements (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:73:6) at C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:92:15
at Array.map ()
at layersSetup (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:90:30)
at startCreating (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\src\main.js:356:20)
at C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\index.js:6:3
at Object. (C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main\index.js:7:3)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
errno: -4058,
syscall: 'scandir',
code: 'ENOENT',
path: 'C:\Users\minai\OneDrive\Pictures\nft\hashlips_art_engine-main/layers/body/'
}

**Comment by WhyUBullyMeNFT** [comment]
Hello, I have the same problem. If you solved this please tell me how or if anybody knows what to do please educate me. Thanks

**Comment by bolshoytoster** [comment]
@WhyUBullyMeNFT you need to make sure your layer names match the folder names exactly (case-sensitive as well).

**Comment by smartconvergence** [comment]
﻿
리눅스라면 ...
[FOR LINUX]
you're in the wrong folder. Run ls -Directory to get the name and run cd + the name. Then run npm run generate.


윈도우즈 비주얼 스투디오 code 라면
폴더 경로가 문제가 있어서 발생된 것이다. index.js 파일이 있는 폴더 경로 'vs code' 프로젝트 경로를 열고 시작하면 된다.

[FOR WINDOWS]
There is a problem with the folder path. You can start by opening the 'vs code' project path to the folder path where the index.js file is located.

﻿

**Comment by bolshoytoster** [comment]
@smartconvergence the "[FOR LINUX]" part actually only works on windows.

Also your answer isn't related to this question.
