### ISSUE TITLE
Mac M1 issues?

### ISSUE THREAD

**Issue by ddcc3388** [HashLips/hashlips_art_engine#758]
Anyone with an M1 Mac managed to get past the npm install and npm run generate? I have installed node 14.19.0 but when I run npm install, it shows up with:

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:130:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at Conf.loadPrefix (/usr/local/lib/node_modules/npm/lib/config/load-prefix.js:46:24)
    at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)
    at Conf.emit (events.js:400:28)
    at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:338:27)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:314:25)
internal/bootstrap/switches/does_own_process_state.js:130
    cachedCwd = rawMethods.cwd();
                           ^

Error: EPERM: operation not permitted, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:130:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:183:30)
    at process.emit (events.js:400:28)
    at process._fatalException (internal/process/execution.js:167:25) {
  errno: -1,
  code: 'EPERM',
  syscall: 'uv_cwd'
}

Does anyone know what i can do?

**Comment by thepeanutgalleryandco** [comment]
I have seen other users getting it to work on 14.19.0.

You are welcome to try my repo as well - https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection

**Comment by ddcc3388** [comment]
> I have seen other users getting it to work on 14.19.0.
> 
> You are welcome to try my repo as well - https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection

Hey, thanks! Your repo does work on my m1 mac. Is your repo equivalent to Hashlip's latest file?
