### ISSUE TITLE
Erreur commande node index. js

### ISSUE THREAD

**Issue by AlexandreFrart** [HashLips/hashlips_art_engine#785]
Bonjour, après avoir entré node index. js pour générer ma collection il apparait ce message d'erreur, que dois-je faire svp ? 

PS E:\NFT\hashlips_art_engine-main> node index. js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'E:\NFT\hashlips_art_engine-main\index.'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.5.0
PS E:\NFT\hashlips_art_engine-main>

![Sans titre](https://user-images.githubusercontent.com/100128427/154998293-5f2fdd70-e380-4496-90e9-8f0a8324c2bf.png)

**Comment by AlexandreFrart** [comment]
D'accord ! Comment est-ce que je dois procéder ?

**Comment by bolshoytoster** [comment]
@AlexandreFrart si vous avez enregistré le fichier (ctrl + s), vous pouvez exécuter à nouveau `node index.js`.

**Comment by AlexandreFrart** [comment]
oui j'ai essayé à plusieurs reprise et j'ai de nouveau l'erreur suivante

PS E:\NFT\hashlips_art_engine-main> node index. js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'E:\NFT\hashlips_art_engine-main\index.'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.5.0
PS E:\NFT\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@AlexandreFrart débarrassez-vous de l'espace dans `index. js`.

**Comment by AlexandreFrart** [comment]
Merciiiiiiiiiiiiiiiiiiiiii !! J'ai réussis, c'est grâce à vous !

**Comment by zoliot25** [comment]
@bolshoytoster Bonjour j'ai le même problème que @AlexandreFrart mais je n'ai pas compris ''@AlexandreFrart débarrassez-vous de l'espace dans index. js.'' Merci d'avance

**Comment by bolshoytoster** [comment]
@zoliot25 Pouvez-vous coller l'erreur s'il vous plaît.

**Comment by zoliot25** [comment]
PS C:\Users\eliot\OneDrive\Bureau\nft> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\eliot\OneDrive\Bureau\nft\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by bolshoytoster** [comment]
@zoliot25 Vous êtes probablement dans le mauvais dossier, exécutez `Get-ChildItem -Directory` pour obtenir le nom, puis exécutez `cd ` + le nom pour le changer

**Comment by zoliot25** [comment]
non j'était dans le bon dossier et j'ai la même erreur

**Comment by bolshoytoster** [comment]
@zoliot25 could you paste the error again please.

**Comment by zoliot25** [comment]
S C:\Users\eliot\OneDrive\Bureau\nft> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\eliot\OneDrive\Bureau\nft\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\eliot\OneDrive\Bureau\nft>

**Comment by bolshoytoster** [comment]
@zoliot25 Vous êtes toujours dans le mauvais dossier, pourriez-vous exécuter `Get-ChildItem` et coller la sortie ici s'il vous plaît.

**Comment by zoliot25** [comment]
PS C:\Users\eliot\OneDrive\Bureau\nft> Get-ChildItem


    Répertoire : C:\Users\eliot\OneDrive\Bureau\nft


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/04/2022     20:28                hashlips_art_engine-main
-a----        10/04/2022     18:48             82 package-lock.json


PS C:\Users\eliot\OneDrive\Bureau\nft>

**Comment by bolshoytoster** [comment]
@zoliot25 Pourriez-vous courir `cd hashlips_art_engine-main`.

**Comment by zoliot25** [comment]
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main/node_modules/sha1'
Require stack:
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\index.js'
  ]
}
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@zoliot25 Pourriez-vous courir `npm install`.

**Comment by zoliot25** [comment]
@bolshoytoster la le npm install a marcher mais avant ca me mettait un erreur **error node erno -4058**

**Comment by zoliot25** [comment]
mais app le npm install j'ai la meme erreur qu'avant 



`PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main/node_modules/sha1'
Require stack:
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\index.js'
  ]
}
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> `

**Comment by bolshoytoster** [comment]
@zoliot25 Pourriez-vous courir `Remove-Item package-lock.json`.

**Comment by zoliot25** [comment]
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> Remove-Item package-lock.json
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main/node_modules/sha1'
Require stack:
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\index.js'
  ]
}
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@zoliot25 Pourriez-vous coller l'erreur complète à partir de `npm install`.

**Comment by zoliot25** [comment]
il n'y a pas d'erreur

**Comment by bolshoytoster** [comment]
@zoliot25 Ensuite, vous n'obtiendrez pas cette erreur de `npm install`.

**Comment by zoliot25** [comment]
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> npm install

up to date, audited 26 packages in 624ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@zoliot25 Quelle erreur donne `node index.js` maintenant?

**Comment by zoliot25** [comment]
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main> node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main/node_modules/sha1'
Require stack:
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js
- C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\src\\main.js',
    'C:\\Users\\eliot\\OneDrive\\Bureau\\nft\\hashlips_art_engine-main\\index.js'
  ]
}
PS C:\Users\eliot\OneDrive\Bureau\nft\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@zoliot25 Je ne suis pas sûr de ce qui ne va pas alors.

**Comment by Aizander** [comment]
Bonjour , quand je fais ma commande node index.js pour générer la collection de nft ce code d'erreur apparait : 
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)        
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
  
  
![image](https://user-images.githubusercontent.com/103539903/163065344-1b265ab2-68b3-46ef-82ff-bd6a34bdbeb8.png)

  
  Merci d'avance
