### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by anthonysilvar** [HashLips/hashlips_art_engine#791]
Please help me with a simple issue:
-In shortcut. I wanted to generate a couple of NFTs. I have all of my layers done and I followed step by step the exact process from the hashlips guy on youtube (how to create an NFT collection - ultimate guide). On the photo connected to this you can see that I'm using the default code that was on Github even with the same layers.
-I did the following: npm install -> node index.js and then some nonsense popped up (I tried so many different methods like npm update/deleting package-lock.json/saving before running/downloading the same old versions as the guy on the video and many others) 
-I am an absolute noob in coding. Please tell me what is the mistake that I'm doing, or just why it doesn't work.
-Thank you for any response :)
![2022-02-23 (1)](https://user-images.githubusercontent.com/100318136/155415294-019064e0-eb09-4d20-8aa7-376deed42aac.png)

**Comment by anthonysilvar** [comment]
> @anthonysilvar try saving the `src/config.js` file.

Doesn't work.

**Comment by bolshoytoster** [comment]
@anthonysilvar the error is because it looks for a layer called `Main` but can't find it. You could create an empty `layers/main` to satisfy it.

**Comment by anthonysilvar** [comment]
> @anthonysilvar the error is because it looks for a layer called `Main` but can't find it. You could create an empty `layers/main` to satisfy it.

-The screenshot is probably without saved layers. On the image below there is the right one (with saved config and layers, right layers, and installed npm).
-There you can also see that the code is looking for layer Black #1 and can not find it but it is clearly there.
![2022-02-24 (1)](https://user-images.githubusercontent.com/100318136/155533079-1bd7664c-6893-4fab-a262-65432932bfab.png)

**Comment by bolshoytoster** [comment]
@anthonysilvar sometimes there can be issues when you have the project in the `OneDrive` folder. Try moving it elsewhere.

**Comment by anthonysilvar** [comment]
Appreciate your help, but still nothing. Any other ideas? :/
![2022-02-24 (3)](https://user-images.githubusercontent.com/100318136/155596968-103873c0-37ed-4f0f-beaa-f38ce57de7f8.png)

**Comment by Thannatos1** [comment]
extracts in program file and tries to open the folder

**Comment by shelly001** [comment]
For windows, you should change / to \.



![image](https://user-images.githubusercontent.com/47731407/157854770-e952087f-eeec-4ea4-863a-2ae0a056f994.png)

**Comment by bolshoytoster** [comment]
@shelly001 it doesn’t matter.

**Comment by emrekacaar** [comment]
did you solve the problem

**Comment by bolshoytoster** [comment]
@emrekacaar can you paste your error please.

**Comment by emrekacaar** [comment]
hashlips_art_engine@1.1.1 generate
> node index.js

(node:5192) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6/layers\Background\Black#1.png'
    at setSource (C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at C:\Users\bkaca\OneDrive\Masaüstü\Solana_project\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\bkaca\\OneDrive\\Masaüstü\\Solana_project\\hashlips_art_engine-1.1.2_patch_v6/layers\\Background\\Black#1.png',
  syscall: 'fopen'

**Comment by bolshoytoster** [comment]
@emrekacaar can you move your project folder to somewhere like `C:/Users/Public` please.

**Comment by emrekacaar** [comment]
brooooooo thank you for helping me

**Comment by emrekacaar** [comment]
please contact me on instagram: kacaremre54
