### ISSUE TITLE
syntax error ????

### ISSUE THREAD

**Issue by chrisreymann** [HashLips/hashlips_art_engine#817]
i get this when i run terminal and have already tried uploading the files twice to a new file in visual studio code. 
what should i do next ???
Apples-Air:hashlips_art_engine-1.1.2_patch_v5 apple$ node index.js
/Users/apple/Downloads/hashlips_art_engine-1.1.2_patch_v5/src/main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Apples-Air:hashlips_art_engine-1.1.2_patch_v5 apple$

**Comment by bolshoytoster** [comment]
@chrisreymann upgrade node
