### ISSUE TITLE
Visual Studio Code errno: -4058,

### ISSUE THREAD

**Issue by TheGODMasterDu** [HashLips/hashlips_art_engine#836]
Got this error code while trying to finish up my NFT. What am I missing?
![Error Code](https://user-images.githubusercontent.com/100662087/156105083-8359602e-a6d2-4ae0-aca7-563f19061ba7.jpg)

**Comment by bolshoytoster** [comment]
@TheGODMasterDu you need to save the `src/config.js` file (`ctrl` + `s`).

**Comment by TheGODMasterDu** [comment]
> @TheGODMasterDu you need to save the `src/config.js` file (`ctrl` + `s`).

Do you mean I have to just hit ctrl + s or do I have to do something with the src/config.js file?

**Comment by Patrizi5** [comment]
what did you do to get it to work, because i click (ctrl + s) and irt still didn't work for me

**Comment by bolshoytoster** [comment]
@Patrizi5 can you paste the error please.

**Comment by Patrizi5** [comment]
(node:18104) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\Patrick\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Patrick\\Desktop\\Masterclass\\hashlips_art_engine-1.1.2_patch_v6/layers/Background/'
}

**Comment by Patrizi5** [comment]
after i npm run generate

**Comment by bolshoytoster** [comment]
@Patrizi5 can you paste your `layerConfigurations` please and make sure you save the `src/config.js` file.

**Comment by Patrizi5** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/97971328/157905295-dee553f9-bebe-4123-91a7-bd758bdc77a3.png)

**Comment by bolshoytoster** [comment]
@Patrizi5 you spelled the folder name wrong.

`Backbround` should be `Background`.

**Comment by Patrizi5** [comment]
🤣😂 im stupid. thank you for helping

**Comment by Patrizi5** [comment]
why does it look weird?

**Comment by bolshoytoster** [comment]
@Patrizi5 could you post an example?
