### ISSUE TITLE
Help me with some err

### ISSUE THREAD

**Issue by sanokkk** [HashLips/hashlips_art_engine#837]
Guys hi im trying to repeat your actions in this tutorial: https://www.youtube.com/watch?v=fzH7Gjadmj0 but i have some troubles
I have installed node.js latest version and used command npm install
Then i added my layers and used node index.js but then there were these err
(node:852) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5/layers/Eyeball/'
    at Object.readdirSync (fs.js:1047:3)
    at getElements (C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:73:6)
    at C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:90:30)
    at startCreating (C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5\src\main.js:356:20)
    at C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js:6:3
    at Object.<anonymous> (C:\Users\Александр\Desktop\hashlips_art_engine-1.1.2_patch_v5\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bolshoytoster** [comment]
@sanokkk make sure your layer names match your folder names exactly (case sensitive as well). Also make sure you save the `src/config.js` file.

**Comment by sanokkk** [comment]
@bolshoytoster i just tried with basic layers in art engine repo so i dont have to change folders names. And again i get err
PS C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5> node index.js
(node:11656) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5/layers/Background/Black#1.png'
    at setSource (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:23:10)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:184:12)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:368:31
    at Array.forEach (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:11656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11656) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5/layers/Eyeball/White#50.png'
    at setSource (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:23:10)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:184:12)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:368:31
    at Array.forEach (<anonymous>)
(node:11656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:11656) UnhandledPromiseRejectionWarning: Error: ENOENT, No such file or directory 'C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5/layers/Eye color/Yellow#10.png'
    at setSource (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\node_modules\canvas\index.js:23:10)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:184:12)
    at C:\Users\Александр\Documents\hashlips_art_engine-1.1.2_patch_v5\src\main.js:368:31
    at Array.forEach (<anonymous>)...(not all err code)

**Comment by Alexandriaaaaa** [comment]
I also suffered from this problem at first.
I found an article that the latest node.js is not compatible, so I downloaded node v14.18.1 and tried it and it worked.

**Comment by pratham-abc** [comment]
I am encountering same error and downgraded node too but its still not working

**Comment by bolshoytoster** [comment]
@pratham-abc can you paste the error please.
