### ISSUE TITLE
node utils/update_info.js does not work on Windows

### ISSUE THREAD

**Issue by AceDontCom213** [HashLips/hashlips_art_engine#853]
Keep getting this error few time have tried.

PS C:\Users\User\Downloads\Mar_2022\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5> node utils/update_info.js
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\User\Downloads\Mar_2022\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5/build/json/_metadata.json'    
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.<anonymous> (C:\Users\User\Downloads\Mar_2022\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5\utils\update_info.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\User\\Downloads\\Mar_2022\\hashlips_art_engine-1.1.2_patch_v5\\hashlips_art_engine-1.1.2_patch_v5/build/json/_metadata.json'
}
PS C:\Users\User\Downloads\Mar_2022\hashlips_art_engine-1.1.2_patch_v5\hashlips_art_engine-1.1.2_patch_v5>

**Comment by bolshoytoster** [comment]
@AceDontCom213 the `build/json/_metadata.json` file doesn’t exist. You have to let the generation finish for it to be generated.
