### ISSUE TITLE
"INVALID_ARG_TYPE" error when generating

### ISSUE THREAD

**Issue by Sats05** [HashLips/hashlips_art_engine#857]
Hello! whenever I try to npm run generate, It only generates 1 jpg, no json, and I get the following text. I have the latest node version (17.6.0) and I'm using hashlips engine vr 1.1.1

(node:13436)` [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined  
    at Object.writeFileSync (node:fs:2159:5)
    at saveMetaDataSingleFile (C:\hashlips_art_engine-1.1.1_update\src\main.js:312:6)
    at C:\hashlips_art_engine-1.1.1_update\src\main.js:401:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (C:\hashlips_art_engine-1.1.1_update\src\main.js:366:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Sats05** [comment]
I just updated Harshlips art engine to the newest version and retried and it worked, thanks.
