### ISSUE TITLE
Build final image is not show correct after place all layers in one layer folder

### ISSUE THREAD

**Issue by proraheelaslam** [HashLips/hashlips_art_engine#877]
Hi,

I have make each folder for every layer it is working fine and image is show correct. But when i want to place all layers in one folder then build final image is not show correct. How can show correct imager after set layers in single  folder. Here is example Art folder has layers 1,2,3,4,5 the image of these layers is not show correct. If we place these layers in own folder then it show correct. As Circle layers show correct image because it has layer in folders.

It is difficult for user if he has 50 layers and make each folder for each layer.

Please guide us.

![image](https://user-images.githubusercontent.com/11072516/156896351-f908ed7f-3fba-44f2-aa0e-f4cec17f3c2c.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam could you give an example of one of the wrong images?

**Comment by proraheelaslam** [comment]
@bolshoytoster Here is example in which first image is show correct if we add each layer in folder. But second image is not correct if we move all layers in one folder. You can see attachments last two images are not correct.

Thanks

1-
![image](https://user-images.githubusercontent.com/11072516/156913221-e82494be-09a8-4afa-906f-dce7a1d372d6.png)
2-

![image](https://user-images.githubusercontent.com/11072516/156913285-91b9b135-adbc-44ba-88b7-cbe4a6f582c6.png)

3- 

![image](https://user-images.githubusercontent.com/11072516/156913421-708b2d75-cbad-46fd-8386-1c4b299a20fc.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam could you paste your `layersOrder` please.

**Comment by proraheelaslam** [comment]
@bolshoytoster Here is layer order

```
const layerConfigurations = [
   {
    growEditionSizeTo: 1,
    layersOrder: [
        { name: "Web Animation/Q 1" },
        { name: "Web Animation/Q 2" },
        { name: "Web Animation/Q 3" },
        { name: "Web Animation/Q 4" },
        { name: "Web Animation/Q 5" },

      
    ],
  },

  {
    growEditionSizeTo: 2,
    layersOrder: [
        { name: "Art/A" },
        { name: "Art/B" },
        { name: "Art/C" },
        { name: "Art/D" },
        { name: "Art/E" },

      
    ],
  },
    {
    growEditionSizeTo: 3,
    layersOrder: [
        { name: "A/" },
       
    ],
  },


  {
    growEditionSizeTo: 4,
    layersOrder: [
        { name: "PI Trait/A" },
        { name: "PI Trait/B" },
        { name: "PI Trait/C" },
        { name: "PI Trait/D" },
        { name: "PI Trait/E" },
        { name: "PI Trait/F" },
        { name: "PI Trait/G" },

      
    ],
  },

  {
    // Creates an additional 100 artworks
    growEditionSizeTo: 5,
    layersOrder: [
        { name: "Circle/A" },
        { name: "Circle/B" },
        { name: "Circle/C" }      
    ],
  },
];

```

**Comment by bolshoytoster** [comment]
@proraheelaslam you can't have the layers in the same folder, hashlips wouldn't know order or anything.

**Comment by proraheelaslam** [comment]
@bolshoytoster Can we change the hashlips accept the layers in one folder as 
```
 layersOrder: [
        { name: "A/" },
       
    ],
```

**Comment by bolshoytoster** [comment]
@proraheelaslam no, because it wouldn't know what order to put the images in.

**Comment by proraheelaslam** [comment]
@bolshoytoster It is very difficult process for users if more than 20 layers. User change manually and make the folder for each layer.

**Comment by proraheelaslam** [comment]
@bolshoytoster I think It should read all layers in directory. For example folder 'A' has 5 layers. It should read 5 layers in one folder.

**Comment by proraheelaslam** [comment]
@bolshoytoster Have any solution for this ? Because designer generate 500 layers for different image. How can automate this process. User just paste the layers in layers directory and program automatically generate the images against the layer.
User will create layer likes this.
- Circle layer
- Rectangle Layer
- Animation
- PI
etc...


Thanks

**Comment by bolshoytoster** [comment]
@proraheelaslam I guess you could, at ~line 112 in `src/config.js`:
```js
const layersSetup = (layersOrder) => {
  const layers = layersOrder.map((layerObj, index) => ({
```
change it to:
```js
const layersSetup = (layersOrder) => {
  if (layersOrder.length == 1) {
    layersOrder = fs
      .readdirsync(`${layersDir}/${layersOrder[0].name}/`)
      .map(name => {
        return {
          ...layersOrder[0],
          name: name
        };
      });
  }
  const layers = layersOrder.map((layerObj, index) => ({
```
I haven't tested this but it might work. If I've understood you correctly.

**Comment by proraheelaslam** [comment]
@bolshoytoster This function exist in main.js can you paste complete function of `layersSetup`.
Thanks
![image](https://user-images.githubusercontent.com/11072516/156920612-88a35e5e-421d-422c-85a7-642c0401c70b.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam
```js
const layersSetup = (layersOrder) => {
  if (layersOrder.length == 1) {
    layersOrder = fs
      .readdirsync(`${layersDir}/${layersOrder[0].name}/`)
      .map(name => {
        return {
          ...layersOrder[0],
          name: name
        };
      });
  }
  const layers = layersOrder.map((layerObj, index) => ({
    id: index,
    elements: getElements(`${layersDir}/${layerObj.name}`),
    name:
      layerObj.options && layerObj.options["displayName"] != undefined
        ? layerObj.options && layerObj.options["displayName"]
        : layerObj.name,
    blend:
      layerObj.options && layerObj.options["blend"] != undefined
        ? layerObj.options && layerObj.options["blend"]
        : "source-over",
    opacity:
      layerObj.options && layerObj.options["opacity"] != undefined
        ? layerObj.options && layerObj.options["opacity"]
        : 1,
    bypassDNA:
      layerObj.options && layerObj.options["bypassDNA"] !== undefined
        ? layerObj.options && layerObj.options["bypassDNA"]
        : false,
  }));
  return layers;
};
```
And in the function above, `getElements`:
```js
const getElements = (path) => {
  if (!fs.existsSync(path)) {
     console.error(`{path} doesn't exist, make sure your layers/ folder matches your src/config.js`);
     process.exit();
  }
  if (fs.lstatSync(path).isDirectory()) {
    return fs
      .readdirSync(path)
      .filter((item) => !/(^|\/)\.[^\/\.]/g.test(item))
      .map((i, index) => {
        if (i.includes(DNA_DELIMITER)) {
          console.error(`layer name can not contain DNA_DELIMITER (${DNA_DELIMITER}), please fix: ${i}`);
          process.exit();
        }
        if (i.includes("\n")) {
          console.error(`layer name can not contain newlines, please fix: ${i}`);
          process.exit();
        }
        return {
          id: index,
          name: cleanName(i),
          filename: i,
          path: `${path}${i}`,
          weight: getRarityWeight(i),
        };
      });
  } else {
    const filename = path.split('/').pop()
    return [{
      id: 0,
      name: cleanName(filename),
      filename: filename,
      path: path,
      weight: getRarityWeight(filename),
    }]
  }
};
```

**Comment by proraheelaslam** [comment]
@bolshoytoster The fs is include on top page but still this error of this `readdirsync `

```
> hashlips_art_engine@1.1.1 build E:\xampp\htdocs\hashlips_art_engine-main
> node index.js

[]
(node:12264) UnhandledPromiseRejectionWarning: TypeError: fs.readdirsync is not a function
    at layersSetup (E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:129:22)
    at startCreating (E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:432:20)
    at E:\xampp\htdocs\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (E:\xampp\htdocs\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/11072516/156921109-6efed00a-e772-4025-9083-57f0fe8b23be.png)
![image](https://user-images.githubusercontent.com/11072516/156921116-bbbc75e4-0c70-40c3-ba73-6729b6e75a4e.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam sorry, the 's' is meant to be uppercase: `readdirSync`.

**Comment by proraheelaslam** [comment]
@bolshoytoster The path is not read.

![image](https://user-images.githubusercontent.com/11072516/156921480-885e0fdd-afd0-400f-a0e0-259277a71390.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam at the top of `layersSetup`, change
```js
        return {
          ...layersOrder[0],
          name: name
        };
```
to
```js
        return {
          ...layersOrder[0],
          name: `${layersOrder[0].name}/${name}`
        };
```

**Comment by proraheelaslam** [comment]
@bolshoytoster  Got this.

```
> hashlips_art_engine@1.1.1 build E:\xampp\htdocs\hashlips_art_engine-main
> node index.js

[{"growEditionSizeTo":false,"layersOrder":[]}]
(node:5724) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:261:63
    at new Promise (<anonymous>)
    at loadLayerImg (E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:260:12)
    at E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:444:31
    at Array.forEach (<anonymous>)
    at startCreating (E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:443:17)
    at E:\xampp\htdocs\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (E:\xampp\htdocs\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/11072516/156922047-7950298f-5f07-472c-b4d1-83b6203322d0.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam at the end of `getElements`:
```js
    return [{
      id: 0,
      name: cleanName(filename),
```
you could try changing `id: 0` to `id: 1`.

**Comment by proraheelaslam** [comment]
@bolshoytoster In both cases `id:0 and id:1` still same thing

![image](https://user-images.githubusercontent.com/11072516/156922340-d64e995f-7348-4ad5-867c-5a97e8b54bbf.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam I recommend just doing it the normal way, having a folder for each layer.

**Comment by proraheelaslam** [comment]
@bolshoytoster Thank you for your effort and time. If you will find another solution then let you can know.

Thanks
