### ISSUE TITLE
'ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by djcol14** [HashLips/hashlips_art_engine#880]
ypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2148:5)
    at saveMetaDataSingleFile (C:\Users\decla\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:320:6)
    at C:\Users\decla\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:409:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (C:\Users\decla\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6\src\main.js:374:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}
PS C:\Users\decla\OneDrive\Desktop\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@djcol14 can you set `debugLogs` in `src/config.js` (~line 42) to true please.
