### ISSUE TITLE
npm i ERRORS

### ISSUE THREAD

**Issue by KeaganM27** [HashLips/hashlips_art_engine#884]
I'm trying to generate my NFT collection, but this error is showing up and I'm unsure how to resolve the issue.

Any suggestions?

*ATTACHED ARE THE VERSIONS OF NODEJS, VSCODE, AND HASHLIPS GENERATOR THAT I'M USING*
<img width="254" alt="Screen Shot 2022-03-06 at 7 17 30 AM" src="https://user-images.githubusercontent.com/97859483/156925041-e230c522-2f15-4b1b-b6e2-18b98409139c.png">

————————

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro-2:create-10k-nft-collection-1.2.0 keaganmouradian$ npm i
npm notice 
npm notice New patch version of npm available! 8.5.1 -> 8.5.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.3
npm notice Run npm install -g npm@8.5.3 to update!
npm notice 
npm ERR! code 1
npm ERR! path /Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@17.6.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@17.6.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.6.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.6.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v17.6.0/node-v17.6.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.6.0/node-v17.6.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v17.6.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v17.6.0/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/keaganmouradian/Library/Caches/node-gyp/17.6.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/keaganmouradian/Library/Caches/node-gyp/17.6.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/keaganmouradian/Library/Caches/node-gyp/17.6.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.2.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
npm ERR! gyp ERR! cwd /Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas
npm ERR! gyp ERR! node -v v17.6.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.2.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v17.6.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/keaganmouradian/.npm/_logs/2022-03-06T12_56_06_101Z-debug-0.log
MacBook-Pro-2:create-10k-nft-collection-1.2.0 keaganmouradian$ npm install -g
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../../../../Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0
npm ERR! dest /usr/local/lib/node_modules/10k-collection-video
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../../../../Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0' -> '/usr/local/lib/node_modules/10k-collection-video'
npm ERR!  [Error: EACCES: permission denied, symlink '../../../../Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0' -> '/usr/local/lib/node_modules/10k-collection-video'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../../../../Volumes/1STPHORM/Keagan/NFTs/Coding/create-10k-nft-collection-1.2.0',
npm ERR!   dest: '/usr/local/lib/node_modules/10k-collection-video'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/keaganmouradian/.npm/_logs/2022-03-06T13_00_32_977Z-debug-0.log
MacBook-Pro-2:create-10k-nft-collection-1.2.0 keaganmouradian$ npm install -g npm@8.5.3
npm ERR! code EACCES

npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/npm',
npm ERR!   dest: '/usr/local/lib/node_modules/.npm-i9nnxROI'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/keaganmouradian/.npm/_logs/2022-03-06T13_09_49_853Z-debug-0.log
MacBook-Pro-2:create-10k-nft-collection-1.2.0 keaganmouradian$

**Comment by bolshoytoster** [comment]
@KeaganM27 rhis is a well known issue with M1 macs. You should check some [other issues](https://github.com/HashLips/hashlips_art_engine/issues?q=is%3Aissue+M1) for potential solutions.

**Comment by KeaganM27** [comment]
Thank you 🤘 I will check it out now
