### ISSUE TITLE
The layer name doesn't accept without dash file name. 

### ISSUE THREAD

**Issue by proraheelaslam** [HashLips/hashlips_art_engine#886]
Hi,

We have to set all layer file name with hash(#). But when we removed the hash from layer file name then image does not build. We have tried to change this script `const rarityDelimiter = " ";` It does not work. 
Actually We do not want to restrict the user to add the hash(#) in file name. It can be any name of file layer.

Thanks

![image](https://user-images.githubusercontent.com/11072516/156927104-a680225f-0372-41ad-b174-2c7206e438ec.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam does it give an error when you try to build?

Also, who do you mean by 'the user'?

**Comment by bolshoytoster** [comment]
@proraheelaslam does it give an error when you try to build?

Also, who do you mean by 'the user'?

**Comment by proraheelaslam** [comment]
@bolshoytoster It gives below error.
User mean any person (designer) who will use the system.
```
(node:11708) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:261:63
    at new Promise (<anonymous>)
    at loadLayerImg (E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:260:12)
    at E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:444:31
    at Array.forEach (<anonymous>)
    at startCreating (E:\xampp\htdocs\hashlips_art_engine-main\src\main.js:443:17)
    at E:\xampp\htdocs\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (E:\xampp\htdocs\hashlips_art_engine-main\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/11072516/156929139-2d9423e6-64d9-4edc-a279-fe3e19853262.png)

**Comment by bolshoytoster** [comment]
@proraheelaslam if you change the `rarityDelimeter` to `" "` you have to change all of the element names accordingly (i.e. `name#1.png` => `name 1.png`)

**Comment by proraheelaslam** [comment]
@bolshoytoster The layer file could have any name. It should accept all name. It should not depend on format.

**Comment by designoor** [comment]
@proraheelaslam this config option gives you the pssibility to set it however you want.
