### ISSUE TITLE
Making at least 2 or 3 different layers

### ISSUE THREAD

**Issue by codehakan** [HashLips/hashlips_art_engine#889]
Hello,

I have 12 layers. Production is provided even with only 1 change in the default settings. But I want to change that. For example, I don't want everything to be the same in 12 layers and only the background to be different. In other words, I want production to occur when there are at least 3 changes. Can anyone help on how I can do this?

**Comment by bolshoytoster** [comment]
@codehakan do you mean you don't want the images to be too similar?

**Comment by codehakan** [comment]
> @codehakan do you mean you don't want the images to be too similar?

@bolshoytoster Yes. For example, the only difference between the 200th produced NFT and the 201st produced NFT is only the background color. I don't want a single difference. I want it to be 2 or 3 differences. The difference between it and the previously produced picture should not be the only one. That is, in the 300th NFT, the eye color is blue, and in the 301st NFT, the eye color is green. I said the numbers 200 and 300 as an example.

**Comment by bolshoytoster** [comment]
@codehakan in `src/main.js` ~line 277:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L277-L280

You could replace that function with:
```js
const isDnaUnique = (_DnaList = new Set(), _dna = "") => {
  const MAX_OVERLAP = 8;
  const _filteredDNA = filterDNAOptions(_dna);
  return Array.from(_DnaList).find(
    x => x.split(DNA_DELIMITER).filter(
      y => _filteredDNA.split(DNA_DELIMITER).includes(y)
    ).length > MAX_OVERLAP
  ) == undefined;
};
```
Then change `MAX_OVERLAP` to be the max number of layers you want to be the same.

I haven't tested this and it's quite inefficient, but it might work.

**Comment by codehakan** [comment]
@bolshoytoster thanks. But im taking error.

(node:24012) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead

TypeError: _DnaList.find is not a function
at isDnaUnique (C:\Users\hakan\Desktop\hashlips_art_engine-main\src\main.js:286:14)
    at startCreating (C:\Users\hakan\Desktop\hashlips_art_engine-main\src\main.js:377:11)
    at C:\Users\hakan\Desktop\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\hakan\Desktop\hashlips_art_engine-main\index.js:7:3)

**Comment by bolshoytoster** [comment]
@codehakan if you add `console.log(_DnaList)` at the start of the function and run it again what does it say?

**Comment by codehakan** [comment]
@bolshoytoster 

Output: `Set(0) {}`

**Comment by bolshoytoster** [comment]
@codehakan I think you could change the line:
```js
  return _DnaList.find(
```
to
```js
  return _DnaList.values.find(
```

**Comment by codehakan** [comment]
@bolshoytoster 
![image](https://user-images.githubusercontent.com/36774186/157123377-b0887cd2-8944-46be-9b89-bc2da540f7d9.png)

**Comment by bolshoytoster** [comment]
@codehakan sorry, It's meant to be
```js
  return _DnaList.values().find(
```

**Comment by codehakan** [comment]
@bolshoytoster ☹️

![image](https://user-images.githubusercontent.com/36774186/157128840-342a3611-69bb-4be1-9afa-4d152bedede2.png)

**Comment by bolshoytoster** [comment]
@codehakan I've actually tested it this time:
```js
  return Array.from(_DnaList).find(
```

**Comment by codehakan** [comment]
@bolshoytoster yup, its working. 👍 But not generating NFT. Console log always saying "DNA exists!". 🤔

I tried change MAX_OVERLAP with 1,2,3,4,5,6,7. But nothing happened.

**Comment by bolshoytoster** [comment]
@codehakan how many layers do you have?

**Comment by codehakan** [comment]
@bolshoytoster i have 12 layers.

**Comment by bolshoytoster** [comment]
@codehakan set `MAX_OVERLAP` to 11 and decrease it until you grt whst you want.

**Comment by designoor** [comment]
@bolshoytoster thank you, works like a charm!
