### ISSUE TITLE
npm run generate / node index.js wats wrong ?

### ISSUE THREAD

**Issue by kasun19944** [HashLips/hashlips_art_engine#894]
> hashlips_art_engine@1.1.1 generate C:\Users\LENOVO\Downloads\hashlips_art_engine-main (1)\hashlips_art_engine-main
> node index.js

C:\Users\LENOVO\Downloads\hashlips_art_engine-main (1)\hashlips_art_engine-main\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\LENOVO\Downloads\hashlips_art_engine-main (1)\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hashlips_art_engine@1.1.1 generate: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashlips_art_engine@1.1.1 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LENOVO\AppData\Roaming\npm-cache\_logs\2022-03-07T06_10_39_183Z-debug.log
PS C:\Users\LENOVO\Downloads\hashlips_art_engine-main (1)\hashlips_art_engine-main>

**Comment by bolshoytoster** [comment]
@kasun19944 you need to update your node.js. If you don't want to, you could use [my fork](https://github.com/bolshoytoster/hashlips_art_engine) instead.

**Comment by kasun19944** [comment]
thanks @bolshoytoster

**Comment by kasun19944** [comment]
How to set the resolution of the image to 300pp @bolshoytoster

**Comment by bolshoytoster** [comment]
@kasun19944 in `src/config.js`, ~line 44:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/config.js#L44-L48

You can change `width` and `height` to the dimensions you want (in pixels).

**Comment by kasun19944** [comment]
Thank you
