### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jgreene88** [HashLips/hashlips_art_engine#9]
Hello,
I am trying to use the code, but I am getting this error. I did not get the error when I downloaded it, but when I tried to run it with my own layers I got the error.

Here is the console log:

`[Joshs-MacBook-Pro:hashlips_art_engine-main jgreene$ node index.js
(node:36554) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at cleanDna (/Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/src/main.js:44:25)
    at /Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/src/main.js:135:22
    at Array.find (<anonymous>)
    at /Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/src/main.js:134:42
    at Array.map (<anonymous>)
    at constructLayerToDna (/Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/src/main.js:133:35)
    at startCreating (/Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/src/main.js:196:23)
    at /Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/index.js:5:3
    at Object.<anonymous> (/Users/jgreene/Desktop/Home/Designs/NFT/CRYPTIC COMPUTER CLUB/hashlips_art_engine-main/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36554) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36554) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.](url)`

**Comment by HashLips** [comment]
Please make sure all your elements have a rarity weight
