### ISSUE TITLE
giving me this error

### ISSUE THREAD

**Issue by musobek253** [HashLips/hashlips_art_engine#913]
(node:21164) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0\src\main.js:73:6)
    at C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0\src\main.js:87:30)
    at startCreating (C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0\src\main.js:351:20)
    at C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0\index.js:6:3
    at Object.<anonymous> (C:\Users\muso_\Desktop\create-10k-nft-collection-1.2.0\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\muso_\\Desktop\\create-10k-nft-collection-1.2.0/layers/Background/'
}

**Comment by bolshoytoster** [comment]
@musobek253
1. make sure you save your `src/config.js`
2. make sure the layer names in there match the folder names exactly (case sensitive as well)

**Comment by musobek253** [comment]
not the mistake I saw

**Comment by CandyClanNFT** [comment]
I am also having issues with this.

Error: ENOENT: no such file or directory, scandir '/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:73:6)
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:90:30)
    at startCreating (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:359:20)
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/index.js:6:3
    at Object.<anonymous> (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/layers/Background/'

**Comment by CandyClanNFT** [comment]
new error

TypeError: Cannot read properties of undefined (reading 'edition')
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:31)
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:409:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:374:9)

**Comment by bolshoytoster** [comment]
@CandyClanNFT try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).
