### ISSUE TITLE
error Failed at the hashlips_art_engine@1.1.1 generate script

### ISSUE THREAD

**Issue by fbba75** [HashLips/hashlips_art_engine#921]
Hi hope you are all well.
I've tried to generate and I have this issue.
Thank you in advance for your help

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.10.0/bin/node',
1 verbose cli   '/usr/local/opt/node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'generate' ]
2 info using npm@6.14.5
3 info using node@v11.10.0
4 verbose run-script [ 'pregenerate', 'generate', 'postgenerate' ]
5 info lifecycle hashlips_art_engine@1.1.1~pregenerate: hashlips_art_engine@1.1.1
6 info lifecycle hashlips_art_engine@1.1.1~generate: hashlips_art_engine@1.1.1
7 verbose lifecycle hashlips_art_engine@1.1.1~generate: unsafe-perm in lifecycle true
8 verbose lifecycle hashlips_art_engine@1.1.1~generate: PATH: /usr/local/Cellar/node/11.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fouad/Documents/NFT/hashlips_art_engine-1.1.2_patch_v6/node_modules/.bin:/usr/local/opt/node/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/node/bin:/usr/local/share/android-sdk/tools:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/ndk-bundle:/usr/local/share/android-sdk/tools:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/ndk-bundle
9 verbose lifecycle hashlips_art_engine@1.1.1~generate: CWD: /Users/fouad/Documents/NFT/hashlips_art_engine-1.1.2_patch_v6
10 silly lifecycle hashlips_art_engine@1.1.1~generate: Args: [ '-c', 'node index.js' ]
11 silly lifecycle hashlips_art_engine@1.1.1~generate: Returned: code: 1  signal: null
12 info lifecycle hashlips_art_engine@1.1.1~generate: Failed to exec generate script
13 verbose stack Error: hashlips_art_engine@1.1.1 generate: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node/11.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node/11.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid hashlips_art_engine@1.1.1
15 verbose cwd /Users/fouad/Documents/NFT/hashlips_art_engine-1.1.2_patch_v6
16 verbose Darwin 21.1.0
17 verbose argv "/usr/local/Cellar/node/11.10.0/bin/node" "/usr/local/opt/node/bin/npm" "run" "generate"
18 verbose node v11.10.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error hashlips_art_engine@1.1.1 generate: `node index.js`
22 error Exit status 1
23 error Failed at the hashlips_art_engine@1.1.1 generate script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bolshoytoster** [comment]
@fbba75 can you run it with `node index.js` instead?

**Comment by fbba75** [comment]
Yes I already try it and same issue 
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)

I also tried to update npm / deleting node module but still not working

**Comment by bolshoytoster** [comment]
@fbba75 you need to either update your node or you could use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by redoxahmii** [comment]
> Yes I already try it and same issue layerObj.options?.["displayName"] != undefined ^
> 
> SyntaxError: Unexpected token . at new Script (vm.js:85:7) at createScript (vm.js:266:10) at Object.runInThisContext (vm.js:314:10) at Module._compile (internal/modules/cjs/loader.js:698:28) at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10) at Module.load (internal/modules/cjs/loader.js:630:32) at tryModuleLoad (internal/modules/cjs/loader.js:570:12) at Function.Module._load (internal/modules/cjs/loader.js:562:3) at Module.require (internal/modules/cjs/loader.js:667:17) at require (internal/modules/cjs/helpers.js:20:18)
> 
> I also tried to update npm / deleting node module but still not working

I have tried as well and i am having the same issue as well commenting in case if there is any solutions.

**Comment by bolshoytoster** [comment]
@Redoxahmii does [this](https://github.com/HashLips/hashlips_art_engine/issues/921#issuecomment-1063311584) comment help?

**Comment by redoxahmii** [comment]
> @Redoxahmii does [this](https://github.com/HashLips/hashlips_art_engine/issues/921#issuecomment-1063311584) comment help?

What i have gathered from this is that the Node version is causing issues i am currently installing the latest build of Node to see if it works with that or not.

**Comment by fbba75** [comment]
I already have the latest version of node 17.7.0 but it doesn't work

**Comment by bolshoytoster** [comment]
@fbba75 can you paste the output of `node -v` please.

**Comment by fbba75** [comment]
@bolshoytoster here it is : v11.10.0

**Comment by redoxahmii** [comment]
> @fbba75 can you paste the output of `node -v` please.

 node -v
v14.18.2

 node -v
v16.14.0

I have tried both of these atm and have the same error.

**Comment by bolshoytoster** [comment]
@fbba75 try uninstalling and reinstalling the latest node version.

@Redoxahmii you can try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by redoxahmii** [comment]
> @fbba75 try uninstalling and reinstalling the latest node version.
> 
> @Redoxahmii you can try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

It is working on your fork what changes did u make from the main repo?

**Comment by fbba75** [comment]
how can I uninstall it totally on MAC ?

**Comment by bolshoytoster** [comment]
@Redoxahmii [quite a bit actually](https://github.com/HashLips/hashlips_art_engine/pull/638/files). But for this issue, I [changed the syntax](https://github.com/HashLips/hashlips_art_engine/pull/638/files#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79L94-R114) to the old (pre node v14) style.

**Comment by bolshoytoster** [comment]
@fbba75 how did you install it? If it was from the website you'll have to (sort of) manually do it, [this tutorial](https://reactgo.com/uninstall-node-npm-from-macos/) goes through it.

**Comment by redoxahmii** [comment]
> @Redoxahmii [quite a bit actually](https://github.com/HashLips/hashlips_art_engine/pull/638/files). But for this issue, I [changed the syntax](https://github.com/HashLips/hashlips_art_engine/pull/638/files#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79L94-R114) to the old (pre node v14) style.

So the code was using syntax for the latest node version so you changed it to the old syntax of v14 which made it work again. Thank you nonetheless.

if the syntax is for the latest then it should have worked with the latest node ver but i guess the syntax issue is a bit more in depth than i understand.

**Comment by fbba75** [comment]
@bolshoytoster I uninstall and install it and it doesn't work

**Comment by bolshoytoster** [comment]
@fbba75 can you send the output of `node -v` please.

**Comment by fbba75** [comment]
macbook-pro-de-fouad:hashlips_art_engine-1.1.2_patch_v6 fouad$ node v
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '/Users/fouad/Documents/NFT/hashlips_art_engine-1.1.2_patch_v6/v'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

**Comment by bolshoytoster** [comment]
@fbba75 you forgot th '`-`'.

**Comment by fbba75** [comment]
sorry noob mistake :) 

v11.10.0

**Comment by bolshoytoster** [comment]
@fbba75 it's probably easier to just use [my fork](https://github.com/bolshoytoster/hashlips_art_engine).

**Comment by fbba75** [comment]
I think the issue is I can not uninstall node 
Someone can help me to unistall it because I dont have any node file in local or user or bin but I still can see node version with node -v command

**Comment by bolshoytoster** [comment]
@fbba75 if you use my fork you won't need to upgrade.

**Comment by redoxahmii** [comment]
> I think the issue is I can not uninstall node Someone can help me to unistall it because I dont have any node file in local or user or bin but I still can see node version with node -v command

i used NVM to switch versions which made to very easy to uninstall and use multiple versions at the same time and switch quickly.
Honestly one of the best tools i ever found for Node.

**Comment by redoxahmii** [comment]
> @fbba75 if you use my fork you won't need to upgrade.

One issue with your repo is that the update_info script does not work as it now has different syntax.

**Comment by bolshoytoster** [comment]
@Redoxahmii how does it not work? Does it throw an error?

**Comment by redoxahmii** [comment]
> throw

Sorry it was an issue on my end i deleted the _metadata.json that is created after npm run generate
With that file deleted when i ran it it did not work but now with the file there it works.

**Comment by fbba75** [comment]
thanks a lot guys 
with the help of @bolshoytoster that identified it was a node version issue now it worked !
FYI I also used which to find where node was installed and I had 3 files lost in opt 
So I delete them and reinstalled the last version and now it's ok
