### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by mkenyon1984** [HashLips/hashlips_art_engine#922]
Hi 
I have just downloaded 1.0.8 to create some solana nfts but now I get this error. I have uninstalled and reinstalled everything. Can anyone help?

PS F:\hashlips_art_engine-1.0.8_update> npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path F:\hashlips_art_engine-1.0.8_update/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'F:\hashlips_art_engine-1.0.8_update\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

**Comment by bolshoytoster** [comment]
@mkenyon1984 I think you're in the wrong folder, run `Get-ChildItem -Directory` to get the name, then run `cd ` + name to go into it.

**Comment by mkenyon1984** [comment]
> @mkenyon1984 I think you're in the wrong folder, run `Get-ChildItem -Directory` to get the name, then run `cd ` + name to go into it.

Thank you.

**Comment by mkenyon1984** [comment]
I have another error lol.
 10k-collection-video@1.2.0 generate
> node index.js

(node:4076) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:306
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
                                                                ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:306:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:306:31)
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:401:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:366:9)

**Comment by bolshoytoster** [comment]
@mkenyon1984 could you add the line
```js
  console.log(metadataList);
```
just before line 306 in `src/main.js`:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L310-L311

(between those lines)
Then paste the output please.

**Comment by mkenyon1984** [comment]
> 10k-collection-video@1.2.0 generate
> node index.js

(node:15912) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
[
  {
    name: 'Versus Mode #0',
    symbol: 'VM',
    description: '5000 NFTs from the Versus Node Prelude Collection', 
    seller_fee_basis_points: 1500,
    image: 'image.png',
    external_url: 'https://www.versusmode.net',
    edition: 0,
    attributes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    properties: { files: [Array], category: 'image', creators: [Array] }
  }
]
F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:307
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
                                                                ^     

TypeError: Cannot read properties of undefined (reading 'edition')    
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:307:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:307:31)
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:402:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startCreating (F:\create-10k-nft-

**Comment by bolshoytoster** [comment]
@mkenyon1984 ah, change the `meta.custom_fields.edition` at line 307 to just `meta.edition`.

**Comment by mkenyon1984** [comment]
Dude thank you so much!

**Comment by mkenyon1984** [comment]
![image](https://user-images.githubusercontent.com/101291297/157536426-fef5a37c-d41b-4754-b7cd-75c21bb6f489.png)

**Comment by mkenyon1984** [comment]
Oh no. Sorry any ideas? There all .PNG with different rarities.

Created edition: 303, with DNA: 00a622c367a42bf2539cabc54f75f970144efeba
F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at Image.<anonymous> (<anonymous>)
    at setSource (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\node_modules\canvas\lib\image.js:91:13)
    at Image.set (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\node_modules\canvas\lib\image.js:62:9)
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\node_modules\canvas\index.js:23:10)
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:183:25
    at new Promise (<anonymous>)
    at loadLayerImg (F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:182:10)
    at F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0\src\main.js:364:31
PS F:\create-10k-nft-collection-1.2.0\create-10k-nft-collection-1.2.0>

**Comment by bolshoytoster** [comment]
@mkenyon1984 this is quite a notorious issue. You should make sure you only have image files in your layer folders (sometimes there can be files with names starting with '`.`' which makes them hidden.) if the error persists, ~line 182 of `src/main.js`, the original developer made a mistake with the `loadLayerImg` function:
```js
const loadLayerImg = async (_layer) => {
  try {
    return new Promise(async (resolve) => {
      const image = await loadImage(`${_layer.selectedElement.path}`);
      resolve({ layer: _layer, loadedImage: image });
    });
  } catch (error) {
    console.error("Error loading image:", error);
  }
};
```
change it to:
```js
const loadLayerImg = async (_layer) => {
  return new Promise(async (resolve) => {
    try {
      const image = await loadImage(`${_layer.selectedElement.path}`);
      resolve({ layer: _layer, loadedImage: image });
    } catch (error) {
      console.error("Error loading image:", error, _layer.selectedElement.path);
    }
  });
};
```
It won't fix the issue, but it'll tell you which file is causing the problem.
