### ISSUE TITLE
path: 'C:\\Users\\muso_\\Downloads\\YJIYKO_NFT_GENERATOR\\layers/body/'

### ISSUE THREAD

**Issue by musobek253** [HashLips/hashlips_art_engine#931]
Error: ENOENT: no such file or directory, scandir 'C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\layers/body/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\src\main.js:67:6)
    at C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\src\main.js:84:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\src\main.js:81:30)
    at startCreating (C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\src\main.js:241:20)
    at C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\index.js:13:3
    at Object.<anonymous> (C:\Users\muso_\Downloads\YJIYKO_NFT_GENERATOR\index.js:14:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\muso_\\Downloads\\YJIYKO_NFT_GENERATOR\\layers/body/'
}
![image](https://user-images.githubusercontent.com/48943355/157851511-2c8cc95c-1237-42fe-8c25-5fc80e652a20.png)

**Comment by musobek253** [comment]
https://prnt.sc/hebjNZZkTZ4O

**Comment by musobek253** [comment]
https://prnt.sc/BKcY4I4SgP5W

**Comment by shelly001** [comment]
for window, you shoud change / to \.
main.js: line 6, 7, 92

![image](https://user-images.githubusercontent.com/47731407/157854533-ba9eb62a-783a-4ae5-a6f3-e4bcf711f773.png)

![image](https://user-images.githubusercontent.com/47731407/157854452-2ccc3dd4-73b3-4aca-952d-0595eb6dc4e7.png)

**Comment by bolshoytoster** [comment]
@shelly001 that doesn’t matter; `/` is basically universal.

@musobek253 you need to save the `src/config.js` file.

**Comment by musobek253** [comment]
Can you give me a ready-made code that won't work anyway?
https://prnt.sc/UCzyx-lmyPbu

**Comment by musobek253** [comment]
> @shelly001 that doesn’t matter; `/` is basically universal.
> 
> @musobek253 you need to save the `src/config.js`.

Can you give me a ready-made code that won't work anyway?
https://prnt.sc/UCzyx-lmyPbu

**Comment by bolshoytoster** [comment]
@musobek253 you need to save the src/config.js file.

**Comment by musobek253** [comment]
> @musobek253 you need to save the src/config.js file.

show how to do it

**Comment by bolshoytoster** [comment]
@musobek253 use `ctrl` + `s`.
