### ISSUE TITLE
Cant deploy build folder 

### ISSUE THREAD

**Issue by DavidYenATUM** [HashLips/hashlips_art_engine#940]
1.1.2_patch_v6\src\main.js:4:14)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\src\\main.js',
    'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\index.js'
  ]
}
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM can you paste the full error please.

**Comment by DavidYenATUM** [comment]
Error: Cannot find module 'C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/node_modules/sha1'
Require stack:
- C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js
- C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)     
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:4:14)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\src\\main.js',
    'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\index.js'
  ]
}
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM you need to run `npm install` first to install the dependencies.

**Comment by DavidYenATUM** [comment]
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm install

up to date, audited 64 packages in 942ms

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM  you can generate now.

**Comment by DavidYenATUM** [comment]
with the npm index.js ???

**Comment by bolshoytoster** [comment]
@DavidYenATUM yes.

**Comment by DavidYenATUM** [comment]
no still no build file 


PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm index.js

Unknown command: "index.js"

To see a list of supported npm commands, run:
  npm help
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM you need to run either `node index.js` or `npm run build`.

**Comment by DavidYenATUM** [comment]
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm run build
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\atumw\AppData\Local\npm-cache\_logs\2022-03-14T16_04_58_300Z-debug.log
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM sorry, it's `npm run generate`. I was confused with a different project.

**Comment by DavidYenATUM** [comment]
im so confused 

S C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> npm run generate
npm ERR! Missing script: "generate"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\atumw\AppData\Local\npm-cache\_logs\2022-03-14T16_07_32_442Z-debug.log
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM you're in the wrong folder then. Run `Get-ChildItem -Directory` to get the name, the run `cd ` + name to go into it.

**Comment by DavidYenATUM** [comment]
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> cd
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> ls


    Directory: C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         3/10/2022     17:47                .vscode
d-----         3/14/2022     11:25                hashlips_art_engine-1.1.2_patch_v6
d-----         3/14/2022     10:53                node_modules
-a----         3/14/2022     11:54          41012 package-lock.json
-a----         3/14/2022     10:53            302 package.json


PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM run `cd hashlips_art_engine-1.1.2_patch_v6`.

**Comment by DavidYenATUM** [comment]
Nothing happened should i move the file or redownload it again 

PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> cd hashlips_art_engine-1.1.2_patch_v6
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> run cd hashlips_art_engine-1.1.2_patch_v6
run : The term 'run' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ run cd hashlips_art_engine-1.1.2_patch_v6
+ ~~~
    + CategoryInfo          : ObjectNotFound: (run:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM without the 'run'.

**Comment by DavidYenATUM** [comment]
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> cd hashlips_art_engine-1.1.2_patch_v6
cd : Cannot find path 'C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6' because it does not 
exist.
At line:1 char:1
+ cd hashlips_art_engine-1.1.2_patch_v6
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\atumw\...-1.1.2_patch_v6:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM can you send the output of `Get-ChildItem` please.

**Comment by DavidYenATUM** [comment]
Directory: C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          3/7/2022     11:33                .github
d-----         3/14/2022     11:20                .yarn
d-----          3/7/2022     11:33                constants
d-----         3/13/2022     16:08                layers
d-----          3/7/2022     11:33                modules
d-----          3/7/2022     11:33                src
d-----          3/7/2022     11:33                utils
-a----          3/7/2022     11:33           1678 .gitignore
-a----          3/7/2022     11:33              9 .nvmrc
-a----         3/14/2022     11:25         630502 .pnp.cjs
-a----          3/7/2022     11:33         441599 banner.png
-a----          3/7/2022     11:33            157 index.js
-a----          3/7/2022     11:33           1065 LICENSE
-a----          3/7/2022     11:33          37711 logo.png
-a----         3/14/2022     11:24          42352 package-lock.json
-a----         3/14/2022     11:24            906 package.json
-a----          3/7/2022     11:33           9930 README.md
-a----         3/14/2022     11:25          38480 yarn.lock


PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM you can run `npm run build` now.

**Comment by DavidYenATUM** [comment]
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/node_modules/sha1'
Require stack:
- C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js
- C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\src\\main.js',
    'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6\\index.js'
  ]
}
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM `npm install`.

**Comment by DavidYenATUM** [comment]
}
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6> npm install

added 67 packages, and audited 68 packages in 4s

6 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM `npm run build`.

**Comment by DavidYenATUM** [comment]
thanks that worked 
 can you kind of explain what the issue was so if i have this problem again i know how to fix it

**Comment by bolshoytoster** [comment]
@DavidYenATUM the main one was that you were in the wrong folder. If you are, it'll give an error like:
```
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR! npm run

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\atumw\AppData\Local\npm-cache_logs\2022-03-14T16_04_58_300Z-debug.log
```
If so, run you can probably run `cd hashlips_art_engine-1.1.2_patch_v6` to go there.

If that gives an error like:
```
cd : Cannot find path 'C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6' because it does not
exist.
At line:1 char:1

cd hashlips_art_engine-1.1.2_patch_v6
  + CategoryInfo          : ObjectNotFound: (C:\Users\atumw\...-1.1.2_patch_v6:String) [Set-Location], ItemNotFoundException
  + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```
Then you can run `Get-ChildItem -Directory` to get a list of sub-folders, run `cd ` + the name of the one most similar to `hashlips_art_engine-1.1.2_patch_v6`.

**Comment by DavidYenATUM** [comment]
ok thanks just 2 more questions what do i do about blurry images 


and  what do i do when all my layers are not showing up

**Comment by DavidYenATUM** [comment]
i made sure all my files had # and it was no dashes or anything but only my back ground is showing up

**Comment by DavidYenATUM** [comment]
C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:77
        throw new Error(`layer name can not contain dashes, please fix: ${i}`);
              ^

Error: layer name can not contain dashes, please fix: FADORA 3 FOR-BEARS#10.psd.png
    at C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:77:15
    at Array.map (<anonymous>)
    at getElements (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:75:6)
    at C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM
>  what do i do about blurry images

In `src/main.js` ~line 113:
https://github.com/HashLips/hashlips_art_engine/blob/d8ee279043d2d4a8de3bdfac0d89d0e966fb04a2/src/main.js#L113-L118

I think you can change `canvas.toBuffer("image/png")` to `canvas.toBuffer("image/png", { resolution: 300 })` and increase the 300 (ppi).

---

You also need to make sure none of your image names have dashes in them.

**Comment by DavidYenATUM** [comment]
ok thanks 
  what about the other layer not showing up in the build

**Comment by bolshoytoster** [comment]
@DavidYenATUM could you paste your `layersConfiguration` please, and which layers aren't showing up.

**Comment by DavidYenATUM** [comment]
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6> layersConfiguration
layersConfiguration : The term 'layersConfiguration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ layersConfiguration
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (layersConfiguration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bolshoytoster** [comment]
@DavidYenATUM it's in your `src/config.js` file.

**Comment by DavidYenATUM** [comment]
good day 
 growEditionSizeTo: 10,
    layersOrder: [
      
      { name: "Background" },
      { name: "Alien head gear" },
      { name: "Alien face accessories" },
      { name: "Alien eyes" },
      { name: "Alien head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" }
    ],
   }, {
    growEditionSizeTo: 20,
    layersOrder: [
      
      { name: "Fox head gear" },
      { name: "Fox face accessories" },
      { name: "Fox eyes" },
      { name: "Fox head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" }
    ],
   },
   {
    growEditionSizeTo: 30,
    layersOrder: [
      
      { name: "Baby head gear" },
      { name: "Baby face accessories" },
      { name: "Baby eyes" },
      { name: "Baby head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" }
    ],
   },
   {
    growEditionSizeTo: 40,
    layersOrder: [
      
      { name: "Bear head gear" },
      { name: "Bear face accessories" },
      { name: "Bear eyes" },
      { name: "Bear head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" }
    ],
   },
   {
    growEditionSizeTo: 100,
    layersOrder: [
      
      { name: "Baby head gear" },
      { name: "baby accessories" },
      { name: "Baby eyes" },
      { name: "Baby girl head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" }

**Comment by DavidYenATUM** [comment]
only the background is showing no matter how i run it

**Comment by bolshoytoster** [comment]
@DavidYenATUM your `layersOrder`s are in the wrong order - background should be first.
i.e.
```js
  { name: "Background" },
  { name: "Shoes" },
  { name: "Tan pants" },
  { name: "Clothes" },
  { name: "Hand accessories" },
  { name: "Fox head" },
  { name: "Fox eyes" },
  { name: "Fox face accessories" },
  { name: "Fox head gear" },
```
instead of
```js
  { name: "Fox head gear" },
  { name: "Fox face accessories" },
  { name: "Fox eyes" },
  { name: "Fox head" },
  { name: "Hand accessories" },
  { name: "Clothes" },
  { name: "Tan pants" },
  { name: "Shoes" },
  { name: "Background" }
```

**Comment by DavidYenATUM** [comment]
Created edition: 39, with DNA: e259a4afb5307c3493a2b7284150662bbea627e9
Created edition: 40, with DNA: 8063a245e6beb3ff1b176cbcea2a40011f040fbf
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/baby accessories/'      
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6/layers/baby accessories/'

**Comment by bolshoytoster** [comment]
@DavidYenATUM make sure the `layers/baby accessories` folder exists, you may have misspelled it.

**Comment by DavidYenATUM** [comment]
its baby face accessories but its not showing as that 
and i removed the rest just to text the fox layers but i tried to pull the baby face accessories

**Comment by bolshoytoster** [comment]
@DavidYenATUM can you change `baby accessories` in your `layersConfiguration` to `baby face accessories` then?

**Comment by DavidYenATUM** [comment]
![Screenshot_90](https://user-images.githubusercontent.com/98710144/158667764-b106c893-868f-48e6-89d4-2fcd33e72de1.png)

**Comment by bolshoytoster** [comment]
@DavidYenATUM can you paste your `layersConfigurations` again please.

**Comment by DavidYenATUM** [comment]
{
    growEditionSizeTo: 10,
    layersOrder: [
      
  { name: "Background" },
  { name: "Shoes" },
  { name: "Tan pants" },
  { name: "Clothes" },
  { name: "Hand accessories" },
  { name: "Fox head" },
  { name: "Fox eyes" },
  { name: "Fox face accessories" },
  { name: "Fox head gear" },
    ],
   }, {
    growEditionSizeTo: 20,
    layersOrder: [
      
      { name: "Fox head gear" },
      { name: "Fox face accessories" },
      { name: "Fox eyes" },
      { name: "Fox head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" },
    ],
   },
   {
    growEditionSizeTo: 30,
    layersOrder: [
      
      { name: "Baby head gear" },
      { name: "Baby face accessories" },
      { name: "Baby eyes" },
      { name: "Baby head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" },
    ],
   },
   {
    growEditionSizeTo: 40,
    layersOrder: [
      
      { name: "Bear head gear" },
      { name: "Bear face accessories" },
      { name: "Bear eyes" },
      { name: "Bear head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" }
    ],
   },
   {
    growEditionSizeTo: 100,
    layersOrder: [
      
      { name: "Baby head gear" },
      { name: "baby accessories" },
      { name: "Baby eyes" },
      { name: "Baby girl head" },
      { name: "Hand accessories" },
      { name: "Clothes" },
      { name: "Tan pants" },
      { name: "Shoes" },
      { name: "Background" },
    ],
   },
];

**Comment by bolshoytoster** [comment]
@DavidYenATUM in the last one, change `baby accessories` to `Baby face accessories`.

**Comment by DavidYenATUM** [comment]
i changed it 

Created edition: 40, with DNA: 989402de6350f69c212cd509847db562b9e28a12
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6/layers/baby accessories/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\atumw\\Downloads\\hashlips_art_engine-1.1.2_patch_v6\\hashlips_art_engine-1.1.2_patch_v6/layers/baby accessories/'
}
PS C:\Users\atumw\Downloads\hashlips_art_engine-1.1.2_patch_v6\hashlips_art_engine-1.1.2_patch_v6>

**Comment by bolshoytoster** [comment]
@DavidYenATUM make sure you save the file when you change it.

**Comment by DavidYenATUM** [comment]
its running all the files now but only background is showing

**Comment by bolshoytoster** [comment]
@DavidYenATUM you need to reverse the `layersOrder`s.

**Comment by DavidYenATUM** [comment]
ok i will try that
