### ISSUE TITLE
npm run build doesnt work

### ISSUE THREAD

**Issue by yantsarakhov** [HashLips/hashlips_art_engine#941]
Error: ENOENT, No such file or directory 'C:\Users\ДОМ\Desktop\hashlips_art_engine-main/layers/Background/Black#1.png'
    at setSource (C:\Users\ДОМ\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\ДОМ\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\ДОМ\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\ДОМ\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\ДОМ\Desktop\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\ДОМ\Desktop\hashlips_art_engine-main\src\main.js:184:12)
    at C:\Users\ДОМ\Desktop\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'C:\\Users\\ДОМ\\Desktop\\hashlips_art_engine-main/layers/Background/Black#1.png',
  syscall: 'fopen'
}

**Comment by bolshoytoster** [comment]
@yantsarakhov this is quite a notorious issue and I'm not sure how to fix it.

However, whenever I see it, the path has russian in it. Could you try moving the `hashlips_art_engine-main` folder somewhere that isn't in your user's folder (`C:/Users/Public/` is probably a good place).

**Comment by yantsarakhov** [comment]
@bolshoytoster it worked, thank you!
