### ISSUE TITLE
Node index.js проблема запуска, как решить?

### ISSUE THREAD

**Issue by Makar170821** [HashLips/hashlips_art_engine#955]
C:\Users\User\Desktop\hashlips_art_engine-main>node index.js
(node:7208) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:274
  return _dna.replace(query, "");
              ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings (C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:274:15)
    at cleanDna (C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:60:26)
    at C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:225:22
    at Array.find (<anonymous>)
    at C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:224:42
    at Array.map (<anonymous>)
    at constructLayerToDna (C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:223:35)
    at startCreating (C:\Users\User\Desktop\hashlips_art_engine-main\src\main.js:364:23)
    at C:\Users\User\Desktop\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\User\Desktop\hashlips_art_engine-main\index.js:7:3)

Node.js v17.6.0

**Comment by bolshoytoster** [comment]
@Makar170821 Не могли бы вы попробовать использовать [мою вилку](https://github.com/bolshoytoster/hashlips_art_engine)?

**Comment by Makar170821** [comment]
> 

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.1.0
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************

C:\Users\User\Downloads\hashlips_art_engine-main>npm install

added 66 packages, and audited 67 packages in 26s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\User\Downloads\hashlips_art_engine-main>node index.js
C:\Users\User\Downloads\hashlips_art_engine-main\src\main.js:322
        `${layer.elements[random].path}${
                                  ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\User\Downloads\hashlips_art_engine-main\src\main.js:322:35
    at Array.forEach (<anonymous>)
    at createDna (C:\Users\User\Downloads\hashlips_art_engine-main\src\main.js:313:11)
    at C:\Users\User\Downloads\hashlips_art_engine-main\src\main.js:423:16
    at Array.every (<anonymous>)
    at startCreating (C:\Users\User\Downloads\hashlips_art_engine-main\src\main.js:421:21)
    at C:\Users\User\Downloads\hashlips_art_engine-main\index.js:6:3
    at Object.<anonymous> (C:\Users\User\Downloads\hashlips_art_engine-main\index.js:7:3)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1097:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)←[39m

Node.js v17.6.0

Выбивает такую информацию.

**Comment by bolshoytoster** [comment]
@Makar170821 Извините, я исправил это, не могли бы вы попробовать перезагрузить мой форк, пожалуйста.

**Comment by Makar170821** [comment]
> @Makar170821 Извините, я исправил это, не могли бы вы попробовать перезагрузить мой форк, пожалуйста.
При вводе команды node index.js она запущена, следующая строка пустая и пол часа ничего не происходит.
Я не профессионал и далек от программирования. Идея состоит  в том, что бы задний фон генерировался из 400 квадратов (1 квадрат 25х25 pixel) общей площадью в 1000х1000 pixel. Возможно я неправильно прописал это?

**Comment by bolshoytoster** [comment]
@Makar170821 Вы должны запустить `node index.js`

**Comment by waitforitx** [comment]
You most probably get this error because you got an empty layer folder.

**Comment by bolshoytoster** [comment]
@waitforitx cheers, I've fixed this in my fork.

@Makar170821 Попробуйте переободрить мою вилку.
