### ISSUE TITLE
Node index.js not working (I am not adept in code)

### ISSUE THREAD

**Issue by rowyant** [HashLips/hashlips_art_engine#966]
This is the error. All help is appreciated

PS C:\Users\Robert Wyant\Desktop\hashlips_art_engine> node index.js
(node:16600) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Robert Wyant\Desktop\hashlips_art_engine/layers/Eyeball/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\Robert Wyant\Desktop\hashlips_art_engine\src\main.js:73:6)
    at C:\Users\Robert Wyant\Desktop\hashlips_art_engine\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Robert Wyant\Desktop\hashlips_art_engine\src\main.js:90:30)
    at startCreating (C:\Users\Robert Wyant\Desktop\hashlips_art_engine\src\main.js:356:20)
    at C:\Users\Robert Wyant\Desktop\hashlips_art_engine\index.js:6:3
    at Object.<anonymous> (C:\Users\Robert Wyant\Desktop\hashlips_art_engine\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Robert Wyant\\Desktop\\hashlips_art_engine/layers/Eyeball/'
}

**Comment by bolshoytoster** [comment]
@rowyant I think you just need to save the `src/config.js` file.

**Comment by rowyant** [comment]
@bolshoytoster Well way to make me feel dumb lol. That did it. Thanks for the help haha

**Comment by bolshoytoster** [comment]
@rowyant don't worry, at least you realised your mistake.
