### ISSUE TITLE
Npm run generate Issue 

### ISSUE THREAD

**Issue by Nachi4265** [HashLips/hashlips_art_engine#971]
When I run the : Npm run generate issue I get the following error 

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:20816) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { 
recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'        
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\hignacio\\Desktop\\NFT HELP\\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'

Not too sure what the issue is here, I'm very new to coding.

**Comment by bolshoytoster** [comment]
@Nachi4265 I think you just need to save the `src/config.js` file.

**Comment by Nachi4265** [comment]
I've tried it, but it doesn't seem to work I get the same error

**Comment by bolshoytoster** [comment]
@Nachi4265 can you paste your `layersConfigurations` here please.

**Comment by Nachi4265** [comment]
do you mean these 

  { name: "Background" },
      { name: "Skin color" },
      { name: "Hair" },
      { name: "Head piece" },
      { name: "Eyes" },
      { name: "Mouth" },

**Comment by bolshoytoster** [comment]
@Nachi4265 yes, can you paste the error again please.

**Comment by Nachi4265** [comment]
yea sure! 

> hashlips_art_engine@1.1.1 generate
> node index.js

(node:18672) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { 
recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'        
    at Object.readdirSync (node:fs:1392:3)
    at getElements (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:73:6)
    at C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:90:30)
    at startCreating (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\src\main.js:356:20)
    at C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\index.js:6:3
    at Object.<anonymous> (C:\Users\hignacio\Desktop\NFT HELP\hashlips_art_engine-1.1.2_patch_v6\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\hignacio\\Desktop\\NFT HELP\\hashlips_art_engine-1.1.2_patch_v6/layers/Eyeball/'

**Comment by bolshoytoster** [comment]
@Nachi4265 could you send a screenshot please.

**Comment by Nachi4265** [comment]
![image_2022-03-21_114456](https://user-images.githubusercontent.com/99918049/159342517-47f0f56d-8571-425f-a8a1-016a7edcfb47.png)

**Comment by bolshoytoster** [comment]
@Nachi4265 press `ctrl` + `s` to save the file then try again.

**Comment by Nachi4265** [comment]
![image_2022-03-21_115041](https://user-images.githubusercontent.com/99918049/159343435-7a300a15-8fe9-4183-8a91-36f105af9b9d.png)

**Comment by Nachi4265** [comment]
this is the error I got after I saved it

**Comment by bolshoytoster** [comment]
@Nachi4265 your image names can't have dashes in them.

If you need them, you could use [my fork](https://github.com/bolshoytoster/hashlips_art_engine), and change `DNA_DELIMITER` ~line 45 in `src/main.js`.

**Comment by Nachi4265** [comment]
yep i just figured it out thank you so much!!

**Comment by Nachi4265** [comment]
whenever i do generate the images they show up as black , is this an issue with some of them not have a background?

**Comment by bolshoytoster** [comment]
@Nachi4265 I noticed you're using jpeg, which doesn't support transparency. Try using png and make sure to add transparency to your images.
