### ISSUE TITLE
Error: EILSEQ, Illegal byte sequence

### ISSUE THREAD

**Issue by SleeepyGom** [HashLips/hashlips_art_engine#979]
Struggling with some error when running 'node index.js'................. :'(

Just right before, I had gotten "MODULE_NOT_FOUND" error :  but this disappears after changing the cavas version from "2.8.0" to "2.9.0" and reinstall npm.

Then I confront the error msg "Error: EILSEQ, Illegal byte sequence"-the full messages are below -
What should I do to fix up the following error msg? The 'build' folder made with nothing in it, and the 'Black#1.png" can be successfully opened.

Please understand me if I do a stupid question..T.T...I am just a computer infant.

And Thanks in advance to anyone who would reply on this !!

------------
E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6>node index.js
E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src)
            ^

Error: EILSEQ, Illegal byte sequence 'E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6/layers/Background/Black#1.png'
    at setSource (E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:91:13)
    at Image.set (E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\lib\image.js:62:9)
    at E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\node_modules\canvas\index.js:23:10)
    at E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:184:12)
    at E:\유진\NFT\hashlips_art_engine-1.1.2_patch_v6\src\main.js:368:31
    at Array.forEach (<anonymous>) {
  errno: 42,
  code: 'EILSEQ',
  path: 'E:\\유진\\NFT\\hashlips_art_engine-1.1.2_patch_v6/layers/Background/Black#1.png',
  syscall: 'fopen'
}

**Comment by bolshoytoster** [comment]
@SleeepyGom I think it's because you have non-ascii characters in your path. Try making a new folder like `E:/hashlips` and move the project into there.

**Comment by SleeepyGom** [comment]
> @SleeepyGom I think it's because you have non-ascii characters in your path. Try making a new folder like `E:/hashlips` and move the project into there.

!!!!!! I couldn't imagine that would be a problem. It works now! Thanks!!
