### ISSUE TITLE
npm installation problem

### ISSUE THREAD

**Issue by JacobeMNA** [HashLips/hashlips_art_engine#984]
Hello hope you have a nice day.
I am traying to build my 10000 NFT collection.
I start downloading the repo version.
( That is creat-10k-nft-collection zip file ( near 12 day ago published ) )

I already extract the file and upload it in my vs code and start working on it but suddenly, this error came when I tried running  npm install :

npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer     
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d 
/s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r901912! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/901912/chrome-win.zip
npm ERR!     at C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:367:27   
npm ERR!     at ClientRequest.requestCallback (C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:493:13)
npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:482:22)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahdi\AppData\Local\npm-cache\_logs\2022-03-23T05_44_53_846Z-debug-0.log

**Comment by JacobeMNA** [comment]
my node and npm version:
node -v :
v16.14.2
npm -v
8.5.5

**Comment by bolshoytoster** [comment]
@JacobeMNA
> creat-10k-nft-collection

You probably meant to open the issue on [codeSTACKr's repo](https://github.com/codeSTACKr/create-10k-nft-collection).

**Comment by JacobeMNA** [comment]
yeah exactly.
 I start again to build my nft collection and doing the last codeSTACKr video about making that.

**Comment by JacobeMNA** [comment]
in the npm installation, this error came

how I can move forward and reach the next step?

**Comment by JacobeMNA** [comment]
Link of the video:
https://www.youtube.com/watch?v=quGdJweadFM

**Comment by bolshoytoster** [comment]
@JacobeMNA yeah, but your issue is in the wrong place, the error doesn't occur on hashlips_art_engine.

The error might be because you're behind a proxy.

**Comment by JacobeMNA** [comment]
what do you mean?
Could you describe more please? cause I already open it by opload (new file window) on vs code?

**Comment by JacobeMNA** [comment]
yeah your right but after turn it off I have this error:


npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer     
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d 
/s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r901912! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/901912/chrome-win.zip
npm ERR!     at C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:367:27   
npm ERR!     at ClientRequest.requestCallback (C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:493:13)
npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:482:22)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahdi\AppData\Local\npm-cache\_logs\2022-03-23T08_23_58_695Z-debug-0.log  
PS C:\Users\Mahdi\Downloads\create-10k-nft-colle

**Comment by JacobeMNA** [comment]
COULD you tell me what does  is saying?

**Comment by JacobeMNA** [comment]
I also tried to open a new terminal an try npm installation again without proxy,  but I have this error:


npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer     
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d 
/s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r901912! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/901912/chrome-win.zip
npm ERR!     at C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:367:27   
npm ERR!     at ClientRequest.requestCallback (C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:493:13)
npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:482:22)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahdi\AppData\Local\npm-cache\_logs\2022-03-23T08_58_17_918Z-debug-0.log

**Comment by bolshoytoster** [comment]
@JacobeMNA open a new issue in codeSTCKr's repo, I can't help you.

**Comment by JacobeMNA** [comment]
How much I should wait till there respond

**Comment by JacobeMNA** [comment]
This guy didn't answer anybody.
Do you know anybody else?

**Comment by JacobeMNA** [comment]
Hello man hope you have special day and I was embarrassed to be bothered again its cause I almost  done and really need help.

I find a way for my last error: ==> Low npm-fetch version make that error.

But now when I try running (node utils/nftport/uploadFiles.js)  after that error, this one came in:

C:\Users\Mahdi\Downloads\hashlips_art_engine-1.1.1_update\utils\nftport\uploadFiles.js:7
fs.readdirSync(`${basePath}/build/images`).foreach((file) => {
                                           ^

TypeError: fs.readdirSync(...).foreach is not a function      
    at Object.<anonymous> (C:\Users\Mahdi\Downloads\hashlips_art_engine-1.1.1_update\utils\nftport\uploadFiles.js:7:44)     
    at Module._compile (node:internal/modules/cjs/loader:
1103:14)
    at Object.Module._extensions..js (node:internal/modul
es/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:
32)
    at Function.Module._load (node:internal/modules/cjs/l
oader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:
internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by JacobeMNA** [comment]
I watch the video that write it several times and even find so many mistakes; but after fixing them this error came again and I can't find more mistake.
I need your help bro

**Comment by bolshoytoster** [comment]
@JacobeMNA this error comes from codeSTACKr's repo, you should open an issue [there](https://github.com/codeSTACKr/create-10k-nft-collection/issues) instead.

**Comment by thVoidy** [comment]
@JacobeMNA head over to https://github.com/puppeteer/puppeteer and update the puppeteer version to the up-to-date version 13.7.0. In order to do so just run npm i puppeteer in your terminal.

regards,
the_voidy
