### ISSUE TITLE
Problem with rarity delimiter after running index.js

### ISSUE THREAD

**Issue by aidantibbitt** [HashLips/hashlips_art_engine#985]
After I run index.js I am met with this prompt. I have tried messing with the rarityDelimiter value but nothings changing. Please help!

/Users/atibbitt/nft-collection/hashlips_art_engine/src/config.js:83
const rarityDelimiter = "#";
^^^^^

SyntaxError: Unexpected token 'const'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/atibbitt/nft-collection/hashlips_art_engine/src/main.js:24:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by bolshoytoster** [comment]
@aidantibbitt there's a syntax error in your `src/config.js`, can you paste lines 75-85 please.

**Comment by aidantibbitt** [comment]
const background = {
  generate: true,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const extraMetadata = {},

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

**Comment by aidantibbitt** [comment]
this is lines 74-85

**Comment by bolshoytoster** [comment]
@aidantibbitt change the line `const extraMetadata = {},` to `const extraMetadata = {};` (change the comma to a semicolon)

**Comment by aidantibbitt** [comment]
IT WORKED TYSM!!
