### ISSUE TITLE
Issue generating my images

### ISSUE THREAD

**Issue by CandyClanNFT** [HashLips/hashlips_art_engine#992]
Bryces-MacBook-Air:hashlips_art_engine-1.1.2_patch_v6 3 Nicholson_approved$ npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:56478) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
                                                                ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:314:31)
    at /Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:409:11
    **at processTicksAndRejections (node:internal/process/task_queues:96:5)**
    at async startCreating (/Users/Nicholson_approved/Downloads/hashlips_art_engine-1.1.2_patch_v6 3/src/main.js:374:9)
Bryces-MacBook-Air:hashlips_art_engine-1.1.2_patch_v6 3 Nicholson_approved$ 
.
.
.
 **at processTicksAndRejections (node:internal/process/task_queues:96:5)** is the error coming up

**Comment by CandyClanNFT** [comment]
![Screen Shot 2022-03-24 at 1 06 48 PM](https://user-images.githubusercontent.com/101203716/159981873-9207c0e9-72eb-4a7e-8ff6-279bb2605c30.png)

**Comment by CandyClanNFT** [comment]
please help

**Comment by bolshoytoster** [comment]
@CandyClanNFT can you use [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.
