### ISSUE TITLE
Getting syntax error - Please help

### ISSUE THREAD

**Issue by sigmagirl** [HashLips/hashlips_art_engine#997]
PS D:\hashlips_art_engine-main> node index.js
D:\hashlips_art_engine-main\src\main.js:94
      layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\hashlips_art_engine-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
PS D:\hashlips_art_engine-main>

**Comment by dancingmonkey** [comment]
Make sure you use node `v14.18.2`. I had this error when I accidentally installed `v12.18.2`. After that just delete the node_modules folder with `rm -rf node_modules` and do a `npm install` again. should work because I tried today

**Comment by sigmagirl** [comment]
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node is not a valid Win32 application.
\\?\D:\hashlips_art_engine-main\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\hashlips_art_engine-main\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
} got this error with nodejs -v 14.18.2 on node index.js

**Comment by bolshoytoster** [comment]
@sigmagirl try deleting the `node_modules` folder and running `npm install` again.

If that doesn’t work then you’ve installed the wrong arch (32 bit / 64 bit) of node, make sure it matches your OS.

**Comment by sigmagirl** [comment]
node_modules folder has to be deleted though VSCode or from cdrive?

**Comment by sigmagirl** [comment]
i have installed the 64 bit and it matches my system

**Comment by bolshoytoster** [comment]
@sigmagirl try deleting `node_modules` (in your project) then run `npm install --build-from-source`.

**Comment by SeemoneB** [comment]
@sigmagirl I had the same problem. Resolved with `nvm use 14.18.2`, then delete `node_modules` and run `npm install`
