### ISSUE TITLE
Error: Unsupported image type

### ISSUE THREAD

**Issue by adnan12wetysw** [HashLips/hashlips_art_engine#999]
Your environment has been set up for using Node.js 16.14.0 (x64) and npm.

C:\Users\sUPER>cd C:\Users\sUPER\Desktop\hashlips_art_engine-main

C:\Users\sUPER\Desktop\hashlips_art_engine-main>npm install

up to date, audited 66 packages in 3s

6 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

C:\Users\sUPER\Desktop\hashlips_art_engine-main>node index.js
(node:3668) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Created edition: 1, with DNA: 84b996153b0e63dba524243538a837709d4becd5
Created edition: 2, with DNA: 0e729ac78c9faa4c3e60482445d4f0a741841e7f
Created edition: 3, with DNA: 27280aada21525225e48ee02e567271f48bcc327
Created edition: 4, with DNA: 42ff7698601d6479f6d1ced7f0044ef82ef6a65f
Created edition: 5, with DNA: f7367b7478063807588e2721c75271686e182a28
Created edition: 6, with DNA: b8336b6eaab62045899d74286759bc6a4b89155b
Created edition: 7, with DNA: 151c0991b5b5b1748107d92462c1000369fb0673
Created edition: 8, with DNA: b5b501e4b60a3ce7c9679c8de7f3a64d0e362563
Created edition: 9, with DNA: 54102334833947c365d837d7ba04a9e4f2258ceb
Created edition: 10, with DNA: 78d7482f69f4a301aeeb96859d480f90b105270c
Created edition: 11, with DNA: 9221d48c474a535578d650b22243a1a1bc810884
Created edition: 12, with DNA: f050f6a19b5a9bc12ed0dddb50ac9de8f2d1673f
Created edition: 13, with DNA: 66de1a328c859204f2855c98cbc748de7a777850
Created edition: 14, with DNA: be58c0a57a58a2d1c103c07e223bb6303c97e8fc
Created edition: 15, with DNA: bb508ebfb320a940e3906c4900f1985a5d50b144
Created edition: 16, with DNA: 5ab0a8f966c422483321b8be779a5fc8c93adff3
Created edition: 17, with DNA: 98ce2f1dc5034e021e4e6c2488dd35642eeee255
Created edition: 18, with DNA: 5f7209a0d5b7350c7be3353c7988ac410aaa605c
Created edition: 19, with DNA: f2afa7706b0da158937720b91a25026cd9bb3999
Created edition: 20, with DNA: a8b0497059793deb9b1846e44bdb27ddc2d66568
Created edition: 21, with DNA: eac82013295fb50fc756d4eaae3a5a2d6486cec4
Created edition: 22, with DNA: 589f3c9f6484150a848904061486253d3e1392ae
Created edition: 23, with DNA: 6403cb648ae5ca6abbbed1c75dc598a954dfaea9
Created edition: 24, with DNA: eef46b6782ca30c0e0ca6f0cba67d9522cf61799
Created edition: 25, with DNA: 37dca9112bd5ca64d4ee59003acc5091a8e1e7c8
Created edition: 26, with DNA: 1b6b8f0d5d1c6624f3ef26f680a44d2513dadd35
C:\Users\sUPER\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: Unsupported image type
    at setSource (C:\Users\sUPER\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\sUPER\Desktop\hashlips_art_engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\sUPER\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\sUPER\Desktop\hashlips_art_engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\sUPER\Desktop\hashlips_art_engine-main\src\main.js:185:27
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\sUPER\Desktop\hashlips_art_engine-main\src\main.js:184:12)
    at C:\Users\sUPER\Desktop\hashlips_art_engine-main\src\main.js:368:31
    at Array.forEach (<anonymous>)

**Comment by bolshoytoster** [comment]
@adnan12wetysw can you try using [my fork](https://github.com/bolshoytoster/hashlips_art_engine) please.
